import { describe, it, expect } from "vitest";
import { seedBuiltinExecutors } from "../../index";
import { getExecutor, hasExecutor } from "@/lib/engine/node-runtime";
import { getNodeType, seedBuiltinDescriptions } from "@/lib/nodes/registry";
import { runNode } from "../helpers";

seedBuiltinExecutors();
seedBuiltinDescriptions();

const TYPE = "n8n-nodes-base.markdown";

describe("batch-queue markdown — n8n-nodes-base.markdown", () => {
  it("is registered as executor + description", () => {
    expect(hasExecutor(TYPE)).toBe(true);
    expect(getNodeType(TYPE).placeholder).not.toBe(true);
    expect(getNodeType(TYPE).displayName).toBe("Markdown");
  });

  it("resolves the same executor under the canonical type string", () => {
    const canonical = getExecutor(TYPE);
    expect(canonical).toBeDefined();
    expect(getExecutor("nodes-base.markdown")).toBe(canonical);
  });

  it("defaults to htmlToMarkdown mode when mode is omitted", async () => {
    const out = await runNode(
      TYPE,
      { html: "<p>Hello</p>", destinationKey: "data" },
      [{}],
    );
    expect(out[0][0].json.data).toBe("Hello");
  });

  it("throws when destinationKey is empty", async () => {
    await expect(
      runNode(
        TYPE,
        { mode: "markdownToHtml", markdown: "# Hi", destinationKey: "" },
        [{}],
      ),
    ).rejects.toThrow(/destinationKey/);
  });

  it("retains existing JSON fields and augments with destinationKey", async () => {
    const out = await runNode(
      TYPE,
      { mode: "markdownToHtml", markdown: "Hi", destinationKey: "data" },
      [{ keep: "me" }],
    );
    expect(out[0][0].json).toEqual({ keep: "me", data: "<p>Hi</p>" });
  });

  it("markdown to HTML (paragraph with strong)", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "markdownToHtml",
        markdown: "Hello **world**",
        destinationKey: "data",
      },
      [{}],
    );
    expect(out[0]).toHaveLength(1);
    expect(out[0][0].json).toEqual({ data: "<p>Hello <strong>world</strong></p>" });
  });

  it("HTML to Markdown (heading + emphasis)", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "htmlToMarkdown",
        html: "<h1>Title</h1>\n<p>Hello <em>there</em></p>",
        destinationKey: "data",
      },
      [{}],
    );
    expect(out[0]).toHaveLength(1);
    expect(out[0][0].json).toEqual({ data: "# Title\n\nHello _there_" });
  });

  it("destination key dot notation nests objects", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "markdownToHtml",
        markdown: "# Hi",
        destinationKey: "out.html",
        options: { noHeaderId: true },
      },
      [{}],
    );
    expect(out[0][0].json).toEqual({ out: { html: "<h1>Hi</h1>" } });
  });

  it("per-item conversion preserves item count", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "markdownToHtml",
        markdown: "- a",
        destinationKey: "data",
        options: { noHeaderId: true },
      },
      [{}, {}],
    );
    expect(out[0]).toHaveLength(2);
    expect(out[0][0].json).toEqual({ data: "<ul>\n<li>a</li>\n</ul>" });
    expect(out[0][1].json).toEqual({ data: "<ul>\n<li>a</li>\n</ul>" });
  });

  it("option effect — strikethrough", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "markdownToHtml",
        markdown: "~~done~~",
        destinationKey: "data",
        options: { strikethrough: true },
      },
      [{}],
    );
    expect(out[0][0].json).toEqual({ data: "<p><del>done</del></p>" });
  });

  it("strikethrough off leaves ~~ literal", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "markdownToHtml",
        markdown: "~~done~~",
        destinationKey: "data",
      },
      [{}],
    );
    expect(out[0][0].json).toEqual({ data: "<p>~~done~~</p>" });
  });

  it("header id generated by default, suppressed with noHeaderId", async () => {
    const withId = await runNode(
      TYPE,
      { mode: "markdownToHtml", markdown: "# Hello World", destinationKey: "data" },
      [{}],
    );
    expect(withId[0][0].json.data).toContain("<h1 ");
    expect(withId[0][0].json.data).toContain('id="');

    const withoutId = await runNode(
      TYPE,
      {
        mode: "markdownToHtml",
        markdown: "# Hello World",
        destinationKey: "data",
        options: { noHeaderId: true },
      },
      [{}],
    );
    expect(withoutId[0][0].json.data).toBe("<h1>Hello World</h1>");
  });

  it("HTML to Markdown converts <strong> with strongDelimiter", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "htmlToMarkdown",
        html: "<p>Hi <strong>bold</strong></p>",
        destinationKey: "data",
      },
      [{}],
    );
    expect(out[0][0].json.data).toBe("Hi **bold**");
  });

  it("HTML to Markdown converts unordered list", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "htmlToMarkdown",
        html: "<ul><li>one</li><li>two</li></ul>",
        destinationKey: "data",
      },
      [{}],
    );
    expect(out[0][0].json.data).toBe("* one\n* two");
  });

  it("HTML to Markdown respects custom emDelimiter", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "htmlToMarkdown",
        html: "<p>Hi <em>there</em></p>",
        destinationKey: "data",
        options: { emDelimiter: "*" },
      },
      [{}],
    );
    expect(out[0][0].json.data).toBe("Hi *there*");
  });

  it("markdown to HTML converts code block", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "markdownToHtml",
        markdown: "```\nconst x = 1;\n```",
        destinationKey: "data",
        options: { noHeaderId: true },
      },
      [{}],
    );
    expect(out[0][0].json.data).toBe("<pre><code>const x = 1;</code></pre>");
  });

  it("markdown to HTML converts blockquote", async () => {
    const out = await runNode(
      TYPE,
      {
        mode: "markdownToHtml",
        markdown: "> quoted text",
        destinationKey: "data",
        options: { noHeaderId: true },
      },
      [{}],
    );
    expect(out[0][0].json.data).toBe("<blockquote>\nquoted text\n</blockquote>");
  });

  it("produces no output for empty input", async () => {
    const out = await runNode(
      TYPE,
      { mode: "markdownToHtml", markdown: "Hi", destinationKey: "data" },
      [],
    );
    expect(out[0]).toEqual([]);
  });
});