import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { createExecutionContext, type ExecutionContext } from "@/sdk";
import type { INodeExecutionData } from "@/lib/workflow/types";
import { seedBuiltinExecutors } from "../../index";
import { getExecutor } from "@/lib/engine/node-runtime";
import { makeNode } from "../helpers";

seedBuiltinExecutors();

const TYPE = "n8n-nodes-base.youTube";
const CREDS = { youTubeOAuth2Api: { accessToken: "tok_yt" } };

function mockResponse(body: unknown, status = 200, headers: Record<string, string> = {}) {
  const text = body === undefined || body === null ? "" : JSON.stringify(body);
  const headerMap = new Map(
    Object.entries({ "content-type": "application/json", ...headers }).map(([k, v]) => [
      k.toLowerCase(),
      v,
    ]),
  );
  return {
    status,
    ok: status >= 200 && status < 300,
    statusText: "OK",
    headers: {
      get: (name: string) => headerMap.get(name.toLowerCase()) ?? null,
    },
    async json() {
      return text ? JSON.parse(text) : {};
    },
    async text() {
      return text;
    },
  };
}

type Handler = (
  url: string,
  method: string,
  body?: unknown,
) => ReturnType<typeof mockResponse>;
let handler: Handler;
let lastBody: unknown;
let lastUrl: string;
let lastMethod: string;
let calls: Array<{ url: string; method: string; body?: unknown }>;

function installFetch(h: Handler) {
  handler = h;
  lastBody = undefined;
  lastUrl = "";
  lastMethod = "";
  calls = [];
  vi.stubGlobal(
    "fetch",
    vi.fn(async (url: string, init?: RequestInit) => {
      let body: unknown;
      if (init?.body && typeof init.body === "string") {
        try {
          body = JSON.parse(init.body);
        } catch {
          body = init.body;
        }
      } else if (init?.body instanceof Uint8Array) {
        body = init.body;
      }
      lastBody = body;
      lastUrl = String(url);
      lastMethod = init?.method ?? "GET";
      calls.push({ url: lastUrl, method: lastMethod, body });
      return handler(String(url), init?.method ?? "GET", body);
    }),
  );
}

async function run(
  parameters: Record<string, unknown>,
  inputItems: INodeExecutionData[] = [{ json: {} }],
  opts?: { continueOnFail?: boolean },
) {
  const node = makeNode({
    name: "N",
    type: TYPE,
    parameters,
    credentials: { youTubeOAuth2Api: { name: "youTubeOAuth2Api" } },
  });
  const ctx: ExecutionContext = createExecutionContext({
    node,
    workflow: {
      id: "wf",
      name: "T",
      active: false,
      nodes: [node],
      connections: {},
      settings: {},
    },
    getNodeInputItems: () => inputItems,
    continueOnFail: opts?.continueOnFail ?? false,
    getCredential: async (name) => CREDS[name as keyof typeof CREDS] ?? null,
  });
  return getExecutor(TYPE)!(ctx, node);
}

beforeEach(() => {
  installFetch(() => mockResponse({}));
});
afterEach(() => {
  vi.unstubAllGlobals();
});

describe("youTube executor – acceptance tests", () => {
  it("is registered", () => {
    expect(getExecutor(TYPE)).toBeTypeOf("function");
  });

  it("channel get single", async () => {
    installFetch((url, method) => {
      if (method === "GET" && url.includes("/channels")) {
        return mockResponse({
          items: [
            {
              kind: "youtube#channel",
              id: "UC_x5XG1OV2P6uZZ5FSM9Ttw",
              snippet: { title: "Google for Developers" },
              statistics: { viewCount: "100" },
            },
          ],
        });
      }
      return mockResponse({});
    });

    const out = await run({
      resource: "channel",
      operation: "get",
      channelId: "UC_x5XG1OV2P6uZZ5FSM9Ttw",
      part: ["snippet", "statistics"],
    });

    expect(out[0][0].json).toMatchObject({
      kind: "youtube#channel",
      id: "UC_x5XG1OV2P6uZZ5FSM9Ttw",
      snippet: expect.any(Object),
      statistics: expect.any(Object),
    });
    expect(lastUrl).toContain("id=UC_x5XG1OV2P6uZZ5FSM9Ttw");
    expect(lastUrl).toContain("part=snippet%2Cstatistics");
  });

  it("playlist create with privacy", async () => {
    installFetch((url, method) => {
      if (method === "POST" && url.includes("/playlists")) {
        return mockResponse({
          id: "PLtest123",
          snippet: {
            title: "My Automation Playlist",
            description: "Generated by n8n",
          },
          status: { privacyStatus: "unlisted" },
        });
      }
      return mockResponse({});
    });

    const out = await run({
      resource: "playlist",
      operation: "create",
      title: "My Automation Playlist",
      options: {
        description: "Generated by n8n",
        privacyStatus: "unlisted",
      },
    });

    expect(out[0][0].json).toMatchObject({
      id: "PLtest123",
      snippet: {
        title: "My Automation Playlist",
        description: "Generated by n8n",
      },
      status: { privacyStatus: "unlisted" },
    });
    expect(lastMethod).toBe("POST");
    expect(lastBody).toMatchObject({
      snippet: {
        title: "My Automation Playlist",
        description: "Generated by n8n",
      },
      status: { privacyStatus: "unlisted" },
    });
  });

  it("video getAll with filters", async () => {
    installFetch((url, method) => {
      if (method === "GET" && url.includes("/search")) {
        return mockResponse({
          items: [
            {
              kind: "youtube#searchResult",
              id: { videoId: "abc123" },
              snippet: { title: "n8n tutorial intro" },
            },
          ],
        });
      }
      return mockResponse({});
    });

    const out = await run({
      resource: "video",
      operation: "getAll",
      returnAll: false,
      limit: 5,
      filters: {
        q: "n8n tutorial",
        videoType: "any",
      },
      options: {
        order: "relevance",
      },
    });

    expect(out[0][0].json).toMatchObject({
      kind: "youtube#searchResult",
      id: { videoId: "abc123" },
      snippet: { title: expect.any(String) },
    });
    expect(lastUrl).toContain("/search");
    expect(lastUrl).toContain("q=n8n%20tutorial");
    expect(lastUrl).toContain("order=relevance");
    expect(lastUrl).toContain("maxResults=5");
    expect(lastUrl).not.toContain("videoType=");
  });

  it("video upload (binary input)", async () => {
    installFetch((url, method) => {
      if (method === "POST" && url.includes("/upload/youtube/v3/videos")) {
        return mockResponse(
          { uploadId: "up-1" },
          200,
          { location: "https://www.googleapis.com/upload/youtube/v3/videos?upload_id=up-1" },
        );
      }
      if (method === "PUT" && url.includes("upload_id=up-1")) {
        return mockResponse({
          uploadId: "up-1",
          id: "vid-xyz",
          snippet: { title: "My Upload" },
          status: { privacyStatus: "private" },
        });
      }
      return mockResponse({});
    });

    const out = await run(
      {
        resource: "video",
        operation: "upload",
        title: "My Upload",
        binaryProperty: "data",
        options: {
          privacyStatus: "private",
          notifySubscribers: false,
        },
      },
      [
        {
          json: {},
          binary: {
            data: {
              data: btoa("fake-video-bytes"),
              mimeType: "video/mp4",
              fileName: "demo.mp4",
            },
          },
        },
      ],
    );

    expect(out[0][0].json).toMatchObject({
      id: "vid-xyz",
      snippet: { title: "My Upload" },
      status: { privacyStatus: "private" },
    });
    expect(calls.length).toBeGreaterThanOrEqual(2);
    expect(calls[0].method).toBe("POST");
    expect(calls[0].body).toMatchObject({
      snippet: { title: "My Upload" },
      status: { privacyStatus: "private" },
    });
    expect(calls[1].method).toBe("PUT");
  });

  it("playlistItem add", async () => {
    installFetch((url, method) => {
      if (method === "POST" && url.includes("/playlistItems")) {
        return mockResponse({
          id: "PLitem1",
          snippet: {
            playlistId: "PLtest",
            resourceId: { videoId: "abc123" },
            position: 0,
          },
        });
      }
      return mockResponse({});
    });

    const out = await run({
      resource: "playlistItem",
      operation: "add",
      playlistId: "PLtest",
      videoId: "abc123",
      options: { position: 0 },
    });

    expect(out[0][0].json).toMatchObject({
      id: "PLitem1",
      snippet: {
        playlistId: "PLtest",
        resourceId: { videoId: "abc123" },
        position: 0,
      },
    });
    expect(lastBody).toMatchObject({
      snippet: {
        playlistId: "PLtest",
        resourceId: { kind: "youtube#video", videoId: "abc123" },
        position: 0,
      },
    });
  });

  it("video getAll rejects relatedToVideoId + forDeveloper", async () => {
    await expect(
      run({
        resource: "video",
        operation: "getAll",
        filters: { relatedToVideoId: "abc", forDeveloper: true },
      }),
    ).rejects.toThrow(/relatedToVideoId and forDeveloper/);
  });

  it("continueOnFail returns error json", async () => {
    installFetch(() => mockResponse({ error: { message: "quotaExceeded" } }, 403));
    const out = await run(
      {
        resource: "channel",
        operation: "get",
        channelId: "missing",
        part: ["snippet"],
      },
      [{ json: {} }],
      { continueOnFail: true },
    );
    expect(out[0][0].json).toMatchObject({ error: expect.stringContaining("quotaExceeded") });
  });
});
