// Executor barrel.
//
// Registration is performed by register-builtins.ts, which statically imports
// every module listed in BUILTIN_EXECUTOR_MODULES. That file is generated by
// `node scripts/generate-executor-register.mjs` (also run from `npm run build`).
//
// Why not import.meta.glob? Nitro/Rolldown production builds tree-shake eager
// glob side-effects, leaving the registry empty ("No executor for node type").
// Static imports cannot be dropped while seedBuiltinExecutors / getExecutorMap
// remain live exports.
import {
  getExecutorMap as getLiveExecutorMap,
  defaultExecutors,
} from "../node-runtime";
import type { NodeExecutor } from "../types";
import { seedBuiltinExecutors as seedFromRegister } from "./register-builtins";

export function seedBuiltinExecutors(): void {
  seedFromRegister();
}

export function getExecutorMap(): Record<string, NodeExecutor> {
  seedBuiltinExecutors();
  return getLiveExecutorMap();
}

// Ensure load of this barrel always seeds (register-builtins already does).
seedBuiltinExecutors();

export { defaultExecutors };
