import type { INodeTypeDescription } from "../types";

const CORE = "https://docs.n8n.io/integrations/builtin/core-nodes/";
const KM = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.kitemaker.md";
const KM_CRED = "https://docs.n8n.io/integrations/builtin/credentials/kitemaker.md";
const KM_API = "https://kitemakerhq.github.io/rest-docs/";

export const kitemakerTool: INodeTypeDescription = {
  name: "n8n-nodes-base.kitemakerTool",
  displayName: "Kitemaker Tool",
  category: "Actions",
  group: ["action"],
  version: 1,
  description: "Interact with Kitemaker API for organizations, spaces, users, and work items",
  defaults: { name: "Kitemaker Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Briefcase",
  credentials: [{ name: "kitemakerApi", required: true }],
  sources: [
    { url: KM, name: "n8n docs" },
    { url: KM_CRED, name: "n8n creds" },
    { url: KM_API, name: "Kitemaker REST API" },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "workItem",
      required: true,
      options: [
        { name: "Organization", value: "organization" },
        { name: "Space", value: "space" },
        { name: "User", value: "user" },
        { name: "Work Item", value: "workItem" },
      ],
      description: "Which Kitemaker entity to operate on",
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      options: [
        { name: "Get", value: "get", description: "Get a single entity" },
        { name: "Get All", value: "getAll", description: "List entities" },
        { name: "Create", value: "create", description: "Create a work item" },
        { name: "Update", value: "update", description: "Update a work item" },
      ],
    },
    {
      displayName: "Space ID",
      name: "spaceId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["workItem"], operation: ["create", "getAll"] } },
      description: "Space key or ID for scope",
    },
    {
      displayName: "Work Item ID",
      name: "workItemId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["workItem"], operation: ["get", "update"] } },
      description: "The work item ID",
    },
    {
      displayName: "Title",
      name: "title",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["workItem"], operation: ["create", "update"] } },
      description: "Work item title. Accepts expressions.",
    },
    {
      displayName: "Status ID",
      name: "statusId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["workItem"], operation: ["create", "update"] } },
      description: "Status/column ID",
    },
    {
      displayName: "Description",
      name: "description",
      type: "string",
      default: "",
      typeOptions: { rows: 4 },
      displayOptions: { show: { resource: ["workItem"], operation: ["create", "update"] } },
      description: "Markdown description. Accepts expressions.",
    },
    {
      displayName: "Label IDs",
      name: "labelIds",
      type: "string",
      default: "",
      typeOptions: { multipleValues: true },
      displayOptions: { show: { resource: ["workItem"], operation: ["create", "update"] } },
      description: "Labels to assign (comma-separated IDs)",
    },
    {
      displayName: "Effort",
      name: "effort",
      type: "options",
      default: "medium",
      options: [
        { name: "Small", value: "small" },
        { name: "Medium", value: "medium" },
        { name: "Large", value: "large" },
      ],
      displayOptions: { show: { resource: ["workItem"], operation: ["create", "update"] } },
      description: "Effort estimate",
    },
    {
      displayName: "Impact",
      name: "impact",
      type: "options",
      default: "medium",
      options: [
        { name: "Small", value: "small" },
        { name: "Medium", value: "medium" },
        { name: "Large", value: "large" },
      ],
      displayOptions: { show: { resource: ["workItem"], operation: ["create", "update"] } },
      description: "Impact estimate",
    },
    {
      displayName: "Placement",
      name: "placement",
      type: "options",
      default: "top",
      options: [
        { name: "Top", value: "top" },
        { name: "Bottom", value: "bottom" },
      ],
      displayOptions: { show: { resource: ["workItem"], operation: ["create"] } },
      description: "Position in status column",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["workItem"], operation: ["getAll"] } },
      description: "Return all items (paginate)",
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["workItem"], operation: ["getAll"] } },
      description: "Max items per page",
    },
  ],
};

export const netlifyTool: INodeTypeDescription = {
  name: "n8n-nodes-base.netlifyTool",
  displayName: "Netlify Tool",
  category: "Action",
  group: ["action"],
  version: 1,
  description: "Manage Netlify sites and deploys",
  defaults: { name: "Netlify Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Globe",
  credentials: [{ name: "netlifyApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.netlify/",
    "https://docs.n8n.io/integrations/builtin/credentials/netlify/",
    "https://docs.netlify.com/api/get-started/",
    "https://open-api.netlify.com",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "deploy",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Deploy", value: "deploy" },
        { name: "Site", value: "site" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["deploy"] } },
      options: [
        { name: "Cancel", value: "cancel" },
        { name: "Create", value: "create" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["site"] } },
      options: [
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Site ID",
      name: "siteId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["deploy"], operation: ["get", "create", "getAll"] },
      },
      description: "Site UUID or domain name — accepts expressions",
    },
    {
      displayName: "Deploy ID",
      name: "deployId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["deploy"], operation: ["get", "cancel"] },
      },
      description: "The deploy UUID — accepts expressions",
    },
    {
      displayName: "Site ID",
      name: "siteId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["site"], operation: ["get", "delete"] },
      },
      description: "Site UUID or domain name — accepts expressions",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { resource: ["deploy", "site"], operation: ["getAll"] },
      },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      typeOptions: { minValue: 1, maxValue: 200 },
      displayOptions: {
        show: { resource: ["deploy", "site"], operation: ["getAll"], returnAll: [false] },
      },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["deploy"], operation: ["create"] } },
      options: [
        {
          displayName: "Branch",
          name: "branch",
          type: "string",
          default: "",
          description: "Git branch name for the deploy",
        },
        {
          displayName: "Title",
          name: "title",
          type: "string",
          default: "",
          description: "Title to identify the deploy",
        },
      ],
    },
  ],
};

export const webSearch: INodeTypeDescription = {
  name: "n8n-nodes-base.webSearch",
  displayName: "Web Search",
  category: "Actions",
  group: ["action"],
  version: 1,
  description: "Search the web for information",
  defaults: { name: "Web Search" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Search",
  sources: [],
  properties: [
    {
      displayName: "Query",
      name: "query",
      type: "string",
      default: "",
      required: true,
      description: "The search query text. Accepts expressions.",
    },
    {
      displayName: "Result Limit",
      name: "resultLimit",
      type: "number",
      default: 10,
      description: "Maximum number of search results to return",
    },
    {
      displayName: "Search Engine",
      name: "searchEngine",
      type: "options",
      default: "google",
      options: [
        { name: "Google", value: "google" },
        { name: "Bing", value: "bing" },
        { name: "DuckDuckGo", value: "duckduckgo" },
        { name: "Custom", value: "custom" },
      ],
      description: "Which search provider to use",
    },
    {
      displayName: "Custom Endpoint",
      name: "customEndpoint",
      type: "string",
      default: "",
      displayOptions: { show: { searchEngine: ["custom"] } },
      description: "Base URL for a custom search API (only used when search engine is custom)",
    },
    {
      displayName: "API Key",
      name: "apiKey",
      type: "string",
      default: "",
      typeOptions: { password: true },
      description: "API key for the chosen or custom search provider",
    },
    {
      displayName: "Additional Options",
      name: "additionalOptions",
      type: "json",
      default: "{}",
      description: "Free-form JSON for provider-specific options",
    },
  ],
};

export const philipsHueTool: INodeTypeDescription = {
  name: "n8n-nodes-base.philipsHueTool",
  displayName: "Philips Hue Tool",
  category: "Actions",
  group: ["action"],
  version: 1,
  description: "Control Philips Hue lights via the Hue CLIP API v2 (AI tool variant)",
  defaults: { name: "Philips Hue Tool" },
  inputs: ["main", "ai_tool"],
  outputs: ["main"],
  icon: "Lightbulb",
  credentials: [{ name: "philipsHueOAuth2Api", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.philipshue.md",
    "https://developers.meethue.com/develop/hue-api-v2/api-reference/",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "light",
      required: true,
      noDataExpression: true,
      options: [{ name: "Light", value: "light" }],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Get All", value: "getAll", description: "Retrieve all lights" },
        { name: "Get", value: "get", description: "Retrieve a light" },
        { name: "Delete", value: "delete", description: "Delete a light" },
        { name: "Update", value: "update", description: "Update a light" },
      ],
    },
    {
      displayName: "Light ID",
      name: "lightId",
      type: "string",
      default: "",
      displayOptions: {
        show: { operation: ["get", "delete", "update"] },
      },
      description: "The Hue light resource ID. Required for get/delete/update operations.",
    },
    {
      displayName: "On",
      name: "on",
      type: "boolean",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      description: "Whether the light is on",
    },
    {
      displayName: "Brightness",
      name: "brightness",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      typeOptions: { minValue: 0, maxValue: 100 },
      description: "Brightness value (0–100)",
    },
    {
      displayName: "Hue",
      name: "hue",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      typeOptions: { minValue: 0, maxValue: 360 },
      description: "Hue value in degrees (0–360)",
    },
    {
      displayName: "Saturation",
      name: "saturation",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      typeOptions: { minValue: 0, maxValue: 100 },
      description: "Saturation percentage (0–100)",
    },
    {
      displayName: "Color Temperature",
      name: "colorTemperature",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      description: "Color temperature in mireds",
    },
    {
      displayName: "Transition Time",
      name: "transitionTime",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      description: "Duration in milliseconds for the state transition",
    },
  ],
};

export const salesmateTool: INodeTypeDescription = {
  name: "n8n-nodes-base.salesmateTool",
  displayName: "Salesmate Tool",
  category: "Actions",
  group: ["action"],
  version: 1,
  description: "Interact with Salesmate CRM for activities, companies, and deals",
  defaults: { name: "Salesmate Tool" },
  inputs: ["main", "ai_tool"],
  outputs: ["main"],
  icon: "Package",
  credentials: [{ name: "salesmateApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.salesmate.md",
    "https://docs.n8n.io/integrations/builtin/credentials/salesmate.md",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "deal",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Activity", value: "activity" },
        { name: "Company", value: "company" },
        { name: "Deal", value: "deal" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["activity", "company", "deal"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Title / Name",
      name: "title",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { operation: ["create"] } },
      description: "Activity title (activity/deal) or company name. Accepts expressions.",
    },
    {
      displayName: "Owner",
      name: "owner",
      type: "options",
      default: "",
      displayOptions: { show: { operation: ["create", "update"] } },
      description: "Owner (dynamic user list)",
      options: [],
    },
    {
      displayName: "Type",
      name: "type",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["activity"], operation: ["create"] } },
      description: "Activity type (call, meeting, etc.)",
    },
    {
      displayName: "Raw Data",
      name: "rawData",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["create", "get", "update"] } },
    },
    {
      displayName: "Activity ID",
      name: "activityId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["activity"], operation: ["get", "delete", "update"] } },
      description: "The activity ID — accepts expressions",
    },
    {
      displayName: "Company ID",
      name: "companyId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["company"], operation: ["get", "delete", "update"] } },
      description: "The company ID — accepts expressions",
    },
    {
      displayName: "Deal ID",
      name: "dealId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["deal"], operation: ["get", "delete", "update"] } },
      description: "The deal ID — accepts expressions",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 10,
      typeOptions: { minValue: 1, maxValue: 25 },
      displayOptions: { show: { operation: ["getAll"], returnAll: [false] } },
    },
    {
      displayName: "JSON Parameters",
      name: "jsonParameters",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["getAll"] } },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "json",
      default: "{}",
      displayOptions: { show: { operation: ["getAll"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["getAll"] } },
      options: [
        { displayName: "Fields", name: "fields", type: "string", default: "", description: "Comma-separated fields to return" },
        { displayName: "Sort By", name: "sortBy", type: "string", default: "" },
        { displayName: "Sort Order", name: "sortOrder", type: "options", default: "asc", options: [{ name: "Ascending", value: "asc" }, { name: "Descending", value: "desc" }] },
      ],
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["create"] } },
      options: [
        { displayName: "Description", name: "description", type: "string", default: "" },
        { displayName: "Tags", name: "tags", type: "string", default: "" },
        { displayName: "Website", name: "website", type: "string", default: "" },
        { displayName: "Phone", name: "phone", type: "string", default: "" },
        { displayName: "Email", name: "email", type: "string", default: "" },
        { displayName: "Deal Value", name: "dealValue", type: "number", default: 0 },
        { displayName: "Currency", name: "currency", type: "string", default: "" },
        { displayName: "Expected Close Date", name: "expectedCloseDate", type: "string", default: "" },
        { displayName: "Priority", name: "priority", type: "string", default: "" },
      ],
    },
    {
      displayName: "Update Fields",
      name: "updateFields",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["update"] } },
      options: [
        { displayName: "Title / Name", name: "title", type: "string", default: "" },
        { displayName: "Owner", name: "owner", type: "string", default: "" },
        { displayName: "Description", name: "description", type: "string", default: "" },
        { displayName: "Tags", name: "tags", type: "string", default: "" },
        { displayName: "Website", name: "website", type: "string", default: "" },
        { displayName: "Phone", name: "phone", type: "string", default: "" },
        { displayName: "Email", name: "email", type: "string", default: "" },
        { displayName: "Deal Value", name: "dealValue", type: "number", default: 0 },
        { displayName: "Currency", name: "currency", type: "string", default: "" },
        { displayName: "Expected Close Date", name: "expectedCloseDate", type: "string", default: "" },
        { displayName: "Priority", name: "priority", type: "string", default: "" },
      ],
    },
  ],
};

export const philipsHue: INodeTypeDescription = {
  name: "n8n-nodes-base.philipsHue",
  displayName: "Philips Hue",
  category: "Actions",
  group: ["action"],
  version: 1,
  description: "Control Philips Hue lights via the Hue CLIP API v2",
  defaults: { name: "Philips Hue" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Lightbulb",
  credentials: [{ name: "philipsHueOAuth2Api", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.philipshue.md",
    "https://developers.meethue.com/develop/hue-api-v2/api-reference/",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "light",
      required: true,
      noDataExpression: true,
      options: [{ name: "Light", value: "light" }],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Get All", value: "getAll", description: "Retrieve all lights" },
        { name: "Get", value: "get", description: "Retrieve a light" },
        { name: "Delete", value: "delete", description: "Delete a light" },
        { name: "Update", value: "update", description: "Update a light" },
      ],
    },
    {
      displayName: "Light ID",
      name: "lightId",
      type: "string",
      default: "",
      displayOptions: {
        show: { operation: ["get", "delete", "update"] },
      },
      description: "The Hue light resource ID. Required for get/delete/update operations.",
    },
    {
      displayName: "On",
      name: "on",
      type: "boolean",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      description: "Whether the light is on",
    },
    {
      displayName: "Brightness",
      name: "brightness",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      typeOptions: { minValue: 0, maxValue: 100 },
      description: "Brightness value (0–100)",
    },
    {
      displayName: "Hue",
      name: "hue",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      typeOptions: { minValue: 0, maxValue: 360 },
      description: "Hue value in degrees (0–360)",
    },
    {
      displayName: "Saturation",
      name: "saturation",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      typeOptions: { minValue: 0, maxValue: 100 },
      description: "Saturation percentage (0–100)",
    },
    {
      displayName: "Color Temperature",
      name: "colorTemperature",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      description: "Color temperature in mireds",
    },
    {
      displayName: "Transition Time",
      name: "transitionTime",
      type: "number",
      default: undefined,
      displayOptions: { show: { operation: ["update"] } },
      description: "Duration in milliseconds for the state transition",
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["update"] } },
      options: [
        {
          displayName: "Alert",
          name: "alert",
          type: "options",
          default: "none",
          options: [
            { name: "None", value: "none" },
            { name: "Breathe", value: "breathe" },
          ],
          description: "Alert effect",
        },
      ],
    },
  ],
};
