import type { INodeTypeDescription } from "../types";
import { perplexity } from "./app";

const LANGCHAIN = "https://docs.n8n.io/integrations/builtin/cluster-nodes/";
const SUB_NODES = "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/";

export const agentTool: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.agentTool",
  displayName: "AI Agent Tool",
  category: "AI",
  group: ["ai"],
  version: 3,
  description: "Wrap an agent as a callable tool for multi-agent orchestration",
  defaults: { name: "AI Agent Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Bot",
  sources: [`${SUB_NODES}n8n-nodes-langchain.toolaiagent/`],
  properties: [
    {
      displayName: "Description",
      name: "toolDescription",
      type: "string",
      default: "",
      required: true,
      description: "Description shown to the parent agent for tool selection",
    },
    {
      displayName: "Prompt (User Message)",
      name: "text",
      type: "string",
      default: "",
      required: true,
      description: "The prompt sent to the nested agent when invoked; supports expressions",
    },
    {
      displayName: "Require Specific Output Format",
      name: "hasOutputParser",
      type: "boolean",
      default: false,
      description: "When on, connect an output parser on the ai_outputParser input",
    },
    {
      displayName: "Enable Fallback Model",
      name: "needsFallback",
      type: "boolean",
      default: false,
      description: "When on, connect a fallback chat model on the second ai_languageModel slot",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "System Message",
          name: "systemMessage",
          type: "string",
          default: "",
          description: "System message for the nested agent; supports expressions",
        },
        {
          displayName: "Max Iterations",
          name: "maxIterations",
          type: "number",
          default: 10,
          description: "Maximum number of model runs the nested agent performs",
        },
        {
          displayName: "Return Intermediate Steps",
          name: "returnIntermediateSteps",
          type: "boolean",
          default: false,
          description: "Include intermediate steps in the final output",
        },
        {
          displayName: "Automatically Passthrough Binary Images",
          name: "passthroughBinaryImages",
          type: "boolean",
          default: true,
          description: "Pass binary images to the agent as image-type messages",
        },
        {
          displayName: "Batch Size",
          name: "batchSize",
          type: "number",
          default: 0,
          description: "Number of items to process in parallel",
        },
        {
          displayName: "Delay Between Batches (ms)",
          name: "delayBetweenBatches",
          type: "number",
          default: 0,
          description: "Milliseconds to wait between batches",
        },
      ],
    },
  ],
};

export const toolCode: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.toolCode",
  displayName: "Custom Code Tool",
  category: "AI",
  group: ["ai"],
  version: [1],
  defaultVersion: 1,
  description:
    "Write code that an AI agent can run. The tool input is exposed as `query`; the return value becomes the tool result.",
  defaults: { name: "Custom Code Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Code",
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolcode.md",
  ],
  properties: [
    {
      displayName: "Description",
      name: "description",
      type: "string",
      default: "",
      required: true,
      description:
        "Free-text guidance telling the agent when to invoke the tool. Supports expressions.",
    },
    {
      displayName: "Language",
      name: "language",
      type: "options",
      default: "JavaScript",
      required: true,
      noDataExpression: true,
      options: [
        { name: "JavaScript", value: "JavaScript" },
        { name: "Python", value: "Python" },
      ],
      description: "Language in which the tool body is written",
    },
    {
      displayName: "JavaScript Code",
      name: "jsCode",
      type: "string",
      typeOptions: { editor: "code", rows: 10 },
      default: "",
      displayOptions: { show: { language: ["JavaScript"] } },
      description: "The JS tool body. Receives the model argument as `query`.",
    },
    {
      displayName: "Python Code",
      name: "pyCode",
      type: "string",
      typeOptions: { editor: "code", rows: 10 },
      default: "",
      displayOptions: { show: { language: ["Python"] } },
      description: "The Python tool body. Receives the model argument as `query`.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Continue on Fail",
          name: "continueOnFail",
          type: "boolean",
          default: false,
          description: "When on, tool failures return an error payload instead of aborting",
        },
      ],
    },
  ],
};

export const textClassifier: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.textClassifier",
  displayName: "Text Classifier",
  category: "Actions",
  group: ["output"],
  version: 1,
  description: "Assign categories to incoming text using a language model",
  defaults: { name: "Text Classifier" },
  inputs: ["main"],
  outputs: ["main", "main"],
  icon: "Braces",
  sources: [`${LANGCHAIN}root-nodes/n8n-nodes-langchain.text-classifier/`],
  properties: [
    {
      displayName: "Input Text",
      name: "inputPrompt",
      type: "string",
      default: "={{ $json.text }}",
      required: true,
      description: "The text to classify; supports expressions resolved per item",
    },
    {
      displayName: "Categories",
      name: "categories",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      options: [
        {
          name: "values",
          displayName: "Category",
          values: [
            {
              displayName: "Name",
              name: "name",
              type: "string",
              default: "",
              required: true,
              description: "Category name",
            },
            {
              displayName: "Description",
              name: "description",
              type: "string",
              default: "",
              description: "Optional description explaining the category to the model",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Allow Multiple Classes",
          name: "allowMultipleClasses",
          type: "boolean",
          default: false,
          description: "When on, the model may select several classes for one item",
        },
        {
          displayName: "When No Clear Match",
          name: "whenNoClearMatch",
          type: "options",
          default: "discardItem",
          options: [
            { name: "Discard Item", value: "discardItem" },
            { name: "Output Extra Branch (Other)", value: "outputExtraBranch" },
          ],
          description: "What to do when no category matches",
        },
        {
          displayName: "System Prompt Template",
          name: "systemPromptTemplate",
          type: "string",
          default: "",
          description:
            "Override the system prompt. Use {categories} placeholder for the category list.",
        },
        {
          displayName: "Enable Auto-Fixing",
          name: "enableAutoFixing",
          type: "boolean",
          default: false,
          description:
            "When on, retry by asking the model to fix malformed output up to a bounded number of attempts",
        },
      ],
    },
  ],
};

export const vectorStoreSupabase: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.vectorStoreSupabase",
  displayName: "Supabase Vector Store",
  category: "AI",
  group: ["input"],
  version: [1],
  defaultVersion: 1,
  description:
    "Provides a Supabase-backed vector store for RAG workflows. Supports getMany, insert, retrieve, retrieveAsTool, and update modes. Data is persisted in a Supabase Postgres table with a pgvector column.",
  defaults: { name: "Supabase Vector Store" },
  inputs: ["main", "ai_embedding", "ai_document", "ai_reranker"],
  inputNames: ["Main", "Embedding", "Document", "Reranker"],
  outputs: ["main", "ai_tool", "ai_retriever"],
  outputNames: ["Main", "Tool", "Retriever"],
  icon: "Database",
  credentials: [{ name: "supabaseApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoresupabase.md",
    "https://docs.n8n.io/integrations/builtin/credentials/supabase.md",
  ],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "getMany",
      noDataExpression: true,
      options: [
        { name: "Get Many", value: "getMany" },
        { name: "Insert Documents", value: "insert" },
        { name: "Retrieve Documents (As Vector Store for Chain/Tool)", value: "retrieve" },
        { name: "Retrieve Documents (As Tool for AI Agent)", value: "retrieveAsTool" },
        { name: "Update Documents", value: "update" },
      ],
      description: "Operation mode for the vector store.",
    },
    {
      displayName: "Table Name",
      name: "tableName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { mode: ["getMany", "insert", "retrieve", "retrieveAsTool", "update"] } },
      description: "Name of the Supabase table that stores the documents.",
    },
    {
      displayName: "Prompt",
      name: "prompt",
      type: "string",
      default: "",
      required: true,
      typeOptions: { rows: 4 },
      displayOptions: { show: { mode: ["getMany"] } },
      description: "Search query text. Evaluated per input item via expressions.",
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 10,
      displayOptions: { show: { mode: ["getMany", "retrieveAsTool"] } },
      description: "Maximum number of results to return.",
    },
    {
      displayName: "Document ID",
      name: "id",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { mode: ["update"] } },
      description: "ID of the embedding entry to update.",
    },
    {
      displayName: "Tool Name",
      name: "name",
      type: "string",
      default: "",
      displayOptions: { show: { mode: ["retrieveAsTool"] } },
      description: "Tool name presented to the LLM.",
    },
    {
      displayName: "Tool Description",
      name: "description",
      type: "string",
      default: "",
      displayOptions: { show: { mode: ["retrieveAsTool"] } },
      description: "Tool description used by the LLM to decide when to query the store.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["getMany", "insert", "retrieve", "retrieveAsTool", "update"] } },
      options: [
        {
          displayName: "Query Name",
          name: "queryName",
          type: "string",
          default: "match_documents",
          description: "Name of the Postgres function that performs similarity search.",
        },
        {
          displayName: "Rerank Results",
          name: "rerankResults",
          type: "boolean",
          default: false,
          displayOptions: { show: { mode: ["getMany", "retrieve", "retrieveAsTool"] } },
          description: "When true, requires a reranker sub-node on ai_reranker.",
        },
        {
          displayName: "Metadata Filter",
          name: "metadataFilter",
          type: "fixedCollection",
          default: {},
          typeOptions: { multipleValues: true },
          displayOptions: { show: { mode: ["getMany"] } },
          options: [
            {
              name: "values",
              displayName: "Values",
              values: [
                {
                  displayName: "Field",
                  name: "field",
                  type: "string",
                  default: "",
                  description: "Metadata field name to filter on.",
                },
                {
                  displayName: "Operator",
                  name: "operator",
                  type: "options",
                  default: "eq",
                  options: [
                    { name: "Equal", value: "eq" },
                    { name: "Not Equal", value: "neq" },
                    { name: "Greater Than", value: "gt" },
                    { name: "Greater Than or Equal", value: "gte" },
                    { name: "Less Than", value: "lt" },
                    { name: "Less Than or Equal", value: "lte" },
                    { name: "In", value: "in" },
                    { name: "Not In", value: "nin" },
                  ],
                  description: "Filter operator.",
                },
                {
                  displayName: "Value",
                  name: "value",
                  type: "string",
                  default: "",
                  description: "Filter value; supports expressions.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const vectorStoreQdrant: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.vectorStoreQdrant",
  displayName: "Qdrant Vector Store",
  category: "AI",
  group: ["input"],
  version: [1],
  defaultVersion: 1,
  description:
    "Provides a Qdrant-backed vector store for RAG workflows. Supports load, insert, retrieve, and retrieve-as-tool modes. Data is persisted in a Qdrant collection via the REST API.",
  defaults: { name: "Qdrant Vector Store" },
  inputs: ["main", "ai_embedding", "ai_document", "ai_reranker"],
  inputNames: ["Main", "Embedding", "Document", "Reranker"],
  outputs: ["main", "ai_tool", "ai_retriever"],
  outputNames: ["Main", "Tool", "Retriever"],
  icon: "Database",
  credentials: [{ name: "qdrantApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreqdrant.md",
    "https://docs.n8n.io/integrations/builtin/credentials/qdrant.md",
  ],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "retrieve",
      noDataExpression: true,
      options: [
        { name: "Get Many", value: "load" },
        { name: "Insert Documents", value: "insert" },
        { name: "Retrieve Documents (As Vector Store for Chain/Tool)", value: "retrieve" },
        { name: "Retrieve Documents (As Tool for AI Agent)", value: "retrieve-as-tool" },
      ],
      description: "Operation mode for the vector store.",
    },
    {
      displayName: "Collection Name",
      name: "qdrantCollection",
      type: "resourceLocator",
      default: { mode: "list", value: "" },
      required: true,
      displayOptions: { show: { mode: ["load", "insert", "retrieve", "retrieve-as-tool"] } },
      description: "Target Qdrant collection. Select from the list or enter the collection ID directly.",
    },
    {
      displayName: "Prompt",
      name: "prompt",
      type: "string",
      default: "",
      required: true,
      typeOptions: { rows: 4 },
      displayOptions: { show: { mode: ["load"] } },
      description: "Search query text. Evaluated per input item via expressions.",
    },
    {
      displayName: "Limit",
      name: "topK",
      type: "number",
      default: 10,
      displayOptions: { show: { mode: ["load", "retrieve-as-tool"] } },
      description: "Maximum number of results to return.",
    },
    {
      displayName: "Include Document Metadata",
      name: "includeDocumentMetadata",
      type: "boolean",
      default: false,
      displayOptions: { show: { mode: ["load", "retrieve-as-tool"] } },
      description: "Whether retrieved items carry the stored document metadata alongside the content.",
    },
    {
      displayName: "Tool Name",
      name: "name",
      type: "string",
      default: "qdrant_vector_store",
      displayOptions: { show: { mode: ["retrieve-as-tool"] } },
      description: "Tool name presented to the LLM.",
    },
    {
      displayName: "Tool Description",
      name: "toolDescription",
      type: "string",
      default: "",
      displayOptions: { show: { mode: ["retrieve-as-tool"] } },
      description: "Tool description used by the LLM to decide when to query the store.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["load", "insert", "retrieve", "retrieve-as-tool"] } },
      options: [
        {
          displayName: "Use Reranker",
          name: "useReranker",
          type: "boolean",
          default: false,
          displayOptions: { show: { mode: ["load", "retrieve", "retrieve-as-tool"] } },
          description: "When true, requires a reranker sub-node on ai_reranker.",
        },
        {
          displayName: "Search Filter (JSON)",
          name: "searchFilterJson",
          type: "json",
          default: "",
          displayOptions: { show: { mode: ["load", "retrieve", "retrieve-as-tool"] } },
          description: "Qdrant filter conditions applied to the search using Qdrant filtering syntax.",
        },
        {
          displayName: "Content Payload Key",
          name: "contentPayloadKey",
          type: "string",
          default: "content",
          description: "Qdrant payload key holding the document text.",
        },
        {
          displayName: "Metadata Payload Key",
          name: "metadataPayloadKey",
          type: "string",
          default: "metadata",
          description: "Qdrant payload key holding the document metadata object.",
        },
        {
          displayName: "Collection Config (JSON)",
          name: "collectionConfig",
          type: "json",
          default: "",
          displayOptions: { show: { mode: ["insert"] } },
          description: "JSON options used when creating the target collection if it does not yet exist.",
        },
        {
          displayName: "Embedding Batch Size",
          name: "embeddingBatchSize",
          type: "number",
          default: 50,
          displayOptions: { show: { mode: ["insert"] } },
          description: "Number of documents embedded/upserted per batch.",
        },
      ],
    },
  ],
};

export const toolSerpApi: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.toolSerpApi",
  displayName: "SerpApi (Google Search)",
  category: "AI",
  group: ["ai"],
  version: [1],
  defaultVersion: 1,
  description:
    "Deprecated LangChain tool sub-node that lets an AI agent run a Google web search through the SerpApi service.",
  defaults: { name: "SerpApi (Google Search)" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Search",
  credentials: [{ name: "serpApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolserpapi.md",
    "https://docs.n8n.io/integrations/builtin/credentials/serp.md",
  ],
  properties: [
    {
      displayName: "Query",
      name: "query",
      type: "string",
      default: "",
      required: true,
      description:
        "The Google search query. Supplied by the model when it invokes the tool; may also be a fixed/expression value.",
    },
    {
      displayName: "Country",
      name: "country",
      type: "string",
      default: "",
      description: "Google country code (SerpApi `gl` parameter).",
    },
    {
      displayName: "Language",
      name: "language",
      type: "string",
      default: "",
      description: "Google UI language code (SerpApi `hl` parameter).",
    },
    {
      displayName: "Google Domain",
      name: "googleDomain",
      type: "string",
      default: "google.com",
      description: "Google domain to search against (SerpApi `google_domain` parameter).",
    },
    {
      displayName: "Device",
      name: "device",
      type: "options",
      default: "desktop",
      noDataExpression: true,
      options: [
        { name: "Desktop", value: "desktop" },
        { name: "Mobile", value: "mobile" },
        { name: "Tablet", value: "tablet" },
      ],
      description: "Device used to fetch the search results.",
    },
    {
      displayName: "Explicit Array",
      name: "explicitArray",
      type: "boolean",
      default: false,
      description:
        "When on, forces SerpApi to fetch fresh Google results (no_cache=true). When off, SerpApi may serve a cached result.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Continue on Fail",
          name: "continueOnFail",
          type: "boolean",
          default: false,
          description: "When on, failed tool calls return an error payload instead of aborting",
        },
      ],
    },
  ],
};

const MEMORY_POSTGRES_CHAT_DOCS =
  "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memorypostgreschat.md";

export const toolHttpRequest: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.toolHttpRequest",
  displayName: "HTTP Request Tool",
  category: "AI",
  group: ["ai"],
  version: [1, 1.1],
  defaultVersion: 1.1,
  description:
    "Deprecated LangChain tool sub-node that lets an AI agent make raw HTTP calls (typically GET) to fetch a website or data from an API. Replaced by the standard HTTP Request node in tool mode.",
  defaults: { name: "HTTP Request Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Globe",
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolhttprequest.md",
  ],
  credentials: [
    { name: "httpBasicAuth", required: false },
    { name: "httpDigestAuth", required: false },
    { name: "httpHeaderAuth", required: false },
    { name: "httpQueryAuth", required: false },
    { name: "oAuth1Api", required: false },
    { name: "oAuth2Api", required: false },
  ],
  properties: [
    {
      displayName: "Method",
      name: "method",
      type: "options",
      default: "GET",
      required: true,
      noDataExpression: true,
      options: [
        { name: "GET", value: "GET" },
        { name: "POST", value: "POST" },
        { name: "PUT", value: "PUT" },
        { name: "PATCH", value: "PATCH" },
        { name: "DELETE", value: "DELETE" },
        { name: "HEAD", value: "HEAD" },
        { name: "OPTIONS", value: "OPTIONS" },
      ],
      description: "HTTP method for the request",
    },
    {
      displayName: "URL",
      name: "url",
      type: "string",
      default: "",
      required: true,
      description: "Target endpoint; supports expressions and $fromAI()",
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "none",
      noDataExpression: true,
      options: [
        { name: "None", value: "none" },
        { name: "Predefined Credential", value: "predefinedCredential" },
        { name: "Generic Credential", value: "genericCredential" },
      ],
      description: "Authentication mode",
    },
    {
      displayName: "Send Query Parameters",
      name: "sendQuery",
      type: "boolean",
      default: false,
      description: "Enable URL query parameters",
    },
    {
      displayName: "Query Parameters",
      name: "queryParameters",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { sendQuery: [true] } },
      options: [
        {
          name: "parameters",
          displayName: "Parameters",
          values: [
            {
              displayName: "Name",
              name: "name",
              type: "string",
              default: "",
              description: "Query parameter name",
            },
            {
              displayName: "Value",
              name: "value",
              type: "string",
              default: "",
              description: "Query parameter value; supports expressions",
            },
          ],
        },
      ],
    },
    {
      displayName: "Send Headers",
      name: "sendHeaders",
      type: "boolean",
      default: false,
      description: "Enable custom request headers",
    },
    {
      displayName: "Header Parameters",
      name: "headerParameters",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { sendHeaders: [true] } },
      options: [
        {
          name: "parameters",
          displayName: "Parameters",
          values: [
            {
              displayName: "Name",
              name: "name",
              type: "string",
              default: "",
              description: "Header name",
            },
            {
              displayName: "Value",
              name: "value",
              type: "string",
              default: "",
              description: "Header value; supports expressions",
            },
          ],
        },
      ],
    },
    {
      displayName: "Send Body",
      name: "sendBody",
      type: "boolean",
      default: false,
      description: "Enable a request body",
    },
    {
      displayName: "Body Content Type",
      name: "bodyContentType",
      type: "options",
      default: "json",
      noDataExpression: true,
      displayOptions: { show: { sendBody: [true] } },
      options: [
        { name: "Form URL-Encoded", value: "formUrlencoded" },
        { name: "Form-Data", value: "formData" },
        { name: "JSON", value: "json" },
        { name: "Raw", value: "raw" },
        { name: "Binary Data", value: "binaryData" },
      ],
      description: "Body format",
    },
    {
      displayName: "JSON Body",
      name: "jsonBody",
      type: "json",
      default: "",
      displayOptions: { show: { sendBody: [true], bodyContentType: ["json"] } },
      description: "JSON request body",
    },
    {
      displayName: "Continue on Fail",
      name: "continueOnFail",
      type: "boolean",
      default: false,
      description: "When on, failed tool calls return an error payload instead of throwing",
    },
  ],
};

export const toolVectorStore: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.toolVectorStore",
  displayName: "Vector Store Question Answer Tool",
  category: "AI",
  group: ["ai"],
  version: [1, 1.1],
  defaultVersion: 1.1,
  description:
    "Answer questions about data in a connected vector store. Retrieves relevant chunks and synthesizes an answer with a language model. Outputs a callable tool descriptor on the ai_tool output.",
  defaults: { name: "Vector Store QA Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Database",
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolvectorstore.md",
  ],
  properties: [
    {
      displayName: "Data Name",
      name: "name",
      type: "string",
      default: "",
      displayOptions: { show: { "@version": [1] } },
      description:
        "Short identifier for the data in the vector store (e.g. users_info). Alphanumeric only.",
    },
    {
      displayName: "Description of Data",
      name: "description",
      type: "string",
      default: "",
      required: true,
      description:
        "What the data in the vector store is about. Supports expressions.",
    },
    {
      displayName: "Limit",
      name: "topK",
      type: "number",
      default: 4,
      description:
        "Maximum number of retrieved results fed to the language model per invocation. Supports expressions (sub-node first-item semantics).",
    },
  ],
};

export const embeddingsGoogleGemini: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.embeddingsGoogleGemini",
  displayName: "Embeddings Google Gemini",
  category: "AI",
  group: ["ai"],
  version: 1,
  description:
    "Configures a Google Gemini text-embedding model and supplies it to a root node on the ai_embedding channel.",
  defaults: { name: "Embeddings Google Gemini" },
  inputs: [],
  outputs: ["ai_embedding"],
  icon: "Google",
  credentials: [{ name: "googlePalmApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.embeddingsgooglegemini.md",
    "https://docs.n8n.io/integrations/builtin/credentials/googleai.md",
  ],
  properties: [
    {
      displayName: "Model",
      name: "modelName",
      type: "options",
      default: "models/gemini-embedding-001",
      required: true,
      noDataExpression: false,
      description:
        "The Gemini embedding model to use. Defaults to models/gemini-embedding-001 (768-dimensional embeddings).",
      options: [
        { name: "models/gemini-embedding-001", value: "models/gemini-embedding-001" },
        { name: "models/text-embedding-004", value: "models/text-embedding-004" },
      ],
    },
  ],
};

export const lmChatDeepSeek: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.lmChatDeepSeek",
  displayName: "DeepSeek Chat Model",
  category: "AI",
  group: ["ai"],
  version: [1],
  defaultVersion: 1,
  description: "Configures a DeepSeek-hosted chat model and supplies it to a root node (AI Agent, Basic LLM Chain) on the ai_languageModel channel.",
  defaults: { name: "DeepSeek Chat Model" },
  inputs: [],
  outputs: ["ai_languageModel"],
  icon: "Robot",
  credentials: [{ name: "deepSeekApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatdeepseek.md",
  ],
  properties: [
    {
      displayName: "Model",
      name: "model",
      type: "resourceLocator",
      default: { mode: "list", value: "" },
      required: true,
      description: "The model that generates the completion. Select from the list or enter a Model ID.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Base URL",
          name: "baseUrl",
          type: "string",
          default: "https://api.deepseek.com",
          description: "Override the default API base URL",
        },
        {
          displayName: "Frequency Penalty",
          name: "frequencyPenalty",
          type: "number",
          default: 0,
          description: "Controls the chance of the model repeating itself; higher values reduce repetition",
        },
        {
          displayName: "Maximum Number of Tokens",
          name: "maxTokens",
          type: "number",
          default: 0,
          description: "Sets the maximum completion length. 0 means model default.",
        },
        {
          displayName: "Response Format",
          name: "responseFormat",
          type: "options",
          default: "text",
          options: [
            { name: "Text", value: "text" },
            { name: "JSON", value: "json" },
          ],
          description: "Choose Text or JSON. JSON ensures the model returns valid JSON.",
        },
        {
          displayName: "Presence Penalty",
          name: "presencePenalty",
          type: "number",
          default: 0,
          description: "Controls the chance of the model talking about new topics; higher values increase it",
        },
        {
          displayName: "Sampling Temperature",
          name: "temperature",
          type: "number",
          default: 0,
          description: "Controls randomness of the sampling process; higher = more diverse",
        },
        {
          displayName: "Timeout",
          name: "timeout",
          type: "number",
          default: 120000,
          description: "Maximum request time in milliseconds",
        },
        {
          displayName: "Max Retries",
          name: "maxRetries",
          type: "number",
          default: 3,
          description: "Maximum number of times to retry a request",
        },
        {
          displayName: "Top P",
          name: "topP",
          type: "number",
          default: 0,
          description: "Sets the probability threshold; lower values ignore less probable options",
        },
      ],
    },
  ],
};

export const memoryPostgresChat: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.memoryPostgresChat",
  displayName: "Postgres Chat Memory",
  category: "AI",
  group: ["input"],
  version: 1,
  description:
    "Provides a durable, Postgres-backed conversation-memory handle to an AI Agent on the ai_memory channel, persisting chat history in a Postgres table keyed by session.",
  defaults: { name: "Postgres Chat Memory" },
  inputs: [],
  outputs: ["ai_memory"],
  icon: "Database",
  credentials: [{ name: "postgres", required: true }],
  sources: [MEMORY_POSTGRES_CHAT_DOCS],
  properties: [
    {
      displayName: "Session Key",
      name: "sessionId",
      type: "string",
      default: "",
      placeholder: "my_chat_session",
      description:
        "Key used to store the memory in the workflow data. When blank, the session ID is retrieved from the connected Chat Trigger.",
    },
    {
      displayName: "Table Name",
      name: "tableName",
      type: "string",
      default: "chat_history",
      required: true,
      description: "Name of the Postgres table that stores the chat history. Created if it does not exist.",
    },
    {
      displayName: "Context Window Length",
      name: "contextWindowLength",
      type: "number",
      default: 5,
      description: "Number of previous interactions to consider for context.",
    },
  ],
};

export const perplexityTool: INodeTypeDescription = {
  name: "n8n-nodes-base.perplexityTool",
  displayName: "Perplexity AI Tool",
  category: "AI Tool",
  group: ["output"],
  version: [2],
  defaultVersion: 2,
  description: "Tool-mode Perplexity node for AI-agent canvases. Supports Chat, Agent, Search, and Embedding operations via the Perplexity API.",
  defaults: { name: "Perplexity Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Zap",
  credentials: [{ name: "perplexityApi", required: true }],
  sources: perplexity.sources ?? [],
  properties: perplexity.properties,
};
