import type { INodeTypeDescription } from "../types";
import { perplexity } from "./app";

const LANGCHAIN = "https://docs.n8n.io/integrations/builtin/cluster-nodes/";
const SUB_NODES = "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/";

export const agentTool: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.agentTool",
  displayName: "AI Agent Tool",
  category: "AI",
  group: ["ai"],
  version: 3,
  description: "Wrap an agent as a callable tool for multi-agent orchestration",
  defaults: { name: "AI Agent Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Bot",
  sources: [`${SUB_NODES}n8n-nodes-langchain.toolaiagent/`],
  properties: [
    {
      displayName: "Description",
      name: "toolDescription",
      type: "string",
      default: "",
      required: true,
      description: "Description shown to the parent agent for tool selection",
    },
    {
      displayName: "Prompt (User Message)",
      name: "text",
      type: "string",
      default: "",
      required: true,
      description: "The prompt sent to the nested agent when invoked; supports expressions",
    },
    {
      displayName: "Require Specific Output Format",
      name: "hasOutputParser",
      type: "boolean",
      default: false,
      description: "When on, connect an output parser on the ai_outputParser input",
    },
    {
      displayName: "Enable Fallback Model",
      name: "needsFallback",
      type: "boolean",
      default: false,
      description: "When on, connect a fallback chat model on the second ai_languageModel slot",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "System Message",
          name: "systemMessage",
          type: "string",
          default: "",
          description: "System message for the nested agent; supports expressions",
        },
        {
          displayName: "Max Iterations",
          name: "maxIterations",
          type: "number",
          default: 10,
          description: "Maximum number of model runs the nested agent performs",
        },
        {
          displayName: "Return Intermediate Steps",
          name: "returnIntermediateSteps",
          type: "boolean",
          default: false,
          description: "Include intermediate steps in the final output",
        },
        {
          displayName: "Automatically Passthrough Binary Images",
          name: "passthroughBinaryImages",
          type: "boolean",
          default: true,
          description: "Pass binary images to the agent as image-type messages",
        },
        {
          displayName: "Batch Size",
          name: "batchSize",
          type: "number",
          default: 0,
          description: "Number of items to process in parallel",
        },
        {
          displayName: "Delay Between Batches (ms)",
          name: "delayBetweenBatches",
          type: "number",
          default: 0,
          description: "Milliseconds to wait between batches",
        },
      ],
    },
  ],
};

export const toolCode: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.toolCode",
  displayName: "Custom Code Tool",
  category: "AI",
  group: ["ai"],
  version: [1],
  defaultVersion: 1,
  description:
    "Write code that an AI agent can run. The tool input is exposed as `query`; the return value becomes the tool result.",
  defaults: { name: "Custom Code Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Code",
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolcode.md",
  ],
  properties: [
    {
      displayName: "Description",
      name: "description",
      type: "string",
      default: "",
      required: true,
      description:
        "Free-text guidance telling the agent when to invoke the tool. Supports expressions.",
    },
    {
      displayName: "Language",
      name: "language",
      type: "options",
      default: "JavaScript",
      required: true,
      noDataExpression: true,
      options: [
        { name: "JavaScript", value: "JavaScript" },
        { name: "Python", value: "Python" },
      ],
      description: "Language in which the tool body is written",
    },
    {
      displayName: "JavaScript Code",
      name: "jsCode",
      type: "string",
      typeOptions: { editor: "code", rows: 10 },
      default: "",
      displayOptions: { show: { language: ["JavaScript"] } },
      description: "The JS tool body. Receives the model argument as `query`.",
    },
    {
      displayName: "Python Code",
      name: "pyCode",
      type: "string",
      typeOptions: { editor: "code", rows: 10 },
      default: "",
      displayOptions: { show: { language: ["Python"] } },
      description: "The Python tool body. Receives the model argument as `query`.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Continue on Fail",
          name: "continueOnFail",
          type: "boolean",
          default: false,
          description: "When on, tool failures return an error payload instead of aborting",
        },
      ],
    },
  ],
};

export const textClassifier: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.textClassifier",
  displayName: "Text Classifier",
  category: "Actions",
  group: ["output"],
  version: 1,
  description: "Assign categories to incoming text using a language model",
  defaults: { name: "Text Classifier" },
  inputs: ["main"],
  outputs: ["main", "main"],
  icon: "Braces",
  sources: [`${LANGCHAIN}root-nodes/n8n-nodes-langchain.text-classifier/`],
  properties: [
    {
      displayName: "Input Text",
      name: "inputPrompt",
      type: "string",
      default: "={{ $json.text }}",
      required: true,
      description: "The text to classify; supports expressions resolved per item",
    },
    {
      displayName: "Categories",
      name: "categories",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      options: [
        {
          name: "values",
          displayName: "Category",
          values: [
            {
              displayName: "Name",
              name: "name",
              type: "string",
              default: "",
              required: true,
              description: "Category name",
            },
            {
              displayName: "Description",
              name: "description",
              type: "string",
              default: "",
              description: "Optional description explaining the category to the model",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Allow Multiple Classes",
          name: "allowMultipleClasses",
          type: "boolean",
          default: false,
          description: "When on, the model may select several classes for one item",
        },
        {
          displayName: "When No Clear Match",
          name: "whenNoClearMatch",
          type: "options",
          default: "discardItem",
          options: [
            { name: "Discard Item", value: "discardItem" },
            { name: "Output Extra Branch (Other)", value: "outputExtraBranch" },
          ],
          description: "What to do when no category matches",
        },
        {
          displayName: "System Prompt Template",
          name: "systemPromptTemplate",
          type: "string",
          default: "",
          description:
            "Override the system prompt. Use {categories} placeholder for the category list.",
        },
        {
          displayName: "Enable Auto-Fixing",
          name: "enableAutoFixing",
          type: "boolean",
          default: false,
          description:
            "When on, retry by asking the model to fix malformed output up to a bounded number of attempts",
        },
      ],
    },
  ],
};

export const vectorStoreSupabase: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.vectorStoreSupabase",
  displayName: "Supabase Vector Store",
  category: "AI",
  group: ["input"],
  version: [1],
  defaultVersion: 1,
  description:
    "Provides a Supabase-backed vector store for RAG workflows. Supports getMany, insert, retrieve, retrieveAsTool, and update modes. Data is persisted in a Supabase Postgres table with a pgvector column.",
  defaults: { name: "Supabase Vector Store" },
  inputs: ["main", "ai_embedding", "ai_document", "ai_reranker"],
  inputNames: ["Main", "Embedding", "Document", "Reranker"],
  outputs: ["main", "ai_tool", "ai_retriever"],
  outputNames: ["Main", "Tool", "Retriever"],
  icon: "Database",
  credentials: [{ name: "supabaseApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoresupabase.md",
    "https://docs.n8n.io/integrations/builtin/credentials/supabase.md",
  ],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "getMany",
      noDataExpression: true,
      options: [
        { name: "Get Many", value: "getMany" },
        { name: "Insert Documents", value: "insert" },
        { name: "Retrieve Documents (As Vector Store for Chain/Tool)", value: "retrieve" },
        { name: "Retrieve Documents (As Tool for AI Agent)", value: "retrieveAsTool" },
        { name: "Update Documents", value: "update" },
      ],
      description: "Operation mode for the vector store.",
    },
    {
      displayName: "Table Name",
      name: "tableName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { mode: ["getMany", "insert", "retrieve", "retrieveAsTool", "update"] } },
      description: "Name of the Supabase table that stores the documents.",
    },
    {
      displayName: "Prompt",
      name: "prompt",
      type: "string",
      default: "",
      required: true,
      typeOptions: { rows: 4 },
      displayOptions: { show: { mode: ["getMany"] } },
      description: "Search query text. Evaluated per input item via expressions.",
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 10,
      displayOptions: { show: { mode: ["getMany", "retrieveAsTool"] } },
      description: "Maximum number of results to return.",
    },
    {
      displayName: "Document ID",
      name: "id",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { mode: ["update"] } },
      description: "ID of the embedding entry to update.",
    },
    {
      displayName: "Tool Name",
      name: "name",
      type: "string",
      default: "",
      displayOptions: { show: { mode: ["retrieveAsTool"] } },
      description: "Tool name presented to the LLM.",
    },
    {
      displayName: "Tool Description",
      name: "description",
      type: "string",
      default: "",
      displayOptions: { show: { mode: ["retrieveAsTool"] } },
      description: "Tool description used by the LLM to decide when to query the store.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["getMany", "insert", "retrieve", "retrieveAsTool", "update"] } },
      options: [
        {
          displayName: "Query Name",
          name: "queryName",
          type: "string",
          default: "match_documents",
          description: "Name of the Postgres function that performs similarity search.",
        },
        {
          displayName: "Rerank Results",
          name: "rerankResults",
          type: "boolean",
          default: false,
          displayOptions: { show: { mode: ["getMany", "retrieve", "retrieveAsTool"] } },
          description: "When true, requires a reranker sub-node on ai_reranker.",
        },
        {
          displayName: "Metadata Filter",
          name: "metadataFilter",
          type: "fixedCollection",
          default: {},
          typeOptions: { multipleValues: true },
          displayOptions: { show: { mode: ["getMany"] } },
          options: [
            {
              name: "values",
              displayName: "Values",
              values: [
                {
                  displayName: "Field",
                  name: "field",
                  type: "string",
                  default: "",
                  description: "Metadata field name to filter on.",
                },
                {
                  displayName: "Operator",
                  name: "operator",
                  type: "options",
                  default: "eq",
                  options: [
                    { name: "Equal", value: "eq" },
                    { name: "Not Equal", value: "neq" },
                    { name: "Greater Than", value: "gt" },
                    { name: "Greater Than or Equal", value: "gte" },
                    { name: "Less Than", value: "lt" },
                    { name: "Less Than or Equal", value: "lte" },
                    { name: "In", value: "in" },
                    { name: "Not In", value: "nin" },
                  ],
                  description: "Filter operator.",
                },
                {
                  displayName: "Value",
                  name: "value",
                  type: "string",
                  default: "",
                  description: "Filter value; supports expressions.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const vectorStoreQdrant: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.vectorStoreQdrant",
  displayName: "Qdrant Vector Store",
  category: "AI",
  group: ["input"],
  version: [1],
  defaultVersion: 1,
  description:
    "Provides a Qdrant-backed vector store for RAG workflows. Supports load, insert, retrieve, and retrieve-as-tool modes. Data is persisted in a Qdrant collection via the REST API.",
  defaults: { name: "Qdrant Vector Store" },
  inputs: ["main", "ai_embedding", "ai_document", "ai_reranker"],
  inputNames: ["Main", "Embedding", "Document", "Reranker"],
  outputs: ["main", "ai_tool", "ai_retriever"],
  outputNames: ["Main", "Tool", "Retriever"],
  icon: "Database",
  credentials: [{ name: "qdrantApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstoreqdrant.md",
    "https://docs.n8n.io/integrations/builtin/credentials/qdrant.md",
  ],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "retrieve",
      noDataExpression: true,
      options: [
        { name: "Get Many", value: "load" },
        { name: "Insert Documents", value: "insert" },
        { name: "Retrieve Documents (As Vector Store for Chain/Tool)", value: "retrieve" },
        { name: "Retrieve Documents (As Tool for AI Agent)", value: "retrieve-as-tool" },
      ],
      description: "Operation mode for the vector store.",
    },
    {
      displayName: "Collection Name",
      name: "qdrantCollection",
      type: "resourceLocator",
      default: { mode: "list", value: "" },
      required: true,
      displayOptions: { show: { mode: ["load", "insert", "retrieve", "retrieve-as-tool"] } },
      description: "Target Qdrant collection. Select from the list or enter the collection ID directly.",
    },
    {
      displayName: "Prompt",
      name: "prompt",
      type: "string",
      default: "",
      required: true,
      typeOptions: { rows: 4 },
      displayOptions: { show: { mode: ["load"] } },
      description: "Search query text. Evaluated per input item via expressions.",
    },
    {
      displayName: "Limit",
      name: "topK",
      type: "number",
      default: 10,
      displayOptions: { show: { mode: ["load", "retrieve-as-tool"] } },
      description: "Maximum number of results to return.",
    },
    {
      displayName: "Include Document Metadata",
      name: "includeDocumentMetadata",
      type: "boolean",
      default: false,
      displayOptions: { show: { mode: ["load", "retrieve-as-tool"] } },
      description: "Whether retrieved items carry the stored document metadata alongside the content.",
    },
    {
      displayName: "Tool Name",
      name: "name",
      type: "string",
      default: "qdrant_vector_store",
      displayOptions: { show: { mode: ["retrieve-as-tool"] } },
      description: "Tool name presented to the LLM.",
    },
    {
      displayName: "Tool Description",
      name: "toolDescription",
      type: "string",
      default: "",
      displayOptions: { show: { mode: ["retrieve-as-tool"] } },
      description: "Tool description used by the LLM to decide when to query the store.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["load", "insert", "retrieve", "retrieve-as-tool"] } },
      options: [
        {
          displayName: "Use Reranker",
          name: "useReranker",
          type: "boolean",
          default: false,
          displayOptions: { show: { mode: ["load", "retrieve", "retrieve-as-tool"] } },
          description: "When true, requires a reranker sub-node on ai_reranker.",
        },
        {
          displayName: "Search Filter (JSON)",
          name: "searchFilterJson",
          type: "json",
          default: "",
          displayOptions: { show: { mode: ["load", "retrieve", "retrieve-as-tool"] } },
          description: "Qdrant filter conditions applied to the search using Qdrant filtering syntax.",
        },
        {
          displayName: "Content Payload Key",
          name: "contentPayloadKey",
          type: "string",
          default: "content",
          description: "Qdrant payload key holding the document text.",
        },
        {
          displayName: "Metadata Payload Key",
          name: "metadataPayloadKey",
          type: "string",
          default: "metadata",
          description: "Qdrant payload key holding the document metadata object.",
        },
        {
          displayName: "Collection Config (JSON)",
          name: "collectionConfig",
          type: "json",
          default: "",
          displayOptions: { show: { mode: ["insert"] } },
          description: "JSON options used when creating the target collection if it does not yet exist.",
        },
        {
          displayName: "Embedding Batch Size",
          name: "embeddingBatchSize",
          type: "number",
          default: 50,
          displayOptions: { show: { mode: ["insert"] } },
          description: "Number of documents embedded/upserted per batch.",
        },
      ],
    },
  ],
};

export const toolSerpApi: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.toolSerpApi",
  displayName: "SerpApi (Google Search)",
  category: "AI",
  group: ["ai"],
  version: [1],
  defaultVersion: 1,
  description:
    "Deprecated LangChain tool sub-node that lets an AI agent run a Google web search through the SerpApi service.",
  defaults: { name: "SerpApi (Google Search)" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Search",
  credentials: [{ name: "serpApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolserpapi.md",
    "https://docs.n8n.io/integrations/builtin/credentials/serp.md",
  ],
  properties: [
    {
      displayName: "Query",
      name: "query",
      type: "string",
      default: "",
      required: true,
      description:
        "The Google search query. Supplied by the model when it invokes the tool; may also be a fixed/expression value.",
    },
    {
      displayName: "Country",
      name: "country",
      type: "string",
      default: "",
      description: "Google country code (SerpApi `gl` parameter).",
    },
    {
      displayName: "Language",
      name: "language",
      type: "string",
      default: "",
      description: "Google UI language code (SerpApi `hl` parameter).",
    },
    {
      displayName: "Google Domain",
      name: "googleDomain",
      type: "string",
      default: "google.com",
      description: "Google domain to search against (SerpApi `google_domain` parameter).",
    },
    {
      displayName: "Device",
      name: "device",
      type: "options",
      default: "desktop",
      noDataExpression: true,
      options: [
        { name: "Desktop", value: "desktop" },
        { name: "Mobile", value: "mobile" },
        { name: "Tablet", value: "tablet" },
      ],
      description: "Device used to fetch the search results.",
    },
    {
      displayName: "Explicit Array",
      name: "explicitArray",
      type: "boolean",
      default: false,
      description:
        "When on, forces SerpApi to fetch fresh Google results (no_cache=true). When off, SerpApi may serve a cached result.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Continue on Fail",
          name: "continueOnFail",
          type: "boolean",
          default: false,
          description: "When on, failed tool calls return an error payload instead of aborting",
        },
      ],
    },
  ],
};

const MEMORY_POSTGRES_CHAT_DOCS =
  "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memorypostgreschat.md";

export const toolHttpRequest: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.toolHttpRequest",
  displayName: "HTTP Request Tool",
  category: "AI",
  group: ["ai"],
  version: [1, 1.1],
  defaultVersion: 1.1,
  description:
    "Deprecated LangChain tool sub-node that lets an AI agent make raw HTTP calls (typically GET) to fetch a website or data from an API. Replaced by the standard HTTP Request node in tool mode.",
  defaults: { name: "HTTP Request Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Globe",
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolhttprequest.md",
  ],
  credentials: [
    { name: "httpBasicAuth", required: false },
    { name: "httpDigestAuth", required: false },
    { name: "httpHeaderAuth", required: false },
    { name: "httpQueryAuth", required: false },
    { name: "oAuth1Api", required: false },
    { name: "oAuth2Api", required: false },
  ],
  properties: [
    {
      displayName: "Method",
      name: "method",
      type: "options",
      default: "GET",
      required: true,
      noDataExpression: true,
      options: [
        { name: "GET", value: "GET" },
        { name: "POST", value: "POST" },
        { name: "PUT", value: "PUT" },
        { name: "PATCH", value: "PATCH" },
        { name: "DELETE", value: "DELETE" },
        { name: "HEAD", value: "HEAD" },
        { name: "OPTIONS", value: "OPTIONS" },
      ],
      description: "HTTP method for the request",
    },
    {
      displayName: "URL",
      name: "url",
      type: "string",
      default: "",
      required: true,
      description: "Target endpoint; supports expressions and $fromAI()",
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "none",
      noDataExpression: true,
      options: [
        { name: "None", value: "none" },
        { name: "Predefined Credential", value: "predefinedCredential" },
        { name: "Generic Credential", value: "genericCredential" },
      ],
      description: "Authentication mode",
    },
    {
      displayName: "Send Query Parameters",
      name: "sendQuery",
      type: "boolean",
      default: false,
      description: "Enable URL query parameters",
    },
    {
      displayName: "Query Parameters",
      name: "queryParameters",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { sendQuery: [true] } },
      options: [
        {
          name: "parameters",
          displayName: "Parameters",
          values: [
            {
              displayName: "Name",
              name: "name",
              type: "string",
              default: "",
              description: "Query parameter name",
            },
            {
              displayName: "Value",
              name: "value",
              type: "string",
              default: "",
              description: "Query parameter value; supports expressions",
            },
          ],
        },
      ],
    },
    {
      displayName: "Send Headers",
      name: "sendHeaders",
      type: "boolean",
      default: false,
      description: "Enable custom request headers",
    },
    {
      displayName: "Header Parameters",
      name: "headerParameters",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { sendHeaders: [true] } },
      options: [
        {
          name: "parameters",
          displayName: "Parameters",
          values: [
            {
              displayName: "Name",
              name: "name",
              type: "string",
              default: "",
              description: "Header name",
            },
            {
              displayName: "Value",
              name: "value",
              type: "string",
              default: "",
              description: "Header value; supports expressions",
            },
          ],
        },
      ],
    },
    {
      displayName: "Send Body",
      name: "sendBody",
      type: "boolean",
      default: false,
      description: "Enable a request body",
    },
    {
      displayName: "Body Content Type",
      name: "bodyContentType",
      type: "options",
      default: "json",
      noDataExpression: true,
      displayOptions: { show: { sendBody: [true] } },
      options: [
        { name: "Form URL-Encoded", value: "formUrlencoded" },
        { name: "Form-Data", value: "formData" },
        { name: "JSON", value: "json" },
        { name: "Raw", value: "raw" },
        { name: "Binary Data", value: "binaryData" },
      ],
      description: "Body format",
    },
    {
      displayName: "JSON Body",
      name: "jsonBody",
      type: "json",
      default: "",
      displayOptions: { show: { sendBody: [true], bodyContentType: ["json"] } },
      description: "JSON request body",
    },
    {
      displayName: "Continue on Fail",
      name: "continueOnFail",
      type: "boolean",
      default: false,
      description: "When on, failed tool calls return an error payload instead of throwing",
    },
  ],
};

export const toolVectorStore: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.toolVectorStore",
  displayName: "Vector Store Question Answer Tool",
  category: "AI",
  group: ["ai"],
  version: [1, 1.1],
  defaultVersion: 1.1,
  description:
    "Answer questions about data in a connected vector store. Retrieves relevant chunks and synthesizes an answer with a language model. Outputs a callable tool descriptor on the ai_tool output.",
  defaults: { name: "Vector Store QA Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Database",
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolvectorstore.md",
  ],
  properties: [
    {
      displayName: "Data Name",
      name: "name",
      type: "string",
      default: "",
      displayOptions: { show: { "@version": [1] } },
      description:
        "Short identifier for the data in the vector store (e.g. users_info). Alphanumeric only.",
    },
    {
      displayName: "Description of Data",
      name: "description",
      type: "string",
      default: "",
      required: true,
      description:
        "What the data in the vector store is about. Supports expressions.",
    },
    {
      displayName: "Limit",
      name: "topK",
      type: "number",
      default: 4,
      description:
        "Maximum number of retrieved results fed to the language model per invocation. Supports expressions (sub-node first-item semantics).",
    },
  ],
};

export const embeddingsGoogleGemini: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.embeddingsGoogleGemini",
  displayName: "Embeddings Google Gemini",
  category: "AI",
  group: ["ai"],
  version: 1,
  description:
    "Configures a Google Gemini text-embedding model and supplies it to a root node on the ai_embedding channel.",
  defaults: { name: "Embeddings Google Gemini" },
  inputs: [],
  outputs: ["ai_embedding"],
  icon: "Google",
  credentials: [{ name: "googlePalmApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.embeddingsgooglegemini.md",
    "https://docs.n8n.io/integrations/builtin/credentials/googleai.md",
  ],
  properties: [
    {
      displayName: "Model",
      name: "modelName",
      type: "options",
      default: "models/gemini-embedding-001",
      required: true,
      noDataExpression: false,
      description:
        "The Gemini embedding model to use. Defaults to models/gemini-embedding-001 (768-dimensional embeddings).",
      options: [
        { name: "models/gemini-embedding-001", value: "models/gemini-embedding-001" },
        { name: "models/text-embedding-004", value: "models/text-embedding-004" },
      ],
    },
  ],
};

export const lmChatDeepSeek: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.lmChatDeepSeek",
  displayName: "DeepSeek Chat Model",
  category: "AI",
  group: ["ai"],
  version: [1],
  defaultVersion: 1,
  description: "Configures a DeepSeek-hosted chat model and supplies it to a root node (AI Agent, Basic LLM Chain) on the ai_languageModel channel.",
  defaults: { name: "DeepSeek Chat Model" },
  inputs: [],
  outputs: ["ai_languageModel"],
  icon: "Robot",
  credentials: [{ name: "deepSeekApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatdeepseek.md",
  ],
  properties: [
    {
      displayName: "Model",
      name: "model",
      type: "resourceLocator",
      default: { mode: "list", value: "" },
      required: true,
      description: "The model that generates the completion. Select from the list or enter a Model ID.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Base URL",
          name: "baseUrl",
          type: "string",
          default: "https://api.deepseek.com",
          description: "Override the default API base URL",
        },
        {
          displayName: "Frequency Penalty",
          name: "frequencyPenalty",
          type: "number",
          default: 0,
          description: "Controls the chance of the model repeating itself; higher values reduce repetition",
        },
        {
          displayName: "Maximum Number of Tokens",
          name: "maxTokens",
          type: "number",
          default: 0,
          description: "Sets the maximum completion length. 0 means model default.",
        },
        {
          displayName: "Response Format",
          name: "responseFormat",
          type: "options",
          default: "text",
          options: [
            { name: "Text", value: "text" },
            { name: "JSON", value: "json" },
          ],
          description: "Choose Text or JSON. JSON ensures the model returns valid JSON.",
        },
        {
          displayName: "Presence Penalty",
          name: "presencePenalty",
          type: "number",
          default: 0,
          description: "Controls the chance of the model talking about new topics; higher values increase it",
        },
        {
          displayName: "Sampling Temperature",
          name: "temperature",
          type: "number",
          default: 0,
          description: "Controls randomness of the sampling process; higher = more diverse",
        },
        {
          displayName: "Timeout",
          name: "timeout",
          type: "number",
          default: 120000,
          description: "Maximum request time in milliseconds",
        },
        {
          displayName: "Max Retries",
          name: "maxRetries",
          type: "number",
          default: 3,
          description: "Maximum number of times to retry a request",
        },
        {
          displayName: "Top P",
          name: "topP",
          type: "number",
          default: 0,
          description: "Sets the probability threshold; lower values ignore less probable options",
        },
      ],
    },
  ],
};

export const anthropic: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.anthropic",
  displayName: "Anthropic",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Provides access to the Anthropic API — send model messages, analyze documents and images, upload files, and generate/improve prompts.",
  defaults: { name: "Anthropic" },
  inputs: ["main", "ai_tool"],
  inputNames: ["Main", "Tool"],
  outputs: ["main"],
  icon: "Bot",
  credentials: [{ name: "anthropicApi", required: true }],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "text",
      noDataExpression: true,
      options: [
        { name: "Document", value: "document" },
        { name: "File", value: "file" },
        { name: "Image", value: "image" },
        { name: "Prompt", value: "prompt" },
        { name: "Text", value: "text" },
      ],
      description: "High-level capability group",
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "message",
      noDataExpression: true,
      displayOptions: { show: { resource: ["text"] } },
      options: [
        { name: "Message a Model", value: "message" },
      ],
      description: "Specific action within the resource",
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "analyze",
      noDataExpression: true,
      displayOptions: { show: { resource: ["document"] } },
      options: [
        { name: "Analyze Document", value: "analyze" },
      ],
      description: "Specific action within the resource",
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "analyze",
      noDataExpression: true,
      displayOptions: { show: { resource: ["image"] } },
      options: [
        { name: "Analyze Image", value: "analyze" },
      ],
      description: "Specific action within the resource",
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "upload",
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Upload File", value: "upload" },
        { name: "Get File Metadata", value: "getMetadata" },
        { name: "List Files", value: "list" },
        { name: "Delete File", value: "delete" },
      ],
      description: "Specific action within the resource",
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "generate",
      noDataExpression: true,
      displayOptions: { show: { resource: ["prompt"] } },
      options: [
        { name: "Generate Prompt", value: "generate" },
        { name: "Improve Prompt", value: "improve" },
        { name: "Templatize Prompt", value: "templatize" },
      ],
      description: "Specific action within the resource",
    },
    {
      displayName: "Model",
      name: "modelId",
      type: "resourceLocator",
      default: { mode: "list", value: "" },
      required: true,
      displayOptions: {
        show: { resource: ["text", "document", "image"] },
      },
      description: "Anthropic model identifier (e.g. claude-sonnet-4-6). Supports dynamic list from API and manual entry.",
    },
    {
      displayName: "Simplify Output",
      name: "simplify",
      type: "boolean",
      default: true,
      description: "Return simplified response shape vs. raw API payload",
    },
    {
      displayName: "Text",
      name: "text",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["document", "image"] } },
      description: "Question or instruction about the document(s) or image(s)",
    },
    {
      displayName: "Input Type",
      name: "inputType",
      type: "options",
      default: "url",
      noDataExpression: true,
      displayOptions: { show: { resource: ["document", "image"], operation: ["analyze"] } },
      options: [
        { name: "URL", value: "url" },
        { name: "Binary", value: "binary" },
      ],
      description: "Source of the content",
    },
    {
      displayName: "Document URLs",
      name: "documentUrls",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["document"], inputType: ["url"] } },
      description: "Document URL(s) to analyze (comma-separated)",
    },
    {
      displayName: "Image URLs",
      name: "imageUrls",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["image"], inputType: ["url"] } },
      description: "Image URL(s) to analyze (comma-separated)",
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["document", "image", "file"], inputType: ["binary"] } },
      description: "Binary data field name(s) containing the content",
    },
    {
      displayName: "Input Type",
      name: "inputType",
      type: "options",
      default: "url",
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
      options: [
        { name: "URL", value: "url" },
        { name: "Binary", value: "binary" },
      ],
      description: "Source of file content",
    },
    {
      displayName: "File URL",
      name: "fileUrl",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["upload"], inputType: ["url"] } },
      description: "URL of file to upload",
    },
    {
      displayName: "File ID",
      name: "fileId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["getMetadata", "delete"] } },
      description: "Anthropic file identifier (e.g. file_123)",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["file"], operation: ["list"] } },
      description: "Return all files (paginated) vs. single page",
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      typeOptions: { minValue: 1, maxValue: 1000 },
      displayOptions: { show: { resource: ["file"], operation: ["list"] } },
      description: "Max results per page",
    },
    {
      displayName: "Messages",
      name: "messages",
      type: "fixedCollection",
      default: { values: [{ content: "", role: "user" }] },
      typeOptions: { multipleValues: true },
      displayOptions: { show: { resource: ["text"], operation: ["message"] } },
      options: [
        {
          name: "values",
          displayName: "Message",
          values: [
            {
              displayName: "Role",
              name: "role",
              type: "options",
              default: "user",
              options: [
                { name: "User", value: "user" },
                { name: "Assistant", value: "assistant" },
              ],
              description: "Role of the message author",
            },
            {
              displayName: "Content",
              name: "content",
              type: "string",
              default: "",
              description: "Message content; supports expressions",
            },
          ],
        },
      ],
      description: "Conversation history; each item has content and role",
    },
    {
      displayName: "Task",
      name: "task",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["prompt"], operation: ["generate"] } },
      description: "Natural-language description of the prompt's purpose",
    },
    {
      displayName: "Messages",
      name: "messages",
      type: "fixedCollection",
      default: { values: [{ content: "", role: "user" }] },
      typeOptions: { multipleValues: true },
      displayOptions: { show: { resource: ["prompt"], operation: ["improve", "templatize"] } },
      options: [
        {
          name: "values",
          displayName: "Message",
          values: [
            {
              displayName: "Role",
              name: "role",
              type: "options",
              default: "user",
              options: [
                { name: "User", value: "user" },
                { name: "Assistant", value: "assistant" },
              ],
              description: "Role of the message author",
            },
            {
              displayName: "Content",
              name: "content",
              type: "string",
              default: "",
              description: "Message content; supports expressions",
            },
          ],
        },
      ],
      description: "Conversation messages forming the prompt",
    },
    {
      displayName: "Add Attachments",
      name: "addAttachments",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["text"], operation: ["message"] } },
      description: "Include file attachments with the message",
    },
    {
      displayName: "Attachments Input Type",
      name: "attachmentsInputType",
      type: "options",
      default: "url",
      noDataExpression: true,
      displayOptions: { show: { resource: ["text"], operation: ["message"], addAttachments: [true] } },
      options: [
        { name: "URL", value: "url" },
        { name: "Binary", value: "binary" },
      ],
      description: "Attachment source type",
    },
    {
      displayName: "Attachment URLs",
      name: "attachmentsUrls",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["text"], operation: ["message"], addAttachments: [true], attachmentsInputType: ["url"] } },
      description: "Attachment URL(s) (comma-separated)",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "System",
          name: "system",
          type: "string",
          default: "",
          description: "System prompt to prime the model",
        },
        {
          displayName: "Max Tokens",
          name: "maxTokens",
          type: "number",
          default: 1024,
          description: "Maximum tokens for the response",
        },
        {
          displayName: "Temperature",
          name: "temperature",
          type: "number",
          default: 1,
          typeOptions: { minValue: 0, maxValue: 1, numberPrecision: 2 },
          description: "Sampling temperature",
        },
        {
          displayName: "Top P",
          name: "topP",
          type: "number",
          default: 0.7,
          typeOptions: { minValue: 0, maxValue: 1, numberPrecision: 2 },
          description: "Nucleus sampling threshold",
        },
        {
          displayName: "Top K",
          name: "topK",
          type: "number",
          default: 5,
          description: "Top-k sampling limit",
        },
        {
          displayName: "Include Merged Response",
          name: "includeMergedResponse",
          type: "boolean",
          default: false,
          description: "Include concatenated text in output",
        },
        {
          displayName: "Code Execution",
          name: "codeExecution",
          type: "boolean",
          default: false,
          description: "Enable code execution tool (model-dependent)",
        },
        {
          displayName: "Web Search",
          name: "webSearch",
          type: "boolean",
          default: false,
          description: "Enable web search tool",
        },
        {
          displayName: "Max Uses",
          name: "maxUses",
          type: "number",
          default: 5,
          displayOptions: { show: { webSearch: [true] } },
          description: "Max web search calls per request",
        },
        {
          displayName: "Allowed Domains",
          name: "allowedDomains",
          type: "string",
          default: "",
          displayOptions: { show: { webSearch: [true] } },
          description: "Restrict search to these domains (comma-separated)",
        },
        {
          displayName: "Blocked Domains",
          name: "blockedDomains",
          type: "string",
          default: "",
          displayOptions: { show: { webSearch: [true] } },
          description: "Exclude these domains from search (comma-separated)",
        },
        {
          displayName: "Max Tool Iterations",
          name: "maxToolsIterations",
          type: "number",
          default: 15,
          description: "Max tool-use iteration cycles (0 = unlimited)",
        },
        {
          displayName: "File Name",
          name: "fileName",
          type: "string",
          default: "",
          displayOptions: { show: { "/resource": ["file"], "/operation": ["upload"] } },
          description: "Custom filename for uploaded file",
        },
      ],
    },
  ],
};

export const rerankerCohere: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.rerankerCohere",
  displayName: "Reranker Cohere",
  category: "AI",
  group: ["transform"],
  version: 1,
  description:
    "Configures a Cohere reranking model and supplies it to a root node (Vector Store Retriever, Question and Answer Chain, etc.) on the ai_reranker channel.",
  defaults: { name: "Reranker Cohere" },
  inputs: [],
  outputs: ["ai_reranker"],
  icon: "Cohere",
  credentials: [{ name: "cohereApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.rerankercohere.md",
    "https://docs.n8n.io/integrations/builtin/credentials/cohere.md",
  ],
  properties: [
    {
      displayName: "Model",
      name: "modelName",
      type: "options",
      default: "rerank-v3.5",
      required: true,
      noDataExpression: false,
      options: [
        { name: "Rerank v3.5", value: "rerank-v3.5" },
        { name: "Rerank English v3.0", value: "rerank-english-v3.0" },
        { name: "Rerank Multilingual v3.0", value: "rerank-multilingual-v3.0" },
      ],
      description: "The Cohere reranking model to use.",
    },
    {
      displayName: "Top N",
      name: "topN",
      type: "number",
      default: 3,
      description: "Maximum number of documents to return after reranking. Supports expressions.",
    },
  ],
};

export const memoryPostgresChat: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.memoryPostgresChat",
  displayName: "Postgres Chat Memory",
  category: "AI",
  group: ["input"],
  version: 1,
  description:
    "Provides a durable, Postgres-backed conversation-memory handle to an AI Agent on the ai_memory channel, persisting chat history in a Postgres table keyed by session.",
  defaults: { name: "Postgres Chat Memory" },
  inputs: [],
  outputs: ["ai_memory"],
  icon: "Database",
  credentials: [{ name: "postgres", required: true }],
  sources: [MEMORY_POSTGRES_CHAT_DOCS],
  properties: [
    {
      displayName: "Session Key",
      name: "sessionId",
      type: "string",
      default: "",
      placeholder: "my_chat_session",
      description:
        "Key used to store the memory in the workflow data. When blank, the session ID is retrieved from the connected Chat Trigger.",
    },
    {
      displayName: "Table Name",
      name: "tableName",
      type: "string",
      default: "chat_history",
      required: true,
      description: "Name of the Postgres table that stores the chat history. Created if it does not exist.",
    },
    {
      displayName: "Context Window Length",
      name: "contextWindowLength",
      type: "number",
      default: 5,
      description: "Number of previous interactions to consider for context.",
    },
  ],
};

const MEMORY_REDIS_CHAT_DOCS =
  "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.memoryredischat.md";

export const memoryRedisChat: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.memoryRedisChat",
  displayName: "Redis Chat Memory",
  category: "AI",
  group: ["input"],
  version: 1,
  description:
    "Provides a durable, Redis-backed conversation-memory handle to an AI Agent on the ai_memory channel, persisting chat history in Redis keyed by session.",
  defaults: { name: "Redis Chat Memory" },
  inputs: [],
  outputs: ["ai_memory"],
  icon: "Database",
  credentials: [{ name: "redis", required: true }],
  sources: [MEMORY_REDIS_CHAT_DOCS],
  properties: [
    {
      displayName: "Session Key",
      name: "sessionId",
      type: "string",
      default: "",
      placeholder: "my_chat_session",
      description:
        "Key used to store the memory in the workflow data. When blank, the session ID is retrieved from the connected Chat Trigger.",
    },
    {
      displayName: "Session Time To Live (seconds)",
      name: "sessionTTL",
      type: "number",
      default: 0,
      description:
        "Makes the session expire after a given number of seconds. 0 means no TTL.",
    },
    {
      displayName: "Context Window Length",
      name: "contextWindowLength",
      type: "number",
      default: 0,
      description:
        "Number of previous interactions to consider for context. 0 disables context loading.",
    },
  ],
};

export const perplexityTool: INodeTypeDescription = {
  name: "n8n-nodes-base.perplexityTool",
  displayName: "Perplexity AI Tool",
  category: "AI Tool",
  group: ["output"],
  version: [2],
  defaultVersion: 2,
  description: "Tool-mode Perplexity node for AI-agent canvases. Supports Chat, Agent, Search, and Embedding operations via the Perplexity API.",
  defaults: { name: "Perplexity Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Zap",
  credentials: [{ name: "perplexityApi", required: true }],
  sources: perplexity.sources ?? [],
  properties: perplexity.properties,
};

export const googleDriveTool: INodeTypeDescription = {
  name: "n8n-nodes-base.googleDriveTool",
  displayName: "Google Drive",
  category: "AI Tool",
  group: ["output"],
  version: [1],
  defaultVersion: 1,
  description: "Tool-mode Google Drive node for AI-agent canvases. Supports File (copy/create/delete/download/move/share/update/upload), File/Folder (search), Folder (create/delete/share), and Shared Drive (create/delete/get/getAll/update) operations.",
  defaults: { name: "Google Drive" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Cloud",
  credentials: [
    { name: "googleDriveOAuth2Api" },
    { name: "googleApi" },
  ],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googledrive/",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "file",
      noDataExpression: true,
      options: [
        { name: "File", value: "file" },
        { name: "File/Folder", value: "fileFolder" },
        { name: "Folder", value: "folder" },
        { name: "Shared Drive", value: "drive" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Copy", value: "copy" },
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Download", value: "download" },
        { name: "Move", value: "move" },
        { name: "Share", value: "share" },
        { name: "Update", value: "update" },
        { name: "Upload", value: "upload" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "search",
      noDataExpression: true,
      displayOptions: { show: { resource: ["fileFolder"] } },
      options: [
        { name: "Search", value: "search" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      displayOptions: { show: { resource: ["folder"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Share", value: "share" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      displayOptions: { show: { resource: ["drive"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "File ID",
      name: "fileId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["file"], operation: ["copy", "delete", "download", "move", "share", "update"] },
      },
      description: "ID of the file. Supports expressions and $fromAI().",
    },
    {
      displayName: "New Name",
      name: "newName",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["copy"] } },
      description: "New name for the copied file",
    },
    {
      displayName: "Copy in Same Folder",
      name: "copyInSameFolder",
      type: "boolean",
      default: true,
      displayOptions: { show: { resource: ["file"], operation: ["copy"] } },
    },
    {
      displayName: "Parent Destination",
      name: "parentId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["file"], operation: ["create", "copy", "move", "upload"] },
      },
      description: "Destination folder ID. Supports expressions and $fromAI().",
    },
    {
      displayName: "File Name",
      name: "fileName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["create", "upload"] } },
      description: "Name of the file. Supports expressions and $fromAI().",
    },
    {
      displayName: "Content",
      name: "content",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["create"] } },
      description: "Text body of the file",
    },
    {
      displayName: "Convert to Google Doc",
      name: "convertToGoogleDocument",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["file"], operation: ["create"] } },
    },
    {
      displayName: "Delete Permanently",
      name: "deletePermanently",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { resource: ["file", "folder"], operation: ["delete"] },
      },
    },
    {
      displayName: "Convert To",
      name: "convertTo",
      type: "options",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
      options: [
        { name: "None", value: "" },
        { name: "PDF", value: "application/pdf" },
        { name: "DOCX", value: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
        { name: "XLSX", value: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
        { name: "CSV", value: "text/csv" },
        { name: "PPTX", value: "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
        { name: "PNG", value: "image/png" },
        { name: "SVG", value: "image/svg+xml" },
        { name: "JPEG", value: "image/jpeg" },
      ],
    },
    {
      displayName: "Output Field Name",
      name: "outputField",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "Permissions",
      name: "permissions",
      type: "json",
      default: "",
      displayOptions: {
        show: { resource: ["file", "folder"], operation: ["share"] },
      },
      description: "Array of permission objects with role, type, and email/domain. Supports expressions and $fromAI().",
    },
    {
      displayName: "New File Name",
      name: "newFileName",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Move to Trash",
      name: "moveToTrash",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Binary Field",
      name: "binaryField",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["upload", "update"] } },
      description: "Name of the binary field on the input item",
    },
    {
      displayName: "Search Mode",
      name: "searchMode",
      type: "options",
      default: "name",
      noDataExpression: true,
      displayOptions: { show: { resource: ["fileFolder"], operation: ["search"] } },
      options: [
        { name: "Name", value: "name" },
        { name: "Advanced", value: "advanced" },
      ],
    },
    {
      displayName: "Query",
      name: "query",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["fileFolder"], operation: ["search"] } },
      description: "Search query. In Name mode this is the file name fragment. Supports expressions and $fromAI().",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["fileFolder"], operation: ["search"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["fileFolder"], operation: ["search"] } },
    },
    {
      displayName: "Folder ID",
      name: "folderId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["folder"], operation: ["delete", "share"] } },
    },
    {
      displayName: "Folder Name",
      name: "folderName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["folder"], operation: ["create"] } },
    },
    {
      displayName: "Drive ID",
      name: "driveId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["drive"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Name",
      name: "name",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["drive"], operation: ["create"] } },
      description: "Name of the shared drive",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["drive"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["drive"], operation: ["getAll"] } },
    },
    {
      displayName: "Query",
      name: "query",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["drive"], operation: ["getAll"] } },
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "oAuth2",
      noDataExpression: true,
      options: [
        { name: "OAuth2", value: "oAuth2" },
        { name: "Service Account", value: "serviceAccount" },
      ],
    },
  ],
};

export const lmOllama: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.lmOllama",
  displayName: "Ollama Model",
  category: "AI",
  group: ["ai"],
  version: [1],
  defaultVersion: 1,
  description:
    "Configures a locally-hosted Ollama text-completion model and supplies it to a root node (Basic LLM Chain) on the ai_languageModel channel. Does not support tool calling — use lmChatOllama for chat models.",
  defaults: { name: "Ollama Model" },
  inputs: [],
  outputs: ["ai_languageModel"],
  icon: "Robot",
  credentials: [{ name: "ollamaApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmollama.md",
    "https://docs.n8n.io/integrations/builtin/credentials/ollama.md",
  ],
  properties: [
    {
      displayName: "Model",
      name: "model",
      type: "resourceLocator",
      default: { mode: "list", value: "llama3.2" },
      required: true,
      description:
        "The Ollama model that generates the completion. Dynamically loaded from the Ollama API. You may also type a model name not in the list.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Sampling Temperature",
          name: "temperature",
          type: "number",
          default: 0.7,
          typeOptions: { minValue: 0, maxValue: 1, numberPrecision: 2 },
          description: "Controls randomness. Lower = more focused/deterministic; higher = more diverse.",
        },
        {
          displayName: "Top K",
          name: "topK",
          type: "number",
          default: -1,
          description: "Limits the number of highest-probability tokens to consider at each step. -1 disables.",
        },
        {
          displayName: "Top P",
          name: "topP",
          type: "number",
          default: 1,
          typeOptions: { minValue: 0, maxValue: 1, numberPrecision: 2 },
          description: "Cumulative probability threshold for token selection. Lower = fewer options.",
        },
        {
          displayName: "Frequency Penalty",
          name: "frequencyPenalty",
          type: "number",
          default: 0,
          typeOptions: { minValue: -2, maxValue: 2, numberPrecision: 2 },
          description: "Penalizes tokens already appearing in the generated text.",
        },
        {
          displayName: "Presence Penalty",
          name: "presencePenalty",
          type: "number",
          default: 0,
          typeOptions: { minValue: -2, maxValue: 2, numberPrecision: 2 },
          description: "Penalizes tokens based on their presence in the text so far. Encourages topic diversity.",
        },
        {
          displayName: "Repetition Penalty",
          name: "repeatPenalty",
          type: "number",
          default: 1,
          typeOptions: { minValue: 0, numberPrecision: 2 },
          description: "Factor for repeating tokens. 1.0 = disabled; higher = stronger penalty.",
        },
        {
          displayName: "Max Tokens to Generate",
          name: "numPredict",
          type: "number",
          default: -1,
          description: "Maximum tokens in the completion. -1 for no limit.",
        },
        {
          displayName: "Context Length",
          name: "numCtx",
          type: "number",
          default: 2048,
          description: "Maximum tokens of context for generating the next token.",
        },
        {
          displayName: "Context Batch Size",
          name: "numBatch",
          type: "number",
          default: 512,
          description: "Batch size for prompt processing. Larger = faster but more memory.",
        },
        {
          displayName: "Number of CPU Threads",
          name: "numThread",
          type: "number",
          default: 0,
          description: "CPU threads for processing. 0 = auto-detect.",
        },
        {
          displayName: "Number of GPUs",
          name: "numGpu",
          type: "number",
          default: -1,
          description: "GPUs for parallel processing. -1 = auto-detect.",
        },
        {
          displayName: "Main GPU ID",
          name: "mainGpu",
          type: "number",
          default: 0,
          description: "Primary GPU for computation. Change only for multi-GPU setups.",
        },
        {
          displayName: "Low VRAM Mode",
          name: "lowVram",
          type: "boolean",
          default: false,
          description: "Reduces memory at cost of slower generation.",
        },
        {
          displayName: "Use Memory Locking",
          name: "useMLock",
          type: "boolean",
          default: false,
          description: "Lock model in memory to prevent swapping.",
        },
        {
          displayName: "Use Memory Mapping",
          name: "useMMap",
          type: "boolean",
          default: true,
          description: "Memory-map model loading. Reduces RAM usage.",
        },
        {
          displayName: "Load Vocabulary Only",
          name: "vocabOnly",
          type: "boolean",
          default: false,
          description: "Load only the model vocabulary without weights.",
        },
        {
          displayName: "Penalize Newlines",
          name: "penalizeNewline",
          type: "boolean",
          default: true,
          description: "Discourages newline characters, encouraging continuous text.",
        },
        {
          displayName: "Enable Thinking",
          name: "think",
          type: "boolean",
          default: true,
          description: "For supported models, separates the thinking process from output.",
        },
        {
          displayName: "Output Format",
          name: "format",
          type: "options",
          default: "default",
          noDataExpression: true,
          options: [
            { name: "Default", value: "default" },
            { name: "JSON", value: "json" },
          ],
          description: "Output format — default (free text) or JSON.",
        },
        {
          displayName: "Stop Sequences",
          name: "stop",
          type: "string",
          default: "",
          description: "Comma-separated strings that stop generation when encountered.",
        },
        {
          displayName: "Seed",
          name: "seed",
          type: "number",
          default: 0,
          description: "Random number seed for reproducible generation. 0 = random.",
        },
        {
          displayName: "Keep Alive",
          name: "keepAlive",
          type: "string",
          default: "5m",
          description: "Duration to keep loaded model in memory (e.g. 5m, 1h30m).",
        },
      ],
    },
  ],
};

export const chat: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.chat",
  displayName: "Chat",
  category: "Input",
  group: ["input"],
  version: [1, 1.1, 1.2, 1.3],
  description:
    "Human-in-the-loop node that sends messages to a chat interface and optionally waits for a user response. Works with the Chat Trigger node in Hosted Chat mode.",
  defaults: { name: "Chat" },
  inputs: ["main", "ai_memory"],
  outputs: ["main"],
  icon: "MessageSquare",
  sources: [
    "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-langchain.chat.md",
  ],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "send",
      noDataExpression: true,
      options: [
        { name: "Send Message", value: "send" },
        { name: "Send and Wait for Response", value: "sendAndWait" },
      ],
    },
    {
      displayName: "Message",
      name: "message",
      type: "string",
      default: "",
      required: true,
      description: "Message text to send to chat",
    },
    {
      displayName: "Response Type",
      name: "responseType",
      type: "options",
      default: "freeText",
      displayOptions: { show: { operation: ["sendAndWait"] } },
      options: [
        { name: "Free Text", value: "freeText" },
        { name: "Approval", value: "approval" },
      ],
    },
    {
      displayName: "Approval Type",
      name: "approvalType",
      type: "options",
      default: "approveAndDisapprove",
      displayOptions: { show: { responseType: ["approval"] } },
      options: [
        { name: "Approve Only", value: "approveOnly" },
        { name: "Approve and Disapprove", value: "approveAndDisapprove" },
      ],
    },
    {
      displayName: "Approve Button Label",
      name: "approveButtonLabel",
      type: "string",
      default: "Approve",
      displayOptions: { show: { responseType: ["approval"] } },
    },
    {
      displayName: "Disapprove Button Label",
      name: "disapproveButtonLabel",
      type: "string",
      default: "Disapprove",
      displayOptions: {
        show: { responseType: ["approval"], approvalType: ["approveAndDisapprove"] },
      },
    },
    {
      displayName: "Block User Input",
      name: "blockUserInput",
      type: "boolean",
      default: false,
      displayOptions: { show: { responseType: ["approval"] } },
      description: "When true, users can only use buttons; when false, users can also type custom messages",
    },
    {
      displayName: "Memory Connection",
      name: "memoryConnection",
      type: "boolean",
      default: false,
      displayOptions: { hide: { responseType: ["approval"] } },
      description: "Whether to add ai_memory input connection and commit messages to connected memory",
    },
    {
      displayName: "Limit Wait Time",
      name: "limitWaitTime",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["sendAndWait"] } },
      options: [
        {
          displayName: "Limit Type",
          name: "limitType",
          type: "options",
          default: "afterTimeInterval",
          options: [
            { name: "After Time Interval", value: "afterTimeInterval" },
            { name: "Max Date and Time", value: "maxDateAndTime" },
          ],
        },
        {
          displayName: "Resume Amount",
          name: "resumeAmount",
          type: "number",
          default: 1,
          displayOptions: { show: { limitType: ["afterTimeInterval"] } },
        },
        {
          displayName: "Resume Unit",
          name: "resumeUnit",
          type: "options",
          default: "hours",
          displayOptions: { show: { limitType: ["afterTimeInterval"] } },
          options: [
            { name: "Seconds", value: "seconds" },
            { name: "Minutes", value: "minutes" },
            { name: "Hours", value: "hours" },
            { name: "Days", value: "days" },
          ],
        },
        {
          displayName: "Max Date and Time",
          name: "maxDateAndTime",
          type: "dateTime",
          default: "",
          displayOptions: { show: { limitType: ["maxDateAndTime"] } },
        },
      ],
    },
  ],
};

export const vectorStorePGVector: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.vectorStorePGVector",
  displayName: "Postgres PGVector Store",
  category: "AI",
  group: ["input"],
  version: [1, 1.1, 1.2, 1.3],
  defaultVersion: 1.3,
  description:
    "Provides a PGVector-backed vector store over a PostgreSQL database for RAG workflows. Supports load, insert, retrieve, and retrieve-as-tool modes. Data is persisted in a PostgreSQL table with a pgvector extension column.",
  defaults: { name: "Postgres PGVector Store" },
  inputs: ["main", "ai_embedding", "ai_document", "ai_reranker"],
  inputNames: ["Main", "Embedding", "Document", "Reranker"],
  outputs: ["main", "ai_vectorStore", "ai_tool"],
  outputNames: ["Main", "Vector Store", "Tool"],
  icon: "Database",
  credentials: [{ name: "postgres", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.vectorstorepgvector.md",
    "https://docs.n8n.io/integrations/builtin/credentials/postgres.md",
  ],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "retrieve",
      noDataExpression: true,
      options: [
        { name: "Get Many", value: "load" },
        { name: "Insert Documents", value: "insert" },
        { name: "Retrieve Documents (As Vector Store for Chain/Tool)", value: "retrieve" },
        { name: "Retrieve Documents (As Tool for AI Agent)", value: "retrieve-as-tool" },
      ],
      description: "Operation mode for the vector store.",
    },
    {
      displayName: "Table Name",
      name: "tableName",
      type: "string",
      default: "n8n_vectors",
      displayOptions: { show: { mode: ["load", "insert", "retrieve", "retrieve-as-tool"] } },
      description: "The table storing vectors. Created automatically if it does not exist.",
    },
    {
      displayName: "Prompt",
      name: "prompt",
      type: "string",
      default: "",
      required: true,
      typeOptions: { rows: 4 },
      displayOptions: { show: { mode: ["load"] } },
      description: "Search query text. Evaluated per input item via expressions.",
    },
    {
      displayName: "Limit",
      name: "topK",
      type: "number",
      default: 4,
      displayOptions: { show: { mode: ["load", "retrieve-as-tool"] } },
      description: "Number of top results to retrieve.",
    },
    {
      displayName: "Include Document Metadata",
      name: "includeDocumentMetadata",
      type: "boolean",
      default: true,
      displayOptions: { show: { mode: ["load", "retrieve-as-tool"] } },
      description: "Whether to include document metadata in the output.",
    },
    {
      displayName: "Tool Name",
      name: "toolName",
      type: "string",
      default: "",
      displayOptions: { show: { mode: ["retrieve-as-tool"] } },
      description: "Name of the vector store tool (alphanumeric).",
    },
    {
      displayName: "Tool Description",
      name: "toolDescription",
      type: "string",
      default: "",
      displayOptions: { show: { mode: ["retrieve-as-tool"] } },
      description: "Description of the tool for the LLM.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["load", "insert", "retrieve", "retrieve-as-tool"] } },
      options: [
        {
          displayName: "Use Reranker",
          name: "useReranker",
          type: "boolean",
          default: false,
          displayOptions: { show: { mode: ["load", "retrieve", "retrieve-as-tool"] } },
          description: "When true, requires a reranker sub-node on ai_reranker.",
        },
        {
          displayName: "Embedding Batch Size",
          name: "embeddingBatchSize",
          type: "number",
          default: 200,
          displayOptions: { show: { mode: ["insert"] } },
          description: "Number of documents to embed in a single batch.",
        },
        {
          displayName: "Distance Strategy",
          name: "distanceStrategy",
          type: "options",
          default: "cosine",
          noDataExpression: true,
          options: [
            { name: "Cosine", value: "cosine" },
            { name: "Inner Product", value: "innerProduct" },
            { name: "Euclidean", value: "euclidean" },
          ],
          displayOptions: { show: { mode: ["load", "retrieve", "retrieve-as-tool"] } },
          description: "Distance metric for similarity search.",
        },
        {
          displayName: "Collection",
          name: "collection",
          type: "fixedCollection",
          default: {},
          options: [
            {
              name: "values",
              displayName: "Collection",
              values: [
                {
                  displayName: "Use Collection",
                  name: "useCollection",
                  type: "boolean",
                  default: false,
                  description: "Scope queries to a named collection.",
                },
                {
                  displayName: "Collection Name",
                  name: "collectionName",
                  type: "string",
                  default: "n8n",
                  displayOptions: { show: { useCollection: [true] } },
                  description: "Name of the collection to scope to.",
                },
                {
                  displayName: "Collection Table Name",
                  name: "collectionTableName",
                  type: "string",
                  default: "n8n_vector_collections",
                  displayOptions: { show: { useCollection: [true] } },
                  description: "Table tracking vector-to-collection membership.",
                },
              ],
            },
          ],
        },
        {
          displayName: "Column Names",
          name: "columnNames",
          type: "fixedCollection",
          default: {},
          options: [
            {
              name: "values",
              displayName: "Column Names",
              values: [
                {
                  displayName: "ID Column Name",
                  name: "idColumnName",
                  type: "string",
                  default: "id",
                  description: "Name of the ID column.",
                },
                {
                  displayName: "Vector Column Name",
                  name: "vectorColumnName",
                  type: "string",
                  default: "embedding",
                  description: "Name of the vector (embedding) column.",
                },
                {
                  displayName: "Content Column Name",
                  name: "contentColumnName",
                  type: "string",
                  default: "text",
                  description: "Name of the content column.",
                },
                {
                  displayName: "Metadata Column Name",
                  name: "metadataColumnName",
                  type: "string",
                  default: "metadata",
                  description: "Name of the metadata column.",
                },
              ],
            },
          ],
        },
        {
          displayName: "Metadata Filter",
          name: "metadata",
          type: "fixedCollection",
          default: {},
          typeOptions: { multipleValues: true },
          displayOptions: { show: { mode: ["load", "retrieve-as-tool"] } },
          options: [
            {
              name: "metadataValues",
              displayName: "Values",
              values: [
                {
                  displayName: "Name",
                  name: "name",
                  type: "string",
                  default: "",
                  description: "Metadata field name.",
                },
                {
                  displayName: "Value",
                  name: "value",
                  type: "string",
                  default: "",
                  description: "Metadata field value; supports expressions.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const embeddingsOllama: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.embeddingsOllama",
  displayName: "Embeddings Ollama",
  category: "AI",
  group: ["transform"],
  version: 1,
  description:
    "Configures an Ollama-hosted text-embedding model and supplies it to a parent root node on the ai_embedding channel. The parent invokes the provider with documents/text to embed.",
  defaults: { name: "Embeddings Ollama" },
  inputs: [],
  outputs: ["ai_embedding"],
  icon: "Robot",
  credentials: [{ name: "ollamaApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.embeddingsollama.md",
    "https://docs.n8n.io/integrations/builtin/credentials/ollama.md",
  ],
  properties: [
    {
      displayName: "Model",
      name: "model",
      type: "options",
      default: "all-minilm",
      required: true,
      noDataExpression: false,
      options: [
        { name: "all-minilm", value: "all-minilm" },
        { name: "nomic-embed-text", value: "nomic-embed-text" },
      ],
      description:
        "The Ollama model used to compute embeddings. all-minilm (384 dimensions) and nomic-embed-text (768 dimensions) are pre-configured; any Ollama model name can be typed.",
    },
  ],
};
export const lmChatXAiGrok: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.lmChatXAiGrok",
  displayName: "xAI Grok Chat Model",
  category: "AI",
  group: ["ai"],
  version: [1],
  defaultVersion: 1,
  description: "Configures an xAI Grok-hosted chat model and supplies it to a root node (AI Agent, Basic LLM Chain, etc.) on the ai_languageModel channel.",
  defaults: { name: "xAI Grok Chat Model" },
  inputs: [],
  outputs: ["ai_languageModel"],
  icon: "Robot",
  credentials: [{ name: "xAiApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatxaigrok.md",
  ],
  properties: [
    {
      displayName: "Model",
      name: "model",
      type: "resourceLocator",
      default: { mode: "list", value: "" },
      required: true,
      description: "The model that generates the completion. Select from the list or enter a Model ID.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Frequency Penalty",
          name: "frequencyPenalty",
          type: "number",
          default: 0,
          description: "Controls the chance of the model repeating itself; higher values reduce repetition",
        },
        {
          displayName: "Maximum Number of Tokens",
          name: "maxTokens",
          type: "number",
          default: 0,
          description: "Sets the maximum completion length. 0 means model default.",
        },
        {
          displayName: "Response Format",
          name: "responseFormat",
          type: "options",
          default: "text",
          options: [
            { name: "Text", value: "text" },
            { name: "JSON", value: "json" },
          ],
          description: "Choose Text or JSON. JSON ensures the model returns valid JSON.",
        },
        {
          displayName: "Presence Penalty",
          name: "presencePenalty",
          type: "number",
          default: 0,
          description: "Controls the chance of the model talking about new topics; higher values increase it",
        },
        {
          displayName: "Sampling Temperature",
          name: "temperature",
          type: "number",
          default: 0,
          description: "Controls randomness of the sampling process; higher = more diverse",
        },
        {
          displayName: "Timeout",
          name: "timeout",
          type: "number",
          default: 120000,
          description: "Maximum request time in milliseconds",
        },
        {
          displayName: "Max Retries",
          name: "maxRetries",
          type: "number",
          default: 3,
          description: "Maximum number of times to retry a request",
        },
        {
          displayName: "Top P",
          name: "topP",
          type: "number",
          default: 0,
          description: "Sets the probability threshold; lower values ignore less probable options",
        },
      ],
    },
  ],
};
