import type { INodeTypeDescription } from "../types";

export const awsCertificateManager: INodeTypeDescription = {
  name: "n8n-nodes-base.awsCertificateManager",
  displayName: "AWS Certificate Manager",
  category: "Development",
  group: ["input"],
  version: 1,
  description: "Manages AWS ACM certificates with delete, get, getMany, getMetadata, and renew operations.",
  defaults: { name: "AWS Certificate Manager" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "ShieldCheck",
  credentials: [{ name: "aws" }, { name: "awsAssumeRole" }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.awscertificatemanager/",
    "https://docs.n8n.io/integrations/builtin/credentials/aws/",
  ],
  properties: [
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "iam",
      noDataExpression: true,
      required: true,
      options: [
        { name: "IAM", value: "iam" },
        { name: "Assume Role", value: "assumeRole" },
      ],
    },
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "certificate",
      noDataExpression: true,
      required: true,
      options: [
        { name: "Certificate", value: "certificate" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "renew",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["certificate"] } },
      options: [
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getMany" },
        { name: "Get Metadata", value: "getMetadata" },
        { name: "Renew", value: "renew" },
      ],
    },
    {
      displayName: "Certificate ARN",
      name: "certificateArn",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: {
          resource: ["certificate"],
          operation: ["renew", "get", "delete", "getMetadata"],
        },
      },
      description: "The full ARN of the ACM certificate",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { operation: ["getMany"] },
      },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 100,
      typeOptions: { minValue: 1, maxValue: 500 },
      displayOptions: {
        show: { operation: ["getMany"], returnAll: [false] },
      },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: {
        show: { operation: ["getMany"] },
      },
      options: [
        {
          displayName: "Certificate Statuses",
          name: "certificateStatuses",
          type: "multiOptions",
          default: [],
          options: [
            { name: "Expired", value: "EXPIRED" },
            { name: "Failed", value: "FAILED" },
            { name: "Inactive", value: "INACTIVE" },
            { name: "Issued", value: "ISSUED" },
            { name: "Pending Validation", value: "PENDING_VALIDATION" },
            { name: "Revoked", value: "REVOKED" },
            { name: "Validation Timed Out", value: "VALIDATION_TIMED_OUT" },
          ],
        },
        {
          displayName: "Extended Key Usage",
          name: "extendedKeyUsage",
          type: "multiOptions",
          default: [],
          options: [
            { name: "Any", value: "ANY" },
            { name: "Code Signing", value: "CODE_SIGNING" },
            { name: "Custom", value: "CUSTOM" },
            { name: "Email Protection", value: "EMAIL_PROTECTION" },
            { name: "IPSEC End System", value: "IPSEC_END_SYSTEM" },
            { name: "IPSEC Tunnel", value: "IPSEC_TUNNEL" },
            { name: "IPSEC User", value: "IPSEC_USER" },
            { name: "None", value: "NONE" },
            { name: "OCSP Signing", value: "OCSP_SIGNING" },
            { name: "Time Stamping", value: "TIME_STAMPING" },
            { name: "TLS Web Client Authentication", value: "TLS_WEB_CLIENT_AUTHENTICATION" },
            { name: "TLS Web Server Authentication", value: "TLS_WEB_SERVER_AUTHENTICATION" },
          ],
        },
        {
          displayName: "Key Types",
          name: "keyTypes",
          type: "multiOptions",
          default: ["RSA_2048"],
          options: [
            { name: "EC prime256v1", value: "EC_prime256v1" },
            { name: "EC secp384r1", value: "EC_secp384r1" },
            { name: "EC secp521r1", value: "EC_secp521r1" },
            { name: "RSA 1024", value: "RSA_1024" },
            { name: "RSA 2048", value: "RSA_2048" },
            { name: "RSA 4096", value: "RSA_4096" },
          ],
        },
        {
          displayName: "Key Usage",
          name: "keyUsage",
          type: "multiOptions",
          default: [],
          options: [
            { name: "CRL Signing", value: "CRL_SIGNING" },
            { name: "Cert Signing", value: "CERTIFICATE_SIGNING" },
            { name: "Data Encipherment", value: "DATA_ENCIPHERMENT" },
            { name: "Decipher Only", value: "DECIPHER_ONLY" },
            { name: "Digital Signature", value: "DIGITAL_SIGNATURE" },
            { name: "Encipher Only", value: "ENCIPHER_ONLY" },
            { name: "Key Agreement", value: "KEY_AGREEMENT" },
            { name: "Key Encipherment", value: "KEY_ENCIPHERMENT" },
            { name: "Non Repudiation", value: "NON_REPUDIATION" },
          ],
        },
      ],
    },
  ],
};
