import type { INodeTypeDescription } from "../types";

const MAILGUN_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mailgun/";

export const mailgun: INodeTypeDescription = {
  name: "n8n-nodes-base.mailgun",
  displayName: "Mailgun",
  category: "Communication",
  group: ["communication"],
  version: 1,
  description: "Sends transactional emails via Mailgun API",
  defaults: { name: "Mailgun" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Mail",
  sources: [MAILGUN_DOCS],
  properties: [
    {
      displayName: "From Email",
      name: "fromEmail",
      type: "string",
      default: "",
      required: true,
      placeholder: "Admin <admin@example.com>",
      description: "Sender address, optionally with display name",
    },
    {
      displayName: "To Email",
      name: "toEmail",
      type: "string",
      default: "",
      required: true,
      placeholder: "recipient@example.com",
      description: "Recipient address(es), comma-separated for multiple",
    },
    {
      displayName: "CC Email",
      name: "ccEmail",
      type: "string",
      default: "",
      description: "CC recipient address(es), comma-separated",
    },
    {
      displayName: "BCC Email",
      name: "bccEmail",
      type: "string",
      default: "",
      description: "BCC recipient address(es), comma-separated",
    },
    {
      displayName: "Subject",
      name: "subject",
      type: "string",
      default: "",
      description: "Email subject line",
    },
    {
      displayName: "Text",
      name: "text",
      type: "string",
      default: "",
      description: "Plain-text body (multi-line string)",
      typeOptions: { rows: 4 },
    },
    {
      displayName: "HTML",
      name: "html",
      type: "string",
      default: "",
      description: "HTML body (rich text editor)",
      typeOptions: { rows: 4 },
    },
    {
      displayName: "Attachments",
      name: "attachments",
      type: "string",
      default: "",
      placeholder: "myFile,report",
      description: "Comma-separated list of binary property names whose data should be attached",
    },
  ],
};

const MAILJET_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mailjet/";

export const mailjet: INodeTypeDescription = {
  name: "n8n-nodes-base.mailjet",
  displayName: "Mailjet",
  category: "Communication",
  group: ["communication"],
  version: 1,
  description: "Sends transactional emails and SMS via Mailjet API",
  defaults: { name: "Mailjet" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Mail",
  sources: [MAILJET_DOCS],
  credentials: [
    { name: "mailjetEmailApi", required: false },
    { name: "mailjetSmsApi", required: false },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "email",
      required: true,
      options: [
        { name: "Email", value: "email" },
        { name: "SMS", value: "sms" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "send",
      required: true,
      displayOptions: {
        show: { resource: ["email"] },
      },
      options: [
        { name: "Send", value: "send" },
        { name: "Send Template", value: "sendTemplate" },
      ],
    },
    {
      displayName: "From Email",
      name: "fromEmail",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["email"] },
      },
      placeholder: "sender@example.com",
    },
    {
      displayName: "To Email",
      name: "toEmail",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["email"] },
      },
      placeholder: "recipient@example.com",
    },
    {
      displayName: "Subject",
      name: "subject",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["email"], operation: ["send"] },
      },
    },
    {
      displayName: "Text",
      name: "text",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["email"], operation: ["send"] },
      },
      typeOptions: { rows: 4 },
    },
    {
      displayName: "HTML",
      name: "html",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["email"], operation: ["send"] },
      },
      typeOptions: { rows: 4 },
    },
    {
      displayName: "JSON Parameters",
      name: "jsonParameters",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { resource: ["email"] },
      },
    },
    {
      displayName: "Template ID",
      name: "templateId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["email"], operation: ["sendTemplate"] },
      },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: {
        show: { resource: ["email"] },
      },
      options: [
        {
          displayName: "BCC Email",
          name: "bccEmail",
          type: "string",
          default: "",
        },
        {
          displayName: "CC Addresses",
          name: "ccAddresses",
          type: "string",
          default: "",
        },
        {
          displayName: "From Name",
          name: "fromName",
          type: "string",
          default: "",
        },
        {
          displayName: "Priority",
          name: "priority",
          type: "number",
          default: 2,
          typeOptions: { minValue: 1, maxValue: 3 },
        },
        {
          displayName: "Reply To",
          name: "replyTo",
          type: "string",
          default: "",
        },
        {
          displayName: "Template Language",
          name: "templateLanguage",
          type: "boolean",
          default: false,
        },
        {
          displayName: "Track Clicks",
          name: "trackClicks",
          type: "options",
          default: "account_default",
          options: [
            { name: "Account Default", value: "account_default" },
            { name: "Enabled", value: "enabled" },
            { name: "Disabled", value: "disabled" },
          ],
        },
        {
          displayName: "Track Opens",
          name: "trackOpens",
          type: "options",
          default: "account_default",
          options: [
            { name: "Account Default", value: "account_default" },
            { name: "Enabled", value: "enabled" },
            { name: "Disabled", value: "disabled" },
          ],
        },
        {
          displayName: "Custom Campaign",
          name: "customCampaign",
          type: "string",
          default: "",
        },
        {
          displayName: "Deduplicate Campaign",
          name: "deduplicateCampaign",
          type: "boolean",
          default: false,
        },
      ],
    },
    {
      displayName: "Variables UI",
      name: "variablesUi",
      type: "fixedCollection",
      default: {},
      displayOptions: {
        show: { resource: ["email"], jsonParameters: [false] },
      },
      options: [
        {
          name: "variablesValues",
          displayName: "Variables",
          values: [
            {
              displayName: "Name",
              name: "name",
              type: "string",
              default: "",
            },
            {
              displayName: "Value",
              name: "value",
              type: "string",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Variables JSON",
      name: "variablesJson",
      type: "json",
      default: "",
      displayOptions: {
        show: { resource: ["email"], jsonParameters: [true] },
      },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "send",
      required: true,
      displayOptions: {
        show: { resource: ["sms"] },
      },
      options: [{ name: "Send", value: "send" }],
    },
    {
      displayName: "From",
      name: "from",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["sms"], operation: ["send"] },
      },
      placeholder: "MyApp",
    },
    {
      displayName: "To",
      name: "to",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["sms"], operation: ["send"] },
      },
      placeholder: "+33612345678",
    },
    {
      displayName: "Text",
      name: "text",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["sms"], operation: ["send"] },
      },
      typeOptions: { rows: 4 },
    },
  ],
};

const GOOGLE_CHAT_DOCS =
  "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googlechat/";

export const googleChat: INodeTypeDescription = {
  name: "n8n-nodes-base.googleChat",
  displayName: "Google Chat",
  category: "Communication",
  group: ["communication"],
  version: 1,
  description: "Send and receive messages via Google Chat API",
  defaults: { name: "Google Chat" },
  inputs: ["main"],
  outputs: ["main"],
  credentials: [
    { name: "googleChatOAuth2Api", required: false },
    { name: "googleApi", required: false },
  ],
  icon: "MessageSquare",
  sources: [GOOGLE_CHAT_DOCS],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "message",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Member", value: "member" },
        { name: "Message", value: "message" },
        { name: "Space", value: "space" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      displayOptions: {
        show: { resource: ["member"] },
      },
      options: [
        { name: "Get All", value: "getAll" },
        { name: "Get", value: "get" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: true,
      displayOptions: {
        show: { resource: ["member"], operation: ["getAll"] },
      },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: {
        show: { resource: ["member"], operation: ["getAll"], returnAll: [false] },
      },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Space ID",
      name: "spaceId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["member"] },
      },
      placeholder: "spaces/AAA",
    },
    {
      displayName: "Membership ID",
      name: "membershipId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["member"], operation: ["get"] },
      },
      placeholder: "spaces/AAA/members/123",
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      displayOptions: {
        show: { resource: ["message"] },
      },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Send and Wait", value: "sendAndWait" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Space ID",
      name: "spaceId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["message"] },
      },
      placeholder: "spaces/AAA",
    },
    {
      displayName: "Text",
      name: "text",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["message"], operation: ["create", "update"] },
      },
      typeOptions: { rows: 4 },
    },
    {
      displayName: "Message ID",
      name: "messageId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["message"], operation: ["delete", "get", "update"] },
      },
      placeholder: "spaces/AAA/messages/123",
    },
    {
      displayName: "Update Fields",
      name: "updateFields",
      type: "collection",
      default: {},
      displayOptions: {
        show: { resource: ["message"], operation: ["update"] },
      },
      options: [
        {
          displayName: "Text",
          name: "text",
          type: "string",
          default: "",
        },
      ],
    },
    {
      displayName: "Response Type",
      name: "responseType",
      type: "options",
      default: "approval",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"] },
      },
      options: [
        { name: "Approval", value: "approval" },
        { name: "Free Text", value: "freeText" },
        { name: "Custom Form", value: "customForm" },
      ],
    },
    {
      displayName: "Limit Wait Time",
      name: "limitWaitTime",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"] },
      },
    },
    {
      displayName: "Limit Wait Time Value",
      name: "limitWaitTimeValue",
      type: "number",
      default: 0,
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], limitWaitTime: [true] },
      },
      typeOptions: { minValue: 0 },
    },
    {
      displayName: "Append Attribution",
      name: "appendAttribution",
      type: "boolean",
      default: true,
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"] },
      },
    },
    {
      displayName: "Approve Button Label",
      name: "approveButtonLabel",
      type: "string",
      default: "Approve",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["approval"] },
      },
    },
    {
      displayName: "Disapprove Button Label",
      name: "disapproveButtonLabel",
      type: "string",
      default: "Disapprove",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["approval"] },
      },
    },
    {
      displayName: "Include Disapprove",
      name: "includeDissapprove",
      type: "boolean",
      default: true,
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["approval"] },
      },
    },
    {
      displayName: "Free Text Button Label",
      name: "freeTextButtonLabel",
      type: "string",
      default: "Reply",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["freeText"] },
      },
    },
    {
      displayName: "Free Text Form Title",
      name: "freeTextFormTitle",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["freeText"] },
      },
    },
    {
      displayName: "Free Text Form Description",
      name: "freeTextFormDescription",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["freeText"] },
      },
    },
    {
      displayName: "Response Button Label",
      name: "responseButtonLabel",
      type: "string",
      default: "Submit",
      displayOptions: {
        show: {
          resource: ["message"],
          operation: ["sendAndWait"],
          responseType: ["freeText", "customForm"],
        },
      },
    },
    {
      displayName: "Custom Form Button Label",
      name: "customFormButtonLabel",
      type: "string",
      default: "Open Form",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["customForm"] },
      },
    },
    {
      displayName: "Custom Form Title",
      name: "customFormTitle",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["customForm"] },
      },
    },
    {
      displayName: "Custom Form Description",
      name: "customFormDescription",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["customForm"] },
      },
    },
    {
      displayName: "Form Elements",
      name: "formElements",
      type: "json",
      default: "[]",
      displayOptions: {
        show: { resource: ["message"], operation: ["sendAndWait"], responseType: ["customForm"] },
      },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      displayOptions: {
        show: { resource: ["space"] },
      },
      options: [
        { name: "Get All", value: "getAll" },
        { name: "Get", value: "get" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: true,
      displayOptions: {
        show: { resource: ["space"], operation: ["getAll"] },
      },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: {
        show: { resource: ["space"], operation: ["getAll"], returnAll: [false] },
      },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Space ID",
      name: "spaceId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["space"], operation: ["get"] },
      },
      placeholder: "spaces/AAA",
    },
  ],
};

const ZENDESK_DOCS =
  "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.zendesk/";

export const zendesk: INodeTypeDescription = {
  name: "n8n-nodes-base.zendesk",
  displayName: "Zendesk",
  category: "Communication",
  group: ["communication"],
  version: 1,
  description: "Access Zendesk ticket, user, and organization data",
  defaults: { name: "Zendesk" },
  inputs: ["main"],
  outputs: ["main"],
  credentials: [
    { name: "zendeskApi", required: false },
    { name: "zendeskOAuth2Api", required: false },
  ],
  icon: "Headphones",
  sources: [ZENDESK_DOCS],
  properties: [
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "apiToken",
      required: true,
      options: [
        { name: "API Token", value: "apiToken" },
        { name: "OAuth2", value: "oAuth2" },
      ],
    },
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "ticket",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Organization", value: "organization" },
        { name: "Ticket", value: "ticket" },
        { name: "Ticket Field", value: "ticketField" },
        { name: "User", value: "user" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      displayOptions: {
        show: { resource: ["ticket"] },
      },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Recover a Suspended Ticket", value: "recover" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      displayOptions: {
        show: { resource: ["ticketField"] },
      },
      options: [
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      displayOptions: {
        show: { resource: ["user"] },
      },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Get Organizations", value: "getOrganizations" },
        { name: "Get User Data", value: "getUserData" },
        { name: "Search", value: "search" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      displayOptions: {
        show: { resource: ["organization"] },
      },
      options: [
        { name: "Count", value: "count" },
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Get Organization Data", value: "getOrganizationData" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "ID",
      name: "id",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: {
          resource: ["ticket", "ticketField", "user", "organization"],
          operation: ["get", "delete", "update", "recover", "getUserData", "getOrganizationData"],
        },
      },
      description: "Resource identifier from Zendesk",
    },
    {
      displayName: "Request Fields",
      name: "requestFields",
      type: "json",
      default: "",
      displayOptions: {
        show: {
          resource: ["ticket", "user", "organization"],
          operation: ["create", "update"],
        },
      },
      placeholder: '{"ticket": {"subject": "...", "description": "..."}}',
      description: "JSON body with resource-specific fields for create/update operations",
    },
    {
      displayName: "Query Parameters",
      name: "queryParameters",
      type: "json",
      default: "",
      displayOptions: {
        show: {
          resource: ["ticket", "ticketField", "user", "organization"],
          operation: ["getAll", "search", "count"],
        },
      },
      placeholder: '{"limit": 100, "include": "users"}',
      description: "Optional query parameters for listing, search, and count operations",
    },
  ],
};

const AWS_SES_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.awsses/";

export const awsSes: INodeTypeDescription = {
  name: "n8n-nodes-base.awsSes",
  displayName: "AWS SES",
  category: "Communication",
  group: ["communication"],
  version: 1,
  description: "Sends transactional emails via AWS SES API",
  defaults: { name: "AWS SES" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Mail",
  credentials: [{ name: "aws", required: true }],
  sources: [AWS_SES_DOCS],
  properties: [
    {
      displayName: "To",
      name: "to",
      type: "string",
      default: "",
      required: true,
      placeholder: "recipient@example.com",
      description: "Recipient email address(es), comma-separated for multiple",
    },
    {
      displayName: "Subject",
      name: "subject",
      type: "string",
      default: "",
      required: true,
      description: "Email subject line",
    },
    {
      displayName: "Text",
      name: "text",
      type: "string",
      default: "",
      description: "Plain-text body content",
      typeOptions: { rows: 4 },
    },
    {
      displayName: "HTML",
      name: "html",
      type: "string",
      default: "",
      description: "HTML-formatted body content",
      typeOptions: { rows: 4 },
    },
    {
      displayName: "From",
      name: "from",
      type: "string",
      default: "",
      required: true,
      placeholder: "sender@example.com",
      description: "Sender email address (must be verified in SES)",
    },
    {
      displayName: "Template",
      name: "template",
      type: "string",
      default: "",
      description: "Optional AWS SES template identifier",
    },
    {
      displayName: "Attachments",
      name: "attachments",
      type: "string",
      default: "",
      placeholder: "myFile,report",
      description: "Comma-separated list of binary property names whose data should be attached",
    },
  ],
};

const GOTIFY_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.gotify/";

export const gotify: INodeTypeDescription = {
  name: "n8n-nodes-base.gotify",
  displayName: "Gotify",
  category: "Communication",
  group: ["communication"],
  version: 1,
  description: "Send push notifications via a Gotify server",
  defaults: { name: "Gotify" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "MessageCircle",
  credentials: [{ name: "gotifyApi" }],
  sources: [GOTIFY_DOCS, "https://gotify.net/docs/pushmsg"],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Message",
      name: "message",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { operation: ["create"] } },
    },
    {
      displayName: "Title",
      name: "title",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["create"] } },
    },
    {
      displayName: "Priority",
      name: "priority",
      type: "number",
      default: 0,
      displayOptions: { show: { operation: ["create"] } },
    },
    {
      displayName: "Message ID",
      name: "messageId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { operation: ["delete"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 20,
      displayOptions: { show: { operation: ["getAll"], returnAll: [false] } },
      typeOptions: { minValue: 1 },
    },
  ],
};

const AMQP_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.amqp/";

export const amqp: INodeTypeDescription = {
  name: "n8n-nodes-base.amqp",
  displayName: "AMQP Sender",
  category: "Communication",
  group: ["communication"],
  version: 1,
  description: "Send messages to an AMQP 1.0 broker",
  defaults: { name: "AMQP Sender" },
  inputs: ["main"],
  outputs: ["main"],
  credentials: [{ name: "amqp", required: true }],
  icon: "MessageCircle",
  sources: [AMQP_DOCS],
  properties: [
    {
      displayName: "Exchange",
      name: "exchange",
      type: "string",
      default: "",
      description: "Target exchange name; if omitted the default exchange is used",
    },
    {
      displayName: "Routing Key",
      name: "routingKey",
      type: "string",
      default: "",
      required: true,
      description: "Routing key for message dispatch",
    },
    {
      displayName: "Send Input Data",
      name: "sendInputData",
      type: "boolean",
      default: true,
      description: "When true, serializes incoming item JSON as the message body",
    },
    {
      displayName: "Message",
      name: "message",
      type: "string",
      default: "",
      displayOptions: { show: { sendInputData: [false] } },
      description: "Custom message body (shown when sendInputData=false)",
    },
  ],
};

const TELEGRAM_DOCS =
  "https://docs.n8n.io/integrations/builtin/trigger-nodes/n8n-nodes-base.telegramtrigger/";

export const telegramTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.telegramTrigger",
  displayName: "Telegram Trigger",
  category: "Communication",
  group: ["trigger"],
  version: 1,
  description: "Listens for Telegram bot updates via webhook and emits each update as a workflow item.",
  defaults: { name: "Telegram Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "Send",
  credentials: [{ name: "telegramApi", required: true }],
  sources: [TELEGRAM_DOCS],
  properties: [
    {
      displayName: "Events",
      name: "events",
      type: "multiOptions",
      default: ["*"],
      required: true,
      noDataExpression: true,
      description: "One or more Telegram update categories to react to. The wildcard (*) covers all updates except Chat Member, Message Reaction, and Message Reaction Count.",
      options: [
        { name: "* (All except restricted)", value: "*" },
        { name: "Message", value: "message" },
        { name: "Edited Message", value: "edited_message" },
        { name: "Channel Post", value: "channel_post" },
        { name: "Edited Channel Post", value: "edited_channel_post" },
        { name: "Callback Query", value: "callback_query" },
        { name: "Inline Query", value: "inline_query" },
        { name: "Chosen Inline Result", value: "chosen_inline_result" },
        { name: "Business Connection", value: "business_connection" },
        { name: "Business Message", value: "business_message" },
        { name: "Edited Business Message", value: "edited_business_message" },
        { name: "Deleted Business Messages", value: "deleted_business_messages" },
        { name: "Chat Boost", value: "chat_boost" },
        { name: "Removed Chat Boost", value: "removed_chat_boost" },
        { name: "Chat Join Request", value: "chat_join_request" },
        { name: "Chat Member", value: "chat_member" },
        { name: "My Chat Member", value: "my_chat_member" },
        { name: "Poll", value: "poll" },
        { name: "Poll Answer", value: "poll_answer" },
        { name: "Pre-Checkout Query", value: "pre_checkout_query" },
        { name: "Shipping Query", value: "shipping_query" },
        { name: "Purchased Paid Media", value: "purchased_paid_media" },
        { name: "Message Reaction", value: "message_reaction" },
        { name: "Message Reaction Count", value: "message_reaction_count" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      placeholder: "Add option",
      options: [
        {
          displayName: "Download Images",
          name: "downloadImages",
          type: "boolean",
          default: false,
          description: "When true, attached images/files are fetched from Telegram and added as binary data to the emitted item",
        },
        {
          displayName: "Image Size",
          name: "imageSize",
          type: "options",
          default: "large",
          displayOptions: { show: { downloadImages: [true] } },
          options: [
            { name: "Small", value: "small" },
            { name: "Medium", value: "medium" },
            { name: "Large", value: "large" },
          ],
        },
        {
          displayName: "Restrict to Chat IDs",
          name: "restrictToChatIds",
          type: "string",
          default: "",
          description: "Comma-separated chat IDs; only updates originating from these chats are emitted",
        },
        {
          displayName: "Restrict to User IDs",
          name: "restrictToUserIds",
          type: "string",
          default: "",
          description: "Comma-separated user IDs; only updates originating from these users are emitted",
        },
      ],
    },
  ],
};

const RABBITMQ_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.rabbitmq/";

export const rabbitmq: INodeTypeDescription = {
  name: "n8n-nodes-base.rabbitmq",
  displayName: "RabbitMQ",
  category: "Communication",
  group: ["communication"],
  version: 1,
  description: "Send and receive messages via RabbitMQ",
  defaults: { name: "RabbitMQ" },
  inputs: ["main"],
  outputs: ["main"],
  credentials: [{ name: "rabbitmq", required: true }],
  icon: "MessageCircle",
  sources: [RABBITMQ_DOCS],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "sendMessage",
      noDataExpression: true,
      options: [
        { name: "Send a Message", value: "sendMessage" },
        { name: "Delete From Queue", value: "deleteMessage" },
      ],
    },
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "queue",
      required: true,
      displayOptions: { show: { operation: ["sendMessage"] } },
      options: [
        { name: "Queue", value: "queue" },
        { name: "Exchange", value: "exchange" },
      ],
    },
    {
      displayName: "Queue",
      name: "queue",
      type: "string",
      default: "",
      description: "Name of the queue (required when mode=queue)",
    },
    {
      displayName: "Exchange",
      name: "exchange",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["sendMessage"], mode: ["exchange"] } },
      description: "Exchange name to publish to",
    },
    {
      displayName: "Exchange Type",
      name: "exchangeType",
      type: "options",
      default: "fanout",
      displayOptions: { show: { operation: ["sendMessage"], mode: ["exchange"] } },
      options: [
        { name: "Direct", value: "direct" },
        { name: "Topic", value: "topic" },
        { name: "Headers", value: "headers" },
        { name: "Fanout", value: "fanout" },
      ],
    },
    {
      displayName: "Routing Key",
      name: "routingKey",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["sendMessage"], mode: ["exchange"] } },
      description: "Routing key for the exchange",
    },
    {
      displayName: "Send Input Data",
      name: "sendInputData",
      type: "boolean",
      default: true,
      displayOptions: { show: { operation: ["sendMessage"] } },
      description: "Whether to send the input data as the message",
    },
    {
      displayName: "Message",
      name: "message",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["sendMessage"], sendInputData: [false] } },
      description: "Custom message to send",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["sendMessage"] } },
      options: [
        {
          displayName: "Alternate Exchange",
          name: "alternateExchange",
          type: "string",
          default: "",
          description: "Fallback exchange when primary exchange cannot route",
        },
        {
          displayName: "Arguments",
          name: "arguments",
          type: "fixedCollection",
          default: {},
          options: [
            {
              name: "values",
              displayName: "Values",
              values: [
                { displayName: "Key", name: "key", type: "string", default: "" },
                { displayName: "Value", name: "value", type: "string", default: "" },
              ],
            },
          ],
        },
        {
          displayName: "Auto Delete Queue",
          name: "autoDelete",
          type: "boolean",
          default: false,
        },
        {
          displayName: "Durable",
          name: "durable",
          type: "boolean",
          default: true,
        },
        {
          displayName: "Exclusive",
          name: "exclusive",
          type: "boolean",
          default: false,
          displayOptions: { show: { "/mode": ["queue"] } },
        },
        {
          displayName: "Headers",
          name: "headers",
          type: "fixedCollection",
          default: {},
          typeOptions: { multipleValues: true },
          options: [
            {
              name: "values",
              displayName: "Values",
              values: [
                { displayName: "Key", name: "key", type: "string", default: "" },
                { displayName: "Value", name: "value", type: "string", default: "" },
              ],
            },
          ],
        },
      ],
    },
  ],
};
