import type { INodeTypeDescription } from "../types";

const CORE = "https://docs.n8n.io/integrations/builtin/core-nodes/";

export const httpRequest: INodeTypeDescription = {
  name: "n8n-nodes-base.httpRequest",
  displayName: "HTTP Request",
  category: "Actions",
  group: ["input"],
  version: 4.2,
  description: "Makes an HTTP request and returns the response.",
  defaults: { name: "HTTP Request" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Globe",
  credentials: [{ name: "httpBasicAuth" }, { name: "httpHeaderAuth" }],
  sources: [`${CORE}n8n-nodes-base.httprequest/`],
  properties: [
    {
      displayName: "Method",
      name: "method",
      type: "options",
      default: "GET",
      noDataExpression: true,
      options: [
        { name: "GET", value: "GET" },
        { name: "POST", value: "POST" },
        { name: "PUT", value: "PUT" },
        { name: "PATCH", value: "PATCH" },
        { name: "DELETE", value: "DELETE" },
        { name: "HEAD", value: "HEAD" },
        { name: "OPTIONS", value: "OPTIONS" },
      ],
    },
    {
      displayName: "URL",
      name: "url",
      type: "string",
      default: "",
      required: true,
      placeholder: "https://api.example.com/resource",
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "none",
      options: [
        { name: "None", value: "none" },
        { name: "Predefined Credential Type", value: "predefinedCredentialType" },
        { name: "Generic Credential Type", value: "genericCredentialType" },
      ],
    },
    {
      displayName: "Send Query Parameters",
      name: "sendQuery",
      type: "boolean",
      default: false,
    },
    {
      displayName: "Query Parameters",
      name: "queryParameters",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { sendQuery: [true] } },
      options: [
        {
          name: "parameters",
          displayName: "Parameter",
          values: [
            { displayName: "Name", name: "name", type: "string", default: "" },
            { displayName: "Value", name: "value", type: "string", default: "" },
          ],
        },
      ],
    },
    {
      displayName: "Send Headers",
      name: "sendHeaders",
      type: "boolean",
      default: false,
    },
    {
      displayName: "Headers",
      name: "headerParameters",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { sendHeaders: [true] } },
      options: [
        {
          name: "parameters",
          displayName: "Header",
          values: [
            { displayName: "Name", name: "name", type: "string", default: "" },
            { displayName: "Value", name: "value", type: "string", default: "" },
          ],
        },
      ],
    },
    {
      displayName: "Send Body",
      name: "sendBody",
      type: "boolean",
      default: false,
      displayOptions: { hide: { method: ["GET", "HEAD"] } },
    },
    {
      displayName: "Body Content Type",
      name: "contentType",
      type: "options",
      default: "json",
      displayOptions: { show: { sendBody: [true] } },
      options: [
        { name: "JSON", value: "json" },
        { name: "Form Urlencoded", value: "form-urlencoded" },
        { name: "Raw", value: "raw" },
      ],
    },
    {
      displayName: "JSON Body",
      name: "jsonBody",
      type: "json",
      default: "{}",
      displayOptions: { show: { sendBody: [true], contentType: ["json"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        { displayName: "Timeout (ms)", name: "timeout", type: "number", default: 10000 },
        {
          displayName: "Ignore SSL Issues",
          name: "allowUnauthorizedCerts",
          type: "boolean",
          default: false,
        },
        { displayName: "Full Response", name: "fullResponse", type: "boolean", default: false },
        { displayName: "Follow Redirects", name: "followRedirect", type: "boolean", default: true },
      ],
    },
  ],
};

export const set: INodeTypeDescription = {
  name: "n8n-nodes-base.set",
  displayName: "Edit Fields (Set)",
  category: "Transform",
  group: ["transform"],
  version: 3.4,
  description: "Adds, renames or removes fields on each item.",
  defaults: { name: "Edit Fields" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "PencilLine",
  sources: [`${CORE}n8n-nodes-base.set/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "manual",
      noDataExpression: true,
      options: [
        { name: "Manual Mapping", value: "manual" },
        { name: "JSON Output", value: "raw" },
      ],
    },
    {
      displayName: "Fields to Set",
      name: "fields",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { mode: ["manual"] } },
      options: [
        {
          name: "values",
          displayName: "Field",
          values: [
            { displayName: "Name", name: "name", type: "string", default: "" },
            {
              displayName: "Type",
              name: "type",
              type: "options",
              default: "stringValue",
              options: [
                { name: "String", value: "stringValue" },
                { name: "Number", value: "numberValue" },
                { name: "Boolean", value: "booleanValue" },
                { name: "Array", value: "arrayValue" },
                { name: "Object", value: "objectValue" },
              ],
            },
            {
              displayName: "String Value",
              name: "stringValue",
              type: "string",
              default: "",
              displayOptions: { show: { type: ["stringValue"] } },
            },
            {
              displayName: "Number Value",
              name: "numberValue",
              type: "string",
              default: "",
              displayOptions: { show: { type: ["numberValue"] } },
            },
            {
              displayName: "Boolean Value",
              name: "booleanValue",
              type: "options",
              default: true,
              options: [
                { name: "True", value: true },
                { name: "False", value: false },
              ],
              displayOptions: { show: { type: ["booleanValue"] } },
            },
            {
              displayName: "Array Value",
              name: "arrayValue",
              type: "string",
              default: "",
              displayOptions: { show: { type: ["arrayValue"] } },
            },
            {
              displayName: "Object Value",
              name: "objectValue",
              type: "json",
              default: "{}",
              displayOptions: { show: { type: ["objectValue"] } },
            },
          ],
        },
      ],
    },
    {
      displayName: "Assignments",
      name: "assignments",
      type: "assignmentCollection",
      default: { assignments: [] },
      displayOptions: { show: { mode: ["manual"] } },
    },
    {
      displayName: "JSON",
      name: "jsonOutput",
      type: "json",
      default: '{\n  "key": "value"\n}',
      displayOptions: { show: { mode: ["raw"] } },
    },
    {
      displayName: "Include in Output",
      name: "include",
      type: "options",
      default: "all",
      options: [
        { name: "All Input Fields", value: "all" },
        { name: "No Input Fields", value: "none" },
        { name: "Selected Input Fields", value: "selected" },
        { name: "All Input Fields Except", value: "except" },
      ],
    },
    {
      displayName: "Include Other Input Fields",
      name: "includeOtherFields",
      type: "boolean",
      default: false,
    },
    {
      displayName: "Fields to Include",
      name: "includeFields",
      type: "string",
      default: "",
      displayOptions: { show: { include: ["selected"] } },
    },
    {
      displayName: "Fields to Exclude",
      name: "excludeFields",
      type: "string",
      default: "",
      displayOptions: { show: { include: ["except"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Ignore Type Conversion Errors",
          name: "ignoreConversionErrors",
          type: "boolean",
          default: false,
        },
        { displayName: "Dot Notation", name: "dotNotation", type: "boolean", default: true },
        {
          displayName: "Include Binary Data",
          name: "includeBinary",
          type: "boolean",
          default: true,
        },
        { displayName: "Strip Binary Data", name: "stripBinary", type: "boolean", default: true },
      ],
    },
  ],
};

export const code: INodeTypeDescription = {
  name: "n8n-nodes-base.code",
  displayName: "Code",
  category: "Transform",
  group: ["transform"],
  version: 2,
  description: "Runs custom JavaScript against the incoming items.",
  defaults: { name: "Code" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Braces",
  sources: [`${CORE}n8n-nodes-base.code/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "runOnceForAllItems",
      noDataExpression: true,
      options: [
        { name: "Run Once for All Items", value: "runOnceForAllItems" },
        { name: "Run Once for Each Item", value: "runOnceForEachItem" },
      ],
    },
    {
      displayName: "Language",
      name: "language",
      type: "options",
      default: "javaScript",
      noDataExpression: true,
      options: [
        { name: "JavaScript", value: "javaScript" },
        { name: "Python", value: "pythonNative" },
      ],
    },
    {
      displayName: "JavaScript",
      name: "jsCode",
      type: "string",
      default: "// Each item is { json: {...} }\nreturn $input.all();",
      noDataExpression: true,
      typeOptions: { editor: "code", rows: 16 },
      displayOptions: { show: { language: ["javaScript"] } },
    },
    {
      displayName: "Python",
      name: "pythonCode",
      type: "string",
      default: "# for item in _items:\n#   pass",
      noDataExpression: true,
      typeOptions: { editor: "code", rows: 16 },
      displayOptions: { show: { language: ["pythonNative", "python"] } },
    },
    {
      displayName: "Code runs in a sandbox. Network access is disabled by default in this build.",
      name: "notice",
      type: "notice",
      default: "",
    },
  ],
};

export const stopAndError: INodeTypeDescription = {
  name: "n8n-nodes-base.stopAndError",
  displayName: "Stop and Error",
  category: "Flow",
  group: ["transform"],
  version: 1,
  description: "Stops the workflow and throws a custom error message or object.",
  defaults: { name: "Stop and Error" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "OctagonAlert",
  sources: [`${CORE}n8n-nodes-base.stopanderror/`],
  properties: [
    {
      displayName: "Error Type",
      name: "errorType",
      type: "options",
      default: "errorMessage",
      noDataExpression: true,
      options: [
        { name: "Error Message", value: "errorMessage" },
        { name: "Error Object", value: "errorObject" },
      ],
    },
    {
      displayName: "Error Message",
      name: "errorMessage",
      type: "string",
      default: "Workflow stopped with an error",
      displayOptions: { show: { errorType: ["errorMessage"] } },
    },
    {
      displayName: "Error Object",
      name: "errorObject",
      type: "json",
      default: '{"message":"Stopped"}',
      displayOptions: { show: { errorType: ["errorObject"] } },
    },
  ],
};

export const noOp: INodeTypeDescription = {
  name: "n8n-nodes-base.noOp",
  displayName: "No Operation",
  category: "Helpers",
  group: ["organization"],
  version: 1,
  description: "Passes items through unchanged. Useful as a join or marker.",
  defaults: { name: "No Operation" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "CircleDashed",
  sources: [`${CORE}n8n-nodes-base.noop/`],
  properties: [
    {
      displayName: "This node does nothing. Items pass through untouched.",
      name: "notice",
      type: "notice",
      default: "",
    },
  ],
};

export const executionData: INodeTypeDescription = {
  name: "n8n-nodes-base.executionData",
  displayName: "Execution Data",
  category: "Helpers",
  group: ["organization"],
  version: 1.1,
  description:
    "Saves custom data on the current execution for later search and review. Items pass through unchanged.",
  defaults: { name: "Execution Data" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Database",
  sources: [
    `${CORE}n8n-nodes-base.executiondata/`,
    "https://docs.n8n.io/build/understand-workflows/understand-executions/customize-executions-data.md",
  ],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "save",
      noDataExpression: true,
      options: [{ name: "Save Highlight Data (for Search/review)", value: "save" }],
    },
    {
      displayName: "Data to Save",
      name: "dataToSave",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { operation: ["save"] } },
      options: [
        {
          name: "values",
          displayName: "Saved Field",
          values: [
            {
              displayName: "Key",
              name: "key",
              type: "string",
              default: "",
              placeholder: "contact",
            },
            {
              displayName: "Value",
              name: "value",
              type: "string",
              default: "",
              placeholder: "={{ $json.email }}",
            },
          ],
        },
      ],
    },
  ],
};

const SIGN_ALGORITHMS = [
  "RSA-MD5", "RSA-RIPEMD160", "RSA-SHA1", "RSA-SHA1-2", "RSA-SHA224",
  "RSA-SHA256", "RSA-SHA3-224", "RSA-SHA3-256", "RSA-SHA3-384",
  "RSA-SHA3-512", "RSA-SHA384", "RSA-SHA512", "RSA-SHA512/224",
  "RSA-SHA512/256", "RSA-SM3", "blake2b512", "blake2s256",
  "id-rsassa-pkcs1-v1_5-with-sha3-224", "id-rsassa-pkcs1-v1_5-with-sha3-256",
  "id-rsassa-pkcs1-v1_5-with-sha3-384", "id-rsassa-pkcs1-v1_5-with-sha3-512",
  "md5", "md5-sha1", "md5WithRSAEncryption", "ripemd", "ripemd160",
  "ripemd160WithRSA", "rmd160", "sha1", "sha1WithRSAEncryption", "sha224",
  "sha224WithRSAEncryption", "sha256", "sha256WithRSAEncryption", "sha3-224",
  "sha3-256", "sha3-384", "sha3-512", "sha384", "sha384WithRSAEncryption",
  "sha512", "sha512-224", "sha512-224WithRSAEncryption", "sha512-256",
  "sha512-256WithRSAEncryption", "sha512WithRSAEncryption", "shake128",
  "shake256", "sm3", "sm3WithRSAEncryption", "ssl3-md5", "ssl3-sha1",
];

export const crypto: INodeTypeDescription = {
  name: "n8n-nodes-base.crypto",
  displayName: "Crypto",
  category: "Transform",
  group: ["transform"],
  version: 2,
  description:
    "Perform cryptographic operations: decrypt, encrypt, generate a random string, hash, HMAC, and sign.",
  defaults: { name: "Crypto" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Lock",
  credentials: [{ name: "crypto" }],
  sources: [`${CORE}n8n-nodes-base.crypto/`],
  properties: [
    {
      displayName: "Action",
      name: "action",
      type: "options",
      default: "hash",
      noDataExpression: true,
      options: [
        { name: "Generate", value: "generate" },
        { name: "Hash", value: "hash" },
        { name: "HMAC", value: "hmac" },
        { name: "Sign", value: "sign" },
        { name: "Encrypt", value: "encrypt" },
        { name: "Decrypt", value: "decrypt" },
      ],
    },
    {
      displayName: "Value",
      name: "value",
      type: "string",
      default: "",
      displayOptions: {
        show: { action: ["hash", "hmac", "sign", "encrypt", "decrypt"] },
      },
    },
    {
      displayName: "Algorithm",
      name: "type",
      type: "options",
      default: "SHA256",
      displayOptions: { show: { action: ["hash", "hmac"] } },
      options: [
        { name: "MD5", value: "MD5" },
        { name: "SHA256", value: "SHA256" },
        { name: "SHA3-256", value: "SHA3-256" },
        { name: "SHA3-384", value: "SHA3-384" },
        { name: "SHA3-512", value: "SHA3-512" },
        { name: "SHA384", value: "SHA384" },
        { name: "SHA512", value: "SHA512" },
      ],
    },
    {
      displayName: "Binary Data",
      name: "binaryData",
      type: "boolean",
      default: false,
      displayOptions: { show: { action: ["hash", "hmac"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: {
        show: { action: ["hash", "hmac"], binaryData: [true] },
      },
    },
    {
      displayName: "Output Property",
      name: "dataPropertyName",
      type: "string",
      default: "data",
      displayOptions: {
        show: {
          action: ["hash", "hmac", "sign", "generate", "encrypt", "decrypt"],
        },
      },
    },
    {
      displayName: "Encoding",
      name: "encoding",
      type: "options",
      default: "hex",
      displayOptions: { show: { action: ["hash", "hmac", "sign"] } },
      options: [
        { name: "Base64", value: "base64" },
        { name: "Hex", value: "hex" },
      ],
    },
    {
      displayName: "Algorithm",
      name: "algorithm",
      type: "options",
      default: "sha256",
      displayOptions: { show: { action: ["sign"] } },
      options: SIGN_ALGORITHMS.map((v) => ({ name: v, value: v })),
    },
    {
      displayName: "Encoding Type",
      name: "encodingType",
      type: "options",
      default: "uuid",
      displayOptions: { show: { action: ["generate"] } },
      options: [
        { name: "ASCII", value: "ascii" },
        { name: "Base64", value: "base64" },
        { name: "Hex", value: "hex" },
        { name: "UUID", value: "uuid" },
      ],
    },
    {
      displayName: "Length",
      name: "stringLength",
      type: "number",
      default: 32,
      displayOptions: {
        show: {
          action: ["generate"],
          encodingType: ["ascii", "base64", "hex"],
        },
      },
    },
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "symmetric",
      displayOptions: { show: { action: ["encrypt", "decrypt"] } },
      options: [
        { name: "Symmetric (Passphrase)", value: "symmetric" },
        { name: "Asymmetric (RSA)", value: "asymmetric" },
      ],
    },
    {
      displayName: "Cipher",
      name: "cipher",
      type: "options",
      default: "AES-256-GCM",
      displayOptions: {
        show: { action: ["encrypt", "decrypt"], mode: ["symmetric"] },
      },
      options: [
        { name: "AES-256-GCM", value: "AES-256-GCM" },
        { name: "AES-192-GCM", value: "AES-192-GCM" },
        { name: "AES-128-GCM", value: "AES-128-GCM" },
        { name: "ChaCha20-Poly1305", value: "ChaCha20-Poly1305" },
      ],
    },
  ],
};

export const ftp: INodeTypeDescription = {
  name: "n8n-nodes-base.ftp",
  displayName: "FTP",
  category: "Actions",
  group: ["input"],
  version: 1,
  description: "Access and transfer files on an FTP or SFTP server.",
  defaults: { name: "FTP" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Server",
  credentials: [{ name: "ftp" }, { name: "sftp" }],
  sources: [`${CORE}n8n-nodes-base.ftp/`],
  properties: [
    {
      displayName: "Protocol",
      name: "protocol",
      type: "options",
      default: "ftp",
      noDataExpression: true,
      options: [
        { name: "FTP", value: "ftp" },
        { name: "SFTP", value: "sftp" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "download",
      noDataExpression: true,
      options: [
        { name: "Delete", value: "delete" },
        { name: "Download", value: "download" },
        { name: "List", value: "list" },
        { name: "Rename", value: "rename" },
        { name: "Upload", value: "upload" },
      ],
    },
    {
      displayName: "Path",
      name: "path",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { operation: ["delete", "download", "list", "upload"] } },
    },
    {
      displayName: "Old Path",
      name: "oldPath",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { operation: ["rename"] } },
    },
    {
      displayName: "New Path",
      name: "newPath",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { operation: ["rename"] } },
    },
    {
      displayName: "Put Output File in Field",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: {
        show: { operation: ["download"] },
      },
    },
    {
      displayName: "Upload from Binary",
      name: "binaryData",
      type: "boolean",
      default: true,
      displayOptions: { show: { operation: ["upload"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { operation: ["upload"], binaryData: [true] } },
    },
    {
      displayName: "File Content",
      name: "fileContent",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["upload"], binaryData: [false] } },
    },
    {
      displayName: "Recursive",
      name: "recursive",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["list"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        { displayName: "Allow Folder Delete", name: "folder", type: "boolean", default: false },
        { displayName: "Recursive Delete", name: "recursive", type: "boolean", default: false },
        {
          displayName: "Create Directories",
          name: "createDirectories",
          type: "boolean",
          default: false,
        },
        { displayName: "Timeout (ms)", name: "timeout", type: "number", default: 10000 },
        {
          displayName: "Enable Concurrent Reads",
          name: "enableConcurrentReads",
          type: "boolean",
          default: false,
        },
        {
          displayName: "Max Concurrent Reads",
          name: "maxConcurrentReads",
          type: "number",
          default: 5,
        },
        { displayName: "Chunk Size (KB)", name: "chunkSize", type: "number", default: 64 },
      ],
    },
  ],
};

export const emailSend: INodeTypeDescription = {
  name: "n8n-nodes-base.emailSend",
  displayName: "Send Email",
  category: "Actions",
  group: ["input"],
  version: 2,
  description: "Sends an email via SMTP.",
  defaults: { name: "Send Email" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Mail",
  credentials: [{ name: "smtp" }],
  sources: [`${CORE}n8n-nodes-base.emailsend/`],
  properties: [
    {
      displayName: "From Email",
      name: "fromEmail",
      type: "string",
      default: "",
      required: true,
      placeholder: "bot@example.com",
    },
    {
      displayName: "From Name",
      name: "fromName",
      type: "string",
      default: "",
    },
    {
      displayName: "To Email",
      name: "toEmail",
      type: "string",
      default: "",
      required: true,
      placeholder: "user@example.com",
    },
    {
      displayName: "CC Email",
      name: "ccEmail",
      type: "string",
      default: "",
    },
    {
      displayName: "BCC Email",
      name: "bccEmail",
      type: "string",
      default: "",
    },
    {
      displayName: "Reply To",
      name: "replyTo",
      type: "string",
      default: "",
    },
    {
      displayName: "Subject",
      name: "subject",
      type: "string",
      default: "",
      required: true,
    },
    {
      displayName: "Email Format",
      name: "emailFormat",
      type: "options",
      default: "text",
      noDataExpression: true,
      options: [
        { name: "Text", value: "text" },
        { name: "HTML", value: "html" },
      ],
    },
    {
      displayName: "Message",
      name: "message",
      type: "string",
      default: "",
      typeOptions: { rows: 8 },
      displayOptions: { show: { emailFormat: ["text"] } },
    },
    {
      displayName: "HTML Message",
      name: "htmlMessage",
      type: "string",
      default: "",
      typeOptions: { rows: 8 },
      displayOptions: { show: { emailFormat: ["html"] } },
    },
    {
      displayName: "Attachments",
      name: "attachmentsUi",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      options: [
        {
          name: "attachments",
          displayName: "Attachment",
          values: [
            {
              displayName: "Binary Property",
              name: "binaryPropertyName",
              type: "string",
              default: "data",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Allow Unauthorized Certs",
          name: "allowUnauthorizedCerts",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const stickyNote: INodeTypeDescription = {
  name: "n8n-nodes-base.stickyNote",
  displayName: "Sticky Note",
  category: "Helpers",
  group: ["organization"],
  version: 1,
  description: "A canvas annotation. Not part of execution.",
  defaults: { name: "Sticky Note" },
  inputs: [],
  outputs: [],
  icon: "StickyNote",
  sources: [`${CORE}n8n-nodes-base.stickynote/`],
  properties: [
    {
      displayName: "Content",
      name: "content",
      type: "string",
      default: "## Note\nAdd context for your team here.",
      typeOptions: { rows: 8 },
      noDataExpression: true,
    },
    { displayName: "Width", name: "width", type: "number", default: 320 },
    { displayName: "Height", name: "height", type: "number", default: 180 },
    {
      displayName: "Color",
      name: "color",
      type: "options",
      default: 1,
      options: [
        { name: "Sand", value: 1 },
        { name: "Teal", value: 2 },
        { name: "Amber", value: 3 },
        { name: "Rose", value: 4 },
      ],
    },
  ],
};

const LANGCHAIN_DOCS =
  "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatopenai.md";

export const lmChatOpenAi: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.lmChatOpenAi",
  displayName: "OpenAI Chat Model",
  category: "Actions",
  group: ["input"],
  version: 1.3,
  description:
    "Configures an OpenAI chat model and supplies it to an AI Agent or Chain on the ai_languageModel channel.",
  defaults: { name: "OpenAI Chat Model" },
  inputs: [],
  outputs: ["ai_languageModel"],
  icon: "Robot",
  credentials: [{ name: "openAiApi", required: true }],
  sources: [LANGCHAIN_DOCS],
  properties: [
    {
      displayName: "Model",
      name: "model",
      type: "resourceLocator",
      default: "",
      required: true,
    },
    {
      displayName: "Use Responses API",
      name: "responsesApiEnabled",
      type: "boolean",
      default: false,
    },
    {
      displayName: "Built-in Tools",
      name: "builtInTools",
      type: "collection",
      default: {},
      displayOptions: { show: { responsesApiEnabled: [true] } },
      options: [
        {
          displayName: "Web Search",
          name: "webSearch",
          type: "collection",
          default: {},
          options: [
            {
              displayName: "Search Context Size",
              name: "searchContextSize",
              type: "options",
              default: "medium",
              options: [
                { name: "Low", value: "low" },
                { name: "Medium", value: "medium" },
                { name: "High", value: "high" },
              ],
            },
          ],
        },
        {
          displayName: "File Search",
          name: "fileSearch",
          type: "collection",
          default: {},
        },
        {
          displayName: "Code Interpreter",
          name: "codeInterpreter",
          type: "collection",
          default: {},
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Sampling Temperature",
          name: "temperature",
          type: "number",
          default: 1,
        },
        {
          displayName: "Maximum Number of Tokens",
          name: "maxTokens",
          type: "number",
          default: 0,
        },
        {
          displayName: "Frequency Penalty",
          name: "frequencyPenalty",
          type: "number",
          default: 0,
        },
        {
          displayName: "Presence Penalty",
          name: "presencePenalty",
          type: "number",
          default: 0,
        },
        { displayName: "Top P", name: "topP", type: "number", default: 1 },
        {
          displayName: "Timeout (ms)",
          name: "timeout",
          type: "number",
          default: 120000,
        },
        {
          displayName: "Max Retries",
          name: "maxRetries",
          type: "number",
          default: 2,
        },
        {
          displayName: "Conversation ID",
          name: "conversationId",
          type: "string",
          default: "",
          displayOptions: { show: { responsesApiEnabled: [true] } },
        },
        {
          displayName: "Prompt Cache Key",
          name: "promptCacheKey",
          type: "string",
          default: "",
          displayOptions: { show: { responsesApiEnabled: [true] } },
        },
        {
          displayName: "Safety Identifier",
          name: "safetyIdentifier",
          type: "string",
          default: "",
          displayOptions: { show: { responsesApiEnabled: [true] } },
        },
        {
          displayName: "Service Tier",
          name: "serviceTier",
          type: "options",
          default: "auto",
          displayOptions: { show: { responsesApiEnabled: [true] } },
          options: [
            { name: "Auto", value: "auto" },
            { name: "Flex", value: "flex" },
            { name: "Default", value: "default" },
            { name: "Priority", value: "priority" },
          ],
        },
      ],
    },
  ],
};

const AGENT_DOCS =
  "https://docs.n8n.io/integrations/builtin/cluster-nodes/root-nodes/n8n-nodes-langchain.agent.md";

export const langchainAgent: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.agent",
  displayName: "AI Agent",
  category: "Actions",
  group: ["input"],
  version: 1.9,
  description:
    "Runs an autonomous agent that uses a connected chat model and tools to answer a user prompt.",
  defaults: { name: "AI Agent" },
  inputs: ["main", "ai_languageModel", "ai_tool", "ai_memory", "ai_outputParser"],
  outputs: ["main"],
  icon: "Robot",
  sources: [AGENT_DOCS],
  properties: [
    {
      displayName: "Prompt",
      name: "promptType",
      type: "options",
      default: "auto",
      noDataExpression: true,
      options: [
        { name: "Define below", value: "define" },
        {
          name: "Take from previous node automatically",
          value: "auto",
        },
      ],
    },
    {
      displayName: "Prompt (User Message)",
      name: "text",
      type: "string",
      default: "",
      typeOptions: { rows: 4 },
      displayOptions: { show: { promptType: ["define"] } },
    },
    {
      displayName: "Require Specific Output Format",
      name: "hasOutputParser",
      type: "boolean",
      default: false,
    },
    {
      displayName: "Enable Fallback Model",
      name: "needsFallback",
      type: "boolean",
      default: false,
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "System Message",
          name: "systemMessage",
          type: "string",
          default: "",
          typeOptions: { rows: 4 },
        },
        {
          displayName: "Max Iterations",
          name: "maxIterations",
          type: "number",
          default: 10,
        },
        {
          displayName: "Return Intermediate Steps",
          name: "returnIntermediateSteps",
          type: "boolean",
          default: false,
        },
        {
          displayName: "Passthrough Binary Images",
          name: "passthroughBinaryImages",
          type: "boolean",
          default: true,
        },
{
      displayName: "Enable Streaming",
      name: "enableStreaming",
      type: "boolean",
      default: true,
    },
      ],
    },
  ],
};

const MCP_CLIENT_TOOL_DOCS =
  "https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.toolmcp.md";

export const mcpClientTool: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.mcpClientTool",
  displayName: "MCP Client Tool",
  category: "Actions",
  group: ["input"],
  version: 1.4,
  description:
    "Connects to an MCP server, discovers its tools, and exposes selected tools to an AI Agent on the ai_tool channel.",
  defaults: { name: "MCP Client Tool" },
  inputs: [],
  outputs: ["ai_tool"],
  icon: "Robot",
  credentials: [
    { name: "httpHeaderAuth" },
    { name: "httpBearerAuth" },
  ],
  sources: [MCP_CLIENT_TOOL_DOCS],
  properties: [
    {
      displayName: "SSE Endpoint",
      name: "sseEndpoint",
      type: "string",
      default: "",
      placeholder: "https://host/mcp/sse",
    },
    {
      displayName: "MCP Endpoint URL",
      name: "endpointUrl",
      type: "string",
      default: "",
      placeholder: "https://host/mcp",
    },
    {
      displayName: "Server Transport",
      name: "serverTransport",
      type: "options",
      default: "",
      options: [
        { name: "SSE", value: "sse" },
        { name: "Streamable HTTP", value: "httpStreamable" },
      ],
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "none",
      options: [
        { name: "None", value: "none" },
        { name: "Bearer Auth", value: "bearerAuth" },
        { name: "Header Auth", value: "headerAuth" },
        { name: "Multiple Headers", value: "multipleHeadersAuth" },
        { name: "OAuth2", value: "oAuth2Api" },
      ],
    },
    {
      displayName: "Tools to Include",
      name: "include",
      type: "options",
      default: "all",
      options: [
        { name: "All", value: "all" },
        { name: "Selected", value: "selected" },
        { name: "All Except", value: "allExcept" },
      ],
    },
    {
      displayName: "Tools to Include",
      name: "includeTools",
      type: "multiOptions",
      default: [],
      displayOptions: { show: { include: ["selected"] } },
    },
    {
      displayName: "Tools to Exclude",
      name: "excludeTools",
      type: "multiOptions",
      default: [],
      displayOptions: { show: { include: ["allExcept"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        { displayName: "Timeout (ms)", name: "timeout", type: "number", default: 60000 },
      ],
    },
  ],
};
