import type { INodeTypeDescription } from "../types";

const SHAREPOINT_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsoftsharepoint/";

export const microsoftSharePoint: INodeTypeDescription = {
  name: "openflow-node-base.microsoftSharePoint",
  displayName: "Microsoft SharePoint",
  category: "Helpers",
  group: ["organization"],
  version: 1,
  description: "Access Microsoft SharePoint lists, items, and files",
  defaults: { name: "Microsoft SharePoint" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileText",
  sources: [SHAREPOINT_DOCS],
  credentials: [
    { name: "microsoftSharePointOAuth2Api", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      options: [
        { name: "File", value: "file" },
        { name: "Item", value: "item" },
        { name: "List", value: "list" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Download", value: "download" },
        { name: "Upload", value: "upload" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "Data Property Name",
      name: "dataPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
      options: [
        {
          displayName: "Metadata",
          name: "metadata",
          type: "json",
          default: "",
        },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["item"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Create or Update", value: "upsert" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"] } },
    },
    {
      displayName: "List",
      name: "list",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"] } },
    },
    {
      displayName: "Columns",
      name: "columns",
      type: "fixedCollection",
      default: {},
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["create", "upsert"] } },
      options: [
        {
          name: "fields",
          displayName: "Fields",
          values: [
            {
              displayName: "Field Values",
              name: "fieldsJson",
              type: "json",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Item",
      name: "item",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Columns",
      name: "columns",
      type: "fixedCollection",
      default: {},
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["update"] } },
      options: [
        {
          name: "fields",
          displayName: "Fields",
          values: [
            {
              displayName: "Field Values",
              name: "fieldsJson",
              type: "json",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      options: [
        {
          displayName: "OData Filter",
          name: "odataFilter",
          type: "string",
          default: "",
          placeholder: "e.g. fields/Title eq 'Task'",
        },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["list"] } },
    },
    {
      displayName: "List",
      name: "list",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["list"], operation: ["get"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
      options: [
        {
          displayName: "OData Filter",
          name: "odataFilter",
          type: "string",
          default: "",
        },
      ],
    },
  ],
};

export const microsoftSharePointTool: INodeTypeDescription = {
  name: "openflow-node-base.microsoftSharePointTool",
  displayName: "Microsoft SharePoint Tool",
  category: "Helpers",
  group: ["organization"],
  version: 1,
  description: "Access Microsoft SharePoint lists, items, and files (tool variant)",
  defaults: { name: "Microsoft SharePoint Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileText",
  sources: [SHAREPOINT_DOCS],
  credentials: [
    { name: "microsoftSharePointOAuth2Api", required: true },
  ],
  usableAsTool: true,
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "file",
      required: true,
      noDataExpression: true,
      options: [
        { name: "File", value: "file" },
        { name: "Item", value: "item" },
        { name: "List", value: "list" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "download",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Download", value: "download" },
        { name: "Update", value: "update" },
        { name: "Upload", value: "upload" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"] } },
    },
    {
      displayName: "Folder",
      name: "folder",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      displayOptions: { show: { resource: ["file"], operation: ["download", "upload"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "Data Property Name",
      name: "dataPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "File Name",
      name: "fileName",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["upload", "update"] } },
    },
    {
      displayName: "File Contents",
      name: "fileContents",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["upload", "update"] } },
    },
    {
      displayName: "Change File Content",
      name: "changeFileContent",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["item"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Create or Update", value: "upsert" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"] } },
    },
    {
      displayName: "List",
      name: "list",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"] } },
    },
    {
      displayName: "Columns",
      name: "columns",
      type: "resourceMapper",
      default: { mappingMode: "defineBelow", value: {} },
      displayOptions: { show: { resource: ["item"], operation: ["create", "upsert", "update"] } },
    },
    {
      displayName: "Item",
      name: "item",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      displayOptions: { show: { resource: ["item"], operation: ["delete", "get", "update", "upsert"] } },
    },
    {
      displayName: "Filter",
      name: "filter",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      placeholder: "e.g. fields/Title eq 'Active'",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Simplify",
      name: "simplify",
      type: "boolean",
      default: true,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      options: [
        {
          displayName: "Fields",
          name: "fields",
          type: "string",
          default: "",
          placeholder: "Comma-separated field names",
        },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["list"] } },
    },
    {
      displayName: "List",
      name: "list",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      displayOptions: { show: { resource: ["list"], operation: ["get"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Simplify",
      name: "simplify",
      type: "boolean",
      default: true,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
    },
    {
      displayName: "Request Options",
      name: "requestOptions",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Batching",
          name: "batching",
          type: "boolean",
          default: false,
        },
        {
          displayName: "Allow Unauthorized Certs",
          name: "allowUnauthorizedCerts",
          type: "boolean",
          default: false,
        },
        {
          displayName: "Proxy",
          name: "proxy",
          type: "string",
          default: "",
        },
        {
          displayName: "Timeout",
          name: "timeout",
          type: "number",
          default: 30000,
          typeOptions: { minValue: 1 },
        },
      ],
    },
  ],
};

export const nextCloud: INodeTypeDescription = {
  name: "openflow-node-base.nextCloud",
  displayName: "Nextcloud",
  category: "Helpers",
  group: ["data"],
  version: 1,
  description: "Access Nextcloud files, folders, and users via WebDAV and OCS APIs",
  defaults: { name: "Nextcloud" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileText",
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.nextcloud/",
  ],
  credentials: [
    { name: "nextCloudApi", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "file",
      required: true,
      noDataExpression: true,
      options: [
        { name: "File", value: "file" },
        { name: "Folder", value: "folder" },
        { name: "User", value: "user" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Copy", value: "copy" },
        { name: "Delete", value: "delete" },
        { name: "Download", value: "download" },
        { name: "Move", value: "move" },
        { name: "Share", value: "share" },
        { name: "Upload", value: "upload" },
      ],
    },
    {
      displayName: "File Path",
      name: "filePath",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["file"], operation: ["copy", "delete", "download", "move", "share", "upload"] },
      },
    },
    {
      displayName: "Source Path",
      name: "sourcePath",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["copy", "move"] } },
    },
    {
      displayName: "Destination Path",
      name: "destinationPath",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["file", "folder"], operation: ["copy", "move"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "Share Type",
      name: "shareType",
      type: "number",
      default: 3,
      displayOptions: { show: { resource: ["file", "folder"], operation: ["share"] } },
      typeOptions: { minValue: 0 },
    },
    {
      displayName: "Share Recipient",
      name: "shareRecipient",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file", "folder"], operation: ["share"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["folder"] } },
      options: [
        { name: "Copy", value: "copy" },
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "List", value: "list" },
        { name: "Move", value: "move" },
        { name: "Share", value: "share" },
      ],
    },
    {
      displayName: "Folder Path",
      name: "folderPath",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["folder"], operation: ["create", "list", "delete"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["user"] } },
      options: [
        { name: "Invite", value: "invite" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Edit", value: "edit" },
      ],
    },
    {
      displayName: "User ID",
      name: "userId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["user"], operation: ["delete", "get", "edit", "invite"] } },
    },
    {
      displayName: "User Data",
      name: "data",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["user"], operation: ["invite", "edit"] } },
    },
  ],
};

export const box: INodeTypeDescription = {
  name: "openflow-node-base.box",
  displayName: "Box",
  category: "Data & Storage",
  group: ["data"],
  version: 1,
  description: "Access Box files, folders, and shares",
  defaults: { name: "Box" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.box/",
  ],
  credentials: [
    { name: "boxOAuth2Api", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "file",
      required: true,
      noDataExpression: true,
      options: [
        { name: "File", value: "file" },
        { name: "Folder", value: "folder" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "copy",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Copy", value: "copy" },
        { name: "Delete", value: "delete" },
        { name: "Download", value: "download" },
        { name: "Get", value: "get" },
        { name: "Search", value: "search" },
        { name: "Share", value: "share" },
        { name: "Upload", value: "upload" },
      ],
    },
    {
      displayName: "File ID",
      name: "fileId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["file"], operation: ["copy", "delete", "download", "get", "share"] },
      },
    },
    {
      displayName: "Parent ID",
      name: "parentId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["copy"] } },
    },
    {
      displayName: "Name",
      name: "name",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["copy", "upload"] } },
    },
    {
      displayName: "File Name",
      name: "fileName",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "Binary Data",
      name: "binaryData",
      type: "boolean",
      default: true,
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "File Content",
      name: "fileContent",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file"], operation: ["upload"], binaryData: [false] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["upload", "download"] } },
    },
    {
      displayName: "Query",
      name: "query",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["search"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["file"], operation: ["copy", "delete", "share", "upload"] } },
      options: [
        {
          displayName: "Parent ID",
          name: "parentId",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
        },
        {
          displayName: "Description",
          name: "description",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
        },
        {
          displayName: "Content Created At",
          name: "contentCreatedAt",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
        },
        {
          displayName: "Content Modified At",
          name: "contentModifiedAt",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
        },
        {
          displayName: "Shared Link Access",
          name: "sharedLinkAccess",
          type: "options",
          default: "open",
          displayOptions: { show: { resource: ["file"], operation: ["share"] } },
          options: [
            { name: "Open", value: "open" },
            { name: "Company", value: "company" },
            { name: "Collaborators", value: "collaborators" },
          ],
        },
        {
          displayName: "Shared Link Password",
          name: "sharedLinkPassword",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["file"], operation: ["share"] } },
        },
        {
          displayName: "Shared Link Permissions",
          name: "sharedLinkPermissions",
          type: "collection",
          default: {},
          displayOptions: { show: { resource: ["file"], operation: ["share"] } },
          options: [
            {
              displayName: "Can Download",
              name: "canDownload",
              type: "boolean",
              default: true,
            },
            {
              displayName: "Can Preview",
              name: "canPreview",
              type: "boolean",
              default: true,
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["file"], operation: ["search"] } },
      options: [
        {
          displayName: "Content Type",
          name: "contentType",
          type: "string",
          default: "",
        },
        {
          displayName: "Sort",
          name: "sort",
          type: "string",
          default: "",
        },
        {
          displayName: "Limit",
          name: "limit",
          type: "number",
          default: 100,
          typeOptions: { minValue: 1 },
        },
        {
          displayName: "Offset",
          name: "offset",
          type: "number",
          default: 0,
          typeOptions: { minValue: 0 },
        },
        {
          displayName: "Ancestor Folder ID",
          name: "ancestorFolderId",
          type: "string",
          default: "",
        },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["folder"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Search", value: "search" },
        { name: "Share", value: "share" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Folder ID",
      name: "folderId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["folder"], operation: ["delete", "get", "share", "update"] } },
    },
    {
      displayName: "Name",
      name: "name",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["folder"], operation: ["create", "update"] } },
    },
    {
      displayName: "Parent ID",
      name: "parentId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["folder"], operation: ["create"] } },
    },
    {
      displayName: "Query",
      name: "query",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["folder"], operation: ["search"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["folder"], operation: ["create", "share", "update"] } },
      options: [
        {
          displayName: "Description",
          name: "description",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["folder"], operation: ["create", "update"] } },
        },
        {
          displayName: "Content Created At",
          name: "contentCreatedAt",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["folder"], operation: ["create", "update"] } },
        },
        {
          displayName: "Content Modified At",
          name: "contentModifiedAt",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["folder"], operation: ["create", "update"] } },
        },
        {
          displayName: "Can Non-Owners Invite",
          name: "canNonOwnersInvite",
          type: "boolean",
          default: true,
          displayOptions: { show: { resource: ["folder"], operation: ["update"] } },
        },
        {
          displayName: "Is Collaboration Restricted To Enterprise",
          name: "isCollaborationRestrictedToEnterprise",
          type: "boolean",
          default: false,
          displayOptions: { show: { resource: ["folder"], operation: ["update"] } },
        },
        {
          displayName: "Tags",
          name: "tags",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["folder"], operation: ["update"] } },
        },
        {
          displayName: "Upload Email Access",
          name: "uploadEmailAccess",
          type: "options",
          default: "",
          displayOptions: { show: { resource: ["folder"], operation: ["update"] } },
          options: [
            { name: "Open", value: "open" },
            { name: "Collaborators", value: "collaborators" },
          ],
        },
        {
          displayName: "Shared Link Access",
          name: "sharedLinkAccess",
          type: "options",
          default: "open",
          displayOptions: { show: { resource: ["folder"], operation: ["share"] } },
          options: [
            { name: "Open", value: "open" },
            { name: "Company", value: "company" },
            { name: "Collaborators", value: "collaborators" },
          ],
        },
        {
          displayName: "Shared Link Password",
          name: "sharedLinkPassword",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["folder"], operation: ["share"] } },
        },
        {
          displayName: "Shared Link Permissions",
          name: "sharedLinkPermissions",
          type: "collection",
          default: {},
          displayOptions: { show: { resource: ["folder"], operation: ["share"] } },
          options: [
            {
              displayName: "Can Download",
              name: "canDownload",
              type: "boolean",
              default: true,
            },
            {
              displayName: "Can Preview",
              name: "canPreview",
              type: "boolean",
              default: true,
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["folder"], operation: ["search"] } },
      options: [
        {
          displayName: "Content Type",
          name: "contentType",
          type: "string",
          default: "",
        },
        {
          displayName: "Sort",
          name: "sort",
          type: "string",
          default: "",
        },
        {
          displayName: "Limit",
          name: "limit",
          type: "number",
          default: 100,
          typeOptions: { minValue: 1 },
        },
        {
          displayName: "Offset",
          name: "offset",
          type: "number",
          default: 0,
          typeOptions: { minValue: 0 },
        },
      ],
    },
  ],
};
