import type { INodeTypeDescription } from "../types";

const SHAREPOINT_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsoftsharepoint/";

export const microsoftSharePoint: INodeTypeDescription = {
  name: "n8n-nodes-base.microsoftSharePoint",
  displayName: "Microsoft SharePoint",
  category: "Helpers",
  group: ["organization"],
  version: 1,
  description: "Access Microsoft SharePoint lists, items, and files",
  defaults: { name: "Microsoft SharePoint" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileText",
  sources: [SHAREPOINT_DOCS],
  credentials: [
    { name: "microsoftSharePointOAuth2Api", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      options: [
        { name: "File", value: "file" },
        { name: "Item", value: "item" },
        { name: "List", value: "list" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Download", value: "download" },
        { name: "Upload", value: "upload" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "Data Property Name",
      name: "dataPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
      options: [
        {
          displayName: "Metadata",
          name: "metadata",
          type: "json",
          default: "",
        },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["item"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Create or Update", value: "upsert" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"] } },
    },
    {
      displayName: "List",
      name: "list",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"] } },
    },
    {
      displayName: "Columns",
      name: "columns",
      type: "fixedCollection",
      default: {},
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["create", "upsert"] } },
      options: [
        {
          name: "fields",
          displayName: "Fields",
          values: [
            {
              displayName: "Field Values",
              name: "fieldsJson",
              type: "json",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Item",
      name: "item",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Columns",
      name: "columns",
      type: "fixedCollection",
      default: {},
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["update"] } },
      options: [
        {
          name: "fields",
          displayName: "Fields",
          values: [
            {
              displayName: "Field Values",
              name: "fieldsJson",
              type: "json",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      options: [
        {
          displayName: "OData Filter",
          name: "odataFilter",
          type: "string",
          default: "",
          placeholder: "e.g. fields/Title eq 'Task'",
        },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["list"] } },
    },
    {
      displayName: "List",
      name: "list",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["list"], operation: ["get"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
      options: [
        {
          displayName: "OData Filter",
          name: "odataFilter",
          type: "string",
          default: "",
        },
      ],
    },
  ],
};

export const nextCloud: INodeTypeDescription = {
  name: "n8n-nodes-base.nextCloud",
  displayName: "Nextcloud",
  category: "Helpers",
  group: ["data"],
  version: 1,
  description: "Access Nextcloud files, folders, and users via WebDAV and OCS APIs",
  defaults: { name: "Nextcloud" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileText",
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.nextcloud/",
  ],
  credentials: [
    { name: "nextCloudApi", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "file",
      required: true,
      noDataExpression: true,
      options: [
        { name: "File", value: "file" },
        { name: "Folder", value: "folder" },
        { name: "User", value: "user" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Copy", value: "copy" },
        { name: "Delete", value: "delete" },
        { name: "Download", value: "download" },
        { name: "Move", value: "move" },
        { name: "Share", value: "share" },
        { name: "Upload", value: "upload" },
      ],
    },
    {
      displayName: "File Path",
      name: "filePath",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["file"], operation: ["copy", "delete", "download", "move", "share", "upload"] },
      },
    },
    {
      displayName: "Source Path",
      name: "sourcePath",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["copy", "move"] } },
    },
    {
      displayName: "Destination Path",
      name: "destinationPath",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["file", "folder"], operation: ["copy", "move"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "Share Type",
      name: "shareType",
      type: "number",
      default: 3,
      displayOptions: { show: { resource: ["file", "folder"], operation: ["share"] } },
      typeOptions: { minValue: 0 },
    },
    {
      displayName: "Share Recipient",
      name: "shareRecipient",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["file", "folder"], operation: ["share"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["folder"] } },
      options: [
        { name: "Copy", value: "copy" },
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "List", value: "list" },
        { name: "Move", value: "move" },
        { name: "Share", value: "share" },
      ],
    },
    {
      displayName: "Folder Path",
      name: "folderPath",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["folder"], operation: ["create", "list", "delete"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["user"] } },
      options: [
        { name: "Invite", value: "invite" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Edit", value: "edit" },
      ],
    },
    {
      displayName: "User ID",
      name: "userId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["user"], operation: ["delete", "get", "edit", "invite"] } },
    },
    {
      displayName: "User Data",
      name: "data",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["user"], operation: ["invite", "edit"] } },
    },
  ],
};
