import type { INodeTypeDescription } from "../types";

const SHAREPOINT_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsoftsharepoint/";

export const microsoftSharePoint: INodeTypeDescription = {
  name: "n8n-nodes-base.microsoftSharePoint",
  displayName: "Microsoft SharePoint",
  category: "Helpers",
  group: ["organization"],
  version: 1,
  description: "Access Microsoft SharePoint lists, items, and files",
  defaults: { name: "Microsoft SharePoint" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileText",
  sources: [SHAREPOINT_DOCS],
  credentials: [
    { name: "microsoftSharePointOAuth2Api", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      options: [
        { name: "File", value: "file" },
        { name: "Item", value: "item" },
        { name: "List", value: "list" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["file"] } },
      options: [
        { name: "Download", value: "download" },
        { name: "Upload", value: "upload" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "Data Property Name",
      name: "dataPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["download"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
    },
    {
      displayName: "File",
      name: "file",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["file"], operation: ["update"] } },
      options: [
        {
          displayName: "Metadata",
          name: "metadata",
          type: "json",
          default: "",
        },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["item"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Create or Update", value: "upsert" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"] } },
    },
    {
      displayName: "List",
      name: "list",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"] } },
    },
    {
      displayName: "Columns",
      name: "columns",
      type: "fixedCollection",
      default: {},
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["create", "upsert"] } },
      options: [
        {
          name: "fields",
          displayName: "Fields",
          values: [
            {
              displayName: "Field Values",
              name: "fieldsJson",
              type: "json",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Item",
      name: "item",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Columns",
      name: "columns",
      type: "fixedCollection",
      default: {},
      required: true,
      displayOptions: { show: { resource: ["item"], operation: ["update"] } },
      options: [
        {
          name: "fields",
          displayName: "Fields",
          values: [
            {
              displayName: "Field Values",
              name: "fieldsJson",
              type: "json",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["item"], operation: ["getAll"] } },
      options: [
        {
          displayName: "OData Filter",
          name: "odataFilter",
          type: "string",
          default: "",
          placeholder: "e.g. fields/Title eq 'Task'",
        },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
      ],
    },
    {
      displayName: "Site",
      name: "site",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["list"] } },
    },
    {
      displayName: "List",
      name: "list",
      type: "resourceLocator",
      default: { mode: "id", value: "" },
      required: true,
      displayOptions: { show: { resource: ["list"], operation: ["get"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["list"], operation: ["getAll"] } },
      options: [
        {
          displayName: "OData Filter",
          name: "odataFilter",
          type: "string",
          default: "",
        },
      ],
    },
  ],
};