import type { INodeTypeDescription } from "../types";

const MAILCHIMP_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mailchimp/";

const campaignOptions: INodeTypeDescription["properties"] = [
  {
    displayName: "Before Create Time",
    name: "beforeCreateTime",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Before Send Time",
    name: "beforeSendTime",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Exclude Fields",
    name: "excludeFields",
    type: "multiOptions",
    default: [],
    typeOptions: { loadOptionsMethod: "getCampaignsFields" },
  },
  {
    displayName: "Fields",
    name: "fields",
    type: "multiOptions",
    default: [],
    typeOptions: { loadOptionsMethod: "getCampaignsFields" },
  },
  {
    displayName: "List ID",
    name: "listId",
    type: "options",
    default: "",
    typeOptions: { loadOptionsMethod: "getLists" },
  },
  {
    displayName: "Since Create Time",
    name: "sinceCreateTime",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Since Send Time",
    name: "sinceSendTime",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Sort Direction",
    name: "sortDirection",
    type: "options",
    default: "ASC",
    options: [
      { name: "ASC", value: "ASC" },
      { name: "DESC", value: "DESC" },
    ],
  },
  {
    displayName: "Sort Field",
    name: "sortField",
    type: "options",
    default: "create_time",
    options: [
      { name: "Create Time", value: "create_time" },
      { name: "Send Time", value: "send_time" },
    ],
  },
  {
    displayName: "Status",
    name: "status",
    type: "options",
    default: "",
    options: [
      { name: "Save", value: "save" },
      { name: "Sending", value: "sending" },
      { name: "Sent", value: "sent" },
      { name: "Schedule", value: "schedule" },
    ],
  },
];

export const mailchimp: INodeTypeDescription = {
  name: "n8n-nodes-base.mailchimp",
  displayName: "Mailchimp",
  category: "Marketing",
  group: ["marketing"],
  version: 1,
  description: "Interact with Mailchimp Marketing API v3.0",
  defaults: { name: "Mailchimp" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Mail",
  sources: [MAILCHIMP_DOCS],
  credentials: [
    { name: "mailchimpApi", required: false },
    { name: "mailchimpOAuth2Api", required: false },
  ],
  properties: [
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "apiKey",
      required: true,
      options: [
        { name: "API Key", value: "apiKey" },
        { name: "OAuth2", value: "oAuth2" },
      ],
    },
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "member",
      required: true,
      options: [
        { name: "Campaign", value: "campaign" },
        { name: "List Group", value: "listGroup" },
        { name: "Member", value: "member" },
        { name: "Member Tag", value: "memberTag" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      displayOptions: { show: { resource: ["member"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "List",
      name: "list",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["member", "memberTag"] } },
      typeOptions: { loadOptionsMethod: "getLists" },
    },
    {
      displayName: "Email",
      name: "email",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["member", "memberTag"], operation: ["create", "delete", "get", "update"] },
      },
      placeholder: "email@example.com",
    },
    {
      displayName: "Status",
      name: "status",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["member"], operation: ["create"] } },
      options: [
        { name: "Cleaned", value: "cleaned" },
        { name: "Pending", value: "pending" },
        { name: "Subscribed", value: "subscribed" },
        { name: "Transactional", value: "transactional" },
        { name: "Unsubscribed", value: "unsubscribed" },
      ],
    },
    {
      displayName: "JSON Parameters",
      name: "jsonParameters",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["member"], operation: ["create", "update"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["create"] } },
      options: [
        { displayName: "Email Type", name: "emailType", type: "string", default: "" },
        { displayName: "Language", name: "language", type: "string", default: "" },
        { displayName: "IP Opt In", name: "ipOptIn", type: "boolean", default: false },
        { displayName: "IP Signup", name: "ipSignup", type: "string", default: "" },
        { displayName: "Timestamp Signup", name: "timestampSignup", type: "dateTime", default: "" },
        { displayName: "Tags", name: "tags", type: "string", default: "" },
        { displayName: "VIP", name: "vip", type: "boolean", default: false },
        { displayName: "Timestamp Opt", name: "timestampOpt", type: "dateTime", default: "" },
      ],
    },
    {
      displayName: "Merge Fields UI",
      name: "mergeFieldsUi",
      type: "fixedCollection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [false] } },
      typeOptions: { multipleValues: true },
      options: [{
        name: "values",
        displayName: "Merge Field",
        values: [
          { displayName: "Field Name", name: "name", type: "string", default: "" },
          { displayName: "Value", name: "value", type: "string", default: "" },
        ],
      }],
    },
    {
      displayName: "Merge Fields JSON",
      name: "mergeFieldsJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [true] } },
    },
    {
      displayName: "Location Fields UI",
      name: "locationFieldsUi",
      type: "fixedCollection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [false] } },
      options: [{
        name: "value",
        displayName: "Location",
        values: [
          { displayName: "Latitude", name: "latitude", type: "number", default: 0 },
          { displayName: "Longitude", name: "longitude", type: "number", default: 0 },
        ],
      }],
    },
    {
      displayName: "Location JSON",
      name: "locationJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [true] } },
    },
    {
      displayName: "Groups UI",
      name: "groupsUi",
      type: "fixedCollection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [false] } },
      typeOptions: { multipleValues: true },
      options: [{
        name: "values",
        displayName: "Group",
        values: [
          { displayName: "Interest Category", name: "category", type: "string", default: "" },
          { displayName: "Value", name: "value", type: "string", default: "" },
        ],
      }],
    },
    {
      displayName: "Groups JSON",
      name: "groupJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [true] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["get"] } },
      options: [
        { displayName: "Fields", name: "fields", type: "string", default: "" },
        { displayName: "Exclude Fields", name: "excludeFields", type: "string", default: "" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["member"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 500,
      displayOptions: { show: { resource: ["member"], operation: ["getAll"], returnAll: [false] } },
      typeOptions: { minValue: 1, maxValue: 1000 },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["getAll"] } },
      options: [
        { displayName: "Before Last Changed", name: "beforeLastChanged", type: "dateTime", default: "" },
        { displayName: "Before Timestamp Opt", name: "beforeTimestampOpt", type: "dateTime", default: "" },
        { displayName: "Email Type", name: "emailType", type: "options", default: "", options: [
          { name: "HTML", value: "html" },
          { name: "Text", value: "text" },
        ]},
        { displayName: "Status", name: "status", type: "options", default: "", options: [
          { name: "Cleaned", value: "cleaned" },
          { name: "Pending", value: "pending" },
          { name: "Subscribed", value: "subscribed" },
          { name: "Transactional", value: "transactional" },
          { name: "Unsubscribed", value: "unsubscribed" },
        ]},
        { displayName: "Since Last Changed", name: "sinceLastChanged", type: "dateTime", default: "" },
      ],
    },
    {
      displayName: "Update Fields",
      name: "updateFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["update"] } },
      options: [
        { displayName: "Email Type", name: "emailType", type: "string", default: "" },
        { displayName: "Language", name: "language", type: "string", default: "" },
        { displayName: "IP Opt In", name: "ipOptIn", type: "boolean", default: false },
        { displayName: "IP Signup", name: "ipSignup", type: "string", default: "" },
        { displayName: "Timestamp Signup", name: "timestampSignup", type: "dateTime", default: "" },
        { displayName: "Skip Merge Validation", name: "skipMergeValidation", type: "boolean", default: false },
        { displayName: "Status", name: "status", type: "options", default: "", options: [
          { name: "Cleaned", value: "cleaned" },
          { name: "Pending", value: "pending" },
          { name: "Subscribed", value: "subscribed" },
          { name: "Transactional", value: "transactional" },
          { name: "Unsubscribed", value: "unsubscribed" },
        ]},
        { displayName: "VIP", name: "vip", type: "boolean", default: false },
        { displayName: "Timestamp Opt", name: "timestampOpt", type: "dateTime", default: "" },
      ],
    },
    {
      displayName: "Merge Fields JSON",
      name: "mergeFieldsJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["update"], jsonParameters: [true] } },
    },
    {
      displayName: "Location JSON",
      name: "locationJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["update"], jsonParameters: [true] } },
    },
    {
      displayName: "Groups JSON",
      name: "groupJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["update"], jsonParameters: [true] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "delete",
      required: true,
      displayOptions: { show: { resource: ["member"], operation: ["delete"] } },
      options: [
        { name: "Delete", value: "delete" },
      ],
    },
    {
      displayName: "List",
      name: "list",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["listGroup"] } },
      typeOptions: { loadOptionsMethod: "getLists" },
    },
    {
      displayName: "Group Category",
      name: "groupCategory",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["listGroup"] } },
      typeOptions: { loadOptionsMethod: "getGroupCategories" },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      displayOptions: { show: { resource: ["listGroup"] } },
      options: [
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["listGroup"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 500,
      displayOptions: { show: { resource: ["listGroup"], returnAll: [false] } },
      typeOptions: { minValue: 1, maxValue: 1000 },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "send",
      required: true,
      displayOptions: { show: { resource: ["campaign"] } },
      options: [
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Replicate", value: "replicate" },
        { name: "Resend", value: "resend" },
        { name: "Send", value: "send" },
      ],
    },
    {
      displayName: "Campaign ID",
      name: "campaignId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["campaign"], operation: ["delete", "get", "replicate", "resend", "send"] },
      },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 10,
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"], returnAll: [false] } },
      typeOptions: { minValue: 1, maxValue: 1000 },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"] } },
      options: campaignOptions,
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      displayOptions: { show: { resource: ["memberTag"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
      ],
    },
    {
      displayName: "Tags",
      name: "tags",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["memberTag"] } },
      placeholder: "vip,newsletter",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["memberTag"] } },
      options: [
        { displayName: "Is Syncing", name: "isSyncing", type: "boolean", default: false },
      ],
    },
  ],
};