import type { INodeTypeDescription } from "../types";

const MAILCHIMP_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mailchimp/";

const campaignOptions: INodeTypeDescription["properties"] = [
  {
    displayName: "Before Create Time",
    name: "beforeCreateTime",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Before Send Time",
    name: "beforeSendTime",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Exclude Fields",
    name: "excludeFields",
    type: "multiOptions",
    default: [],
    typeOptions: { loadOptionsMethod: "getCampaignsFields" },
  },
  {
    displayName: "Fields",
    name: "fields",
    type: "multiOptions",
    default: [],
    typeOptions: { loadOptionsMethod: "getCampaignsFields" },
  },
  {
    displayName: "List ID",
    name: "listId",
    type: "options",
    default: "",
    typeOptions: { loadOptionsMethod: "getLists" },
  },
  {
    displayName: "Since Create Time",
    name: "sinceCreateTime",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Since Send Time",
    name: "sinceSendTime",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Sort Direction",
    name: "sortDirection",
    type: "options",
    default: "ASC",
    options: [
      { name: "ASC", value: "ASC" },
      { name: "DESC", value: "DESC" },
    ],
  },
  {
    displayName: "Sort Field",
    name: "sortField",
    type: "options",
    default: "create_time",
    options: [
      { name: "Create Time", value: "create_time" },
      { name: "Send Time", value: "send_time" },
    ],
  },
  {
    displayName: "Status",
    name: "status",
    type: "options",
    default: "",
    options: [
      { name: "Save", value: "save" },
      { name: "Sending", value: "sending" },
      { name: "Sent", value: "sent" },
      { name: "Schedule", value: "schedule" },
    ],
  },
];

export const mailchimp: INodeTypeDescription = {
  name: "n8n-nodes-base.mailchimp",
  displayName: "Mailchimp",
  category: "Marketing",
  group: ["marketing"],
  version: 1,
  description: "Interact with Mailchimp Marketing API v3.0",
  defaults: { name: "Mailchimp" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Mail",
  sources: [MAILCHIMP_DOCS],
  credentials: [
    { name: "mailchimpApi", required: false },
    { name: "mailchimpOAuth2Api", required: false },
  ],
  properties: [
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "apiKey",
      required: true,
      options: [
        { name: "API Key", value: "apiKey" },
        { name: "OAuth2", value: "oAuth2" },
      ],
    },
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "member",
      required: true,
      options: [
        { name: "Campaign", value: "campaign" },
        { name: "List Group", value: "listGroup" },
        { name: "Member", value: "member" },
        { name: "Member Tag", value: "memberTag" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      displayOptions: { show: { resource: ["member"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "List",
      name: "list",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["member", "memberTag"] } },
      typeOptions: { loadOptionsMethod: "getLists" },
    },
    {
      displayName: "Email",
      name: "email",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["member", "memberTag"], operation: ["create", "delete", "get", "update"] },
      },
      placeholder: "email@example.com",
    },
    {
      displayName: "Status",
      name: "status",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["member"], operation: ["create"] } },
      options: [
        { name: "Cleaned", value: "cleaned" },
        { name: "Pending", value: "pending" },
        { name: "Subscribed", value: "subscribed" },
        { name: "Transactional", value: "transactional" },
        { name: "Unsubscribed", value: "unsubscribed" },
      ],
    },
    {
      displayName: "JSON Parameters",
      name: "jsonParameters",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["member"], operation: ["create", "update"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["create"] } },
      options: [
        { displayName: "Email Type", name: "emailType", type: "string", default: "" },
        { displayName: "Language", name: "language", type: "string", default: "" },
        { displayName: "IP Opt In", name: "ipOptIn", type: "boolean", default: false },
        { displayName: "IP Signup", name: "ipSignup", type: "string", default: "" },
        { displayName: "Timestamp Signup", name: "timestampSignup", type: "dateTime", default: "" },
        { displayName: "Tags", name: "tags", type: "string", default: "" },
        { displayName: "VIP", name: "vip", type: "boolean", default: false },
        { displayName: "Timestamp Opt", name: "timestampOpt", type: "dateTime", default: "" },
      ],
    },
    {
      displayName: "Merge Fields UI",
      name: "mergeFieldsUi",
      type: "fixedCollection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [false] } },
      typeOptions: { multipleValues: true },
      options: [{
        name: "values",
        displayName: "Merge Field",
        values: [
          { displayName: "Field Name", name: "name", type: "string", default: "" },
          { displayName: "Value", name: "value", type: "string", default: "" },
        ],
      }],
    },
    {
      displayName: "Merge Fields JSON",
      name: "mergeFieldsJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [true] } },
    },
    {
      displayName: "Location Fields UI",
      name: "locationFieldsUi",
      type: "fixedCollection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [false] } },
      options: [{
        name: "value",
        displayName: "Location",
        values: [
          { displayName: "Latitude", name: "latitude", type: "number", default: 0 },
          { displayName: "Longitude", name: "longitude", type: "number", default: 0 },
        ],
      }],
    },
    {
      displayName: "Location JSON",
      name: "locationJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [true] } },
    },
    {
      displayName: "Groups UI",
      name: "groupsUi",
      type: "fixedCollection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [false] } },
      typeOptions: { multipleValues: true },
      options: [{
        name: "values",
        displayName: "Group",
        values: [
          { displayName: "Interest Category", name: "category", type: "string", default: "" },
          { displayName: "Value", name: "value", type: "string", default: "" },
        ],
      }],
    },
    {
      displayName: "Groups JSON",
      name: "groupJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["create"], jsonParameters: [true] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["get"] } },
      options: [
        { displayName: "Fields", name: "fields", type: "string", default: "" },
        { displayName: "Exclude Fields", name: "excludeFields", type: "string", default: "" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["member"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 500,
      displayOptions: { show: { resource: ["member"], operation: ["getAll"], returnAll: [false] } },
      typeOptions: { minValue: 1, maxValue: 1000 },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["getAll"] } },
      options: [
        { displayName: "Before Last Changed", name: "beforeLastChanged", type: "dateTime", default: "" },
        { displayName: "Before Timestamp Opt", name: "beforeTimestampOpt", type: "dateTime", default: "" },
        { displayName: "Email Type", name: "emailType", type: "options", default: "", options: [
          { name: "HTML", value: "html" },
          { name: "Text", value: "text" },
        ]},
        { displayName: "Status", name: "status", type: "options", default: "", options: [
          { name: "Cleaned", value: "cleaned" },
          { name: "Pending", value: "pending" },
          { name: "Subscribed", value: "subscribed" },
          { name: "Transactional", value: "transactional" },
          { name: "Unsubscribed", value: "unsubscribed" },
        ]},
        { displayName: "Since Last Changed", name: "sinceLastChanged", type: "dateTime", default: "" },
      ],
    },
    {
      displayName: "Update Fields",
      name: "updateFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["member"], operation: ["update"] } },
      options: [
        { displayName: "Email Type", name: "emailType", type: "string", default: "" },
        { displayName: "Language", name: "language", type: "string", default: "" },
        { displayName: "IP Opt In", name: "ipOptIn", type: "boolean", default: false },
        { displayName: "IP Signup", name: "ipSignup", type: "string", default: "" },
        { displayName: "Timestamp Signup", name: "timestampSignup", type: "dateTime", default: "" },
        { displayName: "Skip Merge Validation", name: "skipMergeValidation", type: "boolean", default: false },
        { displayName: "Status", name: "status", type: "options", default: "", options: [
          { name: "Cleaned", value: "cleaned" },
          { name: "Pending", value: "pending" },
          { name: "Subscribed", value: "subscribed" },
          { name: "Transactional", value: "transactional" },
          { name: "Unsubscribed", value: "unsubscribed" },
        ]},
        { displayName: "VIP", name: "vip", type: "boolean", default: false },
        { displayName: "Timestamp Opt", name: "timestampOpt", type: "dateTime", default: "" },
      ],
    },
    {
      displayName: "Merge Fields JSON",
      name: "mergeFieldsJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["update"], jsonParameters: [true] } },
    },
    {
      displayName: "Location JSON",
      name: "locationJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["update"], jsonParameters: [true] } },
    },
    {
      displayName: "Groups JSON",
      name: "groupJson",
      type: "json",
      default: "",
      displayOptions: { show: { resource: ["member"], operation: ["update"], jsonParameters: [true] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "delete",
      required: true,
      displayOptions: { show: { resource: ["member"], operation: ["delete"] } },
      options: [
        { name: "Delete", value: "delete" },
      ],
    },
    {
      displayName: "List",
      name: "list",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["listGroup"] } },
      typeOptions: { loadOptionsMethod: "getLists" },
    },
    {
      displayName: "Group Category",
      name: "groupCategory",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["listGroup"] } },
      typeOptions: { loadOptionsMethod: "getGroupCategories" },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      displayOptions: { show: { resource: ["listGroup"] } },
      options: [
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["listGroup"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 500,
      displayOptions: { show: { resource: ["listGroup"], returnAll: [false] } },
      typeOptions: { minValue: 1, maxValue: 1000 },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "send",
      required: true,
      displayOptions: { show: { resource: ["campaign"] } },
      options: [
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Replicate", value: "replicate" },
        { name: "Resend", value: "resend" },
        { name: "Send", value: "send" },
      ],
    },
    {
      displayName: "Campaign ID",
      name: "campaignId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["campaign"], operation: ["delete", "get", "replicate", "resend", "send"] },
      },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 10,
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"], returnAll: [false] } },
      typeOptions: { minValue: 1, maxValue: 1000 },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"] } },
      options: campaignOptions,
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      displayOptions: { show: { resource: ["memberTag"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
      ],
    },
    {
      displayName: "Tags",
      name: "tags",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["memberTag"] } },
      placeholder: "vip,newsletter",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["memberTag"] } },
      options: [
        { displayName: "Is Syncing", name: "isSyncing", type: "boolean", default: false },
      ],
    },
  ],
};

const BANNERBEAR_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.bannerbear/";

export const bannerbear: INodeTypeDescription = {
  name: "n8n-nodes-base.bannerbear",
  displayName: "Bannerbear",
  category: "Marketing",
  group: ["marketing"],
  version: 1,
  description: "Generate images and retrieve templates via Bannerbear API",
  defaults: { name: "Bannerbear" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileImage",
  sources: [BANNERBEAR_DOCS],
  credentials: [
    { name: "bannerbearApi", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "Image",
      required: true,
      options: [
        { name: "Image", value: "Image" },
        { name: "Template", value: "Template" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "Create",
      required: true,
      displayOptions: { show: { resource: ["Image"] } },
      options: [
        { name: "Create", value: "Create" },
        { name: "Get", value: "Get" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "Get",
      required: true,
      displayOptions: { show: { resource: ["Template"] } },
      options: [
        { name: "Get", value: "Get" },
        { name: "Get All", value: "Get All" },
      ],
    },
    {
      displayName: "Template UID",
      name: "templateUid",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Image"], operation: ["Create"] } },
    },
    {
      displayName: "Modifications",
      name: "modifications",
      type: "json",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Image"], operation: ["Create"] } },
      typeOptions: { alwaysOpenEditWindow: true },
    },
    {
      displayName: "Webhook URL",
      name: "webhookUrl",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["Image"], operation: ["Create"] } },
    },
    {
      displayName: "Transparent Background",
      name: "transparent",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["Image"], operation: ["Create"] } },
    },
    {
      displayName: "Render PDF",
      name: "renderPdf",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["Image"], operation: ["Create"] } },
    },
    {
      displayName: "Template Version",
      name: "templateVersion",
      type: "number",
      default: "",
      displayOptions: { show: { resource: ["Image"], operation: ["Create"] } },
    },
    {
      displayName: "Metadata",
      name: "metadata",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["Image"], operation: ["Create"] } },
    },
    {
      displayName: "Image UID",
      name: "imageUid",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Image"], operation: ["Get"] } },
    },
    {
      displayName: "Template UID",
      name: "templateUid",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Template"], operation: ["Get"] } },
    },
  ],
};

const MAILCHIMP_TRIGGER_DOCS =
  "https://docs.n8n.io/integrations/builtin/trigger-nodes/n8n-nodes-base.mailchimptrigger/";

export const mailchimpTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.mailchimpTrigger",
  displayName: "Mailchimp Trigger",
  category: "Marketing",
  group: ["trigger"],
  version: 1,
  description: "Starts the workflow when a Mailchimp webhook event is received.",
  defaults: { name: "Mailchimp Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "Mail",
  credentials: [
    { name: "mailchimpApi", required: false },
    { name: "mailchimpOAuth2Api", required: false },
  ],
  sources: [MAILCHIMP_TRIGGER_DOCS],
  properties: [
    {
      displayName: "List ID",
      name: "listId",
      type: "string",
      default: "",
      required: true,
      description: "The Mailchimp audience/list ID to install the webhook on",
    },
    {
      displayName: "Events",
      name: "events",
      type: "multiOptions",
      default: [],
      required: true,
      noDataExpression: true,
      description: "One or more Mailchimp webhook event types to subscribe to",
      options: [
        { name: "Subscribe", value: "subscribe" },
        { name: "Unsubscribe", value: "unsubscribe" },
        { name: "Cleaned", value: "cleaned" },
        { name: "Email Change", value: "upemail" },
        { name: "Campaign", value: "campaign" },
        { name: "Profile Update", value: "profile" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      placeholder: "Add option",
      options: [
        {
          displayName: "Resolve Events",
          name: "resolveEvents",
          type: "boolean",
          default: false,
          description: "When enabled, pool all events into a single output item per firing instead of one item per event",
        },
        {
          displayName: "Only Follow-Up",
          name: "onlyFollowUp",
          type: "boolean",
          default: false,
          description: "When enabled, only emit events that occur after a given follow-up event",
        },
        {
          displayName: "Secret",
          name: "secret",
          type: "string",
          default: "",
          typeOptions: { password: true },
          description: "Optional signing secret for HMAC-SHA256 webhook signature verification",
        },
      ],
    },
  ],
};

const MAUTIC_TRIGGER_DOCS =
  "https://docs.n8n.io/integrations/builtin/trigger-nodes/n8n-nodes-base.mautictrigger/";

const ACTIVECAMPAIGN_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.activecampaign/";

export const activeCampaign: INodeTypeDescription = {
  name: "n8n-nodes-base.activeCampaign",
  displayName: "ActiveCampaign",
  category: "Marketing",
  group: ["marketing"],
  version: 1,
  description: "Access ActiveCampaign v3 API for contacts, deals, campaigns, and more",
  defaults: { name: "ActiveCampaign" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Mail",
  sources: [ACTIVECAMPAIGN_DOCS],
  credentials: [
    { name: "activeCampaignApi", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "contact",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Account", value: "account" },
        { name: "Account Contact", value: "accountContact" },
        { name: "Contact", value: "contact" },
        { name: "Contact List", value: "contactList" },
        { name: "Contact Tag", value: "contactTag" },
        { name: "Connection", value: "connection" },
        { name: "Deal", value: "deal" },
        { name: "E-commerce Customer", value: "ecommerceCustomer" },
        { name: "E-commerce Order", value: "ecommerceOrder" },
        { name: "E-commerce Order Products", value: "ecommerceOrderProducts" },
        { name: "List", value: "list" },
        { name: "Tag", value: "tag" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: {
        show: { resource: ["contact", "account", "connection", "ecommerceOrder", "ecommerceCustomer", "tag"] },
      },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "add",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["contactList", "contactTag"] } },
      options: [
        { name: "Add", value: "add" },
        { name: "Remove", value: "remove" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["accountContact"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["deal"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Create Note", value: "createNote" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
        { name: "Update Note", value: "updateNote" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["ecommerceOrderProducts"] } },
      options: [
        { name: "Get All", value: "getAll" },
        { name: "Get", value: "get" },
        { name: "Get By Order ID", value: "getByOrderId" },
      ],
    },
    {
      displayName: "Email",
      name: "email",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["contact"], operation: ["create"] },
      },
      placeholder: "email@example.com",
    },
    {
      displayName: "Contact ID",
      name: "contactId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["contact"], operation: ["delete", "get", "update"] },
      },
    },
    {
      displayName: "First Name",
      name: "firstName",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["contact"], operation: ["create", "update"] } },
    },
    {
      displayName: "Last Name",
      name: "lastName",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["contact"], operation: ["create", "update"] } },
    },
    {
      displayName: "Phone",
      name: "phone",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["contact"], operation: ["create", "update"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { resource: ["contact", "account", "deal", "ecommerceOrder", "tag"], operation: ["getAll"] },
      },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 20,
      displayOptions: {
        show: { resource: ["contact", "account", "deal", "ecommerceOrder", "tag"], operation: ["getAll"], returnAll: [false] },
      },
      typeOptions: { minValue: 1, maxValue: 100 },
    },
  ],
};

export const mauticTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.mauticTrigger",
  displayName: "Mautic Trigger",
  category: "Marketing",
  group: ["trigger"],
  version: 1,
  description: "Starts the workflow when a Mautic webhook event is received.",
  defaults: { name: "Mautic Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "Link",
  credentials: [
    { name: "mauticApi", required: false },
    { name: "mauticOAuth2Api", required: false },
  ],
  sources: [MAUTIC_TRIGGER_DOCS],
  properties: [
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "credentials",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Credentials", value: "credentials" },
        { name: "OAuth2", value: "oAuth2" },
      ],
    },
    {
      displayName: "Events",
      name: "events",
      type: "multiOptions",
      default: [],
      required: true,
      description: "One or more Mautic webhook trigger event IDs to subscribe to. Loaded from /api/hooks/triggers at runtime.",
      typeOptions: { loadOptionsMethod: "getMauticTriggers" },
    },
    {
      displayName: "Events Order",
      name: "eventsOrder",
      type: "options",
      default: "ASC",
      noDataExpression: true,
      options: [
        { name: "ASC", value: "ASC" },
        { name: "DESC", value: "DESC" },
      ],
    },
  ],
};