import type { INodeTypeDescription } from "../types";

export const affinity: INodeTypeDescription = {
  name: "n8n-nodes-base.affinity",
  displayName: "Affinity",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description: "Access Affinity CRM lists, list entries, organizations, and persons",
  defaults: { name: "Affinity" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.affinity/",
  ],
  credentials: [
    { name: "affinityApi", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      options: [
        { name: "List", value: "list" },
        { name: "List Entry", value: "listEntry" },
        { name: "Organization", value: "organization" },
        { name: "Person", value: "person" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Get All Lists", value: "getAll" },
        { name: "Get a List", value: "get" },
      ],
    },
    {
      displayName: "List ID",
      name: "listId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["list"], operation: ["get"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["listEntry"] } },
      options: [
        { name: "Create a List Entry", value: "create" },
        { name: "Delete a List Entry", value: "delete" },
        { name: "Get a List Entry", value: "get" },
        { name: "Get All List Entries", value: "getAll" },
      ],
    },
    {
      displayName: "List ID",
      name: "listId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["listEntry"] } },
    },
    {
      displayName: "Entity ID",
      name: "entityId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["listEntry"], operation: ["create"] } },
    },
    {
      displayName: "Entity Type",
      name: "entityType",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["listEntry"], operation: ["create"] } },
    },
    {
      displayName: "Entry ID",
      name: "entryId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["listEntry"], operation: ["delete", "get"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["listEntry"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["listEntry"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["listEntry"], operation: ["getAll"] } },
      options: [
        { displayName: "Order By", name: "orderBy", type: "string", default: "" },
        { displayName: "Direction", name: "direction", type: "options", default: "asc", options: [{ name: "Ascending", value: "asc" }, { name: "Descending", value: "desc" }] },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["organization"] } },
      options: [
        { name: "Create an Organization", value: "create" },
        { name: "Delete an Organization", value: "delete" },
        { name: "Get an Organization", value: "get" },
        { name: "Get All Organizations", value: "getAll" },
        { name: "Update an Organization", value: "update" },
      ],
    },
    {
      displayName: "Name",
      name: "name",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["organization"], operation: ["create", "update"] } },
    },
    {
      displayName: "Organization ID",
      name: "organizationId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["organization"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["organization"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["organization"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["organization"], operation: ["create", "update", "getAll"] } },
      options: [
        { displayName: "Domain", name: "domain", type: "string", default: "" },
        { displayName: "Domains", name: "domains", type: "string", default: "" },
        { displayName: "Person IDs", name: "personIds", type: "string", default: "" },
        { displayName: "Order By", name: "orderBy", type: "string", default: "" },
        { displayName: "Direction", name: "direction", type: "options", default: "asc", options: [{ name: "Ascending", value: "asc" }, { name: "Descending", value: "desc" }] },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["person"] } },
      options: [
        { name: "Create a Person", value: "create" },
        { name: "Delete a Person", value: "delete" },
        { name: "Get a Person", value: "get" },
        { name: "Get All Persons", value: "getAll" },
        { name: "Update a Person", value: "update" },
      ],
    },
    {
      displayName: "First Name",
      name: "firstName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["person"], operation: ["create", "update"] } },
    },
    {
      displayName: "Last Name",
      name: "lastName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["person"], operation: ["create", "update"] } },
    },
    {
      displayName: "Person ID",
      name: "personId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["person"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["person"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["person"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["person"], operation: ["create", "update", "getAll"] } },
      options: [
        { displayName: "Emails", name: "emails", type: "string", default: "" },
        { displayName: "Organization IDs", name: "organizationIds", type: "string", default: "" },
        { displayName: "Order By", name: "orderBy", type: "string", default: "" },
        { displayName: "Direction", name: "direction", type: "options", default: "asc", options: [{ name: "Ascending", value: "asc" }, { name: "Descending", value: "desc" }] },
      ],
    },
  ],
};

export const affinityTool: INodeTypeDescription = {
  name: "n8n-nodes-base.affinityTool",
  displayName: "Affinity Tool",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description:
    "Access Affinity CRM lists, list entries, organizations, and persons via AI agent tool",
  defaults: { name: "Affinity Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [{ name: "affinityApi", required: true }],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      options: [
        { name: "List", value: "list" },
        { name: "List Entry", value: "listEntry" },
        { name: "Organization", value: "organization" },
        { name: "Person", value: "person" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Get All Lists", value: "getAll" },
        { name: "Get a List", value: "get" },
      ],
    },
    {
      displayName: "List ID",
      name: "listId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["list"], operation: ["get"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["listEntry"] } },
      options: [
        { name: "Create a List Entry", value: "create" },
        { name: "Delete a List Entry", value: "delete" },
        { name: "Get a List Entry", value: "get" },
        { name: "Get All List Entries", value: "getAll" },
      ],
    },
    {
      displayName: "List ID",
      name: "listId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["listEntry"] } },
    },
    {
      displayName: "Entity ID",
      name: "entityId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["listEntry"], operation: ["create"] } },
    },
    {
      displayName: "Entry ID",
      name: "listEntryId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: {
        show: { resource: ["listEntry"], operation: ["delete", "get"] },
      },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["listEntry"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 5,
      displayOptions: { show: { resource: ["listEntry"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["organization"] } },
      options: [
        { name: "Create an Organization", value: "create" },
        { name: "Delete an Organization", value: "delete" },
        { name: "Get an Organization", value: "get" },
        { name: "Get All Organizations", value: "getAll" },
        { name: "Update an Organization", value: "update" },
      ],
    },
    {
      displayName: "Name",
      name: "name",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["organization"], operation: ["create", "update"] },
      },
    },
    {
      displayName: "Organization ID",
      name: "organizationId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: {
        show: { resource: ["organization"], operation: ["delete", "get", "update"] },
      },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["organization"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 5,
      displayOptions: { show: { resource: ["organization"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: {
        show: { resource: ["organization"], operation: ["create", "update", "getAll"] },
      },
      options: [
        { displayName: "Domain", name: "domain", type: "string", default: "" },
        { displayName: "Person IDs", name: "persons", type: "string", default: "" },
        { displayName: "With Interaction Dates", name: "withInteractionDates", type: "boolean", default: false },
        { displayName: "Term", name: "term", type: "string", default: "" },
      ],
    },
    {
      displayName: "Update Fields",
      name: "updateFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["organization"], operation: ["update"] } },
      options: [
        { displayName: "Domain", name: "domain", type: "string", default: "" },
        { displayName: "Person IDs", name: "persons", type: "string", default: "" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["person"] } },
      options: [
        { name: "Create a Person", value: "create" },
        { name: "Delete a Person", value: "delete" },
        { name: "Get a Person", value: "get" },
        { name: "Get All Persons", value: "getAll" },
        { name: "Update a Person", value: "update" },
      ],
    },
    {
      displayName: "First Name",
      name: "firstName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["person"], operation: ["create", "update"] } },
    },
    {
      displayName: "Last Name",
      name: "lastName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["person"], operation: ["create", "update"] } },
    },
    {
      displayName: "Person ID",
      name: "personId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: {
        show: { resource: ["person"], operation: ["delete", "get", "update"] },
      },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["person"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 5,
      displayOptions: { show: { resource: ["person"], operation: ["getAll"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: {
        show: { resource: ["person"], operation: ["create", "update", "getAll"] },
      },
      options: [
        { displayName: "Emails", name: "emails", type: "string", default: "" },
        { displayName: "Organization IDs", name: "organizations", type: "string", default: "" },
        { displayName: "With Interaction Dates", name: "withInteractionDates", type: "boolean", default: false },
        { displayName: "Term", name: "term", type: "string", default: "" },
      ],
    },
    {
      displayName: "Update Fields",
      name: "updateFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["person"], operation: ["update"] } },
      options: [
        { displayName: "First Name", name: "firstName", type: "string", default: "" },
        { displayName: "Last Name", name: "lastName", type: "string", default: "" },
        { displayName: "Organization IDs", name: "organizations", type: "string", default: "" },
        { displayName: "Emails", name: "emails", type: "string", default: "" },
      ],
    },
  ],
};

const AFFINITY_TRIGGER_DOCS =
  "https://docs.n8n.io/integrations/builtin/trigger-nodes/n8n-nodes-base.affinitytrigger/";

export const affinityTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.affinityTrigger",
  displayName: "Affinity Trigger",
  category: "Sales",
  group: ["trigger"],
  version: 1,
  description: "Starts the workflow when an Affinity webhook event is received.",
  defaults: { name: "Affinity Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "Webhook",
  credentials: [
    { name: "affinityApi", required: true },
  ],
  sources: [AFFINITY_TRIGGER_DOCS],
  properties: [
    {
      displayName: "Events",
      name: "events",
      type: "multiOptions",
      default: [],
      required: true,
      noDataExpression: true,
      description: "One or more Affinity webhook event types to subscribe to.",
      options: [
        { name: "Field Created", value: "field.created" },
        { name: "Field Deleted", value: "field.deleted" },
        { name: "Field Updated", value: "field.updated" },
        { name: "Field Value Created", value: "field_value.created" },
        { name: "Field Value Deleted", value: "field_value.deleted" },
        { name: "Field Value Updated", value: "field_value.updated" },
        { name: "File Created", value: "file.created" },
        { name: "File Deleted", value: "file.deleted" },
        { name: "List Created", value: "list.created" },
        { name: "List Deleted", value: "list.deleted" },
        { name: "List Updated", value: "list.updated" },
        { name: "List Entry Created", value: "list_entry.created" },
        { name: "List Entry Deleted", value: "list_entry.deleted" },
        { name: "Note Created", value: "note.created" },
        { name: "Note Deleted", value: "note.deleted" },
        { name: "Note Updated", value: "note.updated" },
        { name: "Opportunity Created", value: "opportunity.created" },
        { name: "Opportunity Deleted", value: "opportunity.deleted" },
        { name: "Opportunity Updated", value: "opportunity.updated" },
        { name: "Organization Created", value: "organization.created" },
        { name: "Organization Deleted", value: "organization.deleted" },
        { name: "Organization Updated", value: "organization.updated" },
        { name: "Person Created", value: "person.created" },
        { name: "Person Deleted", value: "person.deleted" },
        { name: "Person Updated", value: "person.updated" },
      ],
    },
  ],
};

const COPPER_TRIGGER_DOCS =
  "https://docs.n8n.io/integrations/builtin/trigger-nodes/n8n-nodes-base.coppertrigger/";

export const copperTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.copperTrigger",
  displayName: "Copper Trigger",
  category: "Sales",
  group: ["trigger"],
  version: 1,
  description: "Starts the workflow when a Copper webhook event is received.",
  defaults: { name: "Copper Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "Webhook",
  credentials: [
    { name: "copperApi", required: true },
  ],
  sources: [COPPER_TRIGGER_DOCS],
  properties: [
    {
      displayName: "Events",
      name: "events",
      type: "multiOptions",
      default: ["New", "Update", "Delete"],
      required: true,
      noDataExpression: true,
      description: "Which CRUD event types to subscribe to.",
      options: [
        { name: "New", value: "New" },
        { name: "Update", value: "Update" },
        { name: "Delete", value: "Delete" },
      ],
    },
    {
      displayName: "Additional Options",
      name: "additionalOptions",
      type: "collection",
      default: {},
      placeholder: "Add option",
      options: [
        {
          displayName: "Custom Fields as Values",
          name: "customFieldsAsValues",
          type: "boolean",
          default: false,
          description: "If true, dropdown/multi-select custom fields are delivered with option names instead of option IDs.",
        },
        {
          displayName: "Secret",
          name: "secret",
          type: "fixedCollection",
          default: {},
          description: "Arbitrary key-value pairs passed back in the webhook body as extra fields for verification.",
          options: [
            {
              name: "values",
              displayName: "Secret Key-Value",
              values: [
                {
                  displayName: "Key",
                  name: "key",
                  type: "string",
                  default: "",
                },
                {
                  displayName: "Value",
                  name: "value",
                  type: "string",
                  default: "",
                },
              ],
            },
          ],
        },
        {
          displayName: "Headers",
          name: "headers",
          type: "fixedCollection",
          default: {},
          description: "Custom HTTP headers to include on the webhook POST request to the callback URL.",
          options: [
            {
              name: "values",
              displayName: "Header",
              values: [
                {
                  displayName: "Name",
                  name: "name",
                  type: "string",
                  default: "",
                },
                {
                  displayName: "Value",
                  name: "value",
                  type: "string",
                  default: "",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const copper: INodeTypeDescription = {
  name: "n8n-nodes-base.copper",
  displayName: "Copper",
  category: "Sales",
  group: ["output"],
  version: 1,
  description: "Creates, reads, updates, and deletes companies, leads, opportunities, persons, projects, tasks, and customer sources in Copper CRM.",
  defaults: { name: "Copper" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [{ name: "copperApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.copper/",
    "https://docs.n8n.io/integrations/builtin/credentials/copper/",
    "https://developer.copper.com/",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "Company",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Company", value: "Company" },
        { name: "Customer Source", value: "CustomerSource" },
        { name: "Lead", value: "Lead" },
        { name: "Opportunity", value: "Opportunity" },
        { name: "Person", value: "Person" },
        { name: "Project", value: "Project" },
        { name: "Task", value: "Task" },
        { name: "User", value: "User" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "Create",
      required: true,
      noDataExpression: true,
      displayOptions: {
        show: { resource: ["Company", "Lead", "Opportunity", "Person", "Project", "Task"] },
      },
      options: [
        { name: "Create", value: "Create" },
        { name: "Delete", value: "Delete" },
        { name: "Get", value: "Get" },
        { name: "Get All", value: "GetAll" },
        { name: "Update", value: "Update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "GetAll",
      required: true,
      noDataExpression: true,
      displayOptions: {
        show: { resource: ["CustomerSource", "User"] },
      },
      options: [
        { name: "Get All", value: "GetAll" },
      ],
    },
    {
      displayName: "Company ID",
      name: "companyId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Company"], operation: ["Delete", "Get", "Update"] } },
      description: "Unique identifier of the company record",
    },
    {
      displayName: "Lead ID",
      name: "leadId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Lead"], operation: ["Delete", "Get", "Update"] } },
      description: "Unique identifier of the lead record",
    },
    {
      displayName: "Opportunity ID",
      name: "opportunityId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Opportunity"], operation: ["Delete", "Get", "Update"] } },
      description: "Unique identifier of the opportunity record",
    },
    {
      displayName: "Person ID",
      name: "personId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Person"], operation: ["Delete", "Get", "Update"] } },
      description: "Unique identifier of the person record",
    },
    {
      displayName: "Project ID",
      name: "projectId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Project"], operation: ["Delete", "Get", "Update"] } },
      description: "Unique identifier of the project record",
    },
    {
      displayName: "Task ID",
      name: "taskId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Task"], operation: ["Delete", "Get", "Update"] } },
      description: "Unique identifier of the task record",
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["Create", "Update"] } },
      options: [
        { displayName: "Name", name: "name", type: "string", default: "" },
        { displayName: "Address", name: "address", type: "json", default: "{}" },
        { displayName: "Assignee ID", name: "assignee_id", type: "number", default: 0 },
        { displayName: "Company Name", name: "company_name", type: "string", default: "" },
        { displayName: "Company ID", name: "company_id", type: "number", default: 0 },
        { displayName: "Customer Source ID", name: "customer_source_id", type: "number", default: 0 },
        { displayName: "Description", name: "description", type: "string", default: "" },
        { displayName: "Details", name: "details", type: "string", default: "" },
        { displayName: "Due Date", name: "due_date", type: "number", default: 0 },
        { displayName: "Email", name: "email", type: "json", default: "{}" },
        { displayName: "Loss Reason ID", name: "loss_reason_id", type: "number", default: 0 },
        { displayName: "Monetary Value", name: "monetary_value", type: "number", default: 0 },
        { displayName: "Monetary Value Confidence Score", name: "monetary_value_confidence_score", type: "number", default: 0 },
        { displayName: "Phone Numbers", name: "phone_numbers", type: "json", default: "[]" },
        { displayName: "Pipeline ID", name: "pipeline_id", type: "number", default: 0 },
        { displayName: "Pipeline Stage ID", name: "pipeline_stage_id", type: "number", default: 0 },
        { displayName: "Primary Contact ID", name: "primary_contact_id", type: "number", default: 0 },
        { displayName: "Priority", name: "priority", type: "string", default: "" },
        { displayName: "Socials", name: "socials", type: "json", default: "[]" },
        { displayName: "Status", name: "status", type: "string", default: "" },
        { displayName: "Tags", name: "tags", type: "string", default: "" },
        { displayName: "Title", name: "title", type: "string", default: "" },
        { displayName: "Websites", name: "websites", type: "json", default: "[]" },
        { displayName: "Custom Fields", name: "custom_fields", type: "json", default: "[]" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["GetAll"] } },
      description: "If true, return all matching records (paginate internally)",
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      typeOptions: { minValue: 1 },
      displayOptions: { show: { operation: ["GetAll"] }, hide: { returnAll: [true] } },
      description: "Max records per page when returnAll is false",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["GetAll"] } },
      options: [
        { displayName: "Sort By", name: "sort_by", type: "string", default: "" },
        { displayName: "Sort Direction", name: "sort_direction", type: "options", default: "asc", options: [{ name: "Ascending", value: "asc" }, { name: "Descending", value: "desc" }] },
        { displayName: "Page Number", name: "page_number", type: "number", default: 1 },
        { displayName: "Page Size", name: "page_size", type: "number", default: 50 },
        { displayName: "Filter", name: "filter", type: "json", default: "{}" },
      ],
    },
  ],
};

export const freshworksCrm: INodeTypeDescription = {
  name: "n8n-nodes-base.freshworksCrm",
  displayName: "Freshworks CRM",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description: "Access Freshworks CRM accounts, appointments, contacts, deals, notes, sales activities, tasks, and search",
  defaults: { name: "Freshworks CRM" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [
    { name: "freshworksCrmApi", required: true },
  ],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.freshworkscrm/",
    "https://docs.n8n.io/integrations/builtin/credentials/freshworkscrm/",
    "https://developers.freshworks.com/crm/api/",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "account",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Account", value: "account" },
        { name: "Appointment", value: "appointment" },
        { name: "Contact", value: "contact" },
        { name: "Deal", value: "deal" },
        { name: "Note", value: "note" },
        { name: "Sales Activity", value: "salesActivity" },
        { name: "Task", value: "task" },
        { name: "Search", value: "search" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: {
        show: { resource: ["account", "appointment", "contact", "deal", "task"] },
      },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["note"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["salesActivity"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "search",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["search"] } },
      options: [
        { name: "Search", value: "search" },
      ],
    },
    {
      displayName: "Account ID",
      name: "accountId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["account"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Appointment ID",
      name: "appointmentId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["appointment"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Contact ID",
      name: "contactId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["contact"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Deal ID",
      name: "dealId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["deal"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Note ID",
      name: "noteId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["note"], operation: ["delete", "update"] } },
    },
    {
      displayName: "Sales Activity ID",
      name: "salesActivityId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["salesActivity"], operation: ["get"] } },
    },
    {
      displayName: "Task ID",
      name: "taskId",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["task"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "View",
      name: "view",
      type: "number",
      default: 0,
      displayOptions: { show: { operation: ["getAll"] }, hide: { resource: ["search"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 25,
      typeOptions: { minValue: 1 },
      displayOptions: { show: { operation: ["getAll"] }, hide: { resource: ["search"] } },
    },
    {
      displayName: "Search Term",
      name: "searchTerm",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["search"], operation: ["search"] } },
    },
    {
      displayName: "Entities",
      name: "entities",
      type: "multiOptions",
      default: [],
      displayOptions: { show: { resource: ["search"], operation: ["search"] } },
      options: [
        { name: "Account", value: "account" },
        { name: "Contact", value: "contact" },
        { name: "Deal", value: "deal" },
      ],
    },
    {
      displayName: "Account Fields",
      name: "accountFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["account"], operation: ["create", "update"] } },
      options: [
        { displayName: "Name", name: "name", type: "string", default: "" },
        { displayName: "Website", name: "website", type: "string", default: "" },
        { displayName: "Phone", name: "phone", type: "string", default: "" },
      ],
    },
    {
      displayName: "Contact Fields",
      name: "contactFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["contact"], operation: ["create", "update"] } },
      options: [
        { displayName: "First Name", name: "first_name", type: "string", default: "" },
        { displayName: "Last Name", name: "last_name", type: "string", default: "" },
        { displayName: "Email", name: "email", type: "string", default: "" },
        { displayName: "Mobile Number", name: "mobile_number", type: "string", default: "" },
      ],
    },
    {
      displayName: "Deal Fields",
      name: "dealFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["deal"], operation: ["create", "update"] } },
      options: [
        { displayName: "Deal Name", name: "deal_name", type: "string", default: "" },
        { displayName: "Amount", name: "amount", type: "number", default: 0 },
        { displayName: "Deal Stage ID", name: "deal_stage_id", type: "number", default: 0 },
      ],
    },
    {
      displayName: "Task Fields",
      name: "taskFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["task"], operation: ["create", "update"] } },
      options: [
        { displayName: "Title", name: "title", type: "string", default: "" },
        { displayName: "Due Date", name: "due_date", type: "string", default: "" },
        { displayName: "Owner ID", name: "owner_id", type: "number", default: 0 },
      ],
    },
    {
      displayName: "Appointment Fields",
      name: "appointmentFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["appointment"], operation: ["create", "update"] } },
      options: [
        { displayName: "Title", name: "title", type: "string", default: "" },
        { displayName: "From Date", name: "from_date", type: "string", default: "" },
        { displayName: "End Date", name: "end_date", type: "string", default: "" },
      ],
    },
    {
      displayName: "Note Fields",
      name: "noteFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["note"], operation: ["create", "update"] } },
      options: [
        { displayName: "Description", name: "description", type: "string", default: "" },
      ],
    },
    {
      displayName: "Sales Activity Fields",
      name: "salesActivityFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["salesActivity"], operation: ["getAll"] } },
      options: [
        { displayName: "Sales Activity Type ID", name: "sales_activity_type_id", type: "number", default: 0 },
        { displayName: "Start Date", name: "start_date", type: "string", default: "" },
      ],
    },
  ],
};

const PADDLE_DOCS =
  "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.paddle/";

export const paddle: INodeTypeDescription = {
  name: "n8n-nodes-base.paddle",
  displayName: "Paddle",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description:
    "Access Paddle Classic API to manage coupons, payments, subscription plans, products, and user records",
  defaults: { name: "Paddle" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [{ name: "paddleApi", required: true }],
  sources: [PADDLE_DOCS],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "coupon",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Coupon", value: "coupon" },
        { name: "Payment", value: "payment" },
        { name: "Plan", value: "plan" },
        { name: "Product", value: "product" },
        { name: "User", value: "user" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["coupon"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Coupon ID",
      name: "couponId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["coupon"], operation: ["update"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["payment"] } },
      options: [
        { name: "Get All", value: "getAll" },
        { name: "Reschedule", value: "reschedule" },
      ],
    },
    {
      displayName: "Payment ID",
      name: "paymentId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["payment"], operation: ["reschedule"] } },
    },
    {
      displayName: "Date",
      name: "date",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["payment"], operation: ["reschedule"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["plan"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Plan ID",
      name: "planId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["plan"], operation: ["get"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["product"] } },
      options: [
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["user"] } },
      options: [
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      placeholder: "Add Field",
      options: [
        { displayName: "Coupon Code", name: "couponCode", type: "string", default: "" },
        { displayName: "Discount Type", name: "discountType", type: "options", default: "percentage", options: [
          { name: "Percentage", value: "percentage" },
          { name: "Flat", value: "flat" },
        ]},
        { displayName: "Discount Value", name: "discountValue", type: "number", default: 0 },
        { displayName: "Coupon Type", name: "couponType", type: "options", default: "single", options: [
          { name: "Single Use", value: "single" },
          { name: "Multi Use", value: "multi" },
          { name: "Forever", value: "forever" },
        ]},
        { displayName: "Product IDs", name: "productIds", type: "string", default: "" },
        { displayName: "Expiration Date", name: "expirationDate", type: "string", default: "" },
        { displayName: "Status", name: "status", type: "string", default: "" },
        { displayName: "Limit", name: "limit", type: "number", default: 50 },
        { displayName: "Page", name: "page", type: "number", default: 1 },
      ],
    },
  ],
};

export const unleashedSoftware: INodeTypeDescription = {
  name: "n8n-nodes-base.unleashedSoftware",
  displayName: "Unleashed Software",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description: "Read-only data retrieval node for the Unleashed Software inventory management platform",
  defaults: { name: "Unleashed Software" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [
    { name: "unleashedSoftwareApi", required: true },
  ],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.unleashedsoftware/",
    "https://docs.n8n.io/integrations/builtin/credentials/unleashedsoftware/",
    "https://apidocs.unleashedsoftware.com/",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "salesOrder",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Sales Order", value: "salesOrder" },
        { name: "Stock On Hand", value: "stockOnHand" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["salesOrder"] } },
      options: [
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["stockOnHand"] } },
      options: [
        { name: "Get All", value: "getAll" },
        { name: "Get", value: "get" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 100,
      typeOptions: { minValue: 1, maxValue: 1000 },
      displayOptions: {
        show: { operation: ["getAll"] },
        hide: { returnAll: [true] },
      },
    },
    {
      displayName: "Product ID",
      name: "productId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["stockOnHand"], operation: ["get"] } },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      placeholder: "Add Filter",
      displayOptions: { show: { operation: ["getAll"] } },
      options: [
        {
          displayName: "Customer ID",
          name: "customerId",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["salesOrder"] } },
        },
        {
          displayName: "Customer Code",
          name: "customerCode",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["salesOrder"] } },
        },
        {
          displayName: "End Date",
          name: "endDate",
          type: "dateTime",
          default: "",
          displayOptions: { show: { resource: ["salesOrder"] } },
        },
        {
          displayName: "Modified Since",
          name: "modifiedSince",
          type: "dateTime",
          default: "",
          displayOptions: { show: { operation: ["getAll"] } },
        },
        {
          displayName: "Order Number",
          name: "orderNumber",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["salesOrder"] } },
        },
        {
          displayName: "Order Status",
          name: "orderStatus",
          type: "multiOptions",
          default: [],
          displayOptions: { show: { resource: ["salesOrder"] } },
          options: [
            { name: "Backordered", value: "Backordered" },
            { name: "Completed", value: "Completed" },
            { name: "Deleted", value: "Deleted" },
            { name: "Parked", value: "Parked" },
            { name: "Placed", value: "Placed" },
          ],
        },
        {
          displayName: "Start Date",
          name: "startDate",
          type: "dateTime",
          default: "",
          displayOptions: { show: { resource: ["salesOrder"] } },
        },
        {
          displayName: "As At Date",
          name: "asAtDate",
          type: "dateTime",
          default: "",
          displayOptions: { show: { resource: ["stockOnHand"] } },
        },
        {
          displayName: "Is Assembled",
          name: "IsAssembled",
          type: "boolean",
          default: false,
          displayOptions: { show: { resource: ["stockOnHand"] } },
        },
        {
          displayName: "Order By",
          name: "orderBy",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["stockOnHand"] } },
        },
        {
          displayName: "Product ID",
          name: "productId",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["stockOnHand"] } },
        },
        {
          displayName: "Warehouse Code",
          name: "warehouseCode",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["stockOnHand"] } },
        },
        {
          displayName: "Warehouse Name",
          name: "warehouseName",
          type: "string",
          default: "",
          displayOptions: { show: { resource: ["stockOnHand"] } },
        },
      ],
    },
  ],
};

export const paddleTool: INodeTypeDescription = {
  name: "n8n-nodes-base.paddleTool",
  displayName: "Paddle Tool",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description:
    "AI agent tool variant of the Paddle node. Wraps Paddle Classic API read and write operations so an AI agent can manage coupons, payments, plans, products, and user records.",
  defaults: { name: "Paddle Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  usableAsTool: true,
  credentials: [{ name: "paddleApi", required: true }],
  sources: [PADDLE_DOCS],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "coupon",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Coupon", value: "coupon" },
        { name: "Payment", value: "payment" },
        { name: "Plan", value: "plan" },
        { name: "Product", value: "product" },
        { name: "User", value: "user" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["coupon"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Coupon ID",
      name: "couponId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["coupon"], operation: ["update"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["payment"] } },
      options: [
        { name: "Get All", value: "getAll" },
        { name: "Reschedule", value: "reschedule" },
      ],
    },
    {
      displayName: "Payment ID",
      name: "paymentId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["payment"], operation: ["reschedule"] } },
    },
    {
      displayName: "Date",
      name: "date",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["payment"], operation: ["reschedule"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["plan"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Plan ID",
      name: "planId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["plan"], operation: ["get"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["product"] } },
      options: [
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["user"] } },
      options: [
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      placeholder: "Add Field",
      options: [
        { displayName: "Coupon Type", name: "couponType", type: "string", default: "" },
        { displayName: "Discount Amount", name: "discountAmount", type: "number", default: 0 },
        { displayName: "Recurring Limits", name: "recurringLimits", type: "number", default: 0 },
        { displayName: "Expiration Date", name: "expirationDate", type: "string", default: "" },
        { displayName: "Status", name: "status", type: "string", default: "" },
        { displayName: "Group", name: "group", type: "string", default: "" },
        { displayName: "Subscription ID", name: "subscriptionId", type: "string", default: "" },
        { displayName: "Limit", name: "limit", type: "number", default: 50 },
      ],
    },
  ],
};

export const drift: INodeTypeDescription = {
  name: "n8n-nodes-base.drift",
  displayName: "Drift",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description: "Interact with Drift CRM contact API",
  defaults: { name: "Drift" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [
    { name: "driftApi", required: true },
    { name: "driftOAuth2Api", required: false },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "contact",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Contact", value: "contact" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["contact"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Contact ID",
      name: "contactId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["contact"], operation: ["delete", "get", "update"] } },
    },
    {
      displayName: "Email",
      name: "email",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["contact"], operation: ["create"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["contact"], operation: ["create", "update"] } },
      options: [
        { displayName: "Name", name: "name", type: "string", default: "" },
        { displayName: "Phone", name: "phone", type: "string", default: "" },
        { displayName: "External ID", name: "externalId", type: "string", default: "" },
        { displayName: "Custom Attributes", name: "customAttributes", type: "json", default: "{}" },
      ],
    },
    {
      displayName: "Simplify",
      name: "simplify",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["contact"], operation: ["getAll"] } },
    },
  ],
};

const ODOO_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.odoo/";

export const odooTool: INodeTypeDescription = {
  name: "n8n-nodes-base.odooTool",
  displayName: "Odoo Tool",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description: "AI agent tool variant of the Odoo node. Exposes Odoo CRM and business operations as callable tools.",
  defaults: { name: "Odoo Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [{ name: "odooApi", required: true }],
  usableAsTool: true,
  sources: [ODOO_DOCS],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "contact",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Contact", value: "contact" },
        { name: "Custom Resource", value: "customResource" },
        { name: "Note", value: "note" },
        { name: "Opportunity", value: "opportunity" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["contact", "note", "opportunity"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["customResource"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Custom Resource Model",
      name: "customResourceModel",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["customResource"] } },
      placeholder: "e.g. x_custom.model",
    },
    {
      displayName: "Record ID",
      name: "recordId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["contact", "customResource", "note", "opportunity"], operation: ["get", "update", "delete"] },
      },
    },
    {
      displayName: "Fields",
      name: "fields",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: {
        show: { resource: ["contact", "customResource", "note", "opportunity"], operation: ["create", "update"] },
      },
      options: [
        {
          name: "values",
          displayName: "Field",
          values: [
            { displayName: "Field Name", name: "fieldName", type: "string", default: "" },
            { displayName: "Field Value", name: "fieldValue", type: "string", default: "" },
          ],
        },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["contact", "customResource", "note", "opportunity"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: {
        show: { resource: ["contact", "customResource", "note", "opportunity"], operation: ["getAll"], returnAll: [false] },
      },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["contact", "customResource", "note", "opportunity"] } },
      options: [
        { displayName: "Fields to Return", name: "fieldsToReturn", type: "string", default: "" },
        { displayName: "Order By", name: "orderBy", type: "string", default: "" },
        { displayName: "Filter", name: "filter", type: "string", default: "" },
      ],
    },
  ],
};

export const salesmate: INodeTypeDescription = {
  name: "n8n-nodes-base.salesmate",
  displayName: "Salesmate",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description: "Creates, reads, updates, and deletes activities, companies, and deals in Salesmate CRM",
  defaults: { name: "Salesmate" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [{ name: "salesmateApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.salesmate.md",
    "https://docs.n8n.io/integrations/builtin/credentials/salesmate.md",
    "https://apidocs.salesmate.io/",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "activity",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Activity", value: "activity" },
        { name: "Company", value: "company" },
        { name: "Deal", value: "deal" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["activity", "company", "deal"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Activity Type",
      name: "activityType",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["activity"], operation: ["create"] } },
    },
    {
      displayName: "Title",
      name: "title",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["activity", "deal"], operation: ["create", "update"] } },
    },
    {
      displayName: "Owner",
      name: "owner",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["activity", "company", "deal"], operation: ["create"] } },
    },
    {
      displayName: "Name",
      name: "name",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["company"], operation: ["create"] } },
      description: "Company name",
    },
    {
      displayName: "Date",
      name: "date",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["activity"], operation: ["create"] } },
      description: "Activity date/time in ISO 8601 format",
    },
    {
      displayName: "Description",
      name: "description",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["activity"], operation: ["create"] } },
    },
    {
      displayName: "Attendees",
      name: "attendees",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["activity"], operation: ["create"] } },
      description: "Comma-separated user IDs",
    },
    {
      displayName: "Primary Contact",
      name: "primaryContact",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["deal"], operation: ["create"] } },
    },
    {
      displayName: "Activity ID",
      name: "activityId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["activity"], operation: ["get", "update", "delete"] } },
    },
    {
      displayName: "Company ID",
      name: "companyId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["company"], operation: ["get", "update", "delete"] } },
    },
    {
      displayName: "Deal ID",
      name: "dealId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["deal"], operation: ["get", "update", "delete"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 20,
      typeOptions: { minValue: 1 },
      displayOptions: { show: { operation: ["getAll"] }, hide: { returnAll: [true] } },
    },
    {
      displayName: "Raw Data",
      name: "rawData",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["company", "deal"], operation: ["create", "get", "update"] } },
    },
    {
      displayName: "JSON Parameters",
      name: "jsonParameters",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["getAll", "update"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["create", "update"] } },
      options: [
        { displayName: "Website", name: "website", type: "string", default: "" },
        { displayName: "Phone", name: "phone", type: "string", default: "" },
        { displayName: "Other Phone", name: "otherPhone", type: "string", default: "" },
        { displayName: "Facebook Handle", name: "facebookHandle", type: "string", default: "" },
        { displayName: "Google Plus Handle", name: "googlePlusHandle", type: "string", default: "" },
        { displayName: "LinkedIn Handle", name: "linkedInHandle", type: "string", default: "" },
        { displayName: "Skype ID", name: "skypeId", type: "string", default: "" },
        { displayName: "Twitter Handle", name: "twitterHandle", type: "string", default: "" },
        { displayName: "Currency", name: "currency", type: "string", default: "" },
        { displayName: "Billing Address Line 1", name: "billingAddressLine1", type: "string", default: "" },
        { displayName: "Billing Address Line 2", name: "billingAddressLine2", type: "string", default: "" },
        { displayName: "Billing City", name: "billingCity", type: "string", default: "" },
        { displayName: "Billing Zip Code", name: "billingZipCode", type: "string", default: "" },
        { displayName: "Billing State", name: "billingState", type: "string", default: "" },
        { displayName: "Description", name: "description", type: "string", default: "" },
        { displayName: "Tags", name: "tags", type: "string", default: "" },
        { displayName: "Deal Value", name: "dealValue", type: "number", default: 0 },
        { displayName: "Pipeline", name: "pipeline", type: "string", default: "" },
        { displayName: "Status", name: "status", type: "string", default: "" },
        { displayName: "Stage", name: "stage", type: "string", default: "" },
        { displayName: "Deal Source", name: "dealSource", type: "string", default: "" },
        { displayName: "Probability", name: "probability", type: "number", default: 0 },
        { displayName: "Expected Close Date", name: "expectedCloseDate", type: "string", default: "" },
        { displayName: "Deal Type", name: "dealType", type: "string", default: "" },
        { displayName: "Company Name", name: "companyName", type: "string", default: "" },
        { displayName: "Company ID", name: "companyId", type: "string", default: "" },
        { displayName: "Contact IDs", name: "contactIds", type: "string", default: "" },
        { displayName: "Team IDs", name: "teamIds", type: "string", default: "" },
        { displayName: "Outcome", name: "outcome", type: "string", default: "" },
        { displayName: "Location", name: "location", type: "string", default: "" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["getAll"] } },
      options: [
        { displayName: "Sort By", name: "sortBy", type: "string", default: "" },
        { displayName: "Sort Order", name: "sortOrder", type: "options", default: "asc", options: [{ name: "Ascending", value: "asc" }, { name: "Descending", value: "desc" }] },
        { displayName: "Fields", name: "fields", type: "string", default: "" },
      ],
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["getAll"], jsonParameters: [false] } },
    },
    {
      displayName: "Filters (JSON)",
      name: "filtersJson",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["getAll"], jsonParameters: [true] } },
    },
  ],
};

export const uplead: INodeTypeDescription = {
  name: "n8n-nodes-base.uplead",
  displayName: "UpLead",
  category: "Sales",
  group: ["sales"],
  version: 1,
  description: "Enrich company and person records via the UpLead REST API",
  defaults: { name: "UpLead" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Package",
  credentials: [
    { name: "upleadApi", required: true },
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "Company",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Company", value: "Company" },
        { name: "Person", value: "Person" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "Enrich",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["Company", "Person"] } },
      options: [
        { name: "Enrich", value: "Enrich" },
      ],
    },
    {
      displayName: "By",
      name: "by",
      type: "options",
      default: "domain",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["Company"] } },
      options: [
        { name: "Domain", value: "domain" },
        { name: "Company Name", value: "companyName" },
      ],
    },
    {
      displayName: "Domain",
      name: "domain",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Company"], by: ["domain"] } },
    },
    {
      displayName: "Company Name",
      name: "companyName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Company"], by: ["companyName"] } },
    },
    {
      displayName: "By",
      name: "by",
      type: "options",
      default: "email",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["Person"] } },
      options: [
        { name: "Email", value: "email" },
        { name: "Name + Domain", value: "nameAndDomain" },
      ],
    },
    {
      displayName: "Email",
      name: "email",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Person"], by: ["email"] } },
    },
    {
      displayName: "First Name",
      name: "firstName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Person"], by: ["nameAndDomain"] } },
    },
    {
      displayName: "Last Name",
      name: "lastName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Person"], by: ["nameAndDomain"] } },
    },
    {
      displayName: "Domain",
      name: "domain",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["Person"], by: ["nameAndDomain"] } },
    },
  ],
};


