import type { INodeTypeDescription } from "../types";

export const linearTool: INodeTypeDescription = {
  name: "n8n-nodes-base.linearTool",
  displayName: "Linear (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Create, read, update, and delete issues and comments in Linear (AI tool variant)",
  defaults: { name: "Linear Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Kanban",
  credentials: [{ name: "linearApi", required: false }, { name: "linearOAuth2Api", required: false }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.linear.md",
    "https://developers.linear.app/docs/graphql/working-with-the-graphql-api",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "issue",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Issue", value: "issue" },
        { name: "Comment", value: "comment" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["issue"] } },
      options: [
        { name: "Add Link", value: "addLink" },
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "addComment",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["comment"] } },
      options: [
        { name: "Add Comment", value: "addComment" },
      ],
    },
    {
      displayName: "Issue Identifier",
      name: "issueIdentifier",
      type: "string",
      default: "",
      displayOptions: {
        show: {
          resource: ["issue"],
          operation: ["addLink", "delete", "get", "update"],
        },
      },
      description: "The Linear issue ID or identifier",
    },
    {
      displayName: "Issue Identifier",
      name: "issueIdentifier",
      type: "string",
      default: "",
      displayOptions: {
        show: {
          resource: ["comment"],
          operation: ["addComment"],
        },
      },
      description: "The Linear issue ID or identifier",
    },
    {
      displayName: "Issue Fields",
      name: "issueFields",
      type: "collection",
      default: {},
      displayOptions: {
        show: {
          resource: ["issue"],
          operation: ["create", "update"],
        },
      },
      options: [
        { displayName: "Title", name: "title", type: "string", default: "" },
        { displayName: "Description", name: "description", type: "string", default: "" },
        { displayName: "Team ID", name: "teamId", type: "string", default: "" },
        { displayName: "Status ID", name: "statusId", type: "string", default: "" },
        { displayName: "Priority", name: "priority", type: "number", default: 0 },
        { displayName: "Assignee ID", name: "assigneeId", type: "string", default: "" },
        { displayName: "Project ID", name: "projectId", type: "string", default: "" },
        { displayName: "Labels", name: "labels", type: "multiOptions", default: [] },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["issue"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      typeOptions: { minValue: 1, maxValue: 250 },
      displayOptions: { show: { resource: ["issue"], operation: ["getAll"], returnAll: [false] } },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["issue"], operation: ["getAll"] } },
      options: [
        { displayName: "Status", name: "status", type: "string", default: "" },
        { displayName: "Assignee", name: "assigneeId", type: "string", default: "" },
        { displayName: "Team", name: "teamId", type: "string", default: "" },
        { displayName: "Priority", name: "priority", type: "number", default: 0 },
      ],
    },
    {
      displayName: "Order By",
      name: "orderBy",
      type: "options",
      default: "",
      noDataExpression: true,
      displayOptions: { show: { resource: ["issue"], operation: ["getAll"] } },
      options: [
        { name: "Default", value: "" },
        { name: "Created At", value: "createdAt" },
        { name: "Updated At", value: "updatedAt" },
        { name: "Priority", value: "priority" },
      ],
    },
    {
      displayName: "Link URL",
      name: "linkUrl",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["issue"], operation: ["addLink"] } },
      description: "The URL to associate with the issue",
    },
    {
      displayName: "Link Title",
      name: "linkTitle",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["issue"], operation: ["addLink"] } },
      description: "Optional display title for the link",
    },
    {
      displayName: "Link Label",
      name: "linkLabel",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["issue"], operation: ["addLink"] } },
      description: "Optional label for the link",
    },
    {
      displayName: "Comment Body",
      name: "commentBody",
      type: "string",
      default: "",
      required: true,
      typeOptions: { rows: 4 },
      displayOptions: { show: { resource: ["comment"], operation: ["addComment"] } },
      description: "Markdown/text content for the comment",
    },
    {
      displayName: "Parent Comment ID",
      name: "parentCommentId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["comment"], operation: ["addComment"] } },
      description: "Optional parent comment ID when replying to an existing comment",
    },
  ],
};

export const linkedInTool: INodeTypeDescription = {
  name: "n8n-nodes-base.linkedInTool",
  displayName: "LinkedIn (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Publishes posts to LinkedIn on behalf of a person or organization page (AI agent tool variant)",
  defaults: { name: "LinkedIn Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Globe",
  credentials: [
    { name: "linkedInOAuth2Api", required: false },
    { name: "linkedInCommunityManagementOAuth2Api", required: false },
  ],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.linkedin.md",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "Standard",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Standard", value: "Standard" },
        { name: "Community Management", value: "Community Management" },
      ],
    },
    {
      displayName: "Post As",
      name: "postAs",
      type: "options",
      default: "Person",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Person", value: "Person" },
        { name: "Organization", value: "Organization" },
      ],
    },
    {
      displayName: "Person",
      name: "person",
      type: "string",
      default: "",
      displayOptions: { show: { postAs: ["Person"] } },
    },
    {
      displayName: "Organization",
      name: "organization",
      type: "string",
      default: "",
      displayOptions: { show: { postAs: ["Organization"] } },
    },
    {
      displayName: "Text",
      name: "text",
      type: "string",
      default: "",
      required: true,
      typeOptions: { rows: 4 },
    },
    {
      displayName: "Media Category",
      name: "mediaCategory",
      type: "options",
      default: "None",
      noDataExpression: true,
      options: [
        { name: "None", value: "None" },
        { name: "Article", value: "Article" },
        { name: "Image", value: "Image" },
      ],
    },
    {
      displayName: "Binary Property Name",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      displayOptions: { show: { mediaCategory: ["Image"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Description",
          name: "description",
          type: "string",
          default: "",
        },
      ],
    },
  ],
};

export const microsoftToDoTool: INodeTypeDescription = {
  name: "n8n-nodes-base.microsoftToDoTool",
  displayName: "Microsoft To Do (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Create, read, update, and delete task lists and tasks in Microsoft To Do (AI agent tool variant)",
  defaults: { name: "Microsoft To Do Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "CheckCircle",
  credentials: [
    { name: "microsoftToDoOAuth2Api", required: false },
    { name: "microsoftEntraServicePrincipalApi", required: false },
  ],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.microsofttodo/",
    "https://learn.microsoft.com/en-us/graph/todo-concept-overview",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Linked Resource", value: "linkedResource" },
        { name: "List", value: "list" },
        { name: "Task", value: "task" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "List ID",
      name: "listId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["task", "linkedResource"] },
      },
    },
    {
      displayName: "Display Name",
      name: "displayName",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["list", "linkedResource"] },
      },
    },
    {
      displayName: "Task ID",
      name: "taskId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["linkedResource"] },
      },
    },
    {
      displayName: "Linked Resource ID",
      name: "linkedResourceId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["linkedResource"] },
      },
    },
  ],
};

export const nasaTool: INodeTypeDescription = {
  name: "n8n-nodes-base.nasaTool",
  displayName: "NASA (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Fetches data from NASA APIs as an AI agent tool (APOD, NEO, DONKI, Earth, Mars, Media, Tech Transfer, TLE)",
  defaults: { name: "NASA Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Rocket",
  credentials: [{ name: "nasaApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.nasa.md",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "astronomyPictureOfTheDay",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Astronomy Picture of the Day", value: "astronomyPictureOfTheDay" },
        { name: "Asteroid Neo-Feed", value: "asteroidNeoFeed" },
        { name: "Asteroid Neo-Lookup", value: "asteroidNeoLookup" },
        { name: "Asteroid Neo-Browse", value: "asteroidNeoBrowse" },
        { name: "DONKI Coronal Mass Ejection", value: "donkiCoronalMassEjection" },
        { name: "DONKI Geomagnetic Storm", value: "donkiGeomagneticStorm" },
        { name: "DONKI High Speed Stream", value: "donkiHighSpeedStream" },
        { name: "DONKI Interplanetary Shock", value: "donkiInterplanetaryShock" },
        { name: "DONKI Magnetopause Crossing", value: "donkiMagnetopauseCrossing" },
        { name: "DONKI Notification", value: "donkiNotifications" },
        { name: "DONKI Radiation Belt Enhancement", value: "donkiRadiationBeltEnhancement" },
        { name: "DONKI Solar Energetic Particle", value: "donkiSolarEnergeticParticle" },
        { name: "DONKI Solar Flare", value: "donkiSolarFlare" },
        { name: "DONKI WSA+EnlilSimulation", value: "donkiWsaEnlilSimulation" },
        { name: "Earth Imagery", value: "earthImagery" },
        { name: "Earth Asset (Landsat metadata)", value: "earthAssets" },
        { name: "InSight Mars Weather Service", value: "inSightMarsWeatherService" },
        { name: "Image and Video Library", value: "imageAndVideoLibrary" },
        { name: "TechTransfer (NASA patents/software)", value: "techTransfer" },
        { name: "Two-Line Element Set (satellite TLE)", value: "twoLineElementSet" },
      ],
    },
    {
      displayName: "Asteroid ID",
      name: "asteroidId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["asteroidNeoLookup"] } },
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["asteroidNeoBrowse"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 20,
      displayOptions: { show: { resource: ["asteroidNeoBrowse"] } },
      typeOptions: { minValue: 1 },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Date",
          name: "date",
          type: "dateTime",
          default: "",
          description: "Date for APOD or Earth imagery (YYYY-MM-DD)",
        },
        {
          displayName: "Start Date",
          name: "startDate",
          type: "dateTime",
          default: "",
          description: "Start date for date-range queries (YYYY-MM-DD)",
        },
        {
          displayName: "End Date",
          name: "endDate",
          type: "dateTime",
          default: "",
          description: "End date for date-range queries (YYYY-MM-DD)",
        },
        {
          displayName: "Latitude",
          name: "lat",
          type: "number",
          default: 0,
          description: "Latitude coordinate",
        },
        {
          displayName: "Longitude",
          name: "lon",
          type: "number",
          default: 0,
          description: "Longitude coordinate",
        },
        {
          displayName: "Dimension",
          name: "dim",
          type: "number",
          default: 0.025,
          description: "Width and height in degrees for Earth imagery",
        },
        {
          displayName: "Include Close Approach Data",
          name: "includeCloseApproachData",
          type: "boolean",
          default: false,
          displayOptions: { show: { "/resource": ["asteroidNeoLookup"] } },
        },
        {
          displayName: "Location",
          name: "location",
          type: "options",
          default: "ALL",
          noDataExpression: true,
          options: [
            { name: "All", value: "ALL" },
            { name: "Earth", value: "earth" },
            { name: "MESSENGER", value: "MESSENGER" },
            { name: "STEREO A", value: "STEREO A" },
            { name: "STEREO B", value: "STEREO B" },
          ],
          displayOptions: { show: { "/resource": ["donkiInterplanetaryShock"] } },
        },
        {
          displayName: "Catalog",
          name: "catalog",
          type: "options",
          default: "ALL",
          noDataExpression: true,
          options: [
            { name: "All", value: "ALL" },
            { name: "SWRC Catalog", value: "SWRC_CATALOG" },
            { name: "Winslow Messenger ICME Catalog", value: "WINSLOW_MESSENGER_ICME_CATALOG" },
          ],
          displayOptions: { show: { "/resource": ["donkiInterplanetaryShock"] } },
        },
      ],
    },
  ],
};

const NOCO_DOCS = "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.nocodb/";

export const nocoDbTool: INodeTypeDescription = {
  name: "n8n-nodes-base.nocoDbTool",
  displayName: "NocoDB (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Create, read, update, and delete rows in NocoDB (AI agent tool variant)",
  defaults: { name: "NocoDB Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Database",
  credentials: [
    { name: "nocoDbApi", required: false },
    { name: "nocoDb", required: false },
  ],
  sources: [NOCO_DOCS],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "row",
      required: true,
      noDataExpression: true,
      options: [{ name: "Row", value: "row" }],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Workspace ID",
      name: "workspaceId",
      type: "string",
      default: "",
    },
    {
      displayName: "Project ID (Base)",
      name: "projectId",
      type: "string",
      default: "",
      required: true,
    },
    {
      displayName: "Table",
      name: "table",
      type: "string",
      default: "",
      required: true,
    },
    {
      displayName: "Row ID Value",
      name: "id",
      type: "string",
      default: "",
      displayOptions: {
        show: { operation: ["get", "update", "delete"] },
      },
    },
    {
      displayName: "Data to Send",
      name: "dataToSend",
      type: "options",
      default: "defineBelow",
      displayOptions: { show: { operation: ["create", "update"] } },
      options: [
        { name: "Auto-Map Input Data to Columns", value: "autoMapInputData" },
        { name: "Define Below", value: "defineBelow" },
      ],
    },
    {
      displayName: "Inputs to Ignore",
      name: "inputsToIgnore",
      type: "string",
      default: "",
      displayOptions: {
        show: { operation: ["create", "update"], dataToSend: ["autoMapInputData"] },
      },
    },
    {
      displayName: "Fields to Send",
      name: "fieldsUi",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: {
        show: { operation: ["create", "update"], dataToSend: ["defineBelow"] },
      },
      options: [
        {
          name: "fieldValues",
          displayName: "Field",
          values: [
            { displayName: "Field Name", name: "fieldName", type: "string", default: "" },
            { displayName: "Field Value", name: "fieldValue", type: "string", default: "" },
          ],
        },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { operation: ["getAll"], returnAll: [false] } },
      typeOptions: { minValue: 1, maxValue: 100 },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["getAll"] } },
      options: [
        { displayName: "View ID", name: "viewId", type: "string", default: "" },
        { displayName: "Fields", name: "fields", type: "multiOptions", default: [] },
        {
          displayName: "Sort",
          name: "sort",
          type: "fixedCollection",
          default: {},
          typeOptions: { multipleValues: true },
          options: [
            {
              name: "property",
              displayName: "Sort Property",
              values: [
                { displayName: "Field", name: "field", type: "string", default: "" },
                {
                  displayName: "Direction",
                  name: "direction",
                  type: "options",
                  default: "asc",
                  options: [
                    { name: "Asc", value: "asc" },
                    { name: "Desc", value: "desc" },
                  ],
                },
              ],
            },
          ],
        },
        { displayName: "Filter By Formula", name: "filterByFormula", type: "string", default: "" },
      ],
    },
  ],
};

export const mongoDbTool: INodeTypeDescription = {
  name: "n8n-nodes-base.mongoDbTool",
  displayName: "MongoDB (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Interact with MongoDB via AI Agent tools",
  defaults: { name: "MongoDB Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Database",
  credentials: [{ name: "mongoDb", required: false }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.mongodb.md",
  ],
  properties: [
    {
      displayName: "Collection",
      name: "collection",
      type: "string",
      default: "",
      required: true,
    },
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "document",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Document", value: "document" },
        { name: "Search Index", value: "searchIndex" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "insert",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Aggregate", value: "aggregate" },
        { name: "Delete", value: "delete" },
        { name: "Find", value: "find" },
        { name: "Insert", value: "insert" },
        { name: "Find One And Replace", value: "findOneAndReplace" },
        { name: "Find One And Update", value: "findOneAndUpdate" },
        { name: "Update", value: "update" },
      ],
      displayOptions: { show: { resource: ["document"] } },
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "list",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Create", value: "create" },
        { name: "Drop", value: "drop" },
        { name: "List", value: "list" },
        { name: "Update", value: "update" },
      ],
      displayOptions: { show: { resource: ["searchIndex"] } },
    },
  ],
};

export const pagerDutyTool: INodeTypeDescription = {
  name: "n8n-nodes-base.pagerDutyTool",
  displayName: "PagerDuty (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Create, read, and update PagerDuty incidents, notes, log entries, and users (AI agent tool variant)",
  defaults: { name: "PagerDuty Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "PhoneCall",
  credentials: [
    { name: "pagerDutyApi", required: false },
    { name: "pagerDutyOAuth2Api", required: false },
  ],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.pagerduty.md",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "apiToken",
      required: true,
      noDataExpression: true,
      options: [
        { name: "API Token", value: "apiToken" },
        { name: "OAuth2", value: "oAuth2" },
      ],
    },
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "incident",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Incident", value: "incident" },
        { name: "Incident Note", value: "incidentNote" },
        { name: "Log Entry", value: "logEntry" },
        { name: "User", value: "user" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["incident"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["incidentNote"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["logEntry"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["user"] } },
      options: [
        { name: "Get", value: "get" },
      ],
    },
    {
      displayName: "Incident ID",
      name: "incidentId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["incident", "incidentNote"] } },
    },
    {
      displayName: "User ID",
      name: "userId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["user"] } },
    },
    {
      displayName: "Title",
      name: "title",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["incident"], operation: ["create"] } },
    },
    {
      displayName: "Service ID",
      name: "serviceId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["incident"], operation: ["create"] } },
    },
    {
      displayName: "Email (From)",
      name: "email",
      type: "string",
      default: "",
      description: "Email address of a valid user associated with the PagerDuty account",
      displayOptions: { show: { resource: ["incident", "incidentNote"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["incident"], operation: ["create", "update"] } },
      options: [
        { displayName: "Details", name: "details", type: "string", default: "" },
        { displayName: "Urgency", name: "urgency", type: "options", default: "high", noDataExpression: true, options: [{ name: "High", value: "high" }, { name: "Low", value: "low" }] },
        { displayName: "Incident Key", name: "incidentKey", type: "string", default: "" },
        { displayName: "Escalation Policy ID", name: "escalationPolicyId", type: "string", default: "" },
        { displayName: "Priority ID", name: "priorityId", type: "string", default: "" },
      ],
    },
    {
      displayName: "Update Fields",
      name: "updateFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["incident"], operation: ["update"] } },
      options: [
        { displayName: "Title", name: "title", type: "string", default: "" },
        { displayName: "Status", name: "status", type: "options", default: "acknowledged", noDataExpression: true, options: [{ name: "Acknowledged", value: "acknowledged" }, { name: "Resolved", value: "resolved" }] },
        { displayName: "Escalation Policy ID", name: "escalationPolicyId", type: "string", default: "" },
        { displayName: "Priority ID", name: "priorityId", type: "string", default: "" },
        { displayName: "Resolution", name: "resolution", type: "string", default: "" },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["incident"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      typeOptions: { minValue: 1, maxValue: 100 },
      displayOptions: { show: { resource: ["incident"], operation: ["getAll"], returnAll: [false] } },
    },
  ],
};

export const trelloTool: INodeTypeDescription = {
  name: "n8n-nodes-base.trelloTool",
  displayName: "Trello (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Create, read, update, and delete Trello resources (Attachment, Board, Board Member, Card, Card Comment, Checklist, Label, List) as an AI agent tool",
  defaults: { name: "Trello Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Kanban",
  credentials: [{ name: "trelloApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.trello/",
    "https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "card",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Attachment", value: "attachment" },
        { name: "Board", value: "board" },
        { name: "Board Member", value: "boardMember" },
        { name: "Card", value: "card" },
        { name: "Card Comment", value: "cardComment" },
        { name: "Checklist", value: "checklist" },
        { name: "Label", value: "label" },
        { name: "List", value: "list" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["attachment"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["board"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["boardMember"] } },
      options: [
        { name: "Add", value: "add" },
        { name: "Get All", value: "getAll" },
        { name: "Invite", value: "invite" },
        { name: "Remove", value: "remove" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["card"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["cardComment"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["checklist"] } },
      options: [
        { name: "Create (checklist)", value: "create" },
        { name: "Create (item)", value: "createCheckItem" },
        { name: "Delete (checklist)", value: "delete" },
        { name: "Delete (item)", value: "deleteCheckItem" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Get CheckItem", value: "getCheckItem" },
        { name: "Get Completed CheckItems", value: "getCompletedCheckItems" },
        { name: "Update (item)", value: "updateCheckItem" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["label"] } },
      options: [
        { name: "Add", value: "addLabel" },
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Remove", value: "removeLabel" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Archive", value: "archive" },
        { name: "Create", value: "create" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Get All Cards", value: "getCards" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Board ID",
      name: "boardId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["board", "boardMember", "list", "card", "label", "cardComment", "checklist", "attachment"] },
      },
    },
    {
      displayName: "Card ID",
      name: "cardId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["cardComment", "checklist", "attachment"] },
      },
    },
    {
      displayName: "List ID",
      name: "listId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["list", "card"], operation: ["create", "getCards"] },
      },
    },
    {
      displayName: "Card ID",
      name: "cardId",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["card"], operation: ["update", "get", "delete"] },
      },
    },
    {
      displayName: "Name",
      name: "name",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["card", "list", "label", "checklist"], operation: ["create"] },
      },
    },
  ],
};

export const clickUpTool: INodeTypeDescription = {
  name: "n8n-nodes-base.clickUpTool",
  displayName: "ClickUp (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Create, read, update, and delete ClickUp resources (Checklist, Checklist Item, Comment, Folder, Goal, Goal Key Result, List, Space Tag, Task, Task List, Task Tag, Task Dependency, Time Entry, Time Entry Tag) as an AI agent tool variant",
  defaults: { name: "ClickUp Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Kanban",
  credentials: [
    { name: "clickUpApi", required: false },
    { name: "clickUpOAuth2Api", required: false },
  ],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.clickup/",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "task",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Checklist", value: "checklist" },
        { name: "Checklist Item", value: "checklistItem" },
        { name: "Comment", value: "comment" },
        { name: "Folder", value: "folder" },
        { name: "Goal", value: "goal" },
        { name: "Goal Key Result", value: "goalKeyResult" },
        { name: "List", value: "list" },
        { name: "Space Tag", value: "spaceTag" },
        { name: "Task", value: "task" },
        { name: "Task List", value: "taskList" },
        { name: "Task Tag", value: "taskTag" },
        { name: "Task Dependency", value: "taskDependency" },
        { name: "Time Entry", value: "timeEntry" },
        { name: "Time Entry Tag", value: "timeEntryTag" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["checklist"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["checklistItem"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["comment"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["folder"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["goal"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["goalKeyResult"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["list"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Get Custom Fields", value: "getCustomFields" },
        { name: "Get Members", value: "getMembers" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["spaceTag"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["task"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Get Members", value: "getMembers" },
        { name: "Set Custom Field", value: "setCustomField" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "add",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["taskList"] } },
      options: [
        { name: "Add", value: "add" },
        { name: "Remove", value: "remove" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "add",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["taskTag"] } },
      options: [
        { name: "Add", value: "add" },
        { name: "Remove", value: "remove" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["taskDependency"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["timeEntry"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Start", value: "start" },
        { name: "Stop", value: "stop" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["timeEntryTag"] } },
      options: [
        { name: "Add Tag", value: "addTag" },
        { name: "Get All", value: "getAll" },
        { name: "Remove Tag", value: "removeTag" },
      ],
    },
    {
      displayName: "Workspace ID",
      name: "workspace",
      type: "string",
      default: "",
      required: true,
      description: "ClickUp Workspace (team) ID",
    },
    {
      displayName: "Space ID",
      name: "space",
      type: "string",
      default: "",
      required: true,
      description: "ClickUp Space ID within the selected workspace",
    },
    {
      displayName: "Folder ID",
      name: "folder",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["list", "folder"] } },
    },
    {
      displayName: "List ID",
      name: "list",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["task"] },
      },
    },
    {
      displayName: "Task ID",
      name: "taskId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["task"] },
        hide: { operation: ["create"] },
      },
    },
  ],
};

export const stripeTool: INodeTypeDescription = {
  name: "n8n-nodes-base.stripeTool",
  displayName: "Stripe (AI Tool)",
  category: "AI Tool",
  group: ["output"],
  version: 1,
  description: "Access the Stripe REST API to manage charges, customers, coupons, sources, tokens, meter events, and account balances (AI agent tool variant)",
  defaults: { name: "Stripe Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Globe",
  credentials: [{ name: "stripeApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.stripe.md",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "secretKey",
      noDataExpression: true,
      required: true,
      options: [{ name: "Secret Key", value: "secretKey" }],
    },
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "balance",
      noDataExpression: true,
      required: true,
      options: [
        { name: "Balance", value: "balance" },
        { name: "Charge", value: "charge" },
        { name: "Coupon", value: "coupon" },
        { name: "Customer", value: "customer" },
        { name: "Customer Card", value: "customerCard" },
        { name: "Meter Event", value: "meterEvent" },
        { name: "Source", value: "source" },
        { name: "Token", value: "token" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["balance"] } },
      options: [{ name: "Get", value: "get" }],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["charge"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["coupon"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Get All", value: "getAll" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["customer"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get All", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "add",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["customerCard"] } },
      options: [
        { name: "Add", value: "add" },
        { name: "Get", value: "get" },
        { name: "Remove", value: "remove" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["meterEvent"] } },
      options: [{ name: "Create", value: "create" }],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["source"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Get", value: "get" },
        { name: "Delete", value: "delete" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "create",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["token"] } },
      options: [{ name: "Create", value: "create" }],
    },
    {
      displayName: "Charge ID",
      name: "chargeId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["charge"], operation: ["get", "update"] } },
    },
    {
      displayName: "Customer ID",
      name: "customerId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["customer"], operation: ["get", "delete", "update"] } },
    },
    {
      displayName: "Customer ID",
      name: "customerId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["customerCard", "meterEvent"] } },
    },
    {
      displayName: "Card ID",
      name: "cardId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["customerCard"], operation: ["get", "remove"] } },
    },
    {
      displayName: "Source ID",
      name: "sourceId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["source"], operation: ["get", "delete"] } },
    },
    {
      displayName: "Amount",
      name: "amount",
      type: "number",
      default: 0,
      required: true,
      displayOptions: { show: { resource: ["charge"], operation: ["create"] } },
    },
    {
      displayName: "Currency",
      name: "currency",
      type: "string",
      default: "usd",
      required: true,
      displayOptions: { show: { resource: ["charge"], operation: ["create"] } },
    },
    {
      displayName: "Source",
      name: "source",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["charge"], operation: ["create"] } },
    },
    {
      displayName: "Event Name",
      name: "eventName",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["meterEvent"], operation: ["create"] } },
    },
    {
      displayName: "Value",
      name: "value",
      type: "number",
      default: 1,
      required: true,
      displayOptions: { show: { resource: ["meterEvent"], operation: ["create"] } },
    },
    {
      displayName: "Duration",
      name: "duration",
      type: "options",
      default: "once",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["coupon"], operation: ["create"] } },
      options: [
        { name: "Once", value: "once" },
        { name: "Forever", value: "forever" },
        { name: "Repeating", value: "repeating" },
      ],
    },
    {
      displayName: "Percent Off",
      name: "percentOff",
      type: "number",
      default: 0,
      displayOptions: { show: { resource: ["coupon"], operation: ["create"] } },
    },
    {
      displayName: "Amount Off",
      name: "amountOff",
      type: "number",
      default: 0,
      displayOptions: { show: { resource: ["coupon"], operation: ["create"] } },
    },
    {
      displayName: "Source Type",
      name: "sourceType",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["source"], operation: ["create"] } },
    },
    {
      displayName: "Token Type",
      name: "tokenType",
      type: "string",
      default: "card",
      displayOptions: { show: { resource: ["token"], operation: ["create"] } },
    },
    {
      displayName: "Customer ID",
      name: "customerId",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["source"], operation: ["create"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 10,
      typeOptions: { minValue: 1, maxValue: 100 },
      displayOptions: { show: { resource: ["charge", "customer"], operation: ["getAll"] } },
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: {
        show: {
          resource: ["charge", "customer", "source", "token"],
          operation: ["create", "update"],
        },
      },
      options: [
        { displayName: "Description", name: "description", type: "string", default: "" },
        { displayName: "Name", name: "name", type: "string", default: "" },
        { displayName: "Email", name: "email", type: "string", default: "" },
        { displayName: "Phone", name: "phone", type: "string", default: "" },
        { displayName: "Metadata", name: "metadata", type: "json", default: "{}" },
        { displayName: "Card", name: "card", type: "collection", default: {}, options: [
          { displayName: "Number", name: "number", type: "string", default: "" },
          { displayName: "Exp Month", name: "expMonth", type: "number", default: 0 },
          { displayName: "Exp Year", name: "expYear", type: "number", default: 0 },
          { displayName: "CVC", name: "cvc", type: "string", default: "" },
        ]},
        {
          displayName: "Statement Descriptor",
          name: "statementDescriptor",
          type: "string",
          default: "",
          displayOptions: { show: { "/resource": ["charge"] } },
        },
      ],
    },
  ],
};

export const marketstackTool: INodeTypeDescription = {
  name: "n8n-nodes-base.marketstackTool",
  displayName: "Marketstack (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Retrieves stock market data (end-of-day, exchanges, tickers) via the Marketstack API (AI agent tool variant)",
  defaults: { name: "Marketstack Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "TrendingUp",
  credentials: [{ name: "marketstackApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.marketstack/",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "endOfDayData",
      required: true,
      noDataExpression: true,
      options: [
        { name: "End-of-Day Data", value: "endOfDayData" },
        { name: "Exchange", value: "exchange" },
        { name: "Ticker", value: "ticker" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["endOfDayData"] } },
      options: [{ name: "Get Many", value: "getAll" }],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["exchange"] } },
      options: [{ name: "Get", value: "get" }],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["ticker"] } },
      options: [{ name: "Get", value: "get" }],
    },
    {
      displayName: "Symbols",
      name: "symbols",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["endOfDayData"] } },
      placeholder: "AAPL,MSFT",
    },
    {
      displayName: "Exchange MIC",
      name: "exchange",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["exchange"] } },
      placeholder: "XNAS",
    },
    {
      displayName: "Symbol",
      name: "symbol",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["ticker"] } },
      placeholder: "AAPL",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["endOfDayData"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      typeOptions: { minValue: 1 },
      displayOptions: { show: { resource: ["endOfDayData"], returnAll: [false] } },
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["endOfDayData"] } },
      options: [
        { displayName: "Exchange", name: "exchange", type: "string", default: "", placeholder: "XNAS" },
        { displayName: "Latest", name: "latest", type: "boolean", default: false },
        {
          displayName: "Sort",
          name: "sort",
          type: "options",
          default: "DESC",
          options: [
            { name: "ASC", value: "ASC" },
            { name: "DESC", value: "DESC" },
          ],
        },
        { displayName: "Specific Date", name: "specificDate", type: "dateTime", default: "" },
        { displayName: "Date From", name: "dateFrom", type: "dateTime", default: "" },
        { displayName: "Date To", name: "dateTo", type: "dateTime", default: "" },
      ],
    },
  ],
};

export const gSuiteAdminTool: INodeTypeDescription = {
  name: "n8n-nodes-base.gSuiteAdminTool",
  displayName: "Google Workspace Admin (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Manage ChromeOS devices, Groups, and Users in Google Workspace via the Admin SDK Directory API (AI agent tool variant)",
  defaults: { name: "Google Workspace Admin" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Globe",
  credentials: [{ name: "gSuiteAdminOAuth2Api", required: false }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.gsuiteadmin/",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "user",
      required: true,
      noDataExpression: true,
      options: [
        { name: "ChromeOS Device", value: "device" },
        { name: "Group", value: "group" },
        { name: "User", value: "user" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["user"] } },
      options: [
        { name: "Add to Group", value: "addToGroup" },
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Remove From Group", value: "removeFromGroup" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["group"] } },
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["device"] } },
      options: [
        { name: "Change Status", value: "changeStatus" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
  ],
};

export const googleAdsTool: INodeTypeDescription = {
  name: "n8n-nodes-base.googleAdsTool",
  displayName: "Google Ads (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Google Ads campaign read operations (Get All, Get) for AI Agent tool use. Supports manager-account (MCC) cross-client queries.",
  defaults: { name: "Google Ads Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Google",
  credentials: [{ name: "googleAdsOAuth2Api", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.googleads.md",
    "https://developers.google.com/google-ads/api/docs/start",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "campaign",
      required: true,
      noDataExpression: true,
      options: [{ name: "Campaign", value: "campaign" }],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getAll",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["campaign"] } },
      options: [
        { name: "Get All", value: "getAll" },
        { name: "Get", value: "get" },
      ],
    },
    {
      displayName: "Manager Customer ID",
      name: "managerCustomerId",
      type: "string",
      default: "",
      description: "Manager (MCC) customer ID when querying across child accounts",
    },
    {
      displayName: "Client Customer ID",
      name: "clientCustomerId",
      type: "string",
      default: "",
      description: "Target client customer ID for the specific Google Ads account",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"] } },
    },
    {
      displayName: "Date Range",
      name: "dateRange",
      type: "options",
      default: "",
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"] } },
      options: [
        { name: "All Time", value: "allTime" },
        { name: "Today", value: "TODAY" },
        { name: "Yesterday", value: "YESTERDAY" },
        { name: "Last 7 Days", value: "LAST_7_DAYS" },
        { name: "Last Business Week", value: "LAST_BUSINESS_WEEK" },
        { name: "This Month", value: "THIS_MONTH" },
        { name: "Last Month", value: "LAST_MONTH" },
        { name: "Last 14 Days", value: "LAST_14_DAYS" },
        { name: "Last 30 Days", value: "LAST_30_DAYS" },
      ],
    },
    {
      displayName: "Campaign Status",
      name: "campaignStatus",
      type: "options",
      default: "all",
      displayOptions: { show: { resource: ["campaign"], operation: ["getAll"] } },
      options: [
        { name: "All", value: "all" },
        { name: "Enabled", value: "ENABLED" },
        { name: "Paused", value: "PAUSED" },
        { name: "Removed", value: "REMOVED" },
      ],
    },
    {
      displayName: "Campaign ID",
      name: "campaignId",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["campaign"], operation: ["get"] } },
      description: "Google Ads campaign ID or resource name",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Proxy",
          name: "proxy",
          type: "string",
          default: "",
          description: "HTTP proxy URL for the API request",
        },
        {
          displayName: "Timeout",
          name: "timeout",
          type: "number",
          default: 0,
          description: "Request timeout in milliseconds",
        },
        {
          displayName: "Allow Unauthorized Certificates",
          name: "allowUnauthorizedCerts",
          type: "boolean",
          default: false,
          description: "Skip TLS certificate verification",
        },
      ],
    },
  ],
};

export const spotifyTool: INodeTypeDescription = {
  name: "n8n-nodes-base.spotifyTool",
  displayName: "Spotify (AI Tool)",
  category: "AI Tool",
  group: ["input"],
  version: 1,
  description: "Search albums, artists, playlists, tracks, manage library, and control Spotify playback via the Spotify Web API (AI agent tool variant)",
  defaults: { name: "Spotify Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Music",
  credentials: [{ name: "spotifyOAuth2Api", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.spotify.md",
    "https://docs.n8n.io/build/integrate-ai/understand-ai-components/how-tools-work.md",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "player",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Album", value: "album" },
        { name: "Artist", value: "artist" },
        { name: "Library", value: "library" },
        { name: "My Data", value: "myData" },
        { name: "Player", value: "player" },
        { name: "Playlist", value: "playlist" },
        { name: "Track", value: "track" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "addSongToQueue",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["album"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get New Releases", value: "getNewReleases" },
        { name: "Get Tracks", value: "getTracks" },
        { name: "Search", value: "search" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "search",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["artist"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get Albums", value: "getAlbums" },
        { name: "Get Related Artists", value: "getRelatedArtists" },
        { name: "Get Top Tracks", value: "getTopTracks" },
        { name: "Search", value: "search" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getLikedTracks",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["library"] } },
      options: [
        { name: "Get Liked Tracks", value: "getLikedTracks" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "getFollowingArtists",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["myData"] } },
      options: [
        { name: "Get Following Artists", value: "getFollowingArtists" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "currentlyPlaying",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["player"] } },
      options: [
        { name: "Add Song to Queue", value: "addSongToQueue" },
        { name: "Currently Playing", value: "currentlyPlaying" },
        { name: "Next Song", value: "nextSong" },
        { name: "Pause", value: "pause" },
        { name: "Previous Song", value: "previousSong" },
        { name: "Recently Played", value: "recentlyPlayed" },
        { name: "Resume", value: "resume" },
        { name: "Set Volume", value: "volume" },
        { name: "Start Music", value: "startMusic" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["playlist"] } },
      options: [
        { name: "Add", value: "add" },
        { name: "Create", value: "create" },
        { name: "Get", value: "get" },
        { name: "Get User Playlists", value: "getUserPlaylists" },
        { name: "Get Tracks", value: "getTracks" },
        { name: "Delete", value: "delete" },
        { name: "Search", value: "search" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { resource: ["track"] } },
      options: [
        { name: "Get", value: "get" },
        { name: "Get Audio Features", value: "getAudioFeatures" },
        { name: "Search", value: "search" },
      ],
    },
    {
      displayName: "ID",
      name: "id",
      type: "string",
      default: "",
      description: "Spotify URI or ID",
      displayOptions: {
        show: {
          resource: ["album", "artist", "player", "playlist", "track"],
          operation: ["get", "getTracks", "getAlbums", "getRelatedArtists", "getTopTracks", "startMusic", "addSongToQueue", "add", "delete", "getAudioFeatures"],
        },
      },
    },
    {
      displayName: "Query",
      name: "query",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["album", "artist", "playlist", "track"], operation: ["search"] } },
      description: "Free-text search query",
    },
    {
      displayName: "Name",
      name: "name",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["playlist"], operation: ["create"] } },
      description: "Name of the new playlist",
    },
    {
      displayName: "Track ID",
      name: "trackID",
      type: "string",
      default: "",
      displayOptions: { show: { resource: ["playlist"], operation: ["add", "delete"] } },
      description: "Track URI or ID to add/remove",
    },
    {
      displayName: "Volume Percent",
      name: "volumePercent",
      type: "number",
      default: 50,
      typeOptions: { minValue: 0, maxValue: 100 },
      displayOptions: { show: { resource: ["player"], operation: ["volume"] } },
      description: "Volume value 0–100",
    },
    {
      displayName: "Country",
      name: "country",
      type: "string",
      default: "US",
      displayOptions: { show: { resource: ["artist"], operation: ["getTopTracks"] } },
      description: "ISO 3166-1 alpha-2 country code",
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["search", "getAll", "getTracks", "getLikedTracks", "getFollowingArtists", "getUserPlaylists", "recentlyPlayed"] } },
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 50,
      typeOptions: { minValue: 1, maxValue: 50 },
      displayOptions: { show: { returnAll: [false] } },
      description: "Maximum number of items per page",
    },
    {
      displayName: "Additional Fields",
      name: "additionalFields",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["playlist"], operation: ["create", "add"] } },
      options: [
        { displayName: "Description", name: "description", type: "string", default: "" },
        { displayName: "Public", name: "public", type: "boolean", default: true },
        { displayName: "Position", name: "position", type: "number", default: 0 },
      ],
    },
    {
      displayName: "Filters",
      name: "filters",
      type: "collection",
      default: {},
      displayOptions: { show: { resource: ["album", "artist", "playlist", "track"], operation: ["search", "getNewReleases"] } },
      options: [
        { displayName: "Country", name: "country", type: "string", default: "US", displayOptions: { show: { "/resource": ["album"], "/operation": ["getNewReleases"] } } },
        { displayName: "Market", name: "market", type: "string", default: "", description: "ISO 3166-1 alpha-2 market filter" },
      ],
    },
  ],
};

export const webflowTool: INodeTypeDescription = {
  name: "n8n-nodes-base.webflowTool",
  displayName: "Webflow (AI Tool)",
  category: "AI Tool",
  group: ["output"],
  version: 1,
  description: "Create, read, update, delete, and list Webflow CMS collection items (AI tool variant)",
  defaults: { name: "Webflow Tool" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Globe",
  credentials: [
    { name: "webflowOAuth2Api", required: false },
    { name: "webflowApi", required: false },
  ],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.webflow.md",
    "https://developers.webflow.com/data/reference/rest-introduction",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "fixed",
      default: "item",
      required: true,
      noDataExpression: true,
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "get",
      required: true,
      noDataExpression: true,
      options: [
        { name: "Create", value: "create" },
        { name: "Delete", value: "delete" },
        { name: "Get", value: "get" },
        { name: "Get Many", value: "getAll" },
        { name: "Update", value: "update" },
      ],
    },
    {
      displayName: "Site ID",
      name: "siteId",
      type: "string",
      default: "",
      required: true,
      description: "The Webflow site ID",
    },
    {
      displayName: "Collection ID",
      name: "collectionId",
      type: "string",
      default: "",
      required: true,
      description: "The Webflow collection ID",
    },
    {
      displayName: "Item ID",
      name: "itemId",
      type: "string",
      default: "",
      displayOptions: {
        show: { operation: ["get", "delete", "update"] },
      },
      description: "The Webflow item ID",
    },
    {
      displayName: "Live",
      name: "live",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { operation: ["create", "update"] },
      },
      description: "Publish changes to the live site immediately",
    },
    {
      displayName: "Fields",
      name: "fieldsUi",
      type: "fixedCollection",
      default: {},
      displayOptions: {
        show: { operation: ["create", "update"] },
      },
      typeOptions: {
        multipleValues: true,
      },
      options: [
        {
          name: "fieldValues",
          displayName: "Field Value",
          values: [
            {
              displayName: "Field ID",
              name: "fieldId",
              type: "string",
              default: "",
              description: "The collection field key",
            },
            {
              displayName: "Field Value",
              name: "fieldValue",
              type: "string",
              default: "",
              description: "The value to set for the field",
            },
          ],
        },
      ],
    },
    {
      displayName: "Return All",
      name: "returnAll",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { operation: ["getAll"] },
      },
      description: "Return all items vs paginated",
    },
    {
      displayName: "Limit",
      name: "limit",
      type: "number",
      default: 100,
      typeOptions: { minValue: 1, maxValue: 100 },
      displayOptions: {
        show: { operation: ["getAll"], returnAll: [false] },
      },
      description: "Max items to return (1–100)",
    },
  ],
};

export const whatsAppTool: INodeTypeDescription = {
  name: "n8n-nodes-base.whatsAppTool",
  displayName: "WhatsApp Business Cloud",
  category: "AI Tool",
  group: ["transform"],
  version: 1,
  description: "Send messages and manage media via the WhatsApp Business Cloud API. Designed for use as an AI agent tool with $fromAI() dynamic parameter support.",
  defaults: { name: "WhatsApp Business Cloud" },
  inputs: ["main"],
  outputs: ["main", "main"],
  outputNames: ["Message", "Response"],
  icon: "MessageCircle",
  credentials: [{ name: "whatsAppApi", required: true }],
  sources: [
    "https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.whatsapp.md",
  ],
  properties: [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      default: "Message",
      noDataExpression: true,
      required: true,
      options: [
        { name: "Message", value: "Message" },
        { name: "Media", value: "Media" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "Send",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["Message"] } },
      options: [
        { name: "Send", value: "Send" },
        { name: "Send and Wait for Response", value: "Send and Wait for Response" },
        { name: "Send Template", value: "Send Template" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "Upload",
      noDataExpression: true,
      required: true,
      displayOptions: { show: { resource: ["Media"] } },
      options: [
        { name: "Upload", value: "Upload" },
        { name: "Download", value: "Download" },
        { name: "Delete", value: "Delete" },
      ],
    },
    {
      displayName: "From (Sender Phone Number ID)",
      name: "from",
      type: "string",
      default: "",
      required: true,
      description: "The WhatsApp Business Account phone number ID to send from",
    },
    {
      displayName: "To (Recipient Phone Number)",
      name: "to",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["Message"] },
      },
      description: "The recipient phone number in international format",
    },
    {
      displayName: "Message Type",
      name: "messageType",
      type: "options",
      default: "Text",
      noDataExpression: true,
      displayOptions: {
        show: { resource: ["Message"], operation: ["Send", "Send and Wait for Response"] },
      },
      options: [
        { name: "Text", value: "Text" },
        { name: "Image", value: "Image" },
        { name: "Audio", value: "Audio" },
        { name: "Document", value: "Document" },
        { name: "Video", value: "Video" },
        { name: "Sticker", value: "Sticker" },
        { name: "Location", value: "Location" },
        { name: "Contacts", value: "Contacts" },
        { name: "Interactive", value: "Interactive" },
      ],
    },
    {
      displayName: "Text",
      name: "text",
      type: "string",
      default: "",
      typeOptions: { rows: 4 },
      displayOptions: {
        show: { resource: ["Message"], "/messageType": ["Text"] },
      },
      description: "Message body text",
    },
    {
      displayName: "Template Name",
      name: "template",
      type: "string",
      default: "",
      required: true,
      displayOptions: {
        show: { resource: ["Message"], operation: ["Send Template"] },
      },
      description: "The WhatsApp message template name",
    },
    {
      displayName: "Language",
      name: "language",
      type: "string",
      default: "en_US",
      displayOptions: {
        show: { resource: ["Message"], operation: ["Send Template"] },
      },
      description: "Template language code (e.g. en_US)",
    },
    {
      displayName: "Media ID",
      name: "mediaId",
      type: "string",
      default: "",
      displayOptions: {
        show: {
          resource: ["Message", "Media"],
          operation: ["Send", "Send and Wait for Response", "Download", "Delete"],
        },
        hide: { "/operation": ["Send Template"] },
      },
      description: "ID of the uploaded media",
    },
    {
      displayName: "Media Link",
      name: "mediaLink",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["Message"], "/operation": ["Send", "Send and Wait for Response"] },
        hide: { "/messageType": ["Text", "Location", "Contacts", "Interactive"] },
      },
      description: "URL of the media to send",
    },
    {
      displayName: "Caption",
      name: "caption",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["Message"], "/operation": ["Send", "Send and Wait for Response"] },
        hide: { "/messageType": ["Text", "Audio", "Location", "Contacts", "Interactive", "Sticker"] },
      },
      description: "Media caption",
    },
    {
      displayName: "Filename",
      name: "filename",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["Message"], "/messageType": ["Document"] },
      },
      description: "Filename for document",
    },
    {
      displayName: "Longitude",
      name: "longitude",
      type: "number",
      default: 0,
      displayOptions: {
        show: { resource: ["Message"], "/messageType": ["Location"] },
      },
    },
    {
      displayName: "Latitude",
      name: "latitude",
      type: "number",
      default: 0,
      displayOptions: {
        show: { resource: ["Message"], "/messageType": ["Location"] },
      },
    },
    {
      displayName: "Location Name",
      name: "locationName",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["Message"], "/messageType": ["Location"] },
      },
    },
    {
      displayName: "Location Address",
      name: "locationAddress",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["Message"], "/messageType": ["Location"] },
      },
    },
    {
      displayName: "Preview URL",
      name: "previewUrl",
      type: "boolean",
      default: false,
      displayOptions: {
        show: { resource: ["Message"], "/messageType": ["Text"] },
      },
      description: "Enable URL link preview",
    },
    {
      displayName: "Context Message ID",
      name: "contextMessageId",
      type: "string",
      default: "",
      displayOptions: {
        show: { resource: ["Message"], operation: ["Send", "Send Template"] },
      },
      description: "The message ID to reply to (quoted reply)",
    },
    {
      displayName: "Input Data Field Name",
      name: "inputDataFieldName",
      type: "string",
      default: "data",
      displayOptions: {
        show: { resource: ["Media"], operation: ["Upload"] },
      },
      description: "Name of the binary property holding the media file",
    },
  ],
};

