import type { INodeTypeDescription } from "../types";

const CORE = "https://docs.n8n.io/integrations/builtin/core-nodes/";

export const splitOut: INodeTypeDescription = {
  name: "n8n-nodes-base.splitOut",
  displayName: "Split Out",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Splits a flat item into multiple items by unpacking an array field.",
  defaults: { name: "Split Out" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Split",
  sources: [`${CORE}n8n-nodes-base.splitout/`],
  properties: [
    {
      displayName: "Field to Split Out",
      name: "fieldToSplitOut",
      type: "string",
      default: "",
      required: true,
      placeholder: "data",
      description: "The array field whose elements become individual items.",
    },
    {
      displayName: "Include Prefix",
      name: "includePrefix",
      type: "boolean",
      default: false,
      description: "Prefix output field names with the original field path.",
    },
    {
      displayName: "Destination Prefix",
      name: "destinationPrefix",
      type: "string",
      default: "",
      displayOptions: { show: { includePrefix: [true] } },
      placeholder: "item",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Ignore Missing Fields",
          name: "ignoreMissingFields",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const aggregate: INodeTypeDescription = {
  name: "n8n-nodes-base.aggregate",
  displayName: "Aggregate",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Combines multiple items into a single item or groups by field.",
  defaults: { name: "Aggregate" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Layers",
  sources: [`${CORE}n8n-nodes-base.aggregate/`],
  properties: [
    {
      displayName: "Aggregate",
      name: "aggregate",
      type: "options",
      default: "individualFields",
      noDataExpression: true,
      options: [
        { name: "Individual Fields", value: "individualFields" },
        { name: "All Fields", value: "allFields" },
      ],
    },
    {
      displayName: "Destination Field Name",
      name: "destinationFieldName",
      type: "string",
      default: "data",
      required: true,
      description: "Name of the field that will hold the aggregated array.",
    },
    {
      displayName: "Include Fields",
      name: "includeFields",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { aggregate: ["individualFields"] } },
      options: [
        {
          name: "fields",
          displayName: "Field",
          values: [
            {
              displayName: "Field to Aggregate",
              name: "fieldToAggregate",
              type: "string",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Include Item Data",
          name: "includeItemData",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const filter: INodeTypeDescription = {
  name: "n8n-nodes-base.filter",
  displayName: "Filter",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Filters items based on a condition.",
  defaults: { name: "Filter" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Filter",
  sources: [`${CORE}n8n-nodes-base.filter/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "manual",
      noDataExpression: true,
      options: [
        { name: "Manual", value: "manual" },
        { name: "Expression", value: "expression" },
      ],
    },
    {
      displayName: "Conditions",
      name: "conditions",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { mode: ["manual"] } },
      options: [
        {
          name: "conditions",
          displayName: "Condition",
          values: [
            { displayName: "Left Value", name: "leftValue", type: "string", default: "" },
            {
              displayName: "Operator",
              name: "operator",
              type: "options",
              default: "equals",
              options: [
                { name: "Is Equal To", value: "equals" },
                { name: "Is Not Equal To", value: "notEquals" },
                { name: "Contains", value: "contains" },
                { name: "Does Not Contain", value: "notContains" },
                { name: "Starts With", value: "startsWith" },
                { name: "Ends With", value: "endsWith" },
                { name: "Is Empty", value: "isEmpty" },
                { name: "Is Not Empty", value: "isNotEmpty" },
                { name: "Larger Than", value: "gt" },
                { name: "Smaller Than", value: "lt" },
                { name: "Is True", value: "isTrue" },
                { name: "Is False", value: "isFalse" },
              ],
            },
            { displayName: "Right Value", name: "rightValue", type: "string", default: "" },
          ],
        },
      ],
    },
    {
      displayName: "Combine",
      name: "combinator",
      type: "options",
      default: "and",
      displayOptions: { show: { mode: ["manual"] } },
      options: [
        { name: "All conditions must match (AND)", value: "and" },
        { name: "Any condition may match (OR)", value: "or" },
      ],
    },
    {
      displayName: "Expression",
      name: "expression",
      type: "string",
      default: "={{ $json.field === true }}",
      displayOptions: { show: { mode: ["expression"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [{ displayName: "Ignore Case", name: "ignoreCase", type: "boolean", default: true }],
    },
  ],
};

export const limit: INodeTypeDescription = {
  name: "n8n-nodes-base.limit",
  displayName: "Limit",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Limits the number of items passing through.",
  defaults: { name: "Limit" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Minimize2",
  sources: [`${CORE}n8n-nodes-base.limit/`],
  properties: [
    {
      displayName: "Max Items",
      name: "maxItems",
      type: "number",
      default: 1,
      required: true,
      typeOptions: { minValue: 0 },
      description: "Maximum number of items to keep.",
    },
    {
      displayName: "Keep",
      name: "keep",
      type: "options",
      default: "first",
      noDataExpression: true,
      options: [
        { name: "First Items", value: "first" },
        { name: "Last Items", value: "last" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Remove Other Items",
          name: "removeOtherItems",
          type: "boolean",
          default: true,
        },
      ],
    },
  ],
};

export const executeWorkflow: INodeTypeDescription = {
  name: "n8n-nodes-base.executeWorkflow",
  displayName: "Execute Workflow",
  category: "Actions",
  group: ["transform"],
  version: 1,
  description: "Calls another workflow as a sub-workflow, passing input items through it.",
  defaults: { name: "Execute Workflow" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Workflow",
  sources: [`${CORE}n8n-nodes-base.executeworkflow/`],
  properties: [
    {
      displayName: "Workflow",
      name: "workflowId",
      type: "string",
      default: "",
      required: true,
      noDataExpression: true,
      description: "ID or name of the workflow to execute.",
    },
    {
      displayName: "Execute",
      name: "mode",
      type: "options",
      default: "once",
      noDataExpression: true,
      options: [
        { name: "Once for All Items", value: "once" },
        { name: "Once for Each Item", value: "each" },
      ],
    },
    {
      displayName: "Source",
      name: "source",
      type: "options",
      default: "parameter",
      noDataExpression: true,
      options: [
        { name: "Database", value: "parameter" },
        { name: "Parameter", value: "list" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Wait for Sub-Workflow Completion",
          name: "waitForCompletion",
          type: "boolean",
          default: true,
        },
      ],
    },
  ],
};

export const removeDuplicates: INodeTypeDescription = {
  name: "n8n-nodes-base.removeDuplicates",
  displayName: "Remove Duplicates",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Removes duplicate items by comparing one or more field values.",
  defaults: { name: "Remove Duplicates" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "CopyX",
  sources: [`${CORE}n8n-nodes-base.remove-duplicates/`],
  properties: [
    {
      displayName: "Compare",
      name: "compare",
      type: "options",
      default: "allFields",
      noDataExpression: true,
      options: [
        { name: "All Fields", value: "allFields" },
        { name: "Selected Fields", value: "selectedFields" },
      ],
      description: "Whether to compare every field or only the listed fields.",
    },
    {
      displayName: "Fields to Match",
      name: "fieldsToMatch",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { compare: ["selectedFields"] } },
      options: [
        {
          name: "fields",
          displayName: "Field",
          values: [
            {
              displayName: "Field Name",
              name: "fieldName",
              type: "string",
              default: "",
              placeholder: "id",
              description: "Name of the field to compare when detecting duplicates.",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Case Insensitive",
          name: "caseInsensitive",
          type: "boolean",
          default: false,
          description: "Ignore case when comparing string field values.",
        },
        {
          displayName: "Trim Values",
          name: "trimValues",
          type: "boolean",
          default: false,
          description: "Trim whitespace from string values before comparing.",
        },
      ],
    },
  ],
};

export const itemLists: INodeTypeDescription = {
  name: "n8n-nodes-base.itemLists",
  displayName: "Item Lists",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Splits arrays into items or aggregates items into arrays.",
  defaults: { name: "Item Lists" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "List",
  sources: [`${CORE}n8n-nodes-base.item-lists/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "splitOut",
      noDataExpression: true,
      options: [
        { name: "Split Out Items", value: "splitOut" },
        { name: "Aggregate Items", value: "aggregate" },
      ],
      description: "Whether to split an array into items or aggregate items into an array.",
    },
    {
      displayName: "Array Field Name",
      name: "arrayFieldName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["splitOut"] } },
      description: "Name of the field containing the array to split into items.",
    },
    {
      displayName: "Field Name",
      name: "fieldName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["aggregate"] } },
      description: "Name of the field that will hold the aggregated array.",
    },
    {
      displayName: "Include Prefix",
      name: "includePrefix",
      type: "boolean",
      default: false,
      displayOptions: { show: { mode: ["splitOut"] } },
      description: "Prefix output field names with the original field path.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Ignore Missing Fields",
          name: "ignoreMissingFields",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const dateTime: INodeTypeDescription = {
  name: "n8n-nodes-base.dateTime",
  displayName: "Date & Time",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Formats dates and calculates time differences.",
  defaults: { name: "Date & Time" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "CalendarClock",
  sources: [`${CORE}n8n-nodes-base.date-time/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "format",
      noDataExpression: true,
      options: [
        { name: "Format a Date", value: "format" },
        { name: "Calculate a Date", value: "calculate" },
      ],
      description: "Whether to format a date or calculate a time difference.",
    },
    {
      displayName: "Date",
      name: "date",
      type: "dateTime",
      default: "",
      displayOptions: { show: { mode: ["format"] } },
      description: "The date value to format.",
    },
    {
      displayName: "Format",
      name: "format",
      type: "string",
      default: "YYYY-MM-DD HH:mm:ss",
      displayOptions: { show: { mode: ["format"] } },
      description: "Output format using dayjs-style tokens.",
    },
    {
      displayName: "Timezone",
      name: "timezone",
      type: "string",
      default: "UTC",
      displayOptions: { show: { mode: ["format"] } },
      description: "IANA timezone used when formatting the date.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Output Format",
          name: "outputFormat",
          type: "string",
          default: "",
          placeholder: "YYYY-MM-DD",
        },
      ],
    },
  ],
};
