import type { INodeTypeDescription } from "../types";

const CORE = "https://docs.n8n.io/integrations/builtin/core-nodes/";

export const splitOut: INodeTypeDescription = {
  name: "n8n-nodes-base.splitOut",
  displayName: "Split Out",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Splits a flat item into multiple items by unpacking an array field.",
  defaults: { name: "Split Out" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Split",
  sources: [`${CORE}n8n-nodes-base.splitout/`],
  properties: [
    {
      displayName: "Field to Split Out",
      name: "fieldToSplitOut",
      type: "string",
      default: "",
      required: true,
      placeholder: "data",
      description: "The array field whose elements become individual items.",
    },
    {
      displayName: "Include Prefix",
      name: "includePrefix",
      type: "boolean",
      default: false,
      description: "Prefix output field names with the original field path.",
    },
    {
      displayName: "Destination Prefix",
      name: "destinationPrefix",
      type: "string",
      default: "",
      displayOptions: { show: { includePrefix: [true] } },
      placeholder: "item",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Ignore Missing Fields",
          name: "ignoreMissingFields",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const aggregate: INodeTypeDescription = {
  name: "n8n-nodes-base.aggregate",
  displayName: "Aggregate",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Combines multiple items into a single item or groups by field.",
  defaults: { name: "Aggregate" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Layers",
  sources: [`${CORE}n8n-nodes-base.aggregate/`],
  properties: [
    {
      displayName: "Aggregate",
      name: "aggregate",
      type: "options",
      default: "individualFields",
      noDataExpression: true,
      options: [
        { name: "Individual Fields", value: "individualFields" },
        { name: "All Fields", value: "allFields" },
      ],
    },
    {
      displayName: "Destination Field Name",
      name: "destinationFieldName",
      type: "string",
      default: "data",
      required: true,
      description: "Name of the field that will hold the aggregated array.",
    },
    {
      displayName: "Include Fields",
      name: "includeFields",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { aggregate: ["individualFields"] } },
      options: [
        {
          name: "fields",
          displayName: "Field",
          values: [
            {
              displayName: "Field to Aggregate",
              name: "fieldToAggregate",
              type: "string",
              default: "",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Include Item Data",
          name: "includeItemData",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const filter: INodeTypeDescription = {
  name: "n8n-nodes-base.filter",
  displayName: "Filter",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Filters items based on a condition.",
  defaults: { name: "Filter" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Filter",
  sources: [`${CORE}n8n-nodes-base.filter/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "manual",
      noDataExpression: true,
      options: [
        { name: "Manual", value: "manual" },
        { name: "Expression", value: "expression" },
      ],
    },
    {
      displayName: "Conditions",
      name: "conditions",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { mode: ["manual"] } },
      options: [
        {
          name: "conditions",
          displayName: "Condition",
          values: [
            { displayName: "Left Value", name: "leftValue", type: "string", default: "" },
            {
              displayName: "Operator",
              name: "operator",
              type: "options",
              default: "equals",
              options: [
                { name: "Is Equal To", value: "equals" },
                { name: "Is Not Equal To", value: "notEquals" },
                { name: "Contains", value: "contains" },
                { name: "Does Not Contain", value: "notContains" },
                { name: "Starts With", value: "startsWith" },
                { name: "Ends With", value: "endsWith" },
                { name: "Is Empty", value: "isEmpty" },
                { name: "Is Not Empty", value: "isNotEmpty" },
                { name: "Larger Than", value: "gt" },
                { name: "Smaller Than", value: "lt" },
                { name: "Is True", value: "isTrue" },
                { name: "Is False", value: "isFalse" },
              ],
            },
            { displayName: "Right Value", name: "rightValue", type: "string", default: "" },
          ],
        },
      ],
    },
    {
      displayName: "Combine",
      name: "combinator",
      type: "options",
      default: "and",
      displayOptions: { show: { mode: ["manual"] } },
      options: [
        { name: "All conditions must match (AND)", value: "and" },
        { name: "Any condition may match (OR)", value: "or" },
      ],
    },
    {
      displayName: "Expression",
      name: "expression",
      type: "string",
      default: "={{ $json.field === true }}",
      displayOptions: { show: { mode: ["expression"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [{ displayName: "Ignore Case", name: "ignoreCase", type: "boolean", default: true }],
    },
  ],
};

export const limit: INodeTypeDescription = {
  name: "n8n-nodes-base.limit",
  displayName: "Limit",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Limits the number of items passing through.",
  defaults: { name: "Limit" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Minimize2",
  sources: [`${CORE}n8n-nodes-base.limit/`],
  properties: [
    {
      displayName: "Max Items",
      name: "maxItems",
      type: "number",
      default: 1,
      required: true,
      typeOptions: { minValue: 0 },
      description: "Maximum number of items to keep.",
    },
    {
      displayName: "Keep",
      name: "keep",
      type: "options",
      default: "first",
      noDataExpression: true,
      options: [
        { name: "First Items", value: "first" },
        { name: "Last Items", value: "last" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Remove Other Items",
          name: "removeOtherItems",
          type: "boolean",
          default: true,
        },
      ],
    },
  ],
};

export const executeWorkflow: INodeTypeDescription = {
  name: "n8n-nodes-base.executeWorkflow",
  displayName: "Execute Workflow",
  category: "Actions",
  group: ["transform"],
  version: 1,
  description: "Calls another workflow as a sub-workflow, passing input items through it.",
  defaults: { name: "Execute Workflow" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Workflow",
  sources: [`${CORE}n8n-nodes-base.executeworkflow/`],
  properties: [
    {
      displayName: "Workflow",
      name: "workflowId",
      type: "workflowSelect",
      default: "",
      required: true,
      noDataExpression: true,
      description: "Select a saved workflow to run as a sub-workflow.",
    },
    {
      displayName: "Execute",
      name: "mode",
      type: "options",
      default: "once",
      noDataExpression: true,
      options: [
        { name: "Once for All Items", value: "once" },
        { name: "Once for Each Item", value: "each" },
      ],
    },
    {
      displayName: "Source",
      name: "source",
      type: "options",
      default: "database",
      noDataExpression: true,
      options: [
        { name: "Database", value: "database" },
        { name: "Parameter (JSON)", value: "parameter" },
      ],
    },
    {
      displayName: "Workflow JSON",
      name: "workflowJson",
      type: "json",
      default: "",
      displayOptions: { show: { source: ["parameter"] } },
      description: "Inline sub-workflow definition when Source is Parameter.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Wait for Sub-Workflow Completion",
          name: "waitForCompletion",
          type: "boolean",
          default: true,
        },
      ],
    },
  ],
};

export const removeDuplicates: INodeTypeDescription = {
  name: "n8n-nodes-base.removeDuplicates",
  displayName: "Remove Duplicates",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Removes duplicate items by comparing one or more field values.",
  defaults: { name: "Remove Duplicates" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "CopyX",
  sources: [`${CORE}n8n-nodes-base.remove-duplicates/`],
  properties: [
    {
      displayName: "Compare",
      name: "compare",
      type: "options",
      default: "allFields",
      noDataExpression: true,
      options: [
        { name: "All Fields", value: "allFields" },
        { name: "Selected Fields", value: "selectedFields" },
      ],
      description: "Whether to compare every field or only the listed fields.",
    },
    {
      displayName: "Fields to Match",
      name: "fieldsToMatch",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { compare: ["selectedFields"] } },
      options: [
        {
          name: "fields",
          displayName: "Field",
          values: [
            {
              displayName: "Field Name",
              name: "fieldName",
              type: "string",
              default: "",
              placeholder: "id",
              description: "Name of the field to compare when detecting duplicates.",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Case Insensitive",
          name: "caseInsensitive",
          type: "boolean",
          default: false,
          description: "Ignore case when comparing string field values.",
        },
        {
          displayName: "Trim Values",
          name: "trimValues",
          type: "boolean",
          default: false,
          description: "Trim whitespace from string values before comparing.",
        },
      ],
    },
  ],
};

export const itemLists: INodeTypeDescription = {
  name: "n8n-nodes-base.itemLists",
  displayName: "Item Lists",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Splits arrays into items or aggregates items into arrays.",
  defaults: { name: "Item Lists" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "List",
  sources: [`${CORE}n8n-nodes-base.item-lists/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "splitOut",
      noDataExpression: true,
      options: [
        { name: "Split Out Items", value: "splitOut" },
        { name: "Aggregate Items", value: "aggregate" },
      ],
      description: "Whether to split an array into items or aggregate items into an array.",
    },
    {
      displayName: "Array Field Name",
      name: "arrayFieldName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["splitOut"] } },
      description: "Name of the field containing the array to split into items.",
    },
    {
      displayName: "Field Name",
      name: "fieldName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["aggregate"] } },
      description: "Name of the field that will hold the aggregated array.",
    },
    {
      displayName: "Include Prefix",
      name: "includePrefix",
      type: "boolean",
      default: false,
      displayOptions: { show: { mode: ["splitOut"] } },
      description: "Prefix output field names with the original field path.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Ignore Missing Fields",
          name: "ignoreMissingFields",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const dateTime: INodeTypeDescription = {
  name: "n8n-nodes-base.dateTime",
  displayName: "Date & Time",
  category: "Transform",
  group: ["transform"],
  version: 2,
  description: "Formats dates and calculates time differences.",
  defaults: { name: "Date & Time" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "CalendarClock",
  sources: [`${CORE}n8n-nodes-base.datetime/`],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "formatDate",
      noDataExpression: true,
      options: [
        { name: "Format a Date", value: "formatDate" },
        { name: "Get Current Date", value: "getCurrentDate" },
        { name: "Add to a Date", value: "addToDate" },
        { name: "Subtract From a Date", value: "subtractFromDate" },
        { name: "Extract Part of a Date", value: "extractDate" },
        { name: "Get Time Between Dates", value: "getTimeBetweenDates" },
      ],
    },
    {
      displayName: "Date",
      name: "date",
      type: "string",
      default: "",
      displayOptions: {
        show: { operation: ["formatDate", "addToDate", "subtractFromDate", "extractDate"] },
      },
    },
    {
      displayName: "Format",
      name: "format",
      type: "string",
      default: "YYYY-MM-DD HH:mm:ss",
      displayOptions: { show: { operation: ["formatDate"] } },
    },
    {
      displayName: "Duration",
      name: "duration",
      type: "number",
      default: 1,
      displayOptions: { show: { operation: ["addToDate", "subtractFromDate"] } },
    },
    {
      displayName: "Time Unit",
      name: "timeUnit",
      type: "options",
      default: "days",
      displayOptions: { show: { operation: ["addToDate", "subtractFromDate"] } },
      options: [
        { name: "Days", value: "days" },
        { name: "Hours", value: "hours" },
        { name: "Minutes", value: "minutes" },
        { name: "Seconds", value: "seconds" },
        { name: "Months", value: "months" },
        { name: "Years", value: "years" },
      ],
    },
    {
      displayName: "Part",
      name: "part",
      type: "options",
      default: "day",
      displayOptions: { show: { operation: ["extractDate"] } },
      options: [
        { name: "Year", value: "year" },
        { name: "Month", value: "month" },
        { name: "Day", value: "day" },
        { name: "Hour", value: "hour" },
        { name: "Minute", value: "minute" },
        { name: "Second", value: "second" },
      ],
    },
    {
      displayName: "Start Date",
      name: "startDate",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["getTimeBetweenDates"] } },
    },
    {
      displayName: "End Date",
      name: "endDate",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["getTimeBetweenDates"] } },
    },
    {
      displayName: "Unit",
      name: "unit",
      type: "options",
      default: "days",
      displayOptions: { show: { operation: ["getTimeBetweenDates"] } },
      options: [
        { name: "Days", value: "days" },
        { name: "Hours", value: "hours" },
        { name: "Minutes", value: "minutes" },
        { name: "Seconds", value: "seconds" },
      ],
    },
    {
      displayName: "Include Current Time",
      name: "includeCurrentTime",
      type: "boolean",
      default: true,
      displayOptions: { show: { operation: ["getCurrentDate"] } },
    },
    {
      displayName: "Output Field Name",
      name: "outputFieldName",
      type: "string",
      default: "result",
    },
  ],
};

export const sort: INodeTypeDescription = {
  name: "n8n-nodes-base.sort",
  displayName: "Sort",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Sorts items by field values or randomly.",
  defaults: { name: "Sort" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "ArrowUpDown",
  sources: [`${CORE}n8n-nodes-base.sort/`],
  properties: [
    {
      displayName: "Type",
      name: "type",
      type: "options",
      default: "simple",
      noDataExpression: true,
      options: [
        { name: "Simple", value: "simple" },
        { name: "Random", value: "random" },
      ],
    },
    {
      displayName: "Field Name",
      name: "fieldName",
      type: "string",
      default: "",
      displayOptions: { show: { type: ["simple"] } },
    },
    {
      displayName: "Order",
      name: "order",
      type: "options",
      default: "ascending",
      displayOptions: { show: { type: ["simple"] } },
      options: [
        { name: "Ascending", value: "ascending" },
        { name: "Descending", value: "descending" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Disable Dot Notation",
          name: "disableDotNotation",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const renameKeys: INodeTypeDescription = {
  name: "n8n-nodes-base.renameKeys",
  displayName: "Rename Keys",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Renames keys on each item.",
  defaults: { name: "Rename Keys" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "WholeWord",
  sources: [`${CORE}n8n-nodes-base.renamekeys/`],
  properties: [
    {
      displayName: "Keys",
      name: "keys",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      options: [
        {
          name: "keys",
          displayName: "Key",
          values: [
            { displayName: "Current Key Name", name: "currentKey", type: "string", default: "" },
            { displayName: "New Key Name", name: "newKey", type: "string", default: "" },
          ],
        },
      ],
    },
    {
      displayName: "Current Key Name",
      name: "currentKey",
      type: "string",
      default: "",
    },
    {
      displayName: "New Key Name",
      name: "newKey",
      type: "string",
      default: "",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        { displayName: "Use Regex", name: "regex", type: "boolean", default: false },
        { displayName: "Regular Expression", name: "regularExpression", type: "string", default: "" },
        { displayName: "Replace With", name: "replaceWith", type: "string", default: "" },
        { displayName: "Case Insensitive", name: "caseInsensitive", type: "boolean", default: false },
        { displayName: "Max Depth", name: "maxDepth", type: "number", default: -1 },
      ],
    },
  ],
};
