import type { INodeTypeDescription } from "../types";

const CORE = "https://docs.n8n.io/integrations/builtin/core-nodes/";

export const splitOut: INodeTypeDescription = {
  name: "n8n-nodes-base.splitOut",
  displayName: "Split Out",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Splits a list field inside each input item into separate items.",
  defaults: { name: "Split Out" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Split",
  sources: [`${CORE}n8n-nodes-base.splitout/`],
  properties: [
    {
      displayName: "Field(s) to Split Out",
      name: "fieldToSplitOut",
      type: "string",
      default: "",
      required: true,
      placeholder: "data",
      description: "Name of the field holding the list. Comma-separated for multiple fields.",
    },
    {
      displayName: "Include",
      name: "include",
      type: "options",
      default: "noOtherFields",
      noDataExpression: true,
      options: [
        { name: "No Other Fields", value: "noOtherFields" },
        { name: "All Other Fields", value: "allOtherFields" },
        { name: "Selected Other Fields", value: "selectedOtherFields" },
      ],
      description: "Whether/how to copy other input fields onto each new item.",
    },
    {
      displayName: "Fields to Include",
      name: "fieldsToInclude",
      type: "string",
      default: "",
      displayOptions: { show: { include: ["selectedOtherFields"] } },
      description: "Comma-separated field names to keep.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Disable Dot Notation",
          name: "disableDotNotation",
          type: "boolean",
          default: false,
          description: "When on, treat field paths literally (no parent.child resolution).",
        },
        {
          displayName: "Destination Field Name",
          name: "destinationFieldName",
          type: "string",
          default: "",
          description: "Output field under which to place each split element.",
        },
        {
          displayName: "Include Binary",
          name: "includeBinary",
          type: "boolean",
          default: false,
          description: "When on, copy input item binary onto each output item.",
        },
      ],
    },
  ],
};

export const aggregate: INodeTypeDescription = {
  name: "n8n-nodes-base.aggregate",
  displayName: "Aggregate",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Combines multiple items into a single item with array/list fields.",
  defaults: { name: "Aggregate" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Layers",
  sources: [`${CORE}n8n-nodes-base.aggregate/`],
  properties: [
    {
      displayName: "Aggregate",
      name: "aggregate",
      type: "options",
      default: "aggregateIndividualFields",
      noDataExpression: true,
      options: [
        { name: "Individual Fields", value: "aggregateIndividualFields" },
        { name: "All Item Data", value: "aggregateAllItemData" },
      ],
      description:
        "Whether to aggregate individual fields into arrays or all item data into a list.",
    },
    {
      displayName: "Fields to Aggregate",
      name: "fieldsToAggregate",
      type: "fixedCollection",
      default: { fieldToAggregate: [{ fieldToAggregate: "", renameField: false }] },
      typeOptions: { multipleValues: true },
      displayOptions: { show: { aggregate: ["aggregateIndividualFields"] } },
      options: [
        {
          name: "fieldToAggregate",
          displayName: "Field",
          values: [
            {
              displayName: "Input Field Name",
              name: "fieldToAggregate",
              type: "string",
              default: "",
              required: true,
              placeholder: "id",
              description: "Input field name (or dot path) to collect across items.",
            },
            {
              displayName: "Rename Field",
              name: "renameField",
              type: "boolean",
              default: false,
              description: "When true, use a different output key.",
            },
            {
              displayName: "Output Field Name",
              name: "outputFieldName",
              type: "string",
              default: "",
              displayOptions: { show: { renameField: [true] } },
              description:
                "Output array field name. Must be distinct when renaming multiple fields.",
            },
          ],
        },
      ],
    },
    {
      displayName: "Put Output in Field",
      name: "destinationFieldName",
      type: "string",
      default: "data",
      displayOptions: { show: { aggregate: ["aggregateAllItemData"] } },
      description: "Field that receives the list of item objects.",
    },
    {
      displayName: "Include",
      name: "include",
      type: "options",
      default: "allFields",
      noDataExpression: true,
      displayOptions: { show: { aggregate: ["aggregateAllItemData"] } },
      options: [
        { name: "All Fields", value: "allFields" },
        { name: "Specified Fields", value: "specifiedFields" },
        { name: "All Fields Except", value: "allFieldsExcept" },
      ],
      description: "Which fields from each item's json to keep in the packed objects.",
    },
    {
      displayName: "Fields to Include",
      name: "fieldsToInclude",
      type: "string",
      default: "",
      displayOptions: {
        show: { aggregate: ["aggregateAllItemData"], include: ["specifiedFields"] },
      },
      description: "Comma-separated field names to keep.",
    },
    {
      displayName: "Fields to Exclude",
      name: "fieldsToExclude",
      type: "string",
      default: "",
      displayOptions: {
        show: { aggregate: ["aggregateAllItemData"], include: ["allFieldsExcept"] },
      },
      description: "Comma-separated field names to drop.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Disable Dot Notation",
          name: "disableDotNotation",
          type: "boolean",
          default: false,
          displayOptions: { show: { aggregate: ["aggregateIndividualFields"] } },
          description: "When on, treat field names literally (no parent.child resolution).",
        },
        {
          displayName: "Merge Lists",
          name: "mergeLists",
          type: "boolean",
          default: false,
          displayOptions: { show: { aggregate: ["aggregateIndividualFields"] } },
          description:
            "When the collected value is a list, flatten into one list instead of a list-of-lists.",
        },
        {
          displayName: "Include Binaries",
          name: "includeBinaries",
          type: "boolean",
          default: false,
          description: "Carry binary data from inputs onto the single output item.",
        },
        {
          displayName: "Keep Only Unique",
          name: "keepOnlyUnique",
          type: "boolean",
          default: false,
          description:
            "When including binaries, keep only unique binaries (mime, file type, size, extension).",
        },
        {
          displayName: "Keep Missing and Null Values",
          name: "keepMissing",
          type: "boolean",
          default: false,
          displayOptions: { show: { aggregate: ["aggregateIndividualFields"] } },
          description: "Push null for missing/null input values; otherwise skip them.",
        },
      ],
    },
  ],
};

export const summarize: INodeTypeDescription = {
  name: "n8n-nodes-base.summarize",
  displayName: "Summarize",
  category: "Transform",
  group: ["transform"],
  version: 1.1,
  description: "Sum, count, max, etc. across items.",
  defaults: { name: "Summarize" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Sigma",
  sources: [`${CORE}n8n-nodes-base.summarize/`],
  properties: [
    {
      displayName: "Fields to Summarize",
      name: "fieldsToSummarize",
      type: "fixedCollection",
      default: { values: [{ aggregation: "count", field: "" }] },
      typeOptions: { multipleValues: true },
      options: [
        {
          name: "values",
          displayName: "",
          values: [
            {
              displayName: "Aggregation",
              name: "aggregation",
              type: "options",
              default: "count",
              noDataExpression: true,
              options: [
                { name: "Append", value: "append" },
                { name: "Average", value: "average" },
                { name: "Concatenate", value: "concatenate" },
                { name: "Count", value: "count" },
                { name: "Count Unique", value: "countUnique" },
                { name: "Max", value: "max" },
                { name: "Min", value: "min" },
                { name: "Sum", value: "sum" },
              ],
              description: "How to combine the values of the field you want to summarize.",
            },
            {
              displayName: "Field",
              name: "field",
              type: "string",
              default: "",
              placeholder: "e.g. cost",
              description: "The name of an input field that you want to summarize.",
              displayOptions: {
                hide: {
                  aggregation: ["average", "sum", "countUnique", "count", "max", "min"],
                },
              },
            },
            {
              displayName: "Field",
              name: "field",
              type: "string",
              default: "",
              placeholder: "e.g. cost",
              description:
                "The name of an input field that you want to summarize. The field should contain numerical values; null, undefined, empty strings would be ignored.",
              displayOptions: { show: { aggregation: ["average", "sum"] } },
            },
            {
              displayName: "Field",
              name: "field",
              type: "string",
              default: "",
              placeholder: "e.g. cost",
              description:
                "The name of an input field that you want to summarize; null, undefined, empty strings would be ignored.",
              displayOptions: { show: { aggregation: ["countUnique", "count", "max", "min"] } },
            },
            {
              displayName: "Include Empty Values",
              name: "includeEmpty",
              type: "boolean",
              default: false,
              displayOptions: {
                show: { aggregation: ["append", "concatenate", "count", "countUnique"] },
              },
            },
            {
              displayName: "Separator",
              name: "separateBy",
              type: "options",
              default: ",",
              options: [
                { name: "Comma", value: "," },
                { name: "Comma and Space", value: ", " },
                { name: "New Line", value: "\n" },
                { name: "None", value: "" },
                { name: "Space", value: " " },
                { name: "Other", value: "other" },
              ],
              displayOptions: { show: { aggregation: ["concatenate"] } },
            },
            {
              displayName: "Custom Separator",
              name: "customSeparator",
              type: "string",
              default: "",
              displayOptions: { show: { aggregation: ["concatenate"], separateBy: ["other"] } },
            },
          ],
        },
      ],
    },
    {
      displayName: "Fields to Split By",
      name: "fieldsToSplitBy",
      type: "string",
      default: "",
      placeholder: "e.g. country, city",
      description: "The name of the input fields that you want to split the summary by.",
      displayOptions: { hide: { "/options.outputFormat": ["singleItem"] } },
    },
    {
      displayName: "Fields to Group By",
      name: "fieldsToSplitBy",
      type: "string",
      default: "",
      placeholder: "e.g. country, city",
      description: "The name of the input fields that you want to split the summary by.",
      displayOptions: { show: { "/options.outputFormat": ["singleItem"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Continue if Field Not Found",
          name: "continueIfFieldNotFound",
          type: "boolean",
          default: false,
          description:
            "Whether to continue if field to summarize can't be found in any items and return single empty item, otherwise an error would be thrown.",
        },
        {
          displayName: "Disable Dot Notation",
          name: "disableDotNotation",
          type: "boolean",
          default: false,
          description:
            "Whether to disallow referencing child fields using `parent.child` in the field name.",
        },
        {
          displayName: "Output Format",
          name: "outputFormat",
          type: "options",
          default: "separateItems",
          noDataExpression: true,
          options: [
            { name: "Each Split in a Separate Item", value: "separateItems" },
            { name: "All Splits in a Single Item", value: "singleItem" },
          ],
        },
        {
          displayName: "Ignore items without valid fields to group by",
          name: "skipEmptySplitFields",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const filter: INodeTypeDescription = {
  name: "n8n-nodes-base.filter",
  displayName: "Filter",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Filters items based on a condition.",
  defaults: { name: "Filter" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Filter",
  sources: [`${CORE}n8n-nodes-base.filter/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "manual",
      noDataExpression: true,
      options: [
        { name: "Manual", value: "manual" },
        { name: "Expression", value: "expression" },
      ],
    },
    {
      displayName: "Conditions",
      name: "conditions",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { mode: ["manual"] } },
      options: [
        {
          name: "conditions",
          displayName: "Condition",
          values: [
            { displayName: "Left Value", name: "leftValue", type: "string", default: "" },
            {
              displayName: "Operator",
              name: "operator",
              type: "options",
              default: "equals",
              options: [
                { name: "Is Equal To", value: "equals" },
                { name: "Is Not Equal To", value: "notEquals" },
                { name: "Contains", value: "contains" },
                { name: "Does Not Contain", value: "notContains" },
                { name: "Starts With", value: "startsWith" },
                { name: "Ends With", value: "endsWith" },
                { name: "Is Empty", value: "isEmpty" },
                { name: "Is Not Empty", value: "isNotEmpty" },
                { name: "Larger Than", value: "gt" },
                { name: "Smaller Than", value: "lt" },
                { name: "Is True", value: "isTrue" },
                { name: "Is False", value: "isFalse" },
              ],
            },
            { displayName: "Right Value", name: "rightValue", type: "string", default: "" },
          ],
        },
      ],
    },
    {
      displayName: "Combine",
      name: "combinator",
      type: "options",
      default: "and",
      displayOptions: { show: { mode: ["manual"] } },
      options: [
        { name: "All conditions must match (AND)", value: "and" },
        { name: "Any condition may match (OR)", value: "or" },
      ],
    },
    {
      displayName: "Expression",
      name: "expression",
      type: "string",
      default: "={{ $json.field === true }}",
      displayOptions: { show: { mode: ["expression"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [{ displayName: "Ignore Case", name: "ignoreCase", type: "boolean", default: true }],
    },
  ],
};

export const limit: INodeTypeDescription = {
  name: "n8n-nodes-base.limit",
  displayName: "Limit",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Limits the number of items passing through.",
  defaults: { name: "Limit" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Minimize2",
  sources: [`${CORE}n8n-nodes-base.limit/`],
  properties: [
    {
      displayName: "Max Items",
      name: "maxItems",
      type: "number",
      default: 1,
      required: true,
      typeOptions: { minValue: 0 },
      description: "Maximum number of items to keep.",
    },
    {
      displayName: "Keep",
      name: "keep",
      type: "options",
      default: "firstItems",
      noDataExpression: true,
      options: [
        { name: "First Items", value: "firstItems" },
        { name: "Last Items", value: "lastItems" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Remove Other Items",
          name: "removeOtherItems",
          type: "boolean",
          default: true,
        },
      ],
    },
  ],
};

export const executeWorkflow: INodeTypeDescription = {
  name: "n8n-nodes-base.executeWorkflow",
  displayName: "Execute Workflow",
  category: "Actions",
  group: ["transform"],
  version: 1.2,
  defaultVersion: 1.2,
  description: "Calls another workflow as a sub-workflow, passing input items through it.",
  defaults: { name: "Execute Workflow" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Workflow",
  sources: [`${CORE}n8n-nodes-base.executeworkflow/`],
  properties: [
    {
      displayName: "Workflow",
      name: "workflowId",
      type: "workflowSelect",
      default: "",
      required: true,
      noDataExpression: true,
      displayOptions: { show: { source: ["database"] } },
      description: "Select a saved workflow to run as a sub-workflow.",
    },
    {
      displayName: "Execute",
      name: "mode",
      type: "options",
      default: "once",
      noDataExpression: true,
      options: [
        { name: "Once for All Items", value: "once" },
        { name: "Once for Each Item", value: "each" },
      ],
    },
    {
      displayName: "Source",
      name: "source",
      type: "options",
      default: "database",
      noDataExpression: true,
      options: [
        { name: "Database", value: "database" },
        { name: "Define Below", value: "parameter" },
      ],
    },
    {
      displayName: "Workflow JSON",
      name: "workflowJson",
      type: "json",
      default: "",
      displayOptions: { show: { source: ["parameter"] } },
      description: "Inline sub-workflow definition when Source is Define Below.",
    },
    {
      displayName: "Workflow Inputs",
      name: "workflowInputs",
      type: "resourceMapper",
      default: { mappingMode: "defineBelow", value: null },
      noDataExpression: true,
      displayOptions: { show: { source: ["database"], workflowId: [""] }, hide: { workflowId: [""] } },
      description:
        "Map parent data into the child workflow's declared input schema. Unmapped child inputs become null.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Wait for Sub-Workflow Completion",
          name: "waitForSubWorkflow",
          type: "boolean",
          default: true,
          description:
            "When on, the parent waits for child terminal items before continuing. When off, the parent continues without waiting.",
        },
      ],
    },
  ],
};

export const removeDuplicates: INodeTypeDescription = {
  name: "n8n-nodes-base.removeDuplicates",
  displayName: "Remove Duplicates",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Removes duplicate items by comparing one or more field values.",
  defaults: { name: "Remove Duplicates" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "CopyX",
  sources: [`${CORE}n8n-nodes-base.remove-duplicates/`],
  properties: [
    {
      displayName: "Compare",
      name: "compare",
      type: "options",
      default: "allFields",
      noDataExpression: true,
      options: [
        { name: "All Fields", value: "allFields" },
        { name: "Selected Fields", value: "selectedFields" },
      ],
      description: "Whether to compare every field or only the listed fields.",
    },
    {
      displayName: "Fields to Match",
      name: "fieldsToMatch",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { compare: ["selectedFields"] } },
      options: [
        {
          name: "fields",
          displayName: "Field",
          values: [
            {
              displayName: "Field Name",
              name: "fieldName",
              type: "string",
              default: "",
              placeholder: "id",
              description: "Name of the field to compare when detecting duplicates.",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Case Insensitive",
          name: "caseInsensitive",
          type: "boolean",
          default: false,
          description: "Ignore case when comparing string field values.",
        },
        {
          displayName: "Trim Values",
          name: "trimValues",
          type: "boolean",
          default: false,
          description: "Trim whitespace from string values before comparing.",
        },
      ],
    },
  ],
};

export const itemLists: INodeTypeDescription = {
  name: "n8n-nodes-base.itemLists",
  displayName: "Item Lists",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Splits arrays into items or aggregates items into arrays.",
  defaults: { name: "Item Lists" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "List",
  sources: [`${CORE}n8n-nodes-base.item-lists/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "splitOut",
      noDataExpression: true,
      options: [
        { name: "Split Out Items", value: "splitOut" },
        { name: "Aggregate Items", value: "aggregate" },
      ],
      description: "Whether to split an array into items or aggregate items into an array.",
    },
    {
      displayName: "Array Field Name",
      name: "arrayFieldName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["splitOut"] } },
      description: "Name of the field containing the array to split into items.",
    },
    {
      displayName: "Field Name",
      name: "fieldName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["aggregate"] } },
      description: "Name of the field that will hold the aggregated array.",
    },
    {
      displayName: "Include Prefix",
      name: "includePrefix",
      type: "boolean",
      default: false,
      displayOptions: { show: { mode: ["splitOut"] } },
      description: "Prefix output field names with the original field path.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Ignore Missing Fields",
          name: "ignoreMissingFields",
          type: "boolean",
          default: false,
        },
      ],
    },
  ],
};

export const dateTime: INodeTypeDescription = {
  name: "n8n-nodes-base.dateTime",
  displayName: "Date & Time",
  category: "Transform",
  group: ["transform"],
  version: 2,
  description: "Formats dates and calculates time differences.",
  defaults: { name: "Date & Time" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "CalendarClock",
  sources: [`${CORE}n8n-nodes-base.datetime/`],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "formatDate",
      noDataExpression: true,
      options: [
        { name: "Format a Date", value: "formatDate" },
        { name: "Get Current Date", value: "getCurrentDate" },
        { name: "Add to a Date", value: "addToDate" },
        { name: "Subtract From a Date", value: "subtractFromDate" },
        { name: "Extract Part of a Date", value: "extractDate" },
        { name: "Get Time Between Dates", value: "getTimeBetweenDates" },
        { name: "Round a Date", value: "roundDate" },
      ],
    },
    {
      displayName: "Date",
      name: "date",
      type: "string",
      default: "",
      displayOptions: {
        show: { operation: ["formatDate", "extractDate", "roundDate"] },
      },
    },
    {
      displayName: "Date to Add To",
      name: "magnitude",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["addToDate", "subtractFromDate"] } },
    },
    {
      displayName: "Duration",
      name: "duration",
      type: "number",
      default: 0,
      displayOptions: { show: { operation: ["addToDate", "subtractFromDate"] } },
    },
    {
      displayName: "Time Unit",
      name: "timeUnit",
      type: "options",
      default: "days",
      displayOptions: { show: { operation: ["addToDate", "subtractFromDate"] } },
      options: [
        { name: "Years", value: "years" },
        { name: "Quarters", value: "quarters" },
        { name: "Months", value: "months" },
        { name: "Weeks", value: "weeks" },
        { name: "Days", value: "days" },
        { name: "Hours", value: "hours" },
        { name: "Minutes", value: "minutes" },
        { name: "Seconds", value: "seconds" },
        { name: "Milliseconds", value: "milliseconds" },
      ],
    },
    {
      displayName: "Format",
      name: "format",
      type: "options",
      default: "MM/dd/yyyy",
      noDataExpression: true,
      displayOptions: { show: { operation: ["formatDate"] } },
      options: [
        { name: "Custom", value: "custom" },
        { name: "MM/dd/yyyy", value: "MM/dd/yyyy" },
        { name: "yyyy/MM/dd", value: "yyyy/MM/dd" },
        { name: "MMMM dd yyyy", value: "MMMM dd yyyy" },
        { name: "MM-dd-yyyy", value: "MM-dd-yyyy" },
        { name: "yyyy-MM-dd", value: "yyyy-MM-dd" },
        { name: "Unix Timestamp (seconds)", value: "X" },
        { name: "Unix Timestamp (ms)", value: "x" },
      ],
    },
    {
      displayName: "Custom Format",
      name: "customFormat",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["formatDate"], format: ["custom"] } },
    },
    {
      displayName: "Part",
      name: "part",
      type: "options",
      default: "month",
      displayOptions: { show: { operation: ["extractDate"] } },
      options: [
        { name: "Year", value: "year" },
        { name: "Month", value: "month" },
        { name: "Week", value: "week" },
        { name: "Day", value: "day" },
        { name: "Hour", value: "hour" },
        { name: "Minute", value: "minute" },
        { name: "Second", value: "second" },
      ],
    },
    {
      displayName: "Start Date",
      name: "startDate",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["getTimeBetweenDates"] } },
    },
    {
      displayName: "End Date",
      name: "endDate",
      type: "string",
      default: "",
      displayOptions: { show: { operation: ["getTimeBetweenDates"] } },
    },
    {
      displayName: "Units",
      name: "units",
      type: "multiOptions",
      default: ["day"],
      displayOptions: { show: { operation: ["getTimeBetweenDates"] } },
      options: [
        { name: "Year", value: "year" },
        { name: "Month", value: "month" },
        { name: "Week", value: "week" },
        { name: "Day", value: "day" },
        { name: "Hour", value: "hour" },
        { name: "Minute", value: "minute" },
        { name: "Second", value: "second" },
        { name: "Millisecond", value: "millisecond" },
      ],
    },
    {
      displayName: "Include Time",
      name: "includeTime",
      type: "boolean",
      default: true,
      displayOptions: { show: { operation: ["getCurrentDate"] } },
    },
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "roundDown",
      noDataExpression: true,
      displayOptions: { show: { operation: ["roundDate"] } },
      options: [
        { name: "Round Down", value: "roundDown" },
        { name: "Round Up", value: "roundUp" },
      ],
    },
    {
      displayName: "To Nearest",
      name: "toNearest",
      type: "options",
      default: "month",
      displayOptions: { show: { operation: ["roundDate"], mode: ["roundDown"] } },
      options: [
        { name: "Year", value: "year" },
        { name: "Month", value: "month" },
        { name: "Week", value: "week" },
        { name: "Day", value: "day" },
        { name: "Hour", value: "hour" },
        { name: "Minute", value: "minute" },
        { name: "Second", value: "second" },
      ],
    },
    {
      displayName: "To",
      name: "to",
      type: "options",
      default: "month",
      displayOptions: { show: { operation: ["roundDate"], mode: ["roundUp"] } },
      options: [{ name: "End of Month", value: "month" }],
    },
    {
      displayName: "Output Field Name",
      name: "outputFieldName",
      type: "string",
      default: "",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Include Input Fields",
          name: "includeInputFields",
          type: "boolean",
          default: false,
          description:
            "Whether to preserve all input fields in the output (true) or emit only the output field (false).",
        },
        {
          displayName: "Input Format",
          name: "fromFormat",
          type: "string",
          default: "",
          description: "Luxon format of the input date when auto-detect fails.",
        },
        {
          displayName: "Use Workflow Timezone",
          name: "timezone",
          type: "boolean",
          default: false,
          displayOptions: { show: { operation: ["formatDate"] } },
          description:
            "Format using the workflow timezone (true) or the input's own offset (false).",
        },
        {
          displayName: "Timezone",
          name: "timezone",
          type: "string",
          default: "",
          displayOptions: { show: { operation: ["getCurrentDate"] } },
          description: "Override timezone; blank uses the instance timezone. Use `GMT` for +00:00.",
        },
        {
          displayName: "ISO Duration String",
          name: "isoString",
          type: "boolean",
          default: false,
          displayOptions: { show: { operation: ["getTimeBetweenDates"] } },
          description: "Emit a single ISO 8601 duration string instead of a per-unit object.",
        },
      ],
    },
  ],
};

export const sort: INodeTypeDescription = {
  name: "n8n-nodes-base.sort",
  displayName: "Sort",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Sorts items by field values, randomly, or via a custom code comparator.",
  defaults: { name: "Sort" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "ArrowUpDown",
  sources: [`${CORE}n8n-nodes-base.sort/`],
  properties: [
    {
      displayName: "Type",
      name: "type",
      type: "options",
      default: "simple",
      noDataExpression: true,
      options: [
        { name: "Simple", value: "simple" },
        { name: "Random", value: "random" },
        { name: "Code", value: "code" },
      ],
      description: "Whether to sort by field, shuffle randomly, or use a custom code comparator.",
    },
    {
      displayName: "Fields to Sort By",
      name: "fieldToSortBy",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      displayOptions: { show: { type: ["simple"] } },
      options: [
        {
          name: "fieldToSortBy",
          displayName: "Field",
          values: [
            {
              displayName: "Field Name",
              name: "fieldName",
              type: "string",
              default: "",
              required: true,
              placeholder: "id",
              description: "Field path to sort by. Supports dot notation unless disabled.",
            },
            {
              displayName: "Order",
              name: "order",
              type: "options",
              default: "ascending",
              noDataExpression: true,
              options: [
                { name: "Ascending", value: "ascending" },
                { name: "Descending", value: "descending" },
              ],
            },
          ],
        },
      ],
    },
    {
      displayName: "Disable Dot Notation",
      name: "disableDotNotation",
      type: "boolean",
      default: false,
      displayOptions: { show: { type: ["simple"] } },
      description: "When on, treat field names literally (no parent.child resolution).",
    },
    {
      displayName: "Code",
      name: "code",
      type: "string",
      default: "",
      displayOptions: { show: { type: ["code"] } },
      description:
        "Custom JavaScript comparator body. Receives items as `a` and `b`; return negative/zero/positive.",
    },
  ],
};

export const convertToFile: INodeTypeDescription = {
  name: "n8n-nodes-base.convertToFile",
  displayName: "Convert to File",
  category: "Transform",
  group: ["transform"],
  version: 1.1,
  description: "Convert JSON data to binary data (CSV, HTML, ICS, JSON, RTF, text, XLSX, etc.).",
  defaults: { name: "Convert to File" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileOutput",
  sources: [`${CORE}n8n-nodes-base.converttofile/`],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      default: "csv",
      options: [
        {
          name: "Convert to CSV",
          value: "csv",
          action: "Convert to CSV",
          description: "Transform input data into a CSV file",
        },
        {
          name: "Convert to HTML",
          value: "html",
          action: "Convert to HTML",
          description: "Transform input data into a table in an HTML file",
        },
        {
          name: "Convert to ICS",
          value: "iCal",
          action: "Convert to ICS",
          description: "Converts each input item to an ICS event file",
        },
        {
          name: "Convert to JSON",
          value: "toJson",
          action: "Convert to JSON",
          description: "Transform input data into a single or multiple JSON files",
        },
        {
          name: "Convert to ODS",
          value: "ods",
          action: "Convert to ODS",
          description: "Transform input data into an ODS file",
        },
        {
          name: "Convert to RTF",
          value: "rtf",
          action: "Convert to RTF",
          description: "Transform input data into a table in an RTF file",
        },
        {
          name: "Convert to Text File",
          value: "toText",
          action: "Convert to text file",
          description: "Transform input data string into a file",
        },
        {
          name: "Convert to XLS",
          value: "xls",
          action: "Convert to XLS",
          description: "Transform input data into an Excel file",
        },
        {
          name: "Convert to XLSX",
          value: "xlsx",
          action: "Convert to XLSX",
          description: "Transform input data into an Excel file",
        },
        {
          name: "Move Base64 String to File",
          value: "toBinary",
          action: "Move base64 string to file",
          description: "Convert a base64-encoded string into its original file format",
        },
      ],
    },
    {
      displayName: "Put Output File in Field",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      required: true,
      placeholder: "e.g data",
      description: "The name of the output binary field that receives the generated file.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "File Name",
          name: "fileName",
          type: "string",
          default: "",
          description: "Output file name (without extension).",
        },
        {
          displayName: "Header Row",
          name: "headerRow",
          type: "boolean",
          default: true,
          description: "Whether to include a header row.",
        },
        {
          displayName: "Delimiter",
          name: "delimiter",
          type: "string",
          default: ",",
          description: "CSV column delimiter.",
        },
        {
          displayName: "Include Empty Cells",
          name: "includeEmptyCells",
          type: "boolean",
          default: false,
          description: "Include empty cells as empty strings.",
        },
        {
          displayName: "Raw Data",
          name: "rawData",
          type: "boolean",
          default: false,
          description: "Write raw data without type coercion (XLSX).",
        },
        {
          displayName: "Field Name",
          name: "fieldName",
          type: "string",
          default: "data",
          description: "Input field containing the text/base64 value (toText, toBinary).",
        },
        {
          displayName: "MIME Type",
          name: "mimeType",
          type: "string",
          default: "",
          description: "Override MIME type for decoded binary (toBinary).",
        },
        {
          displayName: "File Extension",
          name: "fileExtension",
          type: "string",
          default: "",
          description: "Override file extension for decoded binary (toBinary).",
        },
        {
          displayName: "Multiple Files",
          name: "multipleFiles",
          type: "boolean",
          default: false,
          description: "Produce one JSON file per item (toJson).",
        },
        {
          displayName: "Event Title",
          name: "eventTitle",
          type: "string",
          default: "",
          description: "Field name or literal for event title (iCal).",
        },
        {
          displayName: "Event Description",
          name: "eventDescription",
          type: "string",
          default: "",
          description: "Field name or literal for event description (iCal).",
        },
        {
          displayName: "Event Location",
          name: "eventLocation",
          type: "string",
          default: "",
          description: "Field name or literal for event location (iCal).",
        },
        {
          displayName: "Event Start",
          name: "eventStart",
          type: "string",
          default: "",
          description: "Field name or literal for event start date (iCal).",
        },
        {
          displayName: "Event End",
          name: "eventEnd",
          type: "string",
          default: "",
          description: "Field name or literal for event end date (iCal).",
        },
      ],
    },
  ],
};

export const extractFromFile: INodeTypeDescription = {
  name: "n8n-nodes-base.extractFromFile",
  displayName: "Extract from File",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description:
    "Extracts data from a binary file (CSV, HTML, ICS, JSON, RTF, text, XLSX, etc.) into JSON items.",
  defaults: { name: "Extract from File" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileInput",
  sources: [`${CORE}n8n-nodes-base.extractfromfile/`],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      default: "csv",
      options: [
        {
          name: "CSV to JSON",
          value: "csv",
          action: "CSV to JSON",
          description: "Extract data from a CSV file",
        },
        {
          name: "HTML to JSON",
          value: "html",
          action: "HTML to JSON",
          description: "Extract data from an HTML table",
        },
        {
          name: "ICS to JSON",
          value: "iCal",
          action: "ICS to JSON",
          description: "Extract events from an ICS file",
        },
        {
          name: "JSON to JSON",
          value: "toJson",
          action: "JSON to JSON",
          description: "Extract data from a JSON file",
        },
        {
          name: "ODS to JSON",
          value: "ods",
          action: "ODS to JSON",
          description: "Extract data from an ODS file",
        },
        {
          name: "RTF to JSON",
          value: "rtf",
          action: "RTF to JSON",
          description: "Extract data from an RTF file",
        },
        {
          name: "Text File to JSON",
          value: "toText",
          action: "Text file to JSON",
          description: "Extract text from a text file",
        },
        {
          name: "XLS to JSON",
          value: "xls",
          action: "XLS to JSON",
          description: "Extract data from an XLS file",
        },
        {
          name: "XLSX to JSON",
          value: "xlsx",
          action: "XLSX to JSON",
          description: "Extract data from an XLSX file",
        },
      ],
    },
    {
      displayName: "Binary Property",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      required: true,
      placeholder: "e.g data",
      description: "The name of the input binary field that holds the file to extract from.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Header Row",
          name: "headerRow",
          type: "boolean",
          default: true,
          description: "Whether the file contains a header row.",
        },
        {
          displayName: "Delimiter",
          name: "delimiter",
          type: "string",
          default: ",",
          description: "CSV column delimiter.",
        },
        {
          displayName: "Field Name",
          name: "fieldName",
          type: "string",
          default: "data",
          description: "Output field name that receives the text content (toText).",
        },
      ],
    },
  ],
};

export const dataTable: INodeTypeDescription = {
  name: "n8n-nodes-base.dataTable",
  displayName: "DataTable",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Manually enter data in a table format; each row becomes an output item.",
  defaults: { name: "DataTable" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Table",
  sources: [`${CORE}n8n-nodes-base.datatable/`],
  properties: [
    {
      displayName: "Table Data",
      name: "tableData",
      type: "json",
      default: "[]",
      description: "JSON array of row objects. Each object becomes one output item.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Keep Input Data",
          name: "keepInput",
          type: "boolean",
          default: false,
          description: "When on, merge each table row onto the corresponding input item by index.",
        },
      ],
    },
  ],
};

export const compareDatasets: INodeTypeDescription = {
  name: "n8n-nodes-base.compareDatasets",
  displayName: "Compare Datasets",
  category: "Transform",
  group: ["transform"],
  version: 2.3,
  defaultVersion: 2.3,
  description:
    "Compares two input datasets by key, routing items to In A only, Same, Different, or In B only branches.",
  defaults: { name: "Compare Datasets" },
  inputs: ["main", "main"],
  outputs: ["main", "main", "main", "main"],
  outputNames: ["In A only", "Same", "Different", "In B only"],
  icon: "GitCompare",
  sources: [`${CORE}n8n-nodes-base.comparedatasets/`],
  properties: [
    {
      displayName: "Fields to Match",
      name: "mergeByFields",
      type: "fixedCollection",
      default: { values: [{ field1: "", field2: "" }] },
      typeOptions: { multipleValues: true },
      description:
        "Pairs an Input A field with an Input B field. Multiple rows form a composite match key.",
      options: [
        {
          name: "values",
          displayName: "",
          values: [
            {
              displayName: "Input A Field",
              name: "field1",
              type: "string",
              default: "",
              required: true,
              description: "Field name or expression path from Input A.",
            },
            {
              displayName: "Input B Field",
              name: "field2",
              type: "string",
              default: "",
              required: true,
              description: "Field name or expression path from Input B.",
            },
          ],
        },
      ],
    },
    {
      displayName: "When There Are Differences",
      name: "resolve",
      type: "options",
      default: "preferInput2",
      noDataExpression: true,
      options: [
        { name: "Use Input A Version", value: "preferInput1" },
        { name: "Use Input B Version", value: "preferInput2" },
        { name: "Mix Versions", value: "mix" },
        { name: "Include Both", value: "includeBoth" },
      ],
      description: "Which version of a differing pair to emit on the Different branch.",
    },
    {
      displayName: "Fuzzy Compare",
      name: "fuzzyCompare",
      type: "boolean",
      default: false,
      description: 'Tolerate small type differences (e.g. 3 == "3") when matching and comparing.',
    },
    {
      displayName: "Prefer",
      name: "preferWhenMix",
      type: "options",
      default: "input1",
      noDataExpression: true,
      displayOptions: { show: { resolve: ["mix"] } },
      options: [
        { name: "Input A Version", value: "input1" },
        { name: "Input B Version", value: "input2" },
      ],
      description: "When resolving with mix, start from this input's version.",
    },
    {
      displayName: "For Everything Except",
      name: "exceptWhenMix",
      type: "string",
      default: "",
      displayOptions: { show: { resolve: ["mix"] } },
      description: "Comma-separated field names taken from the non-preferred input when mixing.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Fields to Skip Comparing",
          name: "skipFields",
          type: "string",
          default: "",
          description: "Comma-separated field names ignored when judging same/different.",
        },
        {
          displayName: "Disable Dot Notation",
          name: "disableDotNotation",
          type: "boolean",
          default: false,
          description: "When on, treat field paths literally (no parent.child resolution).",
        },
        {
          displayName: "Multiple Matches",
          name: "multipleMatches",
          type: "options",
          default: "first",
          noDataExpression: true,
          options: [
            { name: "Include First Match Only", value: "first" },
            { name: "Include All Matches", value: "all" },
          ],
          description: "Whether to emit one item per A key or all matching pairs.",
        },
      ],
    },
  ],
};

export const renameKeys: INodeTypeDescription = {
  name: "n8n-nodes-base.renameKeys",
  displayName: "Rename Keys",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Renames keys on each item.",
  defaults: { name: "Rename Keys" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "WholeWord",
  sources: [`${CORE}n8n-nodes-base.renamekeys/`],
  properties: [
    {
      displayName: "Keys",
      name: "keys",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      options: [
        {
          name: "key",
          displayName: "Key",
          values: [
            {
              displayName: "Current Key Name",
              name: "currentKey",
              type: "string",
              default: "",
              placeholder: "level1.level2.currentKey",
              description: "Current key name. Supports dot-notation deep paths.",
            },
            {
              displayName: "New Key Name",
              name: "newKey",
              type: "string",
              default: "",
              placeholder: "level1.level2.newKey",
              description: "New key name. Supports dot-notation deep paths.",
            },
          ],
        },
      ],
    },
    {
      displayName: "Additional Options",
      name: "additionalOptions",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Regex",
          name: "regexReplacement",
          type: "fixedCollection",
          default: {},
          typeOptions: { multipleValues: true },
          options: [
            {
              name: "replacements",
              displayName: "Replacement",
              values: [
                {
                  displayName: "Regular Expression",
                  name: "searchRegex",
                  type: "string",
                  default: "",
                  description: "Regular expression to match key names.",
                },
                {
                  displayName: "Replace With",
                  name: "replaceRegex",
                  type: "string",
                  default: "",
                  description: "Replacement name. Supports regex captures $1, $2, …",
                },
                {
                  displayName: "Options",
                  name: "options",
                  type: "collection",
                  default: {},
                  options: [
                    {
                      displayName: "Case Insensitive",
                      name: "caseInsensitive",
                      type: "boolean",
                      default: false,
                      description: "When on, match case-insensitively (i flag).",
                    },
                    {
                      displayName: "Max Depth",
                      name: "depth",
                      type: "number",
                      default: -1,
                      description: "-1 = unlimited, 0 = top-level only.",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const html: INodeTypeDescription = {
  name: "n8n-nodes-base.html",
  displayName: "HTML",
  category: "Transform",
  group: ["transform"],
  version: [1, 1.1, 1.2],
  defaultVersion: 1.2,
  description: "Work with HTML: generate templates, extract content, or convert to tables.",
  defaults: { name: "HTML" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "Code",
  sources: [`${CORE}n8n-nodes-base.html/`],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "generateHtmlTemplate",
      noDataExpression: true,
      options: [
        { name: "Generate HTML Template", value: "generateHtmlTemplate" },
        { name: "Extract HTML Content", value: "extractHtmlContent" },
        { name: "Convert to HTML Table", value: "convertToHtmlTable" },
      ],
      description: "What to do with the HTML.",
    },
    {
      displayName: "HTML",
      name: "html",
      type: "string",
      default: "",
      noDataExpression: true,
      displayOptions: { show: { operation: ["generateHtmlTemplate"] } },
      description: "HTML template. Use {{ }} for expressions.",
      typeOptions: { rows: 10 },
    },
    {
      displayName: "Source Data",
      name: "sourceData",
      type: "options",
      default: "json",
      noDataExpression: true,
      displayOptions: { show: { operation: ["extractHtmlContent"] } },
      options: [
        { name: "JSON", value: "json" },
        { name: "Binary", value: "binary" },
      ],
      description: "Where the HTML source comes from.",
    },
    {
      displayName: "Data Property Name",
      name: "dataPropertyName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { operation: ["extractHtmlContent"] } },
      description:
        "JSON property name (or dot-notation path) or binary field name containing the HTML.",
    },
    {
      displayName: "Extraction Values",
      name: "extractionValues",
      type: "fixedCollection",
      default: { values: [{ key: "", cssSelector: "", returnValue: "text", returnArray: false }] },
      typeOptions: { multipleValues: true },
      displayOptions: { show: { operation: ["extractHtmlContent"] } },
      options: [
        {
          name: "values",
          displayName: "Value",
          values: [
            {
              displayName: "Key",
              name: "key",
              type: "string",
              default: "",
              required: true,
              description: "Key under which the extracted value is saved.",
            },
            {
              displayName: "CSS Selector",
              name: "cssSelector",
              type: "string",
              default: "",
              required: true,
              placeholder: ".price",
              description: "CSS selector to search for.",
            },
            {
              displayName: "Return Value",
              name: "returnValue",
              type: "options",
              default: "text",
              noDataExpression: true,
              options: [
                { name: "Attribute", value: "attribute" },
                { name: "HTML", value: "html" },
                { name: "Text", value: "text" },
                { name: "Value", value: "value" },
              ],
              description: "What to return from the matched element.",
            },
            {
              displayName: "Attribute",
              name: "attribute",
              type: "string",
              default: "",
              displayOptions: { show: { returnValue: ["attribute"] } },
              description: "Attribute name whose value to return.",
            },
            {
              displayName: "Skip Selectors",
              name: "skipSelectors",
              type: "string",
              default: "",
              displayOptions: { show: { returnValue: ["text"] } },
              description: "Comma-separated selectors to skip in text extraction.",
            },
            {
              displayName: "Return Array",
              name: "returnArray",
              type: "boolean",
              default: false,
              description:
                "On = return one entry per matched element (array); off = single string.",
            },
          ],
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["extractHtmlContent", "convertToHtmlTable"] } },
      options: [
        {
          displayName: "Trim Values",
          name: "trimValues",
          type: "boolean",
          default: true,
          description: "Remove leading/trailing spaces and newlines from each value.",
        },
        {
          displayName: "Clean Up Text",
          name: "cleanUpText",
          type: "boolean",
          default: true,
          description:
            "Remove leading/trailing whitespace, strip line breaks, condense consecutive whitespace.",
        },
        {
          displayName: "Capitalize Headers",
          name: "capitalize",
          type: "boolean",
          default: false,
          description:
            "Capitalize table headers (split on _, title-case each word, join with space).",
        },
        {
          displayName: "Custom Styling",
          name: "customStyling",
          type: "boolean",
          default: false,
          description:
            "On = no default inline styles; off = default border/font/padding styles applied.",
        },
        {
          displayName: "Caption",
          name: "caption",
          type: "string",
          default: "",
          description: "Caption added inside <caption>.",
        },
        {
          displayName: "Table Attributes",
          name: "tableAttributes",
          type: "string",
          default: "",
          description: 'Attributes for <table> (e.g. style="padding:10px").',
        },
        {
          displayName: "Header Attributes",
          name: "headerAttributes",
          type: "string",
          default: "",
          description: "Attributes for <th> header cells.",
        },
        {
          displayName: "Row Attributes",
          name: "rowAttributes",
          type: "string",
          default: "",
          description: "Attributes for each <tr> (evaluated per item, may be expression).",
        },
        {
          displayName: "Cell Attributes",
          name: "cellAttributes",
          type: "string",
          default: "",
          description: "Attributes for each <td> (evaluated per item, may be expression).",
        },
      ],
    },
  ],
};

export const xml: INodeTypeDescription = {
  name: "n8n-nodes-base.xml",
  displayName: "XML",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Convert data between JSON and XML.",
  defaults: { name: "XML" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileCode",
  sources: [`${CORE}n8n-nodes-base.xml/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "xmlToJson",
      noDataExpression: true,
      options: [
        { name: "JSON to XML", value: "jsonToxml" },
        { name: "XML to JSON", value: "xmlToJson" },
      ],
      description: "Conversion direction.",
    },
    {
      displayName: "Property Name",
      name: "dataPropertyName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["jsonToxml"] } },
      description: "Name of the property containing the JSON value to convert.",
    },
    {
      displayName: "Property Name",
      name: "dataPropertyName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["xmlToJson"] } },
      description: "Name of the property containing the XML string to convert.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["jsonToxml"] } },
      options: [
        {
          displayName: "Allow Surrogate Chars",
          name: "allowSurrogateChars",
          type: "boolean",
          default: false,
          description: "Allow characters from Unicode surrogate blocks.",
        },
        {
          displayName: "Attribute Key",
          name: "attrkey",
          type: "string",
          default: "$",
          description:
            "Prefix used to access attributes. Object keys named this are serialized as element attributes.",
        },
        {
          displayName: "Cdata",
          name: "cdata",
          type: "boolean",
          default: false,
          description: "Wrap text nodes in CDATA instead of escaping when necessary.",
        },
        {
          displayName: "Character Key",
          name: "charkey",
          type: "string",
          default: "_",
          description:
            "Prefix used to access character content. Object keys named this are serialized as element text.",
        },
        {
          displayName: "Headless",
          name: "headless",
          type: "boolean",
          default: false,
          description: "Omit the XML declaration when on; include it when off.",
        },
        {
          displayName: "Root Name",
          name: "rootName",
          type: "string",
          default: "root",
          description: "Root element name to use.",
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["xmlToJson"] } },
      options: [
        {
          displayName: "Attribute Key",
          name: "attrkey",
          type: "string",
          default: "$",
          description: "Prefix used to access attributes (when not merged).",
        },
        {
          displayName: "Character Key",
          name: "charkey",
          type: "string",
          default: "_",
          description: "Prefix used to access character content.",
        },
        {
          displayName: "Explicit Array",
          name: "explicitArray",
          type: "boolean",
          default: false,
          description:
            "Always put child nodes in an array; when off, an array is created only if there is more than one child.",
        },
        {
          displayName: "Explicit Root",
          name: "explicitRoot",
          type: "boolean",
          default: true,
          description: "Include the root node in the resulting object.",
        },
        {
          displayName: "Ignore Attributes",
          name: "ignoreAttrs",
          type: "boolean",
          default: false,
          description: "Ignore all XML attributes and only create text nodes.",
        },
        {
          displayName: "Merge Attributes",
          name: "mergeAttrs",
          type: "boolean",
          default: true,
          description:
            "Merge attributes and child elements as properties of the parent. Ignored if Ignore Attributes is on.",
        },
        {
          displayName: "Normalize",
          name: "normalize",
          type: "boolean",
          default: false,
          description: "Trim whitespaces inside text nodes.",
        },
        {
          displayName: "Normalize Tags",
          name: "normalizeTags",
          type: "boolean",
          default: false,
          description: "Normalize all tag names to lowercase.",
        },
        {
          displayName: "Trim",
          name: "trim",
          type: "boolean",
          default: false,
          description: "Trim whitespace at the beginning and end of text nodes.",
        },
      ],
    },
  ],
};

export const markdown: INodeTypeDescription = {
  name: "n8n-nodes-base.markdown",
  displayName: "Markdown",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Convert data between Markdown and HTML.",
  defaults: { name: "Markdown" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileCode",
  sources: [`${CORE}n8n-nodes-base.markdown/`],
  properties: [
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "htmlToMarkdown",
      noDataExpression: true,
      options: [
        { name: "HTML to Markdown", value: "htmlToMarkdown" },
        { name: "Markdown to HTML", value: "markdownToHtml" },
      ],
      description: "Conversion direction.",
    },
    {
      displayName: "HTML",
      name: "html",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { mode: ["htmlToMarkdown"] } },
      description: "The HTML to convert to Markdown.",
      typeOptions: { rows: 5 },
    },
    {
      displayName: "Markdown",
      name: "markdown",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { mode: ["markdownToHtml"] } },
      description: "The Markdown to convert to HTML.",
      typeOptions: { rows: 5 },
    },
    {
      displayName: "Destination Key",
      name: "destinationKey",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { mode: ["htmlToMarkdown", "markdownToHtml"] } },
      description: "Output field. Nested fields via dots, e.g. level1.level2.newKey.",
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["htmlToMarkdown"] } },
      options: [
        {
          displayName: "Bullet Marker",
          name: "bulletMarker",
          type: "string",
          default: "*",
          description: "Unordered-list bullet character.",
        },
        {
          displayName: "Code Block Fence",
          name: "codeFence",
          type: "string",
          default: "```",
          description: "Code-block fence string.",
        },
        {
          displayName: "Emphasis Delimiter",
          name: "emDelimiter",
          type: "string",
          default: "_",
          description: "<em> delimiter.",
        },
        {
          displayName: "Strong Delimiter",
          name: "strongDelimiter",
          type: "string",
          default: "**",
          description: "<strong> delimiter.",
        },
        {
          displayName: "Style For Code Block",
          name: "codeBlockStyle",
          type: "options",
          default: "fence",
          noDataExpression: true,
          options: [
            { name: "Fenced", value: "fence" },
            { name: "Indented", value: "indented" },
          ],
          description: "How to render code blocks.",
        },
        {
          displayName: "Max Consecutive New Lines",
          name: "maxConsecutiveNewlines",
          type: "number",
          default: 3,
          description: "Max consecutive newlines allowed.",
        },
        {
          displayName: "Place URLs At The Bottom",
          name: "useLinkReferenceDefinitions",
          type: "boolean",
          default: false,
          description: "Move URLs to bottom; use link reference definitions.",
        },
        {
          displayName: "Keep Images With Data",
          name: "keepDataImages",
          type: "boolean",
          default: false,
          description: "Keep data: URI images (up to 1MB each).",
        },
        {
          displayName: "Ignored Elements",
          name: "ignore",
          type: "string",
          default: "",
          description: "Comma-separated elements to ignore (with children).",
        },
        {
          displayName: "Treat As Blocks",
          name: "blockElements",
          type: "string",
          default: "",
          description: "Comma-separated elements to surround with blank lines.",
        },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      displayOptions: { show: { mode: ["markdownToHtml"] } },
      options: [
        {
          displayName: "Add Blank To Links",
          name: "openLinksInNewWindow",
          type: "boolean",
          default: false,
          description: 'Add target="_blank" to <a>.',
        },
        {
          displayName: "Automatic Linking to URLs",
          name: "simplifiedAutoLink",
          type: "boolean",
          default: false,
          description: "Auto-link bare URLs.",
        },
        {
          displayName: "Exclude Trailing Punctuation From URLs",
          name: "excludeTrailingPunctuationFromURLs",
          type: "boolean",
          default: false,
          description: "Only with simplifiedAutoLink.",
        },
        {
          displayName: "Backslash Escapes HTML Tags",
          name: "backslashEscapesHTMLTags",
          type: "boolean",
          default: false,
          description: "Escape \\< \\>.",
        },
        {
          displayName: "Complete HTML Document",
          name: "completeHTMLDocument",
          type: "boolean",
          default: false,
          description: "Emit <!DOCTYPE>, <html>, <head>, <body>.",
        },
        {
          displayName: "Encode Emails",
          name: "encodeEmails",
          type: "boolean",
          default: true,
          description: "Encode ASCII emails as decimal entities.",
        },
        {
          displayName: "GitHub Code Blocks",
          name: "ghCodeBlocks",
          type: "boolean",
          default: true,
          description: "GFM code-block style.",
        },
        {
          displayName: "GitHub Compatible Header IDs",
          name: "ghCompatibleHeaderId",
          type: "boolean",
          default: false,
          description: "GFM-style header IDs.",
        },
        {
          displayName: "GitHub Mentions",
          name: "ghMentions",
          type: "boolean",
          default: false,
          description: "Link @name to GitHub.",
        },
        {
          displayName: "GitHub Mention Link",
          name: "ghMentionsLink",
          type: "string",
          default: "https://github.com/{u}",
          description: "Template for @mentions; {u} → username.",
        },
        {
          displayName: "GitHub Task Lists",
          name: "tasklists",
          type: "boolean",
          default: false,
          description: "GFM task-list syntax.",
        },
        {
          displayName: "Strikethrough",
          name: "strikethrough",
          type: "boolean",
          default: false,
          description: "~~text~~ syntax.",
        },
        {
          displayName: "Tables Support",
          name: "tables",
          type: "boolean",
          default: false,
          description: "Markdown table syntax.",
        },
        {
          displayName: "Tables Header ID",
          name: "tablesHeaderId",
          type: "boolean",
          default: false,
          description: "Add ID to table header cells.",
        },
        {
          displayName: "Customized Header ID",
          name: "customizedHeaderId",
          type: "boolean",
          default: false,
          description: "Use {id} after heading text.",
        },
        {
          displayName: "Header Level Start",
          name: "headerLevelStart",
          type: "number",
          default: 1,
          description: "Treat # as <h{N}> start level.",
        },
        {
          displayName: "Prefix Header ID",
          name: "prefixHeaderId",
          type: "string",
          default: "section",
          description: "Prefix added to generated header IDs.",
        },
        {
          displayName: "Raw Header ID",
          name: "rawHeaderId",
          type: "boolean",
          default: false,
          description: "Replace spaces/'/\" in header IDs with -.",
        },
        {
          displayName: "Raw Prefix Header ID",
          name: "rawPrefixHeaderId",
          type: "boolean",
          default: false,
          description: "Do not modify the prefix.",
        },
        {
          displayName: "No Header ID",
          name: "noHeaderId",
          type: "boolean",
          default: false,
          description: "Disable automatic header-ID generation.",
        },
        {
          displayName: "Mandatory Space Before Header",
          name: "requireSpaceBeforeHeadingText",
          type: "boolean",
          default: false,
          description: "Require space between # and text.",
        },
        {
          displayName: "Middle Word Asterisks",
          name: "literalMidWordAsterisks",
          type: "boolean",
          default: false,
          description: "Treat mid-word * as literal.",
        },
        {
          displayName: "Middle Word Underscores",
          name: "literalMidWordUnderscores",
          type: "boolean",
          default: false,
          description: "Treat mid-word _ as literal.",
        },
        {
          displayName: "Simple Line Breaks",
          name: "simpleLineBreaks",
          type: "boolean",
          default: false,
          description: "Single newline → <br> (GitHub-style).",
        },
        {
          displayName: "Smart Indentation Fix",
          name: "smartIndentationFix",
          type: "boolean",
          default: false,
          description: "Fix ES6 template-string indentation in code.",
        },
        {
          displayName: "Spaces Indented Sublists",
          name: "disableForced4SpacesIndentedSublists",
          type: "boolean",
          default: false,
          description: "Allow 2–3 space sublist indent.",
        },
        {
          displayName: "Split Adjacent Blockquotes",
          name: "splitAdjacentBlockquotes",
          type: "boolean",
          default: false,
          description: "Split adjacent > blocks.",
        },
        {
          displayName: "Parse Image Dimensions",
          name: "parseImgDimensions",
          type: "boolean",
          default: false,
          description: "Image dimensions in Markdown syntax.",
        },
        {
          displayName: "Emoji Support",
          name: "emoji",
          type: "boolean",
          default: false,
          description: ":smile: → emoji.",
        },
      ],
    },
  ],
};

export const compression: INodeTypeDescription = {
  name: "n8n-nodes-base.compression",
  displayName: "Compression",
  category: "Transform",
  group: ["transform"],
  version: [1, 1.1],
  defaultVersion: 1.1,
  description: "Compress and decompress files using zip or gzip.",
  defaults: { name: "Compression" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "FileArchive",
  sources: [`${CORE}n8n-nodes-base.compression/`],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "decompress",
      noDataExpression: true,
      options: [
        { name: "Compress", value: "compress", description: "Compress file(s)" },
        { name: "Decompress", value: "decompress", description: "Decompress file(s)" },
      ],
      description: "Whether to compress or decompress the input file(s).",
    },
    {
      displayName: "Input Binary Field(s)",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      required: true,
      description: "Comma-separated list of binary fields to compress.",
      displayOptions: { show: { operation: ["compress"] } },
    },
    {
      displayName: "Input Binary Field(s)",
      name: "binaryPropertyName",
      type: "string",
      default: "data",
      required: true,
      description: "Comma-separated list of binary fields to decompress.",
      displayOptions: { show: { operation: ["decompress"] } },
    },
    {
      displayName: "Output Format",
      name: "outputFormat",
      type: "options",
      default: "zip",
      noDataExpression: true,
      options: [
        { name: "Zip", value: "zip" },
        { name: "Gzip", value: "gzip" },
      ],
      description: "Format of the compressed archive.",
      displayOptions: { show: { operation: ["compress"] } },
    },
    {
      displayName: "File Name",
      name: "fileName",
      type: "string",
      default: "",
      required: true,
      placeholder: "data.zip",
      description: "Output file name, e.g. data.zip.",
      displayOptions: { show: { operation: ["compress"], outputFormat: ["zip"] } },
    },
    {
      displayName: "Put Output File in Field",
      name: "binaryPropertyOutput",
      type: "string",
      default: "data",
      description: "Output binary field name.",
      displayOptions: { show: { operation: ["compress"], outputFormat: ["zip"] } },
    },
    {
      displayName: "File Name",
      name: "fileName",
      type: "string",
      default: "",
      placeholder: "data.txt",
      description: "Output file name, e.g. data.txt.",
      displayOptions: { show: { operation: ["compress"], outputFormat: ["gzip"] } },
    },
    {
      displayName: "Put Output File in Field",
      name: "binaryPropertyOutput",
      type: "string",
      default: "data",
      description: "Output binary field name.",
      displayOptions: { show: { operation: ["compress"], outputFormat: ["gzip"] } },
    },
    {
      displayName: "Output Prefix",
      name: "outputPrefix",
      type: "string",
      default: "file_",
      required: true,
      description: "Prefix + incrementing index names each extracted file (file_0, file_1, …).",
      displayOptions: { show: { operation: ["decompress"] } },
    },
  ],
};

export const jwt: INodeTypeDescription = {
  name: "n8n-nodes-base.jwt",
  displayName: "JWT",
  category: "Transform",
  group: ["transform"],
  version: 1,
  description: "Sign, verify, and decode JSON Web Tokens.",
  defaults: { name: "JWT" },
  inputs: ["main"],
  outputs: ["main"],
  icon: "KeyRound",
  credentials: [{ name: "jwtAuth", required: true }],
  sources: [`${CORE}n8n-nodes-base.jwt/`],
  properties: [
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      default: "sign",
      noDataExpression: true,
      options: [
        {
          name: "Decode",
          value: "decode",
          description: "Read the token payload without checking the signature.",
        },
        {
          name: "Sign",
          value: "sign",
          description: "Build a JWT from claims using key material from a JWT credential.",
        },
        {
          name: "Verify",
          value: "verify",
          description: "Check a token's signature and time claims.",
        },
      ],
      description: "The JWT operation to perform.",
    },
    {
      displayName: "Use JSON",
      name: "useJson",
      type: "boolean",
      default: false,
      displayOptions: { show: { operation: ["sign"] } },
      description: "When on, build claims from claimsJson; when off, use the claims collection.",
    },
    {
      displayName: "Claims",
      name: "claims",
      type: "collection",
      default: {},
      displayOptions: { show: { operation: ["sign"], useJson: [false] } },
      options: [
        {
          displayName: "Audience",
          name: "audience",
          type: "string",
          default: "",
          description: "Identifies the intended recipients (aud).",
        },
        {
          displayName: "Expire In",
          name: "expiresIn",
          type: "number",
          default: 3600,
          typeOptions: { minValue: 0 },
          description: "Lifetime of the token in seconds (exp).",
        },
        {
          displayName: "Issuer",
          name: "issuer",
          type: "string",
          default: "",
          description: "Identifies the principal that issued the JWT (iss).",
        },
        {
          displayName: "JWT ID",
          name: "jwtid",
          type: "string",
          default: "",
          description: "Unique identifier for the JWT (jti).",
        },
        {
          displayName: "Not Before",
          name: "notBefore",
          type: "number",
          default: 0,
          typeOptions: { minValue: 0 },
          description: "Seconds before which the JWT must not be accepted (nbf).",
        },
        {
          displayName: "Subject",
          name: "subject",
          type: "string",
          default: "",
          description: "Identifies the subject of the JWT (sub).",
        },
      ],
    },
    {
      displayName: "Claims JSON",
      name: "claimsJson",
      type: "json",
      default: '{\n  "my_field_1": "value 1",\n  "my_field_2": "value 2"\n}\n',
      displayOptions: { show: { operation: ["sign"], useJson: [true] } },
      description: "Arbitrary JSON object used as the token payload.",
    },
    {
      displayName: "Token",
      name: "token",
      type: "string",
      default: "",
      required: true,
      displayOptions: { show: { operation: ["verify", "decode"] } },
      description: "The token to verify or decode.",
      typeOptions: { password: true },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        {
          displayName: "Return Additional Info",
          name: "complete",
          type: "boolean",
          default: false,
          displayOptions: { show: { "/operation": ["verify", "decode"] } },
          description:
            "On = return full decoded token (header + payload + signature); off = payload only.",
        },
        {
          displayName: "Ignore Expiration",
          name: "ignoreExpiration",
          type: "boolean",
          default: false,
          displayOptions: { show: { "/operation": ["verify"] } },
          description: "Skip the exp claim check.",
        },
        {
          displayName: "Ignore Not Before Claim",
          name: "ignoreNotBefore",
          type: "boolean",
          default: false,
          displayOptions: { show: { "/operation": ["verify"] } },
          description: "Skip the nbf claim check.",
        },
        {
          displayName: "Clock Tolerance",
          name: "clockTolerance",
          type: "number",
          default: 0,
          typeOptions: { minValue: 0 },
          displayOptions: { show: { "/operation": ["verify"] } },
          description: "Seconds of tolerance when checking nbf and exp.",
        },
        {
          displayName: "Key ID",
          name: "kid",
          type: "string",
          default: "",
          displayOptions: { show: { "/operation": ["sign"] } },
          description: "Optional kid JOSE header claim, used to signal the key for validation.",
        },
        {
          displayName: "Override Algorithm",
          name: "algorithm",
          type: "options",
          default: "HS256",
          displayOptions: { show: { "/operation": ["sign", "verify"] } },
          options: [
            { name: "ES256", value: "ES256" },
            { name: "ES384", value: "ES384" },
            { name: "ES512", value: "ES512" },
            { name: "HS256", value: "HS256" },
            { name: "HS384", value: "HS384" },
            { name: "HS512", value: "HS512" },
            { name: "PS256", value: "PS256" },
            { name: "PS384", value: "PS384" },
            { name: "PS512", value: "PS512" },
            { name: "RS256", value: "RS256" },
            { name: "RS384", value: "RS384" },
            { name: "RS512", value: "RS512" },
          ],
          description: "Algorithm for sign/verify; overrides the credential's algorithm.",
        },
      ],
    },
  ],
};
