import type { INodeTypeDescription } from "../types";

const DOCS = "https://docs.n8n.io/integrations/builtin/core-nodes/";

export const errorTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.errorTrigger",
  displayName: "Error Trigger",
  category: "Triggers",
  group: ["trigger"],
  version: 1,
  description: "Starts when a linked workflow fails (error workflow).",
  defaults: { name: "Error Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "CircleAlert",
  sources: [`${DOCS}n8n-nodes-base.errortrigger/`],
  properties: [
    {
      displayName:
        "This workflow runs when another workflow fails and points here as its Error workflow.",
      name: "notice",
      type: "notice",
      default: "",
    },
  ],
};

export const executeWorkflowTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.executeWorkflowTrigger",
  displayName: "When Executed by Another Workflow",
  category: "Triggers",
  group: ["trigger"],
  version: [1, 1.1],
  defaultVersion: 1.1,
  description: "Starts this workflow when called as a sub-workflow.",
  defaults: { name: "When Executed by Another Workflow" },
  inputs: [],
  outputs: ["main"],
  icon: "Workflow",
  sources: [`${DOCS}n8n-nodes-base.executeworkflowtrigger/`],
  properties: [
    {
      displayName:
        "This node starts the workflow when called by Execute Sub-workflow. The parent payload is emitted on output.",
      name: "notice",
      type: "notice",
      default: "",
      displayOptions: { show: { "@version": [1] } },
    },
    {
      displayName: "This trigger type is outdated. Replace it with the latest version.",
      name: "outdatedVersionWarning",
      type: "notice",
      default: "",
      displayOptions: { show: { "@version": [1] } },
    },
    {
      displayName: "Input data mode",
      name: "inputSource",
      type: "options",
      default: "workflowInputs",
      noDataExpression: true,
      displayOptions: { hide: { "@version": [1] } },
      options: [
        { name: "Define using fields below", value: "workflowInputs" },
        { name: "Define using JSON example", value: "jsonExample" },
        { name: "Accept all data", value: "passthrough" },
      ],
    },
    {
      displayName:
        "Provide an example JSON object. Field names and types are inferred; a null value means any type.",
      name: "jsonExample_notice",
      type: "notice",
      default: "",
      displayOptions: { show: { "@version": [1.1], inputSource: ["jsonExample"] } },
    },
    {
      displayName: "JSON Example",
      name: "jsonExample",
      type: "json",
      default: '{\n  "field1": "value1",\n  "field2": 0,\n  "field3": null,\n  "field4": []\n}',
      noDataExpression: true,
      displayOptions: { show: { "@version": [1.1], inputSource: ["jsonExample"] } },
    },
    {
      displayName: "Workflow Inputs",
      name: "workflowInputs",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      noDataExpression: true,
      displayOptions: { show: { "@version": [1.1], inputSource: ["workflowInputs"] } },
      options: [
        {
          name: "values",
          displayName: "Input Field",
          values: [
            {
              displayName: "Field Name",
              name: "name",
              type: "string",
              default: "",
              required: true,
              noDataExpression: true,
            },
            {
              displayName: "Field Type",
              name: "type",
              type: "options",
              default: "string",
              noDataExpression: true,
              options: [
                { name: "Any", value: "any" },
                { name: "String", value: "string" },
                { name: "Number", value: "number" },
                { name: "Boolean", value: "boolean" },
                { name: "Array", value: "array" },
                { name: "Object", value: "object" },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const workflowTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.workflowTrigger",
  displayName: "Workflow Trigger",
  category: "Triggers",
  group: ["trigger"],
  version: [1, 1.1],
  defaultVersion: 1.1,
  description: "Starts the workflow when a workflow event occurs (started or finished).",
  defaults: { name: "Workflow Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "Workflow",
  sources: [`${DOCS}n8n-nodes-base.workflowtrigger/`],
  properties: [
    {
      displayName: "Trigger On",
      name: "workflowTrigger",
      type: "options",
      default: "workflowStarted",
      noDataExpression: true,
      description: "The workflow event to trigger on.",
      options: [
        { name: "When workflow starts", value: "workflowStarted" },
        { name: "When workflow finishes", value: "workflowFinished" },
      ],
    },
    {
      displayName: "Workflow ID",
      name: "workflowId",
      type: "string",
      default: "",
      placeholder: "1",
      description:
        "Filter to a specific workflow ID. Leave empty to trigger on all workflows.",
    },
  ],
};

export const manualTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.manualTrigger",
  displayName: "Manual Trigger",
  category: "Triggers",
  group: ["trigger"],
  version: 1,
  description: "Runs the workflow when you click Execute.",
  defaults: { name: "When clicking 'Execute workflow'" },
  inputs: [],
  outputs: ["main"],
  icon: "MousePointerClick",
  sources: [`${DOCS}n8n-nodes-base.manualworkflowtrigger/`],
  properties: [
    {
      displayName:
        "This node starts the workflow when you run it manually from the editor. It emits a single empty item.",
      name: "notice",
      type: "notice",
      default: "",
    },
  ],
};

export const scheduleTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.scheduleTrigger",
  displayName: "Schedule Trigger",
  category: "Triggers",
  group: ["trigger"],
  version: 1.2,
  description: "Runs the workflow on a fixed interval or cron expression.",
  defaults: { name: "Schedule Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "Clock",
  sources: [`${DOCS}n8n-nodes-base.scheduletrigger/`],
  properties: [
    {
      displayName: "Trigger Rules",
      name: "rule",
      type: "fixedCollection",
      default: { interval: [{ field: "days" }] },
      typeOptions: { multipleValues: true },
      noDataExpression: true,
      description: "One or more independent schedule rules.",
      options: [
        {
          name: "interval",
          displayName: "Rule",
          values: [
            {
              displayName: "Trigger Interval",
              name: "field",
              type: "options",
              default: "days",
              noDataExpression: true,
              options: [
                { name: "Seconds", value: "seconds" },
                { name: "Minutes", value: "minutes" },
                { name: "Hours", value: "hours" },
                { name: "Days", value: "days" },
                { name: "Weeks", value: "weeks" },
                { name: "Months", value: "months" },
                { name: "Custom (Cron)", value: "cronExpression" },
              ],
            },
            {
              displayName: "Seconds Between Triggers",
              name: "secondsInterval",
              type: "number",
              default: 30,
              typeOptions: { minValue: 1, maxValue: 59 },
              displayOptions: { show: { field: ["seconds"] } },
            },
            {
              displayName: "Minutes Between Triggers",
              name: "minutesInterval",
              type: "number",
              default: 5,
              typeOptions: { minValue: 1, maxValue: 59 },
              displayOptions: { show: { field: ["minutes"] } },
            },
            {
              displayName: "Hours Between Triggers",
              name: "hoursInterval",
              type: "number",
              default: 1,
              typeOptions: { minValue: 1, maxValue: 23 },
              displayOptions: { show: { field: ["hours"] } },
            },
            {
              displayName: "Days Between Triggers",
              name: "daysInterval",
              type: "number",
              default: 1,
              typeOptions: { minValue: 1, maxValue: 31 },
              displayOptions: { show: { field: ["days"] } },
            },
            {
              displayName: "Weeks Between Triggers",
              name: "weeksInterval",
              type: "number",
              default: 1,
              typeOptions: { minValue: 1 },
              displayOptions: { show: { field: ["weeks"] } },
            },
            {
              displayName: "Months Between Triggers",
              name: "monthsInterval",
              type: "number",
              default: 1,
              typeOptions: { minValue: 1, maxValue: 12 },
              displayOptions: { show: { field: ["months"] } },
            },
            {
              displayName: "Minute Past Hour",
              name: "triggerAtMinute",
              type: "number",
              default: 0,
              typeOptions: { minValue: 0, maxValue: 59 },
              displayOptions: { show: { field: ["hours", "days", "weeks", "months"] } },
            },
            {
              displayName: "Hour of Day",
              name: "triggerAtHour",
              type: "number",
              default: 0,
              typeOptions: { minValue: 0, maxValue: 23 },
              displayOptions: { show: { field: ["days", "weeks", "months"] } },
            },
            {
              displayName: "Weekdays to Fire",
              name: "triggerAtDay",
              type: "multiOptions",
              default: [0],
              displayOptions: { show: { field: ["weeks"] } },
              options: [
                { name: "Sunday", value: 0 },
                { name: "Monday", value: 1 },
                { name: "Tuesday", value: 2 },
                { name: "Wednesday", value: 3 },
                { name: "Thursday", value: 4 },
                { name: "Friday", value: 5 },
                { name: "Saturday", value: 6 },
              ],
            },
            {
              displayName: "Day of Month",
              name: "triggerAtDayOfMonth",
              type: "number",
              default: 1,
              typeOptions: { minValue: 1, maxValue: 31 },
              displayOptions: { show: { field: ["months"] } },
            },
            {
              displayName: "Cron Expression",
              name: "expression",
              type: "string",
              default: "",
              placeholder: "0 * * * *",
              displayOptions: { show: { field: ["cronExpression"] } },
            },
          ],
        },
      ],
    },
  ],
};

export const webhook: INodeTypeDescription = {
  name: "n8n-nodes-base.webhook",
  displayName: "Webhook",
  category: "Triggers",
  group: ["trigger"],
  version: 2,
  description: "Starts the workflow when an HTTP request hits its URL.",
  defaults: { name: "Webhook" },
  inputs: [],
  outputs: ["main"],
  icon: "Webhook",
  sources: [`${DOCS}n8n-nodes-base.webhook/`],
  properties: [
    {
      displayName: "HTTP Method",
      name: "httpMethod",
      type: "options",
      default: "GET",
      noDataExpression: true,
      options: [
        { name: "GET", value: "GET" },
        { name: "POST", value: "POST" },
        { name: "PUT", value: "PUT" },
        { name: "PATCH", value: "PATCH" },
        { name: "DELETE", value: "DELETE" },
        { name: "HEAD", value: "HEAD" },
      ],
    },
    {
      displayName: "Path",
      name: "path",
      type: "string",
      default: "",
      placeholder: "my-webhook",
      required: true,
      description: "Path segment appended to the instance webhook base URL.",
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "none",
      options: [
        { name: "None", value: "none" },
        { name: "Basic Auth", value: "basicAuth" },
        { name: "Header Auth", value: "headerAuth" },
      ],
    },
    {
      displayName: "Respond",
      name: "responseMode",
      type: "options",
      default: "onReceived",
      options: [
        { name: "Immediately", value: "onReceived" },
        { name: "When Last Node Finishes", value: "lastNode" },
        { name: "Using 'Respond to Webhook' Node", value: "responseNode" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      options: [
        { displayName: "Raw Body", name: "rawBody", type: "boolean", default: false },
        { displayName: "Response Code", name: "responseCode", type: "number", default: 200 },
        { displayName: "Ignore Bots", name: "ignoreBots", type: "boolean", default: false },
      ],
    },
  ],
};

export const formTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.formTrigger",
  displayName: "n8n Form",
  category: "Triggers",
  group: ["trigger"],
  version: 2,
  description: "Starts the workflow when a user submits a form served by n8n.",
  defaults: { name: "On form submission" },
  inputs: [],
  outputs: ["main"],
  icon: "Form",
  credentials: [{ name: "httpBasicAuth", required: false }],
  sources: [`${DOCS}n8n-nodes-base.formtrigger/`],
  properties: [
    {
      displayName: "Form Title",
      name: "formTitle",
      type: "string",
      default: "",
      placeholder: "My Form",
      required: true,
      description: "Webpage title and main heading on the rendered form.",
    },
    {
      displayName: "Form Description",
      name: "formDescription",
      type: "string",
      typeOptions: { rows: 4 },
      default: "",
      description: "Subtitle below the title. Use \\n or <br> for line breaks. HTML is sanitized.",
    },
    {
      displayName: "Form Path",
      name: "formPath",
      type: "string",
      default: "",
      placeholder: "my-form",
      description: "Custom slug appended to /form/. Replaces the auto-generated UUID when set.",
    },
    {
      displayName: "Form Elements",
      name: "formElements",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      noDataExpression: true,
      required: true,
      description: "Ordered list of form fields.",
      options: [
        {
          name: "values",
          displayName: "Field",
          values: [
            {
              displayName: "Field Label",
              name: "fieldLabel",
              type: "string",
              default: "",
              required: true,
            },
            {
              displayName: "Field Name",
              name: "fieldName",
              type: "string",
              default: "",
              required: true,
              description: "Key used for this field's value in the node output.",
            },
            {
              displayName: "Element Type",
              name: "elementType",
              type: "options",
              noDataExpression: true,
              default: "text",
              required: true,
              options: [
                { name: "Checkboxes", value: "checkboxes" },
                { name: "Custom HTML", value: "customHtml" },
                { name: "Date", value: "date" },
                { name: "Dropdown", value: "dropdown" },
                { name: "Email", value: "email" },
                { name: "File", value: "file" },
                { name: "Hidden Field", value: "hidden" },
                { name: "Number", value: "number" },
                { name: "Password", value: "password" },
                { name: "Radio Buttons", value: "radio" },
                { name: "Text", value: "text" },
                { name: "Textarea", value: "textarea" },
              ],
            },
            {
              displayName: "Placeholder",
              name: "placeholder",
              type: "string",
              default: "",
              displayOptions: {
                show: {
                  elementType: ["email", "number", "password", "text", "textarea"],
                },
              },
            },
            {
              displayName: "Default Value",
              name: "defaultValue",
              type: "string",
              default: "",
              displayOptions: {
                hide: {
                  elementType: ["customHtml", "file", "hidden", "password"],
                },
              },
            },
            {
              displayName: "Required Field",
              name: "requiredField",
              type: "boolean",
              default: false,
            },
          ],
        },
      ],
    },
    {
      displayName: "Respond When",
      name: "responseMode",
      type: "options",
      noDataExpression: true,
      default: "formSubmitted",
      options: [
        { name: "Form Is Submitted", value: "formSubmitted" },
        { name: "Workflow Finishes", value: "workflowFinishes" },
      ],
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      noDataExpression: true,
      default: "none",
      options: [
        { name: "None", value: "none" },
        { name: "Basic Auth", value: "basicAuth" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      placeholder: "Add option",
      options: [
        {
          displayName: "Append n8n Attribution",
          name: "appendAttribution",
          type: "boolean",
          default: true,
        },
        {
          displayName: "Button Label",
          name: "buttonLabel",
          type: "string",
          default: "",
        },
        {
          displayName: "Form Path",
          name: "formPath",
          type: "string",
          default: "",
        },
        {
          displayName: "Ignore Bots",
          name: "ignoreBots",
          type: "boolean",
          default: false,
          description: "Drop requests from bots, link previewers, and web crawlers.",
        },
        {
          displayName: "Use Workflow Timezone",
          name: "useWorkflowTimezone",
          type: "boolean",
          default: false,
          description: "Use the Workflow settings timezone instead of UTC for submittedAt.",
        },
        {
          displayName: "Custom Form Styling",
          name: "customFormStyling",
          type: "string",
          typeOptions: { rows: 4 },
          default: "",
        },
        {
          displayName: "Form Submitted Text",
          name: "formSubmittedText",
          type: "string",
          typeOptions: { rows: 4 },
          default: "",
          displayOptions: { show: { responseMode: ["formSubmitted"] } },
          description:
            "Response text shown after submission. Supports HTML and <br> for line breaks.",
        },
      ],
    },
  ],
};

export const localFileTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.localFileTrigger",
  displayName: "Local File Trigger",
  category: "Triggers",
  group: ["trigger"],
  version: 1,
  description: "Starts the workflow when a local file or folder changes.",
  defaults: { name: "Local File Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "FileClock",
  sources: [`${DOCS}n8n-nodes-base.localfiletrigger/`],
  properties: [
    {
      displayName: "Trigger On",
      name: "triggerOn",
      type: "options",
      default: "",
      noDataExpression: true,
      required: true,
      description: "What to watch.",
      options: [
        { name: "Changes to a Specific File", value: "file" },
        { name: "Changes Involving a Specific Folder", value: "folder" },
      ],
    },
    {
      displayName: "File to Watch",
      name: "path",
      type: "string",
      default: "",
      required: true,
      placeholder: "/data/invoices/1.pdf",
      displayOptions: { show: { triggerOn: ["file"] } },
      description: "Absolute or host-local filesystem path of the file to watch.",
    },
    {
      displayName: "Folder to Watch",
      name: "path",
      type: "string",
      default: "",
      required: true,
      placeholder: "/data/invoices",
      displayOptions: { show: { triggerOn: ["folder"] } },
      description: "Absolute or host-local filesystem path of the folder to watch.",
    },
    {
      displayName: "Watch for",
      name: "events",
      type: "multiOptions",
      default: [],
      displayOptions: { show: { triggerOn: ["folder"] } },
      description: "Which folder-related change kinds to fire on.",
      options: [
        { name: "File Added", value: "add" },
        { name: "File Changed", value: "change" },
        { name: "File Deleted", value: "unlink" },
        { name: "Folder Added", value: "addDir" },
        { name: "Folder Deleted", value: "unlinkDir" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      placeholder: "Add option",
      options: [
        {
          displayName: "Wait for Write to Finish",
          name: "awaitWriteFinish",
          type: "boolean",
          default: false,
          description: "Wait until a write settles before firing.",
        },
        {
          displayName: "Include Linked Files/Folders",
          name: "followSymlinks",
          type: "boolean",
          default: true,
          description: "Also watch through symlinks / OS aliases / shortcuts.",
        },
        {
          displayName: "Ignore",
          name: "ignored",
          type: "string",
          default: "",
          placeholder: "**/*.txt",
          description:
            "Path patterns to skip. Matched against the full path. Supports Anymatch syntax.",
        },
        {
          displayName: "Ignore Existing Files/Folders",
          name: "ignoreInitial",
          type: "boolean",
          default: true,
          description: "Do not emit for paths already present when the watcher starts.",
        },
        {
          displayName: "Max Folder Depth",
          name: "depth",
          type: "number",
          default: -1,
          typeOptions: { minValue: -1 },
          description:
            "How deep under the root folder to watch. -1 = unlimited, 0 = top folder only.",
        },
        {
          displayName: "Use Polling",
          name: "usePolling",
          type: "boolean",
          default: false,
          description: "Use polling instead of native FS events (network mounts).",
        },
        {
          displayName: "Ignore Mode",
          name: "ignoreMode",
          type: "options",
          default: "match",
          noDataExpression: true,
          options: [
            { name: "Match", value: "match" },
            { name: "Contain", value: "contain" },
          ],
        },
      ],
    },
  ],
};

export const sseTrigger: INodeTypeDescription = {
  name: "n8n-nodes-base.sseTrigger",
  displayName: "SSE Trigger",
  category: "Triggers",
  group: ["trigger"],
  version: 1,
  description: "Starts the workflow when an SSE event is received.",
  defaults: { name: "SSE Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "RadioTower",
  sources: [`${DOCS}n8n-nodes-base.ssetrigger/`],
  properties: [
    {
      displayName: "URL",
      name: "url",
      type: "string",
      default: "",
      required: true,
      placeholder: "http://example.com",
      description: "The URL to receive the SSE from.",
    },
    {
      displayName:
        "You can now make calls to your SSE URL to trigger executions.",
      name: "notice",
      type: "notice",
      default: "",
    },
  ],
};

const CHAT_TRIGGER_DOCS =
  "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-langchain.chattrigger.md";

export const chatTrigger: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.chatTrigger",
  displayName: "Chat Trigger",
  category: "Triggers",
  group: ["trigger"],
  version: [1, 1.1, 1.2],
  defaultVersion: 1.2,
  description:
    "Starts a workflow on each incoming chat message and returns a chat response. Connect an agent or chain root node on main.",
  defaults: { name: "Chat Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "MessageCircle",
  credentials: [{ name: "httpBasicAuth", required: false }],
  sources: [CHAT_TRIGGER_DOCS],
  dynamicInputs(parameters) {
    const options = parameters.options as { loadPreviousSession?: string } | undefined;
    if (options?.loadPreviousSession === "fromMemory") {
      return ["ai_memory"];
    }
    return [];
  },
  properties: [
    {
      displayName: "Make Chat Publicly Available",
      name: "public",
      type: "boolean",
      default: false,
    },
    {
      displayName: "Mode",
      name: "mode",
      type: "options",
      default: "hosted",
      noDataExpression: true,
      displayOptions: { show: { public: [true] } },
      options: [
        { name: "Hosted Chat", value: "hosted" },
        { name: "Embedded Chat", value: "embedded" },
      ],
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "none",
      noDataExpression: true,
      displayOptions: { show: { public: [true] } },
      options: [
        { name: "None", value: "none" },
        { name: "Basic Auth", value: "basicAuth" },
        { name: "n8n User Auth", value: "n8nUserAuth" },
      ],
    },
    {
      displayName: "Initial Message(s)",
      name: "initialMessages",
      type: "string",
      default: "",
      typeOptions: { rows: 4 },
      displayOptions: { show: { public: [true], mode: ["hosted"] } },
    },
    {
      displayName: "Make Available in n8n Chat",
      name: "makeAvailableInChat",
      type: "boolean",
      default: false,
    },
    {
      displayName: "Agent Name",
      name: "agentName",
      type: "string",
      default: "",
      displayOptions: { show: { makeAvailableInChat: [true] } },
    },
    {
      displayName: "Agent description",
      name: "agentDescription",
      type: "string",
      default: "",
      typeOptions: { rows: 4 },
      displayOptions: { show: { makeAvailableInChat: [true] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      placeholder: "Add option",
      options: [
        {
          displayName: "Allowed Origin (CORS)",
          name: "allowedOrigins",
          type: "string",
          default: "*",
        },
        {
          displayName: "Input Placeholder",
          name: "inputPlaceholder",
          type: "string",
          default: "",
          displayOptions: { show: { mode: ["hosted"] } },
        },
        {
          displayName: "Title",
          name: "title",
          type: "string",
          default: "",
          displayOptions: { show: { mode: ["hosted"] } },
        },
        {
          displayName: "Subtitle",
          name: "subtitle",
          type: "string",
          default: "",
          displayOptions: { show: { mode: ["hosted"] } },
        },
        {
          displayName: "Load Previous Session",
          name: "loadPreviousSession",
          type: "options",
          default: "off",
          noDataExpression: true,
          options: [
            { name: "Off", value: "off" },
            { name: "From Memory", value: "fromMemory" },
          ],
        },
        {
          displayName: "Response Mode",
          name: "responseMode",
          type: "options",
          default: "whenLastNode",
          noDataExpression: true,
          options: [
            { name: "When Last Node Finishes", value: "whenLastNode" },
            { name: "Using Response Nodes", value: "responseNodes" },
            { name: "Streaming response", value: "streaming" },
          ],
        },
        {
          displayName: "Require Button Click to Start Chat",
          name: "requireButton",
          type: "boolean",
          default: false,
          displayOptions: { show: { mode: ["hosted"] } },
        },
      ],
    },
  ],
};

const MCP_TRIGGER_DOCS =
  "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-langchain.mcptrigger.md";

export const mcpTrigger: INodeTypeDescription = {
  name: "@n8n/n8n-nodes-langchain.mcpTrigger",
  displayName: "MCP Server Trigger",
  category: "Triggers",
  group: ["trigger"],
  version: [1, 1.1, 1.2],
  defaultVersion: 1.2,
  description:
    "Exposes the workflow as an MCP server. Starts on each tools/call from an external MCP client.",
  defaults: { name: "MCP Server Trigger" },
  inputs: [],
  outputs: ["main"],
  icon: "Webhook",
  credentials: [{ name: "httpBearerAuth", required: false }, { name: "httpHeaderAuth", required: false }],
  sources: [MCP_TRIGGER_DOCS],
  properties: [
    {
      displayName: "Server Path",
      name: "path",
      type: "string",
      default: "",
      placeholder: "my-mcp-server",
      required: true,
      description: "URL path segment the MCP server listens on.",
    },
    {
      displayName: "Tools",
      name: "tools",
      type: "fixedCollection",
      default: {},
      typeOptions: { multipleValues: true },
      noDataExpression: true,
      required: true,
      description: "Tool definitions the MCP server exposes to clients.",
      options: [
        {
          name: "values",
          displayName: "Tool",
          values: [
            {
              displayName: "Tool Name",
              name: "name",
              type: "string",
              default: "",
              required: true,
              noDataExpression: true,
            },
            {
              displayName: "Description",
              name: "description",
              type: "string",
              default: "",
              typeOptions: { rows: 2 },
            },
            {
              displayName: "Input Schema (JSON)",
              name: "schema",
              type: "json",
              default: '{"type":"object"}',
              noDataExpression: true,
              description: "JSON Schema for the tool's input arguments.",
            },
          ],
        },
      ],
    },
    {
      displayName: "Authentication",
      name: "authentication",
      type: "options",
      default: "none",
      noDataExpression: true,
      options: [
        { name: "None", value: "none" },
        { name: "Bearer Auth", value: "bearerAuth" },
        { name: "Header Auth", value: "headerAuth" },
      ],
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      placeholder: "Add option",
      options: [
        {
          displayName: "Timeout (ms)",
          name: "timeout",
          type: "number",
          default: 60000,
          typeOptions: { minValue: 1000 },
          description: "Max wait for MCP connect / call in milliseconds.",
        },
      ],
    },
  ],
};

export const respondToWebhook: INodeTypeDescription = {
  name: "n8n-nodes-base.respondToWebhook",
  displayName: "Respond to Webhook",
  category: "Actions",
  group: ["output"],
  version: [1, 1.1, 1.2, 1.3, 1.4, 1.5],
  defaultVersion: 1.5,
  description: "Returns a response to the caller of the Webhook node.",
  defaults: { name: "Respond to Webhook" },
  inputs: ["main"],
  outputs: ["main"],
  outputNames: ["Input Data", "Response"],
  icon: "Reply",
  credentials: [{ name: "jwtAuth", required: false }],
  sources: [`${DOCS}n8n-nodes-base.respondtowebhook/`],
  properties: [
    {
      displayName: "Respond With",
      name: "respondWith",
      type: "options",
      default: "firstIncomingItem",
      noDataExpression: true,
      options: [
        { name: "All Incoming Items", value: "allIncomingItems" },
        { name: "First Incoming Item", value: "firstIncomingItem" },
        { name: "JSON", value: "json" },
        { name: "Text", value: "text" },
        { name: "No Data", value: "noData" },
        { name: "Redirect", value: "redirect" },
        { name: "Binary File", value: "binary" },
        { name: "JWT Token", value: "jwt" },
      ],
    },
    {
      displayName: "Response Body",
      name: "responseBody",
      type: "json",
      default: '{\n  "myField": "value"\n}',
      displayOptions: { show: { respondWith: ["json"] } },
    },
    {
      displayName: "Response Body",
      name: "responseBody",
      type: "string",
      default: "",
      displayOptions: { show: { respondWith: ["text"] } },
    },
    {
      displayName: "Redirect URL",
      name: "redirectURL",
      type: "string",
      default: "",
      placeholder: "https://example.com",
      displayOptions: { show: { respondWith: ["redirect"] } },
    },
    {
      displayName: "Payload",
      name: "payload",
      type: "json",
      default: '{\n  "myField": "value"\n}',
      displayOptions: { show: { respondWith: ["jwt"] } },
    },
    {
      displayName: "Response Data Source",
      name: "responseDataSource",
      type: "options",
      default: "automatically",
      displayOptions: { show: { respondWith: ["binary"] } },
      options: [
        { name: "Automatically", value: "automatically" },
        { name: "Set Below", value: "set" },
      ],
    },
    {
      displayName: "Input Binary Field",
      name: "inputFieldName",
      type: "string",
      default: "data",
      required: true,
      displayOptions: { show: { respondWith: ["binary"], responseDataSource: ["set"] } },
    },
    {
      displayName: "Options",
      name: "options",
      type: "collection",
      default: {},
      placeholder: "Add option",
      options: [
        {
          displayName: "Response Code",
          name: "responseCode",
          type: "number",
          default: 200,
          typeOptions: { minValue: 100, maxValue: 599 },
        },
        {
          displayName: "Response Headers",
          name: "responseHeaders",
          type: "fixedCollection",
          default: {},
          placeholder: "Add header",
          options: [
            {
              displayName: "Entries",
              name: "entries",
              values: [
                { displayName: "Name", name: "name", type: "string", default: "" },
                { displayName: "Value", name: "value", type: "string", default: "" },
              ],
            },
          ],
        },
        {
          displayName: "Put Response in Field",
          name: "responseKey",
          type: "string",
          default: "",
          displayOptions: {
            show: { respondWith: ["allIncomingItems", "firstIncomingItem"] },
          },
        },
        {
          displayName: "Enable Streaming",
          name: "enableStreaming",
          type: "boolean",
          default: true,
          displayOptions: {
            show: {
              respondWith: ["allIncomingItems", "firstIncomingItem", "text", "json", "jwt"],
            },
          },
        },
      ],
    },
  ],
};
