#!/usr/bin/env bash
# Install OpenFlow with Docker (no Node.js required on the host).
#
#   curl -fsSL https://raw.githubusercontent.com/OWNER/REPO/main/scripts/install.sh | bash
#
# Flags:
#   --prod          Enable auth (AUTH_DISABLED=false); first open creates the owner
#   --port N        Host port (default 3000)
#   --home PATH     Install directory (default ~/openflow or OPENFLOW_HOME)
#   --no-open       Do not open a browser
#   --skip-wait     Do not poll /health/ready
#   --help
set -euo pipefail

BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}ℹ${NC}  $*"; }
ok()    { echo -e "${GREEN}✔${NC}  $*"; }
warn()  { echo -e "${YELLOW}⚠${NC}  $*"; }
fail()  { echo -e "${RED}✘${NC}  $*"; exit 1; }

OPENFLOW_HOME="${OPENFLOW_HOME:-$HOME/openflow}"
OPENFLOW_IMAGE="${OPENFLOW_IMAGE:-ghcr.io/real-limitless/openflow:latest}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-openflow}"
OPENFLOW_PORT="${OPENFLOW_PORT:-3000}"
PROD=false
NO_OPEN=false
SKIP_WAIT=false
WAIT_SECONDS="${OPENFLOW_WAIT_SECONDS:-90}"

usage() {
  cat <<EOF
OpenFlow installer

Usage: install.sh [options]

  --prod          Production-ish defaults (AUTH_DISABLED=false)
  --port N        Host port for the UI (default: 3000)
  --home PATH     Data / compose directory (default: ~/openflow)
  --no-open       Do not open a browser when ready
  --skip-wait     Skip waiting for /health/ready
  --help          Show this help

Environment:
  OPENFLOW_HOME, OPENFLOW_IMAGE, OPENFLOW_PORT, COMPOSE_PROJECT_NAME, OPENFLOW_WAIT_SECONDS
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prod) PROD=true; shift ;;
    --port)
      OPENFLOW_PORT="${2:-}"
      [[ -n "$OPENFLOW_PORT" ]] || fail "--port requires a value"
      shift 2
      ;;
    --home)
      OPENFLOW_HOME="${2:-}"
      [[ -n "$OPENFLOW_HOME" ]] || fail "--home requires a path"
      shift 2
      ;;
    --no-open) NO_OPEN=true; shift ;;
    --skip-wait) SKIP_WAIT=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "Unknown option: $1 (try --help)" ;;
  esac
done

compose_cmd() {
  if command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
    echo "docker compose"
  elif command -v docker-compose &>/dev/null; then
    echo "docker-compose"
  else
    return 1
  fi
}

port_in_use() {
  local port="$1"
  if command -v ss &>/dev/null; then
    ss -ltn "( sport = :$port )" 2>/dev/null | grep -q ":$port" && return 0
    return 1
  fi
  if command -v lsof &>/dev/null; then
    lsof -iTCP:"$port" -sTCP:LISTEN -n -P &>/dev/null && return 0
    return 1
  fi
  # best-effort: try binding via bash /dev/tcp is not reliable for "in use"
  return 1
}

open_browser() {
  local url="$1"
  if [[ "$NO_OPEN" == true ]]; then
    return 0
  fi
  if [[ ! -t 0 && ! -t 1 ]]; then
    # non-interactive pipe (curl | bash) — still try if DISPLAY is set
    :
  fi
  if command -v xdg-open &>/dev/null; then
    xdg-open "$url" &>/dev/null || true
  elif command -v open &>/dev/null; then
    open "$url" &>/dev/null || true
  fi
}

wait_ready() {
  local port="$1"
  local url="http://127.0.0.1:${port}/health/ready"
  local i
  info "Waiting for OpenFlow to become ready (up to ${WAIT_SECONDS}s)…"
  for i in $(seq 1 "$WAIT_SECONDS"); do
    if command -v curl &>/dev/null; then
      if curl -fsS "$url" &>/dev/null; then
        ok "Ready: ${url}"
        return 0
      fi
    elif command -v wget &>/dev/null; then
      if wget -q -O /dev/null "$url" 2>/dev/null; then
        ok "Ready: ${url}"
        return 0
      fi
    else
      # No curl/wget — sleep once and hope
      sleep 5
      warn "curl/wget not found; skipped readiness probe"
      return 0
    fi
    sleep 1
  done
  return 1
}

echo ""
echo -e "${BOLD}OpenFlow installer${NC}"
echo -e "${DIM}──────────────────────────────────────${NC}"

if ! compose_cmd &>/dev/null; then
  fail "Docker Compose is required. Install Docker: https://docs.docker.com/engine/install/"
fi
DC="$(compose_cmd)"
ok "Compose: $DC"

if ! [[ "$OPENFLOW_PORT" =~ ^[0-9]+$ ]] || (( OPENFLOW_PORT < 1 || OPENFLOW_PORT > 65535 )); then
  fail "Invalid port: $OPENFLOW_PORT"
fi

if port_in_use "$OPENFLOW_PORT"; then
  warn "Port ${OPENFLOW_PORT} looks busy. If start fails, re-run with --port 3001"
else
  ok "Port ${OPENFLOW_PORT} available"
fi

mkdir -p "$OPENFLOW_HOME"
cd "$OPENFLOW_HOME"

AUTH_DEFAULT="true"
if [[ "$PROD" == true ]]; then
  AUTH_DEFAULT="false"
fi

if [[ ! -f .env ]]; then
  KEY="$(
    if command -v openssl &>/dev/null; then
      openssl rand -hex 32
    elif command -v python3 &>/dev/null; then
      python3 -c 'import secrets; print(secrets.token_hex(32))'
    else
      docker run --rm node:22-slim node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))"
    fi
  )"
  cat > .env <<EOF
# Generated by scripts/install.sh — $(date -u +%Y-%m-%dT%H:%MZ)
AUTH_DISABLED=${AUTH_DEFAULT}
CREDENTIALS_KEY=${KEY}
OPENFLOW_ASSISTANT_ENABLED=true
EOF
  ok "Wrote ${OPENFLOW_HOME}/.env (CREDENTIALS_KEY generated)"
  if [[ "$PROD" == true ]]; then
    ok "Production mode: AUTH_DISABLED=false (create owner on first open)"
  fi
else
  info ".env already exists (left unchanged)"
  if [[ "$PROD" == true ]]; then
    warn "--prod does not rewrite an existing .env; set AUTH_DISABLED=false manually if needed"
  fi
fi

cat > docker-compose.yml <<EOF
# Generated by OpenFlow install.sh — edit OPENFLOW_IMAGE to pin a version
services:
  api:
    image: ${OPENFLOW_IMAGE}
    ports:
      - "${OPENFLOW_PORT}:3000"
    env_file:
      - path: .env
        required: false
    environment:
      DATABASE_URL: postgresql://openflow:openflow@db:5432/openflow
      REDIS_URL: redis://redis:6379
      AUTH_DISABLED: \${AUTH_DISABLED:-${AUTH_DEFAULT}}
      CREDENTIALS_KEY: \${CREDENTIALS_KEY:-}
      BINARY_STORAGE_DIR: /data/binary
      OPENFLOW_SECRETS_DIR: /data/secrets
      RUN_WORKER: \${RUN_WORKER:-true}
      WORKER_CONCURRENCY: \${WORKER_CONCURRENCY:-5}
    volumes:
      - binary-data:/data/binary
      - secrets-data:/data/secrets
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \\"fetch('http://127.0.0.1:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: openflow
      POSTGRES_USER: openflow
      POSTGRES_PASSWORD: openflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openflow -d openflow"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  binary-data:
  secrets-data:
  redis-data:
EOF
ok "Wrote ${OPENFLOW_HOME}/docker-compose.yml"

info "Pulling images (first run may take a few minutes)…"
set +e
$DC pull
pull_rc=$?
set -e

if [[ $pull_rc -ne 0 ]]; then
  warn "Could not pull ${OPENFLOW_IMAGE}."
  warn "If the image is not published yet, clone the repo and run: docker compose up -d --build"
fi

info "Starting OpenFlow…"
$DC up -d

UI_URL="http://localhost:${OPENFLOW_PORT}"
READY=false

if [[ "$SKIP_WAIT" == true ]]; then
  warn "Skipped readiness wait (--skip-wait)"
else
  if wait_ready "$OPENFLOW_PORT"; then
    READY=true
  else
    echo ""
    warn "Timed out waiting for ${UI_URL}/health/ready"
    warn "Recent API logs:"
    $DC logs --tail=40 api 2>/dev/null || true
    echo ""
    warn "See docs: https://github.com/real-limitless/OpenFlow/blob/main/docs/install.md"
  fi
fi

echo ""
if [[ "$READY" == true ]]; then
  echo -e "${GREEN}${BOLD}OpenFlow is ready.${NC}"
else
  echo -e "${YELLOW}${BOLD}OpenFlow is starting (not ready yet).${NC}"
fi
echo ""
echo -e "  UI:       ${BOLD}${UI_URL}${NC}"
echo -e "  Data dir: ${BOLD}${OPENFLOW_HOME}${NC}"
echo -e "  Logs:     ${BOLD}cd ${OPENFLOW_HOME} && ${DC} logs -f api${NC}"
echo -e "  Stop:     ${BOLD}cd ${OPENFLOW_HOME} && ${DC} down${NC}"
echo ""
echo -e "${BOLD}Next steps${NC}"
if [[ "$AUTH_DEFAULT" == "false" ]] || grep -qE '^AUTH_DISABLED=(false|0)' .env 2>/dev/null; then
  echo -e "  1. Open ${BOLD}${UI_URL}${NC} and create the ${BOLD}instance owner${NC} account"
  echo -e "  2. On the home page, choose ${BOLD}Run sample workflow${NC}"
  echo -e "  3. Click ${BOLD}Execute${NC} for your first successful run"
else
  echo -e "  1. Open ${BOLD}${UI_URL}${NC}"
  echo -e "  2. Choose ${BOLD}Run sample workflow${NC} (no account needed in try-out mode)"
  echo -e "  3. Click ${BOLD}Execute${NC} for your first successful run"
  echo ""
  echo -e "${DIM}Auth is off by default. For production: re-run with --prod or set AUTH_DISABLED=false and put TLS in front.${NC}"
fi
echo ""

if [[ "$READY" == true ]]; then
  open_browser "$UI_URL"
fi
