#!/usr/bin/env bash
# Install OpenFlow with Docker (no Node.js required on the host).
#
#   curl -fsSL https://raw.githubusercontent.com/OWNER/REPO/main/scripts/install.sh | bash
#
# Or:
#   ./scripts/install.sh
set -euo pipefail

BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}ℹ${NC}  $*"; }
ok()    { echo -e "${GREEN}✔${NC}  $*"; }
warn()  { echo -e "${YELLOW}⚠${NC}  $*"; }
fail()  { echo -e "${RED}✘${NC}  $*"; exit 1; }

OPENFLOW_HOME="${OPENFLOW_HOME:-$HOME/openflow}"
# Override when publishing under your org, e.g. ghcr.io/acme/openflow:latest
OPENFLOW_IMAGE="${OPENFLOW_IMAGE:-ghcr.io/real-limitless/openflow:latest}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-openflow}"

compose_cmd() {
  if command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
    echo "docker compose"
  elif command -v docker-compose &>/dev/null; then
    echo "docker-compose"
  else
    return 1
  fi
}

echo ""
echo -e "${BOLD}OpenFlow installer${NC}"
echo -e "${DIM}──────────────────────────────────────${NC}"

if ! compose_cmd &>/dev/null; then
  fail "Docker Compose is required. Install Docker: https://docs.docker.com/engine/install/"
fi
DC="$(compose_cmd)"
ok "Compose: $DC"

mkdir -p "$OPENFLOW_HOME"
cd "$OPENFLOW_HOME"

if [[ ! -f .env ]]; then
  KEY="$(
    if command -v openssl &>/dev/null; then
      openssl rand -hex 32
    elif command -v python3 &>/dev/null; then
      python3 -c 'import secrets; print(secrets.token_hex(32))'
    else
      # last resort: docker node
      docker run --rm node:22-slim node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))"
    fi
  )"
  cat > .env <<EOF
# Generated by scripts/install.sh — $(date -u +%Y-%m-%dT%H:%MZ)
AUTH_DISABLED=true
CREDENTIALS_KEY=${KEY}
OPENFLOW_ASSISTANT_ENABLED=true
EOF
  ok "Wrote ${OPENFLOW_HOME}/.env (CREDENTIALS_KEY generated)"
else
  info ".env already exists (left unchanged)"
fi

cat > docker-compose.yml <<EOF
# Generated by OpenFlow install.sh — edit OPENFLOW_IMAGE to pin a version
services:
  api:
    image: ${OPENFLOW_IMAGE}
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: false
    environment:
      DATABASE_URL: postgresql://openflow:openflow@db:5432/openflow
      REDIS_URL: redis://redis:6379
      AUTH_DISABLED: \${AUTH_DISABLED:-true}
      CREDENTIALS_KEY: \${CREDENTIALS_KEY:-}
      BINARY_STORAGE_DIR: /data/binary
      OPENFLOW_SECRETS_DIR: /data/secrets
      RUN_WORKER: \${RUN_WORKER:-true}
      WORKER_CONCURRENCY: \${WORKER_CONCURRENCY:-5}
    volumes:
      - binary-data:/data/binary
      - secrets-data:/data/secrets
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \\"fetch('http://127.0.0.1:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: openflow
      POSTGRES_USER: openflow
      POSTGRES_PASSWORD: openflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openflow -d openflow"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  binary-data:
  secrets-data:
  redis-data:
EOF
ok "Wrote ${OPENFLOW_HOME}/docker-compose.yml"

info "Pulling images (first run may take a few minutes)…"
# Prefer pull; if image missing from registry, fall back is user's problem until GHCR publishes
set +e
$DC pull
pull_rc=$?
set -e

if [[ $pull_rc -ne 0 ]]; then
  warn "Could not pull ${OPENFLOW_IMAGE}."
  warn "If the image is not published yet, clone the repo and run: docker compose up -d --build"
fi

info "Starting OpenFlow…"
$DC up -d

echo ""
echo -e "${GREEN}${BOLD}OpenFlow is starting.${NC}"
echo ""
echo -e "  UI:       ${BOLD}http://localhost:3000${NC}"
echo -e "  Data dir: ${BOLD}${OPENFLOW_HOME}${NC}"
echo -e "  Logs:     ${BOLD}cd ${OPENFLOW_HOME} && ${DC} logs -f api${NC}"
echo -e "  Stop:     ${BOLD}cd ${OPENFLOW_HOME} && ${DC} down${NC}"
echo ""
echo -e "${DIM}Auth is off by default. For production set AUTH_DISABLED=false and put TLS in front.${NC}"
echo ""
