/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsCompatibilityRouteImport } from './routes/docs.compatibility'
import { Route as WorkflowIdRouteImport } from './routes/workflow.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCompatibilityRoute = DocsCompatibilityRouteImport.update({
  id: '/docs/compatibility',
  path: '/docs/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs/compatibility' | '/workflow/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/compatibility' | '/workflow/$id'
  id: '__root__' | '/' | '/docs/compatibility' | '/workflow/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsCompatibilityRoute: typeof DocsCompatibilityRoute
  WorkflowIdRoute: typeof WorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/compatibility': {
      id: '/docs/compatibility'
      path: '/docs/compatibility'
      fullPath: '/docs/compatibility'
      preLoaderRoute: typeof DocsCompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsCompatibilityRoute: DocsCompatibilityRoute,
  WorkflowIdRoute: WorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
