/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as DataTablesRouteImport } from './routes/data-tables'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ChatsWorkflowIdRouteImport } from './routes/chats_.$workflowId'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as VariablesRouteImport } from './routes/variables'
import { Route as DataTablesIdRouteImport } from './routes/data-tables_.$id'
import { Route as DocsCompatibilityRouteImport } from './routes/docs.compatibility'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as SettingsCodeRouteImport } from './routes/settings.code'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as SettingsEnvironmentsRouteImport } from './routes/settings.environments'
import { Route as SettingsLogsRouteImport } from './routes/settings.logs'
import { Route as SettingsSecretProvidersRouteImport } from './routes/settings.secret-providers'
import { Route as SettingsTemplatesRouteImport } from './routes/settings.templates'
import { Route as TemplatesIdRouteImport } from './routes/templates_.$id'
import { Route as WorkflowIdRouteImport } from './routes/workflow.$id'
import { Route as ExecutionsIdRouteImport } from './routes/executions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTablesRoute = DataTablesRouteImport.update({
  id: '/data-tables',
  path: '/data-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsWorkflowIdRoute = ChatsWorkflowIdRouteImport.update({
  id: '/chats_/$workflowId',
  path: '/chats/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const VariablesRoute = VariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTablesIdRoute = DataTablesIdRouteImport.update({
  id: '/data-tables_/$id',
  path: '/data-tables/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCompatibilityRoute = DocsCompatibilityRouteImport.update({
  id: '/docs/compatibility',
  path: '/docs/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCodeRoute = SettingsCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEnvironmentsRoute = SettingsEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecretProvidersRoute = SettingsSecretProvidersRouteImport.update({
  id: '/secret-providers',
  path: '/secret-providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SettingsRoute,
} as any)
const TemplatesIdRoute = TemplatesIdRouteImport.update({
  id: '/templates_/$id',
  path: '/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsIdRoute = ExecutionsIdRouteImport.update({
  id: '/executions/$id',
  path: '/executions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/data-tables': typeof DataTablesRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/shared': typeof SharedRoute
  '/chats': typeof ChatsRoute
  '/chats/$workflowId': typeof ChatsWorkflowIdRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/data-tables/$id': typeof DataTablesIdRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/code': typeof SettingsCodeRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/secret-providers': typeof SettingsSecretProvidersRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/executions/$id': typeof ExecutionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/data-tables': typeof DataTablesRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/shared': typeof SharedRoute
  '/chats': typeof ChatsRoute
  '/chats/$workflowId': typeof ChatsWorkflowIdRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/data-tables/$id': typeof DataTablesIdRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/code': typeof SettingsCodeRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/secret-providers': typeof SettingsSecretProvidersRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/executions/$id': typeof ExecutionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/data-tables': typeof DataTablesRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/shared': typeof SharedRoute
  '/chats': typeof ChatsRoute
  '/chats_/$workflowId': typeof ChatsWorkflowIdRoute
  '/templates': typeof TemplatesRoute
  '/variables': typeof VariablesRoute
  '/data-tables_/$id': typeof DataTablesIdRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/code': typeof SettingsCodeRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/secret-providers': typeof SettingsSecretProvidersRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/templates_/$id': typeof TemplatesIdRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/executions/$id': typeof ExecutionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credentials'
    | '/data-tables'
    | '/login'
    | '/projects'
    | '/register'
    | '/settings'
    | '/setup'
    | '/shared'
    | '/chats'
    | '/chats/$workflowId'
    | '/templates'
    | '/variables'
    | '/data-tables/$id'
    | '/docs/compatibility'
    | '/projects/$id'
    | '/settings/api-keys'
    | '/settings/code'
    | '/settings/mcp'
    | '/settings/environments'
    | '/settings/logs'
    | '/settings/secret-providers'
    | '/settings/templates'
    | '/templates/$id'
    | '/workflow/$id'
    | '/executions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credentials'
    | '/data-tables'
    | '/login'
    | '/projects'
    | '/register'
    | '/settings'
    | '/setup'
    | '/shared'
    | '/chats'
    | '/chats/$workflowId'
    | '/templates'
    | '/variables'
    | '/data-tables/$id'
    | '/docs/compatibility'
    | '/projects/$id'
    | '/settings/api-keys'
    | '/settings/code'
    | '/settings/mcp'
    | '/settings/environments'
    | '/settings/logs'
    | '/settings/secret-providers'
    | '/settings/templates'
    | '/templates/$id'
    | '/workflow/$id'
    | '/executions/$id'
  id:
    | '__root__'
    | '/'
    | '/credentials'
    | '/data-tables'
    | '/login'
    | '/projects'
    | '/register'
    | '/settings'
    | '/setup'
    | '/shared'
    | '/chats'
    | '/chats_/$workflowId'
    | '/templates'
    | '/variables'
    | '/data-tables_/$id'
    | '/docs/compatibility'
    | '/projects/$id'
    | '/settings/api-keys'
    | '/settings/code'
    | '/settings/mcp'
    | '/settings/environments'
    | '/settings/logs'
    | '/settings/secret-providers'
    | '/settings/templates'
    | '/templates_/$id'
    | '/workflow/$id'
    | '/executions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CredentialsRoute: typeof CredentialsRoute
  DataTablesRoute: typeof DataTablesRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  SharedRoute: typeof SharedRoute
  ChatsRoute: typeof ChatsRoute
  ChatsWorkflowIdRoute: typeof ChatsWorkflowIdRoute
  TemplatesRoute: typeof TemplatesRoute
  VariablesRoute: typeof VariablesRoute
  DataTablesIdRoute: typeof DataTablesIdRoute
  DocsCompatibilityRoute: typeof DocsCompatibilityRoute
  TemplatesIdRoute: typeof TemplatesIdRoute
  WorkflowIdRoute: typeof WorkflowIdRoute
  ExecutionsIdRoute: typeof ExecutionsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-tables': {
      id: '/data-tables'
      path: '/data-tables'
      fullPath: '/data-tables'
      preLoaderRoute: typeof DataTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats_/$workflowId': {
      id: '/chats_/$workflowId'
      path: '/chats/$workflowId'
      fullPath: '/chats/$workflowId'
      preLoaderRoute: typeof ChatsWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variables': {
      id: '/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-tables_/$id': {
      id: '/data-tables_/$id'
      path: '/data-tables/$id'
      fullPath: '/data-tables/$id'
      preLoaderRoute: typeof DataTablesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/compatibility': {
      id: '/docs/compatibility'
      path: '/docs/compatibility'
      fullPath: '/docs/compatibility'
      preLoaderRoute: typeof DocsCompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/code': {
      id: '/settings/code'
      path: '/code'
      fullPath: '/settings/code'
      preLoaderRoute: typeof SettingsCodeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/environments': {
      id: '/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof SettingsEnvironmentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/secret-providers': {
      id: '/settings/secret-providers'
      path: '/secret-providers'
      fullPath: '/settings/secret-providers'
      preLoaderRoute: typeof SettingsSecretProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/templates': {
      id: '/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/templates_/$id': {
      id: '/templates_/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof TemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/$id': {
      id: '/executions/$id'
      path: '/executions/$id'
      fullPath: '/executions/$id'
      preLoaderRoute: typeof ExecutionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsCodeRoute: typeof SettingsCodeRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsEnvironmentsRoute: typeof SettingsEnvironmentsRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsSecretProvidersRoute: typeof SettingsSecretProvidersRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsCodeRoute: SettingsCodeRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsEnvironmentsRoute: SettingsEnvironmentsRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsSecretProvidersRoute: SettingsSecretProvidersRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CredentialsRoute: CredentialsRoute,
  DataTablesRoute: DataTablesRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  SharedRoute: SharedRoute,
  ChatsRoute: ChatsRoute,
  ChatsWorkflowIdRoute: ChatsWorkflowIdRoute,
  TemplatesRoute: TemplatesRoute,
  VariablesRoute: VariablesRoute,
  DataTablesIdRoute: DataTablesIdRoute,
  DocsCompatibilityRoute: DocsCompatibilityRoute,
  TemplatesIdRoute: TemplatesIdRoute,
  WorkflowIdRoute: WorkflowIdRoute,
  ExecutionsIdRoute: ExecutionsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
