/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as VariablesRouteImport } from './routes/variables'
import { Route as DataTablesRouteImport } from './routes/data-tables'
import { Route as DataTablesIdRouteImport } from './routes/data-tables_.$id'
import { Route as DocsCompatibilityRouteImport } from './routes/docs.compatibility'
import { Route as WorkflowIdRouteImport } from './routes/workflow.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const VariablesRoute = VariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTablesRoute = DataTablesRouteImport.update({
  id: '/data-tables',
  path: '/data-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTablesIdRoute = DataTablesIdRouteImport.update({
  id: '/data-tables_/$id',
  path: '/data-tables/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCompatibilityRoute = DocsCompatibilityRouteImport.update({
  id: '/docs/compatibility',
  path: '/docs/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/variables': typeof VariablesRoute
  '/data-tables': typeof DataTablesRoute
  '/data-tables/$id': typeof DataTablesIdRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/variables': typeof VariablesRoute
  '/data-tables': typeof DataTablesRoute
  '/data-tables/$id': typeof DataTablesIdRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credentials': typeof CredentialsRoute
  '/variables': typeof VariablesRoute
  '/data-tables': typeof DataTablesRoute
  '/data-tables_/$id': typeof DataTablesIdRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/workflow/$id': typeof WorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credentials'
    | '/variables'
    | '/data-tables'
    | '/data-tables/$id'
    | '/docs/compatibility'
    | '/workflow/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credentials'
    | '/variables'
    | '/data-tables'
    | '/data-tables/$id'
    | '/docs/compatibility'
    | '/workflow/$id'
  id:
    | '__root__'
    | '/'
    | '/credentials'
    | '/variables'
    | '/data-tables'
    | '/data-tables_/$id'
    | '/docs/compatibility'
    | '/workflow/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CredentialsRoute: typeof CredentialsRoute
  VariablesRoute: typeof VariablesRoute
  DataTablesRoute: typeof DataTablesRoute
  DataTablesIdRoute: typeof DataTablesIdRoute
  DocsCompatibilityRoute: typeof DocsCompatibilityRoute
  WorkflowIdRoute: typeof WorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variables': {
      id: '/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-tables': {
      id: '/data-tables'
      path: '/data-tables'
      fullPath: '/data-tables'
      preLoaderRoute: typeof DataTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-tables_/$id': {
      id: '/data-tables_/$id'
      path: '/data-tables/$id'
      fullPath: '/data-tables/$id'
      preLoaderRoute: typeof DataTablesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/compatibility': {
      id: '/docs/compatibility'
      path: '/docs/compatibility'
      fullPath: '/docs/compatibility'
      preLoaderRoute: typeof DocsCompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CredentialsRoute: CredentialsRoute,
  VariablesRoute: VariablesRoute,
  DataTablesRoute: DataTablesRoute,
  DataTablesIdRoute: DataTablesIdRoute,
  DocsCompatibilityRoute: DocsCompatibilityRoute,
  WorkflowIdRoute: WorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
